apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  interval: 10m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true 
  chart:
    spec:
      chart: vaultwarden
      sourceRef:
        kind: HelmRepository
        name:  vaultwarden
        namespace: flux-system
      version: "0.43.1"
  valuesFrom:
    - kind: Secret
      name: vaultwarden-secrets
      valuesKey: values.yaml
  values:

    image:
      tag: "1.36.0-alpine"

    resourceType: "Deployment"

    storage:
      data:
        name: "vaultwarden-data"
        size: "2Gi"
        class: "csi-cephfs-sc"
        path: "/data"
        accessMode: "ReadWriteMany"
        keepPvc: true

    database:
      type: "postgresql"
      host: "vaultwarden-db-rw"
      port: "5432"
      dbName: "vaultwarden"
      existingSecret: vaultwarden-db-secret
      existingSecretUserKey: username
      existingSecretPasswordKey: password

    domain: "https://bitwarden.exmaple.com"

    smtp:
      host: "mail.exmaple.com"
      security: "force_tls"
      port: 465
      from: "bitwarden@exmaple.com"
      authMechanism: "Login"
      debug: false

    adminToken:
      existingSecret: "vaultwarden-disable-admin"
      existingSecretKey: "token"

    replicas: 1
    service:
      sessionAffinity: ClientIP
      sessionAffinityConfig:
        clientIP:
          timeoutSeconds: 10800    
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/name: vaultwarden
                app.kubernetes.io/instance: vaultwarden
            topologyKey: kubernetes.io/hostname

    ingress:
      enabled: true
      class: "cilium"
      nginxIngressAnnotations: true
      additionalAnnotations: {}
      labels: {}
      tls: true
      tlsSecret: "external-tls"
      hostname: "bitwarden.exmaple.com"

    timeZone: "Europe/Berlin"

    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
      seccompProfile:
        type: RuntimeDefault

    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
      capabilities:
        drop:
          - ALL

    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi