apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: vaultwarden
stringData:
    values.yaml: ENC[AES256_GCM,data:4kDF9GCq/b7vMXaxdDqG0mMkOmMENr1zc2KKjklPNTrxzTK8Hcxa50RSup44MmFQkRk/t/2S/0wBUWtPanpBDCLwnQcI9Zt/WP6Z8NlwdlIwiRIre3dEglKJLGQ63duMWgKiZIZduPJhlleVX3tSqv8TxHwiNWdSGFbsQoU7K80BDcsaQGM=,iv:fR+YkUyRD1knBUfKSQwkb+YIBaBDfWbfuA5RxM/t6I4=,tag:cDHpSrlHSsC0zmjsEDsB5w==,type:str]
type: Opaque
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-11T11:47:38Z"
    mac: ENC[AES256_GCM,data:u8QmYMFuusX1ZpTnVpv6R67igiNZpvUyQ+CGzOtkTyN+PqDigLhnhA11WRSsYNeHP69CqXo9oKZT49AoO0UKVpiyZGU5Pab3YDhTqCwDE8IIRk5k2hv3r1PWjlXbsdX2soKckZXO/d3cvO23tGNyrpEOJ3flEKRP1nkWQzwh05o=,iv:iN0GSdfR7PpurY14OaEmb6O7acDc3r5O2HUstqWZMo8=,tag:2fddKTOQDs1mPeOW+5XDJw==,type:str]
    pgp:
        - created_at: "2026-05-11T11:47:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQwApkaOeYhlRVQe5PhZiwsGxL1ZDKOVBckRpA91oASZvz+3
            Y0fdO+6NssrGja4g5gA1KNQFHKM06YXUBf7hPXEW9kLrNkaKo3vR8d+lG1PgEwbo
            bbDO1p7DfNqcpXQqBTHu/LILAhdYnjnxyIYWNBENDItYzFQYoynnPxwX2X1H6n0d
            +vHDPbmGhJMH0e1pScJWMgPZzDup0uyr3T/KD+7gHyPZ6VHOw2UEhlPaN4BKpN0n
            n8/oAQ4po1Mo2orwWfFDAlPx2lKwwn+tRFV+y7xfxyv23N6LhWxUQ0FDkPQ5UasW
            ugZceA0hUE8Ihpy4/vFiYCHJ6rknopx/Avl1C+jBWnIsPiS7ZojgJovK1TD24TBS
            9Fpcf2pqkK5a+JeYGCTEMW4L1lNDw0IT9mp1N2DVZEt+hl5sPsqWq7f0OGTkDIFY
            cU7K4HzupxkawNIRkXGoLbJbgH184KnlmbyUQgokEhy+kFf8w8ovqVEKS4s/K0qL
            BDFliV/cM6cPjSvYKNgx0l4BOJU8AffkUKmrwfIMefQbXXax9malhX5+KqRCrrEi
            p/+HAKrPWGK5j1G38J7A+jlqT1yaWGXWZAjmz9FOEF7hkFeTQYZhPR4f6UJCPbAy
            9Rl7czXR3GqTRx8NlrfQ
            =T8Ie
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-config-vaultwarden
    namespace: vaultwarden
type: Opaque
stringData:
    #ENC[AES256_GCM,data:6jBlKnGNQXW2QCuYYajTDW6v0db5olEgY9+z7FaFktH7lfZDhuJNRCDHcbfmWHfWzixQJA3z3omfUAcIdGoIDWs=,iv:E9rFP/PW0GbCIWFRU1RU14oBkO1lcthPiNJENyYUxe0=,tag:ks5ioXFqe22YoVSRBTrU1A==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:o4vcSs1ZkCzoix0QZ6OuSBe3p+KDyxsqYhx9l1Y9jftNGg9qEa7McIjPFgH1Rv7Bz4+e,iv:1DiXLagxos3h8qWbxrj4/iHmYyT1tJBUVxoXCaKKKEQ=,tag:pSr6YtxmaRbIDNqi4qG91A==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:g1Y6pnbdiNEmDlvlTwl4cAghs32oUNJRDD1LiMck+NbwSdxdodPmrkKDsdMXrLhx,iv:cvp/Tm0amO5Iuj7VT7bexsQqd5J833jWsMZriyR2Uyg=,tag:bvAS9cf02AUOYENGWOiL8Q==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:gsZnu+2FTACyyTqXjLBSxDVA3AEAN2kB5uU=,iv:eXYPMKA+bus3LTULHUdhXuH+Y2By5Dqqc4iF78Jl5TQ=,tag:S9iWRUSxT4ZFxYyr2SqLWg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:G8GBz6ewREEl/XWLhgnEE0PY829OCuGcAH20rp0t9zzVg5JjMfDWOzPMoTit+LoWwzgnUSsdoNPtnnPQr44gYA==,iv:zIFSRnnYItH/rwyJwMFQhuEI9Mz9AZvlGNGaalTMUnc=,tag:gMct0ORa9zV9JxoHdpDrDw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-11T11:47:38Z"
    mac: ENC[AES256_GCM,data:u8QmYMFuusX1ZpTnVpv6R67igiNZpvUyQ+CGzOtkTyN+PqDigLhnhA11WRSsYNeHP69CqXo9oKZT49AoO0UKVpiyZGU5Pab3YDhTqCwDE8IIRk5k2hv3r1PWjlXbsdX2soKckZXO/d3cvO23tGNyrpEOJ3flEKRP1nkWQzwh05o=,iv:iN0GSdfR7PpurY14OaEmb6O7acDc3r5O2HUstqWZMo8=,tag:2fddKTOQDs1mPeOW+5XDJw==,type:str]
    pgp:
        - created_at: "2026-05-11T11:47:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQwApkaOeYhlRVQe5PhZiwsGxL1ZDKOVBckRpA91oASZvz+3
            Y0fdO+6NssrGja4g5gA1KNQFHKM06YXUBf7hPXEW9kLrNkaKo3vR8d+lG1PgEwbo
            bbDO1p7DfNqcpXQqBTHu/LILAhdYnjnxyIYWNBENDItYzFQYoynnPxwX2X1H6n0d
            +vHDPbmGhJMH0e1pScJWMgPZzDup0uyr3T/KD+7gHyPZ6VHOw2UEhlPaN4BKpN0n
            n8/oAQ4po1Mo2orwWfFDAlPx2lKwwn+tRFV+y7xfxyv23N6LhWxUQ0FDkPQ5UasW
            ugZceA0hUE8Ihpy4/vFiYCHJ6rknopx/Avl1C+jBWnIsPiS7ZojgJovK1TD24TBS
            9Fpcf2pqkK5a+JeYGCTEMW4L1lNDw0IT9mp1N2DVZEt+hl5sPsqWq7f0OGTkDIFY
            cU7K4HzupxkawNIRkXGoLbJbgH184KnlmbyUQgokEhy+kFf8w8ovqVEKS4s/K0qL
            BDFliV/cM6cPjSvYKNgx0l4BOJU8AffkUKmrwfIMefQbXXax9malhX5+KqRCrrEi
            p/+HAKrPWGK5j1G38J7A+jlqT1yaWGXWZAjmz9FOEF7hkFeTQYZhPR4f6UJCPbAy
            9Rl7czXR3GqTRx8NlrfQ
            =T8Ie
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-db-secret
    namespace: vaultwarden
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:MqoeDqoH2kEIQnw=,iv:ko9oFGAj1IfTsVJeumKZi8fRjMBlGG5t/AXQuPZ1xH0=,tag:0TkgNx7a1R2dQyMr4siu0Q==,type:str]
    password: ENC[AES256_GCM,data:jk0tK87wJz+EMvJ6N+71Lw==,iv:Jyly8LNrGgnjeSk8MqgkDQl7FQInopaNwoauAtcvrb4=,tag:Ip4U/znm8qvkBT7NbxSIXw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-11T11:47:38Z"
    mac: ENC[AES256_GCM,data:u8QmYMFuusX1ZpTnVpv6R67igiNZpvUyQ+CGzOtkTyN+PqDigLhnhA11WRSsYNeHP69CqXo9oKZT49AoO0UKVpiyZGU5Pab3YDhTqCwDE8IIRk5k2hv3r1PWjlXbsdX2soKckZXO/d3cvO23tGNyrpEOJ3flEKRP1nkWQzwh05o=,iv:iN0GSdfR7PpurY14OaEmb6O7acDc3r5O2HUstqWZMo8=,tag:2fddKTOQDs1mPeOW+5XDJw==,type:str]
    pgp:
        - created_at: "2026-05-11T11:47:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQwApkaOeYhlRVQe5PhZiwsGxL1ZDKOVBckRpA91oASZvz+3
            Y0fdO+6NssrGja4g5gA1KNQFHKM06YXUBf7hPXEW9kLrNkaKo3vR8d+lG1PgEwbo
            bbDO1p7DfNqcpXQqBTHu/LILAhdYnjnxyIYWNBENDItYzFQYoynnPxwX2X1H6n0d
            +vHDPbmGhJMH0e1pScJWMgPZzDup0uyr3T/KD+7gHyPZ6VHOw2UEhlPaN4BKpN0n
            n8/oAQ4po1Mo2orwWfFDAlPx2lKwwn+tRFV+y7xfxyv23N6LhWxUQ0FDkPQ5UasW
            ugZceA0hUE8Ihpy4/vFiYCHJ6rknopx/Avl1C+jBWnIsPiS7ZojgJovK1TD24TBS
            9Fpcf2pqkK5a+JeYGCTEMW4L1lNDw0IT9mp1N2DVZEt+hl5sPsqWq7f0OGTkDIFY
            cU7K4HzupxkawNIRkXGoLbJbgH184KnlmbyUQgokEhy+kFf8w8ovqVEKS4s/K0qL
            BDFliV/cM6cPjSvYKNgx0l4BOJU8AffkUKmrwfIMefQbXXax9malhX5+KqRCrrEi
            p/+HAKrPWGK5j1G38J7A+jlqT1yaWGXWZAjmz9FOEF7hkFeTQYZhPR4f6UJCPbAy
            9Rl7czXR3GqTRx8NlrfQ
            =T8Ie
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: garage-creds
    namespace: vaultwarden
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:LQocLwkYdvF/gMCR+y5oDEGHdqKFGJFD2aI=,iv:tcakRsK9K5XIYsJcWUNHTq8DCCVqYsC+GBSTas4oq+g=,tag:reiXX2dEGEbElqu9tZluUQ==,type:str]
    secret-access-key: ENC[AES256_GCM,data:nVeHxIlDFvUqCLOvWUGtNr7l6HKB4vS3HZQxwR/NiaOdgOBDHBo8TZXfXeB6nF+gEsfvKx8naT9C5TwocG1lKQ==,iv:iIcgtqCPJ1LdsbzsSE7y/nCm0iVWtEYCA7YTXX0213k=,tag:zD31YwWPDArLM9sCMAjYyQ==,type:str]
    region: ENC[AES256_GCM,data:rXQkNQ==,iv:t7GXnCuDS475gbGhzlwbR4GhdfW2GOzb11zWx2Sa9iQ=,tag:ecMHIenpH/TZ3ewQvbYRDg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-11T11:47:38Z"
    mac: ENC[AES256_GCM,data:u8QmYMFuusX1ZpTnVpv6R67igiNZpvUyQ+CGzOtkTyN+PqDigLhnhA11WRSsYNeHP69CqXo9oKZT49AoO0UKVpiyZGU5Pab3YDhTqCwDE8IIRk5k2hv3r1PWjlXbsdX2soKckZXO/d3cvO23tGNyrpEOJ3flEKRP1nkWQzwh05o=,iv:iN0GSdfR7PpurY14OaEmb6O7acDc3r5O2HUstqWZMo8=,tag:2fddKTOQDs1mPeOW+5XDJw==,type:str]
    pgp:
        - created_at: "2026-05-11T11:47:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQwApkaOeYhlRVQe5PhZiwsGxL1ZDKOVBckRpA91oASZvz+3
            Y0fdO+6NssrGja4g5gA1KNQFHKM06YXUBf7hPXEW9kLrNkaKo3vR8d+lG1PgEwbo
            bbDO1p7DfNqcpXQqBTHu/LILAhdYnjnxyIYWNBENDItYzFQYoynnPxwX2X1H6n0d
            +vHDPbmGhJMH0e1pScJWMgPZzDup0uyr3T/KD+7gHyPZ6VHOw2UEhlPaN4BKpN0n
            n8/oAQ4po1Mo2orwWfFDAlPx2lKwwn+tRFV+y7xfxyv23N6LhWxUQ0FDkPQ5UasW
            ugZceA0hUE8Ihpy4/vFiYCHJ6rknopx/Avl1C+jBWnIsPiS7ZojgJovK1TD24TBS
            9Fpcf2pqkK5a+JeYGCTEMW4L1lNDw0IT9mp1N2DVZEt+hl5sPsqWq7f0OGTkDIFY
            cU7K4HzupxkawNIRkXGoLbJbgH184KnlmbyUQgokEhy+kFf8w8ovqVEKS4s/K0qL
            BDFliV/cM6cPjSvYKNgx0l4BOJU8AffkUKmrwfIMefQbXXax9malhX5+KqRCrrEi
            p/+HAKrPWGK5j1G38J7A+jlqT1yaWGXWZAjmz9FOEF7hkFeTQYZhPR4f6UJCPbAy
            9Rl7czXR3GqTRx8NlrfQ
            =T8Ie
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.0
