apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: prometheus
type: Opaque
data:
    admin-user: ENC[AES256_GCM,data:BExY+thJPJE=,iv:8P0+CZxYKaGp3S07aQZvAINM68sMBUz3hsvzJhGNjmw=,tag:pFwjXxwBQrTUatZ/xKrPeA==,type:str]
    admin-password: ENC[AES256_GCM,data:ufku1enXSXrM6X9DTHhKL1j3Jao=,iv:PLJ6de17/ZO4CLi0cBPxtjlhokCWE49A0q2A04K3MYg=,tag:XnLWOjCvalnAARAugFz4EA==,type:str]
sops:
    lastmodified: "2025-09-17T17:42:14Z"
    mac: ENC[AES256_GCM,data:EtY4i7x+TqoPyyEII8xwxabDLmZpUXJCpgzwHhU1aAc7ctNlz1yWoXdKGabfMXNOLLAmcgd4geTq5jPKIuO9ztlqn9xawi/tvMuy0sUjcMSo9ks8y4+AwZoU3tn7Nb8Gnwo0PKSXGg6l7CrsSsbM6T6T0CNlYwid5S701ntP54w=,iv:Yt4vi2mdlyFR55iXAN07zjylBxJtaEoA0LYbP/peaDQ=,tag:L+ESU7ecFXkftO/UD2iw9g==,type:str]
    pgp:
        - created_at: "2025-09-17T17:42:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/V7gwsxO6Y9T8OC2/LORFyPDBO1PYfyLTER5dbLZK16mM
            OEp6Gd7EXp3kmJEZzyoUSGzKKnTjunYOEU6OJawaAC0Ic1WSXdI69z8QTmaxLF+Y
            1XGYFt6CeqHywciRM0MiXxkxK/JX9S27eEjSllaOvorZZ50qb2zGa7bCb5iXAvew
            ZYpqps/IbbhRd3s3O4PMo3XfmT0wOtoNg1b4FBv6v7uqC/BOD4CgZXZnJhpmbc1/
            sjmT93Jw5Q15PJQ4nWDH4eJzlwTQ4HbA92oc+nxq1WKxu/9MXnWANa0OgeOctMdv
            h7bw2TqrNbksO1u32T6ql7NyVWdqoVzDei3IPkklvLzcMXExxPCZ8yBl9Jy7wKaH
            Q3wM3i3iYMXv6Pi9hAlqfRrOQZvOlJBnJxthvTMfel4SL5OMfc0fCm/ttZUvpzmf
            QE+9ybcUVEdid5n+bNsr2GGm9Sq+ik5Qm1mX2CVRnodThuj6PBq0Q+7Kc9c+bl1k
            NZdbe8UUQBTAZdqc/qJB0lwBE2+WOlN/QHLuubm202Ggv4nrgtRCQ5Rf09orCWU+
            Io9XDjbUFsPmxrVsQBuf0uYcLifdNQ65cVC9jTXZV+t2V/Xa+rNivI8QLA51y2l1
            d0LeB/JIglhcKUybTA==
            =8mzE
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc
    namespace: prometheus
type: Opaque
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:yEfbZMfzzKHonqX12hZRsH8HuhfxSIwYdHLS9k8LSTP9xCpTum6OvA==,iv:FUmj0CVL03KIHXCSqEPtZxcZAezyqXbi53oMQedivKY=,tag:Hg86HSU6cqUs4uzvNdKdkg==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Q2FVYvxp0LXqcJk+kPokA78Q3kReyD2eFGFGDWgDJ/kV7h48BmhsTLt/tlDeNtwzG/OH4lA7VoMn5/6gIUc1uq/yPBNSNsUW6iEvOwJ8hOpjxf3YkBAWl4zxvAzoMIAZoTOJHogTeAylDtHfQo/H9xb61BynwQgWlZrnJrBzuzg=,iv:qcH/C2y+5w+/86KUyCz39jDi53WRCRuhQvOpWlvQjao=,tag:IhVMMmBtkbGFSgcWvTuPHg==,type:str]
sops:
    lastmodified: "2025-09-17T17:42:14Z"
    mac: ENC[AES256_GCM,data:EtY4i7x+TqoPyyEII8xwxabDLmZpUXJCpgzwHhU1aAc7ctNlz1yWoXdKGabfMXNOLLAmcgd4geTq5jPKIuO9ztlqn9xawi/tvMuy0sUjcMSo9ks8y4+AwZoU3tn7Nb8Gnwo0PKSXGg6l7CrsSsbM6T6T0CNlYwid5S701ntP54w=,iv:Yt4vi2mdlyFR55iXAN07zjylBxJtaEoA0LYbP/peaDQ=,tag:L+ESU7ecFXkftO/UD2iw9g==,type:str]
    pgp:
        - created_at: "2025-09-17T17:42:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/V7gwsxO6Y9T8OC2/LORFyPDBO1PYfyLTER5dbLZK16mM
            OEp6Gd7EXp3kmJEZzyoUSGzKKnTjunYOEU6OJawaAC0Ic1WSXdI69z8QTmaxLF+Y
            1XGYFt6CeqHywciRM0MiXxkxK/JX9S27eEjSllaOvorZZ50qb2zGa7bCb5iXAvew
            ZYpqps/IbbhRd3s3O4PMo3XfmT0wOtoNg1b4FBv6v7uqC/BOD4CgZXZnJhpmbc1/
            sjmT93Jw5Q15PJQ4nWDH4eJzlwTQ4HbA92oc+nxq1WKxu/9MXnWANa0OgeOctMdv
            h7bw2TqrNbksO1u32T6ql7NyVWdqoVzDei3IPkklvLzcMXExxPCZ8yBl9Jy7wKaH
            Q3wM3i3iYMXv6Pi9hAlqfRrOQZvOlJBnJxthvTMfel4SL5OMfc0fCm/ttZUvpzmf
            QE+9ybcUVEdid5n+bNsr2GGm9Sq+ik5Qm1mX2CVRnodThuj6PBq0Q+7Kc9c+bl1k
            NZdbe8UUQBTAZdqc/qJB0lwBE2+WOlN/QHLuubm202Ggv4nrgtRCQ5Rf09orCWU+
            Io9XDjbUFsPmxrVsQBuf0uYcLifdNQ65cVC9jTXZV+t2V/Xa+rNivI8QLA51y2l1
            d0LeB/JIglhcKUybTA==
            =8mzE
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
