apiVersion: v1
kind: Secret
metadata:
    name: trilium-oidc
    namespace: trilium
type: Opaque
stringData:
    TRILIUM_MULTIFACTORAUTHENTICATION_OAUTHCLIENTID: ENC[AES256_GCM,data:bWu4gIjbBeCxzfEUSUZqED7D27ozGw+GMO3zBrIHtvcR+5dhBRbTsA==,iv:/1Oq9kW95gslMPKYU3AtNFv5D+ks9HLadxIfTqCUzw0=,tag:LPncZMW1dPCcyho92FgU5w==,type:str]
    TRILIUM_MULTIFACTORAUTHENTICATION_OAUTHCLIENTSECRET: ENC[AES256_GCM,data:XxkBTBufVgAdIbAPTVv2d3qjruualiXvWvivBeb4Pix1OUq73GjhKaTiDq885jA0h8q60B8MCkOQI/HKLiw/2rig2/zdxBm+ZYlW8urqODQ2Q9mByGM0dG0ZfaovpoegCF+wR3xUsAu1rwpATPxjSV1JcYq/TwxTllLt56zDsBM=,iv:V12YZJknK92jwO9PYotwKVPMOu/CdAuWVK4TLpZzWpo=,tag:zHy9BQ8lUdDlWbBmK2gQIg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T14:22:20Z"
    mac: ENC[AES256_GCM,data:r9PO2039Bsha5meyl3RpkjoSu5x/LXdJiWDijPUZdaaOngTJ8wUHFNU2Qr4oDHwV3tHv7g8fOURpgq8z28qbOYIOHePNfwUBR7M3p5m6l6y2w9MXEl8e+QdbldwXUoNbCpY7prf8vHsXmSbgwIwZ3qNkBmBxq6X120BSzt6ugSQ=,iv:R/9gxXD1qqjJRrGIDhEXv/A1Wcm9XOpDB2QcSBiX4dc=,tag:xeYwAz6L0ICACFEVJepSKw==,type:str]
    pgp:
        - created_at: "2026-09-27T14:22:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv+OiwujpO3B9rmFyNg3h8jQ4qXyenRJx+bBeF6CCV/yOJh
            c/rwSkeLbz/1rMcgV1UEJDtSxLhXaWlXWr2KSswDEc/sJsMWvPhh8yS43BzWgsVk
            wapQ4GGAJECm2IhY22Gz8OvLmABYRW5mFUTiiAKtwNJ86NdOMavTQvg8bTW3NOPC
            dIsaHVJjmYyoa2HL/fO9rbE6dtScvYs7Pz7pYgMzSgHmXkEb8oZiZCANl3xdSY2+
            Bs+cJ7rxt8m/L3bnVnhllrEqnKIAudQOQvIkHc11J1Vwhl2J+Yhpy0/AWBe5zZym
            r6V1ORxPlKvvC7eRQHmVnGtR9Ny8Bo/uzGcHDCTQ3jvgcVDVBDhis9Va2pLN6xVc
            5kfW7gH2VpAxUCAaxCHUliIX2ItBRoG6MogeXW2zvxW5s2F7uHH3vSnnI8oNpMsH
            FlUc4fi0vhS4yk3kptuag3m5Em//4rce2ZnmnPOwsRaAyHmk987CPwDOURDuvTVT
            XM61BLT4NYrs+o21Ycg/0l4Bp/gu3JJL9fWE7VyAzitscY+gbL35Q5MF9uh6tJOY
            AyGJaDMgylRa6qxus8Rl7bASlJZlfEA+UVMaBU3P8oecGVb8E2bP/U7Uj9oCmW9Q
            CdkzQTlmdV7PLrVZiZ2D
            =EH8w
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.3
