apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secrets
    namespace: vikunja
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:Fc0suAjWtW28BXNAsXY/71svRROGgQPMq6DGYM+vNgHj2wrOC3qBxyra9JoCV1FcXKit3VaHdEz7iwjGPvDM5Ib/vKPGMOmwE35stoOhjXdx0yfwGTz7Qldb8NqGWjnvAVrxgQYQ/8dXtilnd7m5Zw3NDjdsvpq2K16ENqpSGV3AIZ2Q/dcBBr9jNLvo/6INyuocvjSfSoDbqYLa8zMKHU1nv2dNg2s0SVvQtOVRaNlFQGSCViktCw==,iv:MRaiHf0bdb+PVNtJJPy/DuA1mKdxHVrd5DkjjYivBeU=,tag:edACXIIfRnE0dFMv984Cpw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-14T19:17:26Z"
    mac: ENC[AES256_GCM,data:zRgREBrhlvlmviNdeM3HrWaejWuwdXo9keJVJ5VnSvFG/+0aEypYY7FNGQf/P8e+a6az9yvxoJeSEEfE1HDChr+OfI/Q0/2ElEe6rUqT00gipouFakG61wOrtezSjIOOE91IZwoezGlp9WpXLTSSsYpEPLFcu1EyUAyJx4KaDbg=,iv:A+kd/4qx0X6FH4MrDREvBK7Z4iv2JB04KUOxKaj2HKs=,tag:7PIPcpopopQ1Oj4+9iGOPg==,type:str]
    pgp:
        - created_at: "2026-05-14T19:17:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv+O03top7wwW8PhF09JMbh3aDPDPeEVEuYRzNYjnj5lLMo
            1uQ/sPdK/UbWat/dyGAurto6yADhTh69q/LK11Z+I6QkBsmhn7qHbvGdxv6IXWlU
            z6W4Wrt6iPoPKIQlBxqloHmsKi3glGXQhGqxq6XWvQgX4id7HKcZ2noMsKRsQ+OP
            OWusPeL8dW/eAOXZQKAR3t4lrBoQ0nriT3N7kcZw8MIDlSIwryd2ejD/IWiZh0we
            JS32LuNfx3qkC3oyVvxnQ2pphsHKs4L83PRkrhdWIpdEQcPa5zFpV1rtFsPrcsmc
            Xqj6yrjPxsamc45vx35SEJ3Q716xTToffkNJum950kkCcprTfkNIv2n4Bvw4jzXY
            ORzNvvy+Gt6Vm0CFbin+UreYljHsg4gjsetOICJBYAHlrHCW8YUl4KjDZPzMx6nK
            4LOD3mKExAYFk0CJa2UI88szjJzYb7XlGgrr2GZegzI8lOIhydpodLkwXr60hZXF
            V3hWDX49QZYFPWjO2iig0l4BBwAnZ1EX6Eu+BYWEQ1DdW2Hpi4nTRILtYvxtJXqb
            eAYJzfPX5m78Tes6UaIjaNnEjCpKfE8aLBeUbMQhFiD9QrakGUG7S5pBD6lnQGfY
            mWRry9zGrsdXecWGxmty
            =6nLg
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vikunja-config
    namespace: vikunja
type: Opaque
stringData:
    config.yml: ENC[AES256_GCM,data:CsnK9RzWtk9ihey4VvkndZdGFea/jJImGGoQ7C00LwOwyimJvLfq8Cm8G8GCjXYv3XAWZjbhADi/hHIlp4ROsSmtsdyVSf5eaa4WDKCZR+Dsl4EZ64QBYs8CJgnJuZimjervrjkcLASjSEwL27/X2FnxYCNxkDVnT2wIReYAq5PPjaqQ1wB6QS3wMNaWAAQUp+7WSndG6c8as5kdh6X89j04qwr7dAXuNGlDJYz2rTpG9Ym66FYf8HRZb/xGfp5GkFDtgyU6CcXDEryF4WrOZZpBa0u/4c37Ks5GJ663XFaGBP4bHIqmKeI7f1i0l+Qm+vnT9MLnK3Lmabs799cT0b/TItyXCQuDsFny/CQ/1EIJvoU7YxvcjtWzKV8RNKvQvUbYgC79FKr8AIHG3/fBo0Wpr31iMOXelk1Ml0DpIJZGTrIqdHnk3Jk+D6sZUOBQFd+bCreUvlF07k6LJ4khthpq1jVpygN3bZSjYZEyCSDfIoDnkRGI78QIZKcDqFdzuqkjwVmNmh74ZW3DRw6PQQXxDU0AEUCC4TuSeBuZSBWKCA6mgGllER7y5J5fhWXO8QVAAvG0xckuCg0gdD49Ep1TVc7DXBNkpGl5zwhJenWx3HpedJwG6PJLZapYT/tY4l0ZExtV3PHLi07ff/zUjwbcPCei447Ia617yUySfLwQz/zao7CUwX4mwjKHBJtO+TU4RRw9hRc+CzkgbxH9wkbAacHu0V3oSmh32Us6F0Ul+nvdKEtZzFnx71DhhFbv3rhflFtArwY8JEElP6mpeKgk2AaxZzG4bSHcEc6j+lSDa0dtkvoKeopcxO6m4bzQO7+xTe3D4sjmtNuSaX8S3hLiP9wWV0CmFwDmw4SUGESTAz4wMer/f2cwm7/uYW9XBoSmjd5tsap09Wu1ktC4L5qBidJNoQUWMcW0/D2lRc61z/eiuf3hGoxZmUfD+eFnS5nEGeblvoa9+AeXu+8OqUCEVGmoBvUYyw5KZ14wJw51ZX65eNrw99ROWBmMTvGT5W4KRTFTYYoS+33xHpJgmI83UHdhG37F7GdvF2ZhoYqQtaCLirWZrq0KIyCOPm2yMb6K+Mk/OWI/khgtrl8w5upu2lkDSMd5wNqDswN7zBa4SFnO29CPHuR1jKq3PinxCUiAke8Df9lNIiyu,iv:lbX7aib0KC3835Q36gxISILULMvkMGE/5rO47SHm+9U=,tag:M/LtLo2w2nuDDGKsp9G9Mg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-14T19:17:26Z"
    mac: ENC[AES256_GCM,data:zRgREBrhlvlmviNdeM3HrWaejWuwdXo9keJVJ5VnSvFG/+0aEypYY7FNGQf/P8e+a6az9yvxoJeSEEfE1HDChr+OfI/Q0/2ElEe6rUqT00gipouFakG61wOrtezSjIOOE91IZwoezGlp9WpXLTSSsYpEPLFcu1EyUAyJx4KaDbg=,iv:A+kd/4qx0X6FH4MrDREvBK7Z4iv2JB04KUOxKaj2HKs=,tag:7PIPcpopopQ1Oj4+9iGOPg==,type:str]
    pgp:
        - created_at: "2026-05-14T19:17:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv+O03top7wwW8PhF09JMbh3aDPDPeEVEuYRzNYjnj5lLMo
            1uQ/sPdK/UbWat/dyGAurto6yADhTh69q/LK11Z+I6QkBsmhn7qHbvGdxv6IXWlU
            z6W4Wrt6iPoPKIQlBxqloHmsKi3glGXQhGqxq6XWvQgX4id7HKcZ2noMsKRsQ+OP
            OWusPeL8dW/eAOXZQKAR3t4lrBoQ0nriT3N7kcZw8MIDlSIwryd2ejD/IWiZh0we
            JS32LuNfx3qkC3oyVvxnQ2pphsHKs4L83PRkrhdWIpdEQcPa5zFpV1rtFsPrcsmc
            Xqj6yrjPxsamc45vx35SEJ3Q716xTToffkNJum950kkCcprTfkNIv2n4Bvw4jzXY
            ORzNvvy+Gt6Vm0CFbin+UreYljHsg4gjsetOICJBYAHlrHCW8YUl4KjDZPzMx6nK
            4LOD3mKExAYFk0CJa2UI88szjJzYb7XlGgrr2GZegzI8lOIhydpodLkwXr60hZXF
            V3hWDX49QZYFPWjO2iig0l4BBwAnZ1EX6Eu+BYWEQ1DdW2Hpi4nTRILtYvxtJXqb
            eAYJzfPX5m78Tes6UaIjaNnEjCpKfE8aLBeUbMQhFiD9QrakGUG7S5pBD6lnQGfY
            mWRry9zGrsdXecWGxmty
            =6nLg
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vikunja-db-secret
    namespace: vikunja
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:qhBKJniPSA==,iv:iiV3Mt+BGNh22bnkt6A/SG/IBpN8r3qP7XX3TkEWYWc=,tag:kMS0AU72prUK3FdwCylBVw==,type:str]
    password: ENC[AES256_GCM,data:40fNDJQnrNE1On+blS/jhg==,iv:bv2Ylr5VOID2GFRNpDMBwFubFB/eEnNZXpF3m1vJ7R0=,tag:sev5I0QfUaLnOWWmqwfU6A==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-14T19:17:26Z"
    mac: ENC[AES256_GCM,data:zRgREBrhlvlmviNdeM3HrWaejWuwdXo9keJVJ5VnSvFG/+0aEypYY7FNGQf/P8e+a6az9yvxoJeSEEfE1HDChr+OfI/Q0/2ElEe6rUqT00gipouFakG61wOrtezSjIOOE91IZwoezGlp9WpXLTSSsYpEPLFcu1EyUAyJx4KaDbg=,iv:A+kd/4qx0X6FH4MrDREvBK7Z4iv2JB04KUOxKaj2HKs=,tag:7PIPcpopopQ1Oj4+9iGOPg==,type:str]
    pgp:
        - created_at: "2026-05-14T19:17:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv+O03top7wwW8PhF09JMbh3aDPDPeEVEuYRzNYjnj5lLMo
            1uQ/sPdK/UbWat/dyGAurto6yADhTh69q/LK11Z+I6QkBsmhn7qHbvGdxv6IXWlU
            z6W4Wrt6iPoPKIQlBxqloHmsKi3glGXQhGqxq6XWvQgX4id7HKcZ2noMsKRsQ+OP
            OWusPeL8dW/eAOXZQKAR3t4lrBoQ0nriT3N7kcZw8MIDlSIwryd2ejD/IWiZh0we
            JS32LuNfx3qkC3oyVvxnQ2pphsHKs4L83PRkrhdWIpdEQcPa5zFpV1rtFsPrcsmc
            Xqj6yrjPxsamc45vx35SEJ3Q716xTToffkNJum950kkCcprTfkNIv2n4Bvw4jzXY
            ORzNvvy+Gt6Vm0CFbin+UreYljHsg4gjsetOICJBYAHlrHCW8YUl4KjDZPzMx6nK
            4LOD3mKExAYFk0CJa2UI88szjJzYb7XlGgrr2GZegzI8lOIhydpodLkwXr60hZXF
            V3hWDX49QZYFPWjO2iig0l4BBwAnZ1EX6Eu+BYWEQ1DdW2Hpi4nTRILtYvxtJXqb
            eAYJzfPX5m78Tes6UaIjaNnEjCpKfE8aLBeUbMQhFiD9QrakGUG7S5pBD6lnQGfY
            mWRry9zGrsdXecWGxmty
            =6nLg
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: garage-creds
    namespace: vikunja
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:Az+9m7y60DmDoLBYyj9D6HqmMl0arETqIJs=,iv:luJY1X8+9xri3K8DbBuTRlcj7Ez6BgZ/fzFXT0Dpc+0=,tag:9Gzo4dpg6RLQO/1Hz/HCLg==,type:str]
    secret-access-key: ENC[AES256_GCM,data:p9rv3jART3jw2PcDEm0vsRyzr6AW9J4UI8d5smpSRfRGhLg1X4TxSzHULh0xWqaryxSMBktH70U6+Nu0upDQnw==,iv:+0NNvk8lZHH2ow8iBKv2iU4CeKW97vH98fki0EK55XY=,tag:2BIO6wS388GwnlZNYgVi3g==,type:str]
    region: ENC[AES256_GCM,data:fiHVIA==,iv:I2RPU9gCDVBKX4q4QklubBjYjwyjebz+yVrcjUA46PE=,tag:lBG95g4Sfjmyi2LfmPxkpg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-14T19:17:26Z"
    mac: ENC[AES256_GCM,data:zRgREBrhlvlmviNdeM3HrWaejWuwdXo9keJVJ5VnSvFG/+0aEypYY7FNGQf/P8e+a6az9yvxoJeSEEfE1HDChr+OfI/Q0/2ElEe6rUqT00gipouFakG61wOrtezSjIOOE91IZwoezGlp9WpXLTSSsYpEPLFcu1EyUAyJx4KaDbg=,iv:A+kd/4qx0X6FH4MrDREvBK7Z4iv2JB04KUOxKaj2HKs=,tag:7PIPcpopopQ1Oj4+9iGOPg==,type:str]
    pgp:
        - created_at: "2026-05-14T19:17:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv+O03top7wwW8PhF09JMbh3aDPDPeEVEuYRzNYjnj5lLMo
            1uQ/sPdK/UbWat/dyGAurto6yADhTh69q/LK11Z+I6QkBsmhn7qHbvGdxv6IXWlU
            z6W4Wrt6iPoPKIQlBxqloHmsKi3glGXQhGqxq6XWvQgX4id7HKcZ2noMsKRsQ+OP
            OWusPeL8dW/eAOXZQKAR3t4lrBoQ0nriT3N7kcZw8MIDlSIwryd2ejD/IWiZh0we
            JS32LuNfx3qkC3oyVvxnQ2pphsHKs4L83PRkrhdWIpdEQcPa5zFpV1rtFsPrcsmc
            Xqj6yrjPxsamc45vx35SEJ3Q716xTToffkNJum950kkCcprTfkNIv2n4Bvw4jzXY
            ORzNvvy+Gt6Vm0CFbin+UreYljHsg4gjsetOICJBYAHlrHCW8YUl4KjDZPzMx6nK
            4LOD3mKExAYFk0CJa2UI88szjJzYb7XlGgrr2GZegzI8lOIhydpodLkwXr60hZXF
            V3hWDX49QZYFPWjO2iig0l4BBwAnZ1EX6Eu+BYWEQ1DdW2Hpi4nTRILtYvxtJXqb
            eAYJzfPX5m78Tes6UaIjaNnEjCpKfE8aLBeUbMQhFiD9QrakGUG7S5pBD6lnQGfY
            mWRry9zGrsdXecWGxmty
            =6nLg
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.0
