apiVersion: v1
data:
    password: ENC[AES256_GCM,data:ObLb+DUwUkGcZYJwe0Vp+lbjV0YUBXeU,iv:Y0mU/1c59H4p7J325oT4EWhNOWyyicYZRdKqEJWXEH4=,tag:XF29Gjs9y4Dp3bUgrWrhGw==,type:str]
    username: ENC[AES256_GCM,data:zkLTzyQIjPs=,iv:7B16uFIx2hF+d0KXIun+ADDzCjTS4rrhc2TFFQgiBo0=,tag:/XkE4uGsuPWk8EdVBlbaGg==,type:str]
kind: Secret
metadata:
    name: immich-postgresql
    namespace: immich
type: Opaque
sops:
    lastmodified: "2026-01-26T18:48:51Z"
    mac: ENC[AES256_GCM,data:NJi+S6qCLrqIKzNYAtEz9vplQ1rd3UwoaWzH8Rl7PSNIlEeRdkJpACtJVtmBr7F48bmKa95wa+gTAtNju7jbT2smGDl7z5+k7zx0N2KONfbN5wWeHw3fjVGbXuBKXXGl+OeBJQJEkhthTmt3qrXafeTpwTGAEHU/6OuLrdJ/MTY=,iv:yuehO+von772R2S1+J25mvw/KZm2Qag5s/F94H1qtEU=,tag:llQAeWdkj/isxEon4nh8Cw==,type:str]
    pgp:
        - created_at: "2026-01-26T18:48:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQwAqUAdoMIv16gU4zwKOnsg4xl/+eARopklYQzmeJhe/1W/
            iocM6eeR846xt0Icqs7z7XVNo/vZK5e+E5t1r8qnJ3VD4PvUv/Z7U+w6JreyB8l7
            EDcxAwrQ4r1glyP63NIVxThvDQj67pPYraj/nPifaueArs3sdZb0tF8gF8bBM3+E
            NI7TjMimyKY/gLYLIyjnyd1nkDcSehy9snNiBRSAcVISln6uTD7cDNM+qUm1Z3SM
            t+f6bCYGw/rqo4s9aBTz0NCQp79oq21cehlNU23rIZHpD3Qs6dPo/qbHT8JPCIBJ
            X30w0rB7FCevUnh+S6Lr4srmxjHyepd100ChJGr3RxUKKyGtPEizp26SE+eaUASx
            zAXWL4h3wZAXn8CYB6QB7ftmat+L9mJ7/hi9n3YLGSOhscqjzlXP7x4aErL1g2vb
            bEHFLwNU2L+n1mBLeWTD7pTIfmVJYleJ2fGj3Gds/cLGmdi5t6LfBmN8JYZar0e4
            ZLydjvt8sMalA++MO4UF0l4B0axG1AVqZpUg+VsaIEeFIVu1C0Fg8G7zUb/k7u/m
            ey4gxSMJ5HWjdS+2sshJYN8ShMZjtqeo86+VNfUfRlPssEOFChvs78v20tut9F8D
            /FI0pw15kgZ3YVhluAsb
            =eHWF
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: garage-creds
    namespace: immich
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:Fz7QL0Vcp2YHJrkrxf2ZDhDfxZ5vjxVqoNw=,iv:a/9b2nZ8YgG4QfLZ8j41/SDp+4IiaSANNm2oycQLYLU=,tag:ZMUWfv7kQcfJd25TEalqpg==,type:str]
    secret-access-key: ENC[AES256_GCM,data:+uJul26bAwwixMT8L8+lvcYGXTF16Hg/eC0rFo36/8jmaJiOmbqycvWpfJn3Q8TYbCeJTWOq7CVkKdm/afSCKg==,iv:J/OKXQqmcrfC58AxCZfJjvL9S+xF2Ka0M+T8cwdHyG0=,tag:LifCjRLZEDMBIyOVBl7pSw==,type:str]
    region: ENC[AES256_GCM,data:npf1vw==,iv:8dkcj7LMUMPNUcNzgxqA1kMmla+ViLZGP7cIWxHS1lA=,tag:1uYfaM+okCN3dZoP0xC/kA==,type:str]
sops:
    lastmodified: "2026-01-26T18:48:51Z"
    mac: ENC[AES256_GCM,data:NJi+S6qCLrqIKzNYAtEz9vplQ1rd3UwoaWzH8Rl7PSNIlEeRdkJpACtJVtmBr7F48bmKa95wa+gTAtNju7jbT2smGDl7z5+k7zx0N2KONfbN5wWeHw3fjVGbXuBKXXGl+OeBJQJEkhthTmt3qrXafeTpwTGAEHU/6OuLrdJ/MTY=,iv:yuehO+von772R2S1+J25mvw/KZm2Qag5s/F94H1qtEU=,tag:llQAeWdkj/isxEon4nh8Cw==,type:str]
    pgp:
        - created_at: "2026-01-26T18:48:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQwAqUAdoMIv16gU4zwKOnsg4xl/+eARopklYQzmeJhe/1W/
            iocM6eeR846xt0Icqs7z7XVNo/vZK5e+E5t1r8qnJ3VD4PvUv/Z7U+w6JreyB8l7
            EDcxAwrQ4r1glyP63NIVxThvDQj67pPYraj/nPifaueArs3sdZb0tF8gF8bBM3+E
            NI7TjMimyKY/gLYLIyjnyd1nkDcSehy9snNiBRSAcVISln6uTD7cDNM+qUm1Z3SM
            t+f6bCYGw/rqo4s9aBTz0NCQp79oq21cehlNU23rIZHpD3Qs6dPo/qbHT8JPCIBJ
            X30w0rB7FCevUnh+S6Lr4srmxjHyepd100ChJGr3RxUKKyGtPEizp26SE+eaUASx
            zAXWL4h3wZAXn8CYB6QB7ftmat+L9mJ7/hi9n3YLGSOhscqjzlXP7x4aErL1g2vb
            bEHFLwNU2L+n1mBLeWTD7pTIfmVJYleJ2fGj3Gds/cLGmdi5t6LfBmN8JYZar0e4
            ZLydjvt8sMalA++MO4UF0l4B0axG1AVqZpUg+VsaIEeFIVu1C0Fg8G7zUb/k7u/m
            ey4gxSMJ5HWjdS+2sshJYN8ShMZjtqeo86+VNfUfRlPssEOFChvs78v20tut9F8D
            /FI0pw15kgZ3YVhluAsb
            =eHWF
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: immich-restic-config
    namespace: immich
type: Opaque
stringData:
    #ENC[AES256_GCM,data:1Mkaa2qdWoxKEgBIQwN6eRjNEn5UPJPPPG6W4Ctqb8scCDI7uYEHdMLga7RxP1NQxug94EKVa5FkZRaVO+g6vzE=,iv:P1soC5saSVM9oVFbQnQd2AkULdphdeu/jgrRKcsVj0M=,tag:hQhcMR/lEvpiWaXSnLBF4g==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:xz4WNrYO8kbvEX7OZ+js1cGNginoluzAT1nUhax/zU76vLT0KhRSrWhR/aKIhQ==,iv:iD3fi97fJKmkJDIeaCc4siwG6s+FoQXXM5cQaBnxBi8=,tag:8srC/RL3SbfX9Z02B5f10w==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:faSeO7QfIODs5IHMJQ54atl15EdPiDwMN2++aljtTTVHSc5/ZfAnowEWwONMyjyV,iv:0/jZad7lzbUkxf63KgjPJBQKaWytjPVwx3St7d8yDrw=,tag:jDQDCs1MoBNy0A94yPY/zQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:lcPNIZz0JEtJVbgVyDbrgpGfTxZ1osLEpik=,iv:ZdkU+ljwmq/ecEf1XkackdERq+0JJcpeWqlLKlHYFYE=,tag:tvQBM7JHPYT7r59H3o9LAA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:5noepwsGc6JuV99OYSFqm+FTtiLGnRBnqjLgBQMeClMlvKuWUkSLrhQBPMtxRaKe5VHrfRR9lg+8i511PzaiXA==,iv:tY1ofJLxHVXxm7GUbvAHgNiO/oJ/6eVrl5E7vh7lsrE=,tag:HYWZ78hig6pyF61fu3lLVA==,type:str]
sops:
    lastmodified: "2026-01-26T18:48:51Z"
    mac: ENC[AES256_GCM,data:NJi+S6qCLrqIKzNYAtEz9vplQ1rd3UwoaWzH8Rl7PSNIlEeRdkJpACtJVtmBr7F48bmKa95wa+gTAtNju7jbT2smGDl7z5+k7zx0N2KONfbN5wWeHw3fjVGbXuBKXXGl+OeBJQJEkhthTmt3qrXafeTpwTGAEHU/6OuLrdJ/MTY=,iv:yuehO+von772R2S1+J25mvw/KZm2Qag5s/F94H1qtEU=,tag:llQAeWdkj/isxEon4nh8Cw==,type:str]
    pgp:
        - created_at: "2026-01-26T18:48:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQwAqUAdoMIv16gU4zwKOnsg4xl/+eARopklYQzmeJhe/1W/
            iocM6eeR846xt0Icqs7z7XVNo/vZK5e+E5t1r8qnJ3VD4PvUv/Z7U+w6JreyB8l7
            EDcxAwrQ4r1glyP63NIVxThvDQj67pPYraj/nPifaueArs3sdZb0tF8gF8bBM3+E
            NI7TjMimyKY/gLYLIyjnyd1nkDcSehy9snNiBRSAcVISln6uTD7cDNM+qUm1Z3SM
            t+f6bCYGw/rqo4s9aBTz0NCQp79oq21cehlNU23rIZHpD3Qs6dPo/qbHT8JPCIBJ
            X30w0rB7FCevUnh+S6Lr4srmxjHyepd100ChJGr3RxUKKyGtPEizp26SE+eaUASx
            zAXWL4h3wZAXn8CYB6QB7ftmat+L9mJ7/hi9n3YLGSOhscqjzlXP7x4aErL1g2vb
            bEHFLwNU2L+n1mBLeWTD7pTIfmVJYleJ2fGj3Gds/cLGmdi5t6LfBmN8JYZar0e4
            ZLydjvt8sMalA++MO4UF0l4B0axG1AVqZpUg+VsaIEeFIVu1C0Fg8G7zUb/k7u/m
            ey4gxSMJ5HWjdS+2sshJYN8ShMZjtqeo86+VNfUfRlPssEOFChvs78v20tut9F8D
            /FI0pw15kgZ3YVhluAsb
            =eHWF
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
