apiVersion: v1
kind: Secret
metadata:
    name: immich-postgresql
    namespace: immich
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:nF21U8Tv3S4CV/GOx4+Xuw==,iv:S0f7Fn+fIGlQcesccr7zlFxiMOzzT8W1Vs9YEOxOwn4=,tag:+68bwsIUsI2andICpSO6QA==,type:str]
    username: ENC[AES256_GCM,data:M0FqlaFn,iv:qyNqgleuch6bYrzA+VYuPxLs4Trf6qmSY0gqMO8REEM=,tag:dmkAYdQtNiB2yPez1OufzQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T17:14:16Z"
    mac: ENC[AES256_GCM,data:BB2RIWlmBbkArTCI6mZeyS1kJS3tqdsQQ/75AVLLPh4nvcd9f3TbKp52IQTjYLlFoT19tjVBf6niOjb1uIpRmRqcFfWzJnDHOzZ/8TPWI8aCMosCH3zWV5zZxIkNokywa+svDzy2osB/A/iLDYNrutjPbBVhSeJy0wFsOy5q5qs=,iv:JgiMAVgpYEpV6b6ceU4T91S6iJe/+At/9iFMRXiHB8c=,tag:ulWWqrh2H8htW0IuKv7Y1g==,type:str]
    pgp:
        - created_at: "2026-07-03T17:14:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/SwyMdLB/HGRGNvjnwMboCcNUqzLjB8Tvr95vghlHN/IY
            JZZM++wcLKHpbp15raPenWagHqAhK6KGEYc+5gRVuQLlecabSrJ/58qVazexGDj5
            JP4+NmfCrrbSxcVrVmQ6U7lu9uStBY+FtSR8oBMTaHOxRWC7iywUiJ6hgMEFJIrw
            aGuLmVficNtu62el8N+RE9IylX8OYkd9437rrHmAgAoUWMxBcnjcBzDNUDDftNJU
            y0bWVPtnMxCbfIaFG2IQhDjMOR7q9oSR0mARtYDGUcF0l2xybWi/zZgZoVvG4H6A
            Rhm8lf4SHOas6zN5IcrB6l7xTi6sjSWR+WbwvS8IzY8cL3/qqzNlMrpVqx3hnWg4
            GZl0Il1CFYT7TzbkJJVKuAO47F7PVf8ic/Ave6fx8jXu+0rt63mM6EyS36iki1wP
            TRqJWcUJJHh3UVf97YDpBLX+xgkKsTqvBlah3D9L+i7jzfOp+GKOPq0bnIDCziyh
            0MM8BXrdeBDnpH6mZ7IG0l4Bi9/DEFtiFrArH/jHNoY93150ya+6H2oBSBF2E66t
            lLvgxhu0yvjSMaREL/8w8TctDxvtrOaEok1Kw03tdH4w+PBq48G7R5viZunIYHdZ
            z/YqXMt7pMWMXO2F+TRy
            =car+
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: garage-creds
    namespace: immich
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:E+tM9OZRZuAJrGuZd7XuQRSJundX6YDiuJ4=,iv:qENXu0wcKNHjCBqSU1yOi59jgZP9zNRy6zHAEdry3t8=,tag:BFBwtqKnuRqd9zYYShAZ5Q==,type:str]
    secret-access-key: ENC[AES256_GCM,data:fs8zzKfjJFMvNQzqeNaudLYLOm85XTrZ9h3HpzRtleKVZ0itznIRbz5CDm8x6N4FzzD5WXmzAtt0ztJJE5QFUg==,iv:kyzF/UkYBZHjdzV4tKuO06buQvF4ANRaSXjFyAre0gk=,tag:ExYWWhaOXwevS4va4BHRmg==,type:str]
    region: ENC[AES256_GCM,data:aoJS3w==,iv:TiT94rqfAIYbTo0jgm43Y4oohkoaikpr8CimAjKQrrU=,tag:Bsr/wiwJrXF+A/S4Y0Ppdw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T17:14:16Z"
    mac: ENC[AES256_GCM,data:BB2RIWlmBbkArTCI6mZeyS1kJS3tqdsQQ/75AVLLPh4nvcd9f3TbKp52IQTjYLlFoT19tjVBf6niOjb1uIpRmRqcFfWzJnDHOzZ/8TPWI8aCMosCH3zWV5zZxIkNokywa+svDzy2osB/A/iLDYNrutjPbBVhSeJy0wFsOy5q5qs=,iv:JgiMAVgpYEpV6b6ceU4T91S6iJe/+At/9iFMRXiHB8c=,tag:ulWWqrh2H8htW0IuKv7Y1g==,type:str]
    pgp:
        - created_at: "2026-07-03T17:14:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/SwyMdLB/HGRGNvjnwMboCcNUqzLjB8Tvr95vghlHN/IY
            JZZM++wcLKHpbp15raPenWagHqAhK6KGEYc+5gRVuQLlecabSrJ/58qVazexGDj5
            JP4+NmfCrrbSxcVrVmQ6U7lu9uStBY+FtSR8oBMTaHOxRWC7iywUiJ6hgMEFJIrw
            aGuLmVficNtu62el8N+RE9IylX8OYkd9437rrHmAgAoUWMxBcnjcBzDNUDDftNJU
            y0bWVPtnMxCbfIaFG2IQhDjMOR7q9oSR0mARtYDGUcF0l2xybWi/zZgZoVvG4H6A
            Rhm8lf4SHOas6zN5IcrB6l7xTi6sjSWR+WbwvS8IzY8cL3/qqzNlMrpVqx3hnWg4
            GZl0Il1CFYT7TzbkJJVKuAO47F7PVf8ic/Ave6fx8jXu+0rt63mM6EyS36iki1wP
            TRqJWcUJJHh3UVf97YDpBLX+xgkKsTqvBlah3D9L+i7jzfOp+GKOPq0bnIDCziyh
            0MM8BXrdeBDnpH6mZ7IG0l4Bi9/DEFtiFrArH/jHNoY93150ya+6H2oBSBF2E66t
            lLvgxhu0yvjSMaREL/8w8TctDxvtrOaEok1Kw03tdH4w+PBq48G7R5viZunIYHdZ
            z/YqXMt7pMWMXO2F+TRy
            =car+
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: immich-restic-config
    namespace: immich
type: Opaque
stringData:
    #ENC[AES256_GCM,data:tWKBZol9VapAPJsQeWeZSgFxAMOfScmxocGdY3rQjy3bRKkND9IMtsRtXOudZ44ODm45sGoXuswrIbpN+egLt1I=,iv:vN58dGOtqM30lvO8D//qjokLcHUHTNt2gDmWOieRSNE=,tag:4QQzpn/fvpTJyCFkUs0Weg==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:ltb9ZEdMLJu8ucKzjJaCSnlu0+UlWyzOPEhThpDXRsMJ6asjxlBBzny58oyAyA==,iv:IGicpJLKnnGiKiG7zAYIGfgX6EXogzs5QLFN3T/7fHw=,tag:WDRjsG9bSM8VCIqEZyK5Yw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:pFXUg+K53r7AuAvBIeH+dit6uVDuzyT0a2LgaluaquOSF0wXJCYifA900AgqKOhf,iv:JlVLRHy8Xpr8hyW9+6vZ/Le2ZuZK0GS4EpIdNf7ALdA=,tag:O/+jUv58cb4F/nLMwUVKrg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:qubXdIB+EjJPK2EmMyexB55xbfFiklYbRDM=,iv:rHgXbeV2Z255Rkn1t14jbPl+w2TrL5qixXK9OiWcbVM=,tag:jiWrGzSi3NcKo3jZEBzrig==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:NIXxgHzrTdUzJslVbwiuWvjd13rGWoVQoiXUhcTr6NdYs+p665r9xZ/iFXef05rwVqSsgpuNRWndNopHFc5PFg==,iv:pCa+PEYxKZU9UtQwtT0o3h3+UjPeMmZohPs8LkzAmQE=,tag:rldnTc3ueUQyW3y6ow/OzA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T17:14:16Z"
    mac: ENC[AES256_GCM,data:BB2RIWlmBbkArTCI6mZeyS1kJS3tqdsQQ/75AVLLPh4nvcd9f3TbKp52IQTjYLlFoT19tjVBf6niOjb1uIpRmRqcFfWzJnDHOzZ/8TPWI8aCMosCH3zWV5zZxIkNokywa+svDzy2osB/A/iLDYNrutjPbBVhSeJy0wFsOy5q5qs=,iv:JgiMAVgpYEpV6b6ceU4T91S6iJe/+At/9iFMRXiHB8c=,tag:ulWWqrh2H8htW0IuKv7Y1g==,type:str]
    pgp:
        - created_at: "2026-07-03T17:14:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/SwyMdLB/HGRGNvjnwMboCcNUqzLjB8Tvr95vghlHN/IY
            JZZM++wcLKHpbp15raPenWagHqAhK6KGEYc+5gRVuQLlecabSrJ/58qVazexGDj5
            JP4+NmfCrrbSxcVrVmQ6U7lu9uStBY+FtSR8oBMTaHOxRWC7iywUiJ6hgMEFJIrw
            aGuLmVficNtu62el8N+RE9IylX8OYkd9437rrHmAgAoUWMxBcnjcBzDNUDDftNJU
            y0bWVPtnMxCbfIaFG2IQhDjMOR7q9oSR0mARtYDGUcF0l2xybWi/zZgZoVvG4H6A
            Rhm8lf4SHOas6zN5IcrB6l7xTi6sjSWR+WbwvS8IzY8cL3/qqzNlMrpVqx3hnWg4
            GZl0Il1CFYT7TzbkJJVKuAO47F7PVf8ic/Ave6fx8jXu+0rt63mM6EyS36iki1wP
            TRqJWcUJJHh3UVf97YDpBLX+xgkKsTqvBlah3D9L+i7jzfOp+GKOPq0bnIDCziyh
            0MM8BXrdeBDnpH6mZ7IG0l4Bi9/DEFtiFrArH/jHNoY93150ya+6H2oBSBF2E66t
            lLvgxhu0yvjSMaREL/8w8TctDxvtrOaEok1Kw03tdH4w+PBq48G7R5viZunIYHdZ
            z/YqXMt7pMWMXO2F+TRy
            =car+
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.2
