apiVersion: v1
kind: Secret
metadata:
    name: searxng-secret
    namespace: searxng
type: Opaque
stringData:
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:nr2U9Pdyt9ynjaU=,iv:CvhFDmqOLj7U5D8m4s0icN01OoA9W14HF5kM3wYWMFQ=,tag:W3w1WHsGnMKwIHsM6YKFXg==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:CrR9eok=,iv:00lvwsM7Mka0o1+cCK008XQ/0wUJiXcV1p1/aJu6ZiU=,tag:9xqi0ye+kT3sXm2k0HxS1A==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:qaM/kKnRuBzvlpwnsDcPsGh22AbgH4PbETYRSG92a7PQMb8gd4vO5yB3TjY=,iv:q2mxHojX8e2uYPmtLjNIJRubgzndiXWy0RDAil3pPwQ=,tag:Dw0ciw5lZASYacub/KlGaA==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:CVIMx5qEMnvJ/nRpSen02rIgXffWVP2e9b8CoJ1obMroxWnt6AojASAwu4M=,iv:/2MiRTMVt4UEPIcFT9aJhU+/QJ0bZvL0eM8Mjo371P4=,tag:fNnAFwxhA0dnNmDO1FHlUA==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:D8GpL6xvyQ0ElyE=,iv:YYL6s03yn4YRsoxHLonou/xc6k/Q7TH5t4ico8ycmjM=,tag:ocqiaCro+JL5UoedTJW3yg==,type:str]
    SEARXNG_SECRET: ENC[AES256_GCM,data:1W383e/lxsxeD9zy7M7wbsOVOTUwfe76SpYOrGal8zBE0euGXQJUECAahvh6oqzx6PyVTmH/nLPJdeysA6x5hQ==,iv:xqbiiGSXv3tT+0bi6mT0UcnZ7OY6uYHubx/eRxiCtFw=,tag:Lxr+6T93HHcnZgAaQl0XYQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T09:56:26Z"
    mac: ENC[AES256_GCM,data:isuEqMvkh61zmV+UuxPDs7ff+GD06KRrvbkH6Ia1jo7FRuD141uUilwFk3JIDK5HMKqlfR8xCrzW4sROyoNmTCAfyro7JQFsRS3CGYL2l9KXvVBfIsRJNkYXR+xtSvsRux5s7dJxc6HH0JHbMVyyXxyyCvkWnuk6RHsU/RW4w4w=,iv:110xzGwiWrCC5ambi58Osyren5fc4tmkZ1pHB/Yjglk=,tag:65BpmNiUpVJK6q0qZ/JNpg==,type:str]
    pgp:
        - created_at: "2026-09-19T09:56:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv+JbexgTJISmQBsdA6mauykhld17ZILKe1gPHt0dAapjko
            7SoXbTR5JmL1GDiz46RqlTP8Ox9/Ej/+bpxHxcJaeQBqwJtvxHchHyEpBpNWr0bu
            xX3lv19CD6qPLGzShznsGQtBd5GvP7rPgdriIhCKoKlkpdDNMAvVFPt15ySHstjK
            J33QzuWmwyhqu5WlbaAxKRQB5CaWToiiWb7zWyoqCAZ0jVoWZLzrmqE04wUKDSXP
            pThURawXFVPfxv8E+/i1Z6/c+5CTh/brjN/O6OQAjLaMbq6meg4IPis2RW/zzSwW
            gJv2nq5Ce2It75gd8fVUo7jr64qvOqhZi8ySwQaAVgL+r6HJv2ualBLXzIYTm/0W
            YzvE4pYBVvCZZTLrPBUExDOdMMVJdvI8sU00wc0GLglMlj3hAgvpEjpm5DhduP1v
            z6LtvgGNurXMy6AXe9/XC+RBECJvrxxa4uqeLZhFreH4c/JfGTTch4XAdmzXegek
            XqumCPlUqstGzD0JLqrS0lwBYoEEPRfTu0CVnCJNhcgzEWRY6TgUzfZuWA92rlFN
            dYo9d2QXE+KsQo41n4ZTQ/F7igXoRsvQRKdfwT0Stj7XZfgIkk2pVqOreZOPWDKu
            Ygg7jtGOKPwq7Tafew==
            =Q/wd
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.3
