apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-tls
  namespace: cert-manager
spec:
  secretName: default-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - "*.k8s.exmaple.com"   
  - "k8s.exmaple.com"     
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "gameserver,actual"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"