apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-webhook-hetzner
  namespace: cert-manager
spec:
  interval: 10m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true 
  chart:
    spec:
      chart: cert-manager-webhook-hetzner
      sourceRef:
        kind: HelmRepository
        name: hcloud
        namespace: flux-system
      version: "0.7.0"