apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:e/tS9H390gjs6rEruXA3T7ckogiu6eZezasZIwmr8dj0YqBfPrmZFreV8w+CSmDG1Td7Q+ZbRtc=,iv:RARKtueezqjkPu5y5Xfp7p2hiLOs/jHTUPx3aJxy0Gs=,tag:bQ4ZeZcS9iPs0X8ztQ3B8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-16T18:39:51Z"
    mac: ENC[AES256_GCM,data:1hfRXe/xmYB6xaZ16pP+poJFo4QBRgzJAtC5AnYhEsfS3HVBLUXKw0GdYQln9EcCl4DM+9rUP3gjdGPicS+O3+s+HugDwefM2MIBmfOkccbqsMV3p+g0f6eIVDYfvIpVn5mKnl5SFmm4ia0rfViMSsr8dffHEQHG84mmmX9BRUE=,iv:DPF3Pn2MNFA4hkjV6fNMSHlqX7OjYyBHWdcLWDJYT3Y=,tag:5mJAKd7rOFn9aEJXNvMQWA==,type:str]
    pgp:
        - created_at: "2024-12-16T18:39:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv9Hvou+zOI0fBU6D1+HfL56U9FcIGUsLAh5uRkzWb0aIDj
            ugEueXFLG8HMxGVM6UqyFf4tDceVtm7nzqQNkdJJ8msJhz8RpbFlp5RAUt1jr5Bl
            x3w6Uco5p8DiIH2Fkxbttn6HJmElQ9iqZu0xsS8s9gsi3O+elawG9Kn+L350Bqm1
            PfV8qwig15YBl31nmIixcHjFcnpqBGyOGrbEhxAHQO84MhmuUcyu0UYLztsAqaA3
            fZzuFEUVoPxaBLsPIm2Hk49kdiGDiWUC5PinURIc7yeGSOwQ1Xaq89AB8no/1YLf
            YIFsv4NriQ8gpaBiME4HJZ0fd4yLZPxrsTprWADE958Tm9/I6jLaNupLwpdA0ZuV
            gsoGPu4Lb2Q32mqnKDQWVlB4PsVGgLt1kGkRlzJczVSj5d2bSzgvsrAuncqBrZai
            WLO7HbCy7JlgZG1bXXl2Dg0XlfCfO9CgrSc37wwz4aF3cGSIXY95MXhdv9M8PO5G
            qFWqnxM8ymlPSDOWReAo0l4BuOhXCqFDh42reSHi6YILHajT0t1T9hICLwLflQgT
            VMZjvZaWV+m6BfLn2SbpIJdKcg+jdKicpa3Xu9buzSvyuNDDSrD68cW2wJ2S+WP7
            zPRthRfHe46zfbv6mTbw
            =Jw8t
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
