apiVersion: v1
kind: Secret
metadata:
    name: hetzner-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:7McvDyM6BXzgJO6NGckaFMRe4HUaT891DUsp7UmYIvQtwQp2cGlf62lnSp3aCnvjM9iFXLRbEIQXCR7iuxo2GA==,iv:hMLhChhjqfJg3heaCeW+7N2z7at51PGg/cMI20q6oBw=,tag:wnMTmsVOEQNAd7jvdrewFQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T08:58:08Z"
    mac: ENC[AES256_GCM,data:QZMdgUTFpkAEU2NIKY74qt7cyKADctmP7lS0Dku0QnfbTSeeN6LPVCURfCJLwIOnT7QVE9UgsEfoBUFVjdxTuVlYa55Y3VOnOIIUKfO0xWk3mRkP+nseNIJ5ymOUOrB4h9JFQZrVEeX29oyJBB5/uoPBtY80/6kmzW0Te57ERcw=,iv:ZiHT1EAEeqz7n3wB3ifj8NNqhdwsQOipmct0yqGUGdI=,tag:bS2cmZUPcFwsUWnaqFctuQ==,type:str]
    pgp:
        - created_at: "2026-06-04T08:58:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQwAhzse+3bU2v7ptGhdCGgmvE5zY+6ydSjwcZBQOx5ws3K1
            Ubz030z9tEv0Kkx/7XKjgt8zpzneTGBGQq+G+IpdzS1IaL0cvki1EQH6NdqI49iq
            64EX83WKg6GlwOci6SuThjLbNK/WbXzybx8uN/NAqksI1vXMxmNEDLnfUKS9v2aA
            6shGJ9aoKWhBW3jKxcazFV6ZVp2Vb9uDyYA/9ISQKu1sb7GeIA2jAId1EYa1ry5u
            0YKw5RrfwYJeXTDfu8aYofgiji+tOPj22KMM6Zus2mOle/0iC2/F2bXesETEVAht
            AeUrXEv2oLqBCaRsvmsJcX0VNK89p3UN4tep1sy1dbDhOdrRXJa0K6zh7UmKgjWk
            8T++IJPKhGlpt08b83q5szRU3dNQOOgKMc+xMw+8MvtceHkkclu3G+7CQwB50wL5
            rg1xj0X8mIJU8A0wtCF3WmthCyuxhk/cS6EZrZuPVDO3flb0yU34Y3IKFPf+6pxI
            Fvq6fjgFI67KW4ghNmoO0lEBg3cQPV5O4W8p39/T5HtUKSHg2fFfOoNq5pL+Z9wj
            NeKocKF1/pGQHfQxZgCVXsHNmopYih1TabUjDDRSTgSemA5n56cFU4SUBXCNkcxj
            nWk=
            =BMEw
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
