apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: grafana
spec:
  interval: 10m
  valuesFrom:
    - kind: Secret
      name: loki-secrets
      valuesKey: values.yaml
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true 
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: "7.0.0"
  values:
    deploymentMode: SimpleScalable
    loki:
      auth_enabled: false
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h

      storage:
        type: s3
        bucketNames:
          chunks: loki
          ruler: loki
          admin: loki
        s3:
          endpoint: "http://10.50.0.30"
          region: ""
          s3ForcePathStyle: true
          insecure: true


      ingester:
          chunk_encoding: snappy
          chunk_idle_period: 5m
          max_chunk_age: 1h
      limits_config:
        allow_structured_metadata: true
        volume_enabled: true
        retention_period: 4320h # 180 days retention
        tsdb_max_query_parallelism: 16
        split_queries_by_interval: 1h
        query_timeout: 5m
      querier:
          max_concurrent: 8
      compactor:
        retention_enabled: true 
        delete_request_store: s3
      ruler:
        enable_api: true
        storage:
          type: s3
          s3:
            region: local
            bucketnames: loki

    chunksCache:
      allocatedMemory: 2048

    resultsCache:
      allocatedMemory: 1024

    minio:
      enabled: false
          
    gateway:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: "cilium"
        hosts:
          - host: "loki.k8s.exmaple.com"
            paths:
              - path: /
                pathType: Prefix
        tls: 
          - hosts:
              - loki.k8s.exmaple.com



    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
      retention_enabled: true
      delete_request_store: s3
    indexGateway:
      replicas: 0

    bloomPlanner:
      replicas: 0
    bloomBuilder:
      replicas: 0

    backend:
      replicas: 2
      persistence:
        size: 5Gi
        enableStatefulSetAutoDeletePVC: true
        storageClass: csi-rbd-sc
    read:
      replicas: 2
      persistence:
        size: 15Gi
        enableStatefulSetAutoDeletePVC: true
        storageClass: csi-rbd-sc
    write:
      replicas: 2
      persistence:
        size: 25Gi
        enableStatefulSetAutoDeletePVC: true
        storageClass: csi-rbd-sc


    singleBinary:
      replicas: 0

    lokiCanary:
      enabled: false

    test:
      enabled: false