apiVersion: v1
kind: Secret
metadata:
    name: influxdb-auth
    namespace: grafana
type: Opaque
stringData:
    influxdb-user: ENC[AES256_GCM,data:wjm+HjMg,iv:jgzAcOF+9/hrep84bB7IL3/UaD0Ui+WiCYFB0LlD6C8=,tag:sFvOOHGo1wKYO75mH2ZRZA==,type:str]
    influxdb-password: ENC[AES256_GCM,data:G3En/RPetPEboWXo1t5zRnNL,iv:TgE/vXRmdsrL9Qo+XK2B0rjovPzgri2OY9Oo3TgWaoA=,tag:gg85RiRWtP0lcTRZtrcIrA==,type:str]
sops:
    lastmodified: "2026-04-25T16:53:07Z"
    mac: ENC[AES256_GCM,data:3/VrZfzsVru44d6YUDtqRVqMniHi2POWTu3lGigE4RQp38Er4CYK53zAPyJi5egmauGXB3aPhmDyJrkZic1evxKfWY8PmRL5XfEtLlMr5IPNGBqPNDnN7ciXCBlwBMpWBRJuDuWWObEYdPmNXLtzIalidkfDEdn0k2+nDYXpQRk=,iv:bWluTbU6j0aKIOvRvweSTRVwTHOde2KZ5/O4WvuvPp8=,tag:e6Bk0rIWNODBuAQ4paCeWw==,type:str]
    pgp:
        - created_at: "2026-04-25T16:53:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/UkVVzYr3IkoY0+iHG+jEZ0bAFud9A6jiQt9Qa7eyDQF8
            ZsMTuBGrYiBWAsiWkHSqoeJBq2MS/Uu+uDnWcZk1c/GNNPZrEztXmhLbajvdnvAU
            sR4eIiJv98+b78yKzTf08f9t4iLPjnTJnO3nk3wUb8HYVGJ4nYuLqZaj0Du6H5vF
            aDmLDvNwu2HQwNnSJBJ9vOt8FHkITYwiKXXNxoInKAxB8/tpXnTC6h81R3nFAVNF
            trAl2MAjuKVrhhkD6NOwiboGaydIx2LCn2HVyOM09gVQFscAwmvgFbKFsXLbF9Bk
            S6U/1nPBJ3RuIRg8zCwa7A2+UC+DFUA89oXQXCd3XtqFKr4wnKLQGcW6M+baWBQx
            kdc5xPuz4Z7f8rMY3/T7LwUlY/lvAG/MPV1UVHTWuofZqxVgAyuRcfH2mTpf8lIu
            ExPFcyrDe4V2xK4adUyzh5Ag+ZCMIvsR7esXcNrueW1i90obFjjfZqmugAaQnKXK
            JMSXJby8qDBk3BlO20Bo0l4BeXlEahTgVB+2kXL7CKnqcfnJunlR+GksewrORXB/
            KSNmFk+6uZvO2C/4D/QF7ppoO9L0wXLz5NYP4+DMNkgHlV5bdprN1FwWmdJXRWiE
            26rCZ9YINHkzfWUu/tBn
            =/JBc
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: influxdb2-auth
    namespace: grafana
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:0d8rRPpHXJJ5uan+sdkG4kGN,iv:wSZU9hthKnBTf5zzxitX2WlWCWNrohNQl+X3KqITY40=,tag:YC7qwC+lwawaCkucHBaeVw==,type:str]
    admin-token: ENC[AES256_GCM,data:hWn4dk7T38rqBcHbjVhK3WIV,iv:aWdH0Pl0HldFn2UViobRuhMHIQOyLNnL/WjOdbmHSzw=,tag:wwSVp5NSDHbyM+AMyh7RNA==,type:str]
sops:
    lastmodified: "2026-04-25T16:53:07Z"
    mac: ENC[AES256_GCM,data:3/VrZfzsVru44d6YUDtqRVqMniHi2POWTu3lGigE4RQp38Er4CYK53zAPyJi5egmauGXB3aPhmDyJrkZic1evxKfWY8PmRL5XfEtLlMr5IPNGBqPNDnN7ciXCBlwBMpWBRJuDuWWObEYdPmNXLtzIalidkfDEdn0k2+nDYXpQRk=,iv:bWluTbU6j0aKIOvRvweSTRVwTHOde2KZ5/O4WvuvPp8=,tag:e6Bk0rIWNODBuAQ4paCeWw==,type:str]
    pgp:
        - created_at: "2026-04-25T16:53:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/UkVVzYr3IkoY0+iHG+jEZ0bAFud9A6jiQt9Qa7eyDQF8
            ZsMTuBGrYiBWAsiWkHSqoeJBq2MS/Uu+uDnWcZk1c/GNNPZrEztXmhLbajvdnvAU
            sR4eIiJv98+b78yKzTf08f9t4iLPjnTJnO3nk3wUb8HYVGJ4nYuLqZaj0Du6H5vF
            aDmLDvNwu2HQwNnSJBJ9vOt8FHkITYwiKXXNxoInKAxB8/tpXnTC6h81R3nFAVNF
            trAl2MAjuKVrhhkD6NOwiboGaydIx2LCn2HVyOM09gVQFscAwmvgFbKFsXLbF9Bk
            S6U/1nPBJ3RuIRg8zCwa7A2+UC+DFUA89oXQXCd3XtqFKr4wnKLQGcW6M+baWBQx
            kdc5xPuz4Z7f8rMY3/T7LwUlY/lvAG/MPV1UVHTWuofZqxVgAyuRcfH2mTpf8lIu
            ExPFcyrDe4V2xK4adUyzh5Ag+ZCMIvsR7esXcNrueW1i90obFjjfZqmugAaQnKXK
            JMSXJby8qDBk3BlO20Bo0l4BeXlEahTgVB+2kXL7CKnqcfnJunlR+GksewrORXB/
            KSNmFk+6uZvO2C/4D/QF7ppoO9L0wXLz5NYP4+DMNkgHlV5bdprN1FwWmdJXRWiE
            26rCZ9YINHkzfWUu/tBn
            =/JBc
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-creds
    namespace: grafana
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:8JxPJv4=,iv:MfEXPburhpGOujMsVFz0aQtLQtZIospyGX0orq14Fjo=,tag:2BlU2b3OshJXc8PfLHxjqg==,type:str]
    admin-password: ENC[AES256_GCM,data:zI+ErFVH1S5QPL94NPU=,iv:7PbQJ4sXViroQaKqQqeGoNcucomALeC+tgT7Fdp30QA=,tag:1P1BHs/JN7unk+m4KpggaQ==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:vbIAKLAVY8Mh1Fox55m2L69GAZUVNIld8zWSL1nP6NHJBsVeRr8z7g==,iv:cgziMS8LFz7zxLMDyUubLKnCrDjG/vnv2/xCK5DqQNw=,tag:Zp0MOXtEaLYs25bESMy/oA==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:kgRVhDRHSrx0Z8QEwbKp/vmlzs7MDzXpLpbwbFxjzIqSBrkAubVtu6gWBaOmn2FBmEeNaKprpsAsrLSPsprH+ZGWV8Gqi4kRWOHwzMNCZkwH5PoN1L+NgbZ/0vGk+b+XOyO8XiR4LdIanJ0quRkYH65CXudWtktC4LQEN1Bb6rs=,iv:v7OUuJ2z2HirBmGXdePOLs9kBPE9YuOxAsrvwRU4IxE=,tag:j4HQWKlvR87y6f5r/O35/Q==,type:str]
sops:
    lastmodified: "2026-04-25T16:53:07Z"
    mac: ENC[AES256_GCM,data:3/VrZfzsVru44d6YUDtqRVqMniHi2POWTu3lGigE4RQp38Er4CYK53zAPyJi5egmauGXB3aPhmDyJrkZic1evxKfWY8PmRL5XfEtLlMr5IPNGBqPNDnN7ciXCBlwBMpWBRJuDuWWObEYdPmNXLtzIalidkfDEdn0k2+nDYXpQRk=,iv:bWluTbU6j0aKIOvRvweSTRVwTHOde2KZ5/O4WvuvPp8=,tag:e6Bk0rIWNODBuAQ4paCeWw==,type:str]
    pgp:
        - created_at: "2026-04-25T16:53:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/UkVVzYr3IkoY0+iHG+jEZ0bAFud9A6jiQt9Qa7eyDQF8
            ZsMTuBGrYiBWAsiWkHSqoeJBq2MS/Uu+uDnWcZk1c/GNNPZrEztXmhLbajvdnvAU
            sR4eIiJv98+b78yKzTf08f9t4iLPjnTJnO3nk3wUb8HYVGJ4nYuLqZaj0Du6H5vF
            aDmLDvNwu2HQwNnSJBJ9vOt8FHkITYwiKXXNxoInKAxB8/tpXnTC6h81R3nFAVNF
            trAl2MAjuKVrhhkD6NOwiboGaydIx2LCn2HVyOM09gVQFscAwmvgFbKFsXLbF9Bk
            S6U/1nPBJ3RuIRg8zCwa7A2+UC+DFUA89oXQXCd3XtqFKr4wnKLQGcW6M+baWBQx
            kdc5xPuz4Z7f8rMY3/T7LwUlY/lvAG/MPV1UVHTWuofZqxVgAyuRcfH2mTpf8lIu
            ExPFcyrDe4V2xK4adUyzh5Ag+ZCMIvsR7esXcNrueW1i90obFjjfZqmugAaQnKXK
            JMSXJby8qDBk3BlO20Bo0l4BeXlEahTgVB+2kXL7CKnqcfnJunlR+GksewrORXB/
            KSNmFk+6uZvO2C/4D/QF7ppoO9L0wXLz5NYP4+DMNkgHlV5bdprN1FwWmdJXRWiE
            26rCZ9YINHkzfWUu/tBn
            =/JBc
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: mktxp-credentials
    namespace: grafana
type: Opaque
stringData:
    _mktxp.conf: ENC[AES256_GCM,data:HEqsJCxf8f13wJun0hCwk9k+D/b5s7MQSfekJxzIGDKIN7veJ1fi9EEVVFr2spxY29yKl9gdws+9ymil5DlxWI/HtrohFd10dUGiteVe+2VkASSapkR1tuhY74zvNT25a8uPjIZnqNPBGbWUNQYedaVzKwvULOIiJX0gNlL3JoHm5ysFFeXWQA4mPX5IzNFo8lDZhaowHAD+d5xGmVt4GwA9DftqmWZZf5WffI0WYQajc+HdkU/5XJ4JqEWz2TPubyZM77l25HV8W1WQQDbPqp7spJ5w9OQfuS3qpRj9StHAKi3hnKRNf/zGwBAJk3f0T7HTBhq0JtARL57490IL5uja1dvUh27SjzU/N3w184dTEjaSLMWJK6+DkC8SNg+WM08gcDi+fYNJCWpYe1K90VyTQldd2SHo4Hnx42k/eXVX0umFQsAyHv9e9FaghBbEDQw3luCQ3ILOM80XjGRrmyl1iZ40qpz35UX1c0oCIEN2Z2d4MU5V2h/yGoDDrpz8Mb+JSuuUiwU1d+kkWZM1Er8dE07s7EnNwoR9IN/7bSg1xECHqc53e8gnnP1UbhgSrxhw7EurYtVQvLflZnH3A7n8m3sgs6ZM0GumboTbtuBFmleQ4giwcDEZmHJR0QqrECSbQLMQ3vHaP+GC9HuDkh0sRLHolMurQ5zzQJqgtIVJANMZTLkyKlelJXNOKqe+l4RunN6hC8X65Zhu+GOtnAbk/tzFHP1ZTgdEwftxhlfML5CLhAwkm6JChzqqeElwUHx0//1MggfZWUvte31wiOUxYFJf35c/yE7kic79o87pPRs9tXPDOX2w/RJd0oSo/vUKxR4BZr1MdfQhIQntTPNRounTQnK1gwppgUBzfXYEe8eI2X11BupY8GHufYeKV6gQVSIv04X7znLRZ5s5PHaHXQa3NdvOuxXb9K1rQW2TGANINHpFBghOmTTZ1KLNMq0uQJ17M9MwKXC9nrzwCWaHF4I4tGOsxnNdRZT8H5Mx4sYvjp8yR7CPVGLgeO/aGiXWefSL71aCZ46CoOcTp7cvh/TVD/i81zcztd5eI2oFF6U2hoRMUOUFKguEwNx+bafjOScVzr1dhA2BrpO4fu6k3LTxETI4hgaEB0c0Bhl7B82Gfig8mM0+sRoAmHXeqG60KDXO/mnvVsILIwiVF4qSowKjB2CkSGRVaxbAkv09Y5gZN784rTDCHFFmCZ92fl/t7pqwE+a2GJZ+a48nvOp5JGr5ZrwHrkq7SSPu95Mp/7FGzAaQ/6pvMxSX9bZJyumgpp+l9uCRR+l74KPk1DC2ub+KuvHGewl+sS+cPcIUdcA/JZOnMWul2wM6QTv15xTCnuFGlYF67RqqZ6lrYEkIApJTEs0i7+tAyctLGD4G90hHyANZSmR7e0UhgONPs9V4QXs9yE6iw8OA8eRDp53ZYr9W6RbFVqj0IMfVfF371/z8SJJuoZRHH7KY4vcAJImmGhDhA26syRZgEQt7XuSdwtz8HnM9qIiy,iv:ymMqUfa/+OQSPgsR3WrPXWUh6eA0/qz2LXskIedj8R8=,tag:lRNDUW2S00ZMMZcCeP5PTQ==,type:str]
    mktxp.conf: ENC[AES256_GCM,data:V8g+ZtuMrp+faCuIYj87eqSHpTcsJPDbqEgKh3Ugcnz4fParU0dyrB0DrLK9oXbdmM8HRcGQRfj5xBiOVTMaEJnH5POGxadC8jDTxDCj0wql4juujXgNozGLL+wwnNbC7NCnqePvrGd732yYmdeghXafLHCyoxhIRzOWo4l2VvoT1ohkmDkD9C/GKuXLp2p0XnSbi+DXMxbkpaV7vRlvRO91+49v6A2bP4B+9HkqhG4kkjdzldqTTSDFHRWnUJGcCrB6EQK67is+izlO4XrJ96l8QE/tmFqHSF8nDjFSSFwL2lUL/VwpuO8O46MuQtTnKNvPbXhnGHH2XbkaZzqr3WLWsKU1kibuPZF0QDDpIGqwGVFVR81bQ6Avl6brnuUkHcHKW4QrJtGaml+b5YouuJaAOJRQnzUBtDIQosl1DUXJAzToJdwKNTSkIiepNQwlzfx0338xlPxa6U67V90hjioie3QdntqRH1WSWzpa7z88ZadHt2LU8UEpcXkOCKRlvL8FZiSDSXRjecxVk2OHYrCpglS/pQIiy0tv+Jvtog2xgepm9zsN8SNUd8yIx/vUT4enVnxpo3vz9u7UDIbdeky/UL+BbyyaTfP5vtr/2OrvZZgbzTk1d1ORi8/97biq7nL5KbnWBDvzAjMboUZhpBb9oeIOVt16FmFD3BtrNTxQ9PKaXtsYRFIWAe05zi2aLvp5QIqHBvqYRXCeueXXLBtQdwZ3b/3e7dYZgwJudWyRKOq1gPwm/rTFVEFmPgPHBItnEptT3A0Lziw68x9ZIxlweB79obICht8u/XkkORkoXfuO1eayJ6ByEkmSfjWZF4w1dIKo715OTTba7YrO9hzUblMGogJTOfiT/YO2PpJ8qe0RiIx6QXMFUCgdH9Tfdz4YdgQNk5IL21lRkNMZFRuhCP669QJBtfzb0o8hLerZU4sp0nSCctwE0fdExL0uHIriIpqMtxa3vNGmE8LwDk6BKo2w84bFABZ4v90OMBl4WpWT0btr3tGRSmC+QXdIPdE7ZtGRAJcXe6DbwUoMx00hxVG+adcsdEIHVbOoo1mB5kS1zKKt98reU5EmuHxPk5eY7wZb7Yo5ZfIgpvzTPKpmYvLG5+AkjqLtVM6mYVAcJZCvaPMAYjR6zofwmU6XMIDDR+zgbgTCU3zadRqvqoziAppV1nC/0y9xzsoCkdXyA2WiLuQ9MJkEF9ps07OH8qydRpSBogghBu3M4DAzU2/bOks1k5Z+/RyFHj7oh244X4BQvlrYUvC5VAXaIDyxwM00IZ/1sGk01LANkCNMUlfS5vnM5rorbrR0uZOCWz84yILZVwLKS+Q6Iq7Fe2TO553Q8Bq0diYq7mF0C74fz5roL41YMwEQ29d5h4Axzg2y9A6WoSSBaN5A4Zsh8vzC8K8deb1EN247j5HoZ/T1vtanDsoIUzpFfWMo/Om9KseSRxEDX51+GwkZvINtX8URVZ8QKEUdQxJ6MdA439PXcb8jcKxM/fYScxqCv5tpHq0qwrx6HBJfEAvhHcpdgHK262H/ujg+IjNAebtfbSu/ly+OiEvItfmv+10tAK/A3+MN211+6l41cda8vYkry0HQXZucSUsPkM+/phLmYWs2MMTx6RPFX2yZZz5wz8CSEpjDOkYIzpJMIBdkCIati+N5idWYET13dRPZRLX4/Rg+k6KB7KzQAju5i2aP/VHYue0L3Rp+PexG60pNqm8OlLaIEe5tClAgm+Hi8jumZFU+zCnfsZtVjc7kjPUyX1x7bTZ7QwSWlo4EFFFx3hdI6JRWDjsEbAd4e+uwKqVhn6Vuj52ZcFuZZYUIeo5lFYXXJRunrhU7V8Pv+Og6X5ePO2u+e82sHkQ=,iv:1t8+R/ngYDkaKEIbSitbHFZetvcv6O/FydQ0o1YilGg=,tag:PWE0hPwPH6zdOeFdNz4iHA==,type:str]
sops:
    lastmodified: "2026-04-25T16:53:07Z"
    mac: ENC[AES256_GCM,data:3/VrZfzsVru44d6YUDtqRVqMniHi2POWTu3lGigE4RQp38Er4CYK53zAPyJi5egmauGXB3aPhmDyJrkZic1evxKfWY8PmRL5XfEtLlMr5IPNGBqPNDnN7ciXCBlwBMpWBRJuDuWWObEYdPmNXLtzIalidkfDEdn0k2+nDYXpQRk=,iv:bWluTbU6j0aKIOvRvweSTRVwTHOde2KZ5/O4WvuvPp8=,tag:e6Bk0rIWNODBuAQ4paCeWw==,type:str]
    pgp:
        - created_at: "2026-04-25T16:53:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/UkVVzYr3IkoY0+iHG+jEZ0bAFud9A6jiQt9Qa7eyDQF8
            ZsMTuBGrYiBWAsiWkHSqoeJBq2MS/Uu+uDnWcZk1c/GNNPZrEztXmhLbajvdnvAU
            sR4eIiJv98+b78yKzTf08f9t4iLPjnTJnO3nk3wUb8HYVGJ4nYuLqZaj0Du6H5vF
            aDmLDvNwu2HQwNnSJBJ9vOt8FHkITYwiKXXNxoInKAxB8/tpXnTC6h81R3nFAVNF
            trAl2MAjuKVrhhkD6NOwiboGaydIx2LCn2HVyOM09gVQFscAwmvgFbKFsXLbF9Bk
            S6U/1nPBJ3RuIRg8zCwa7A2+UC+DFUA89oXQXCd3XtqFKr4wnKLQGcW6M+baWBQx
            kdc5xPuz4Z7f8rMY3/T7LwUlY/lvAG/MPV1UVHTWuofZqxVgAyuRcfH2mTpf8lIu
            ExPFcyrDe4V2xK4adUyzh5Ag+ZCMIvsR7esXcNrueW1i90obFjjfZqmugAaQnKXK
            JMSXJby8qDBk3BlO20Bo0l4BeXlEahTgVB+2kXL7CKnqcfnJunlR+GksewrORXB/
            KSNmFk+6uZvO2C/4D/QF7ppoO9L0wXLz5NYP4+DMNkgHlV5bdprN1FwWmdJXRWiE
            26rCZ9YINHkzfWUu/tBn
            =/JBc
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-config-grafana
    namespace: grafana
type: Opaque
stringData:
    #ENC[AES256_GCM,data:0kI3cDcDO5tGNktCavanHGSkJuKhs6tBeG6PL3HKS4qv5qBKRLiHYiKblXVZHjgmag10Q9+cU/3WuKq+3DKseXQ=,iv:g2R215ilWyppz2CVvPdga2BjVFye4E96NXzS9oGfKSQ=,tag:v5NV+loGMXzItHIugc9u6g==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:ckNEca3AhPVS9m/TlvfVWAeSoS4YzVjHSj2JS6zwtkAfi1zbgJHxtUuJiuS3CzA=,iv:Oe1YSc0GyhseFfPR9K1sxvJUHP6PQhIy9irG/xwa6BY=,tag:lPxLv3ptqQgYHJxsASdJfw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:regVf6Ks2Q+ApCzX6znXX01VfhgnTGXtjr7ICK1UnxfGtebGURB2iSL6SIT6v/AB,iv:Mn0o3UI4QooUaHgNmiCknXSwn7eMkaAM2L1CMyy+QVc=,tag:swXfDYImHx9dgoUSzED3fg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ti/CXVMyAukCsHtU9WSiJ+xkmCX6X1wD2uE=,iv:AOnuIJOO8VKIApRwLaste7m4n8nVcN+zH/XWn3/j3c0=,tag:jyyoqF6osT1Ypl8NjsVQPA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:LWqvbde7DLhMJuMKAAkkgM4sXdryf6EvkIRDRASS74Lq2m3t3jxLiSKovDa6LeJECDWSfhCKLiJZKVAloPMUgA==,iv:nT3VdCaKSqvAeNwYO5MrbH3n7MQV8h1GWE57dnQVkPo=,tag:eME53GN6hxeXoaeZNj8jow==,type:str]
sops:
    lastmodified: "2026-04-25T16:53:07Z"
    mac: ENC[AES256_GCM,data:3/VrZfzsVru44d6YUDtqRVqMniHi2POWTu3lGigE4RQp38Er4CYK53zAPyJi5egmauGXB3aPhmDyJrkZic1evxKfWY8PmRL5XfEtLlMr5IPNGBqPNDnN7ciXCBlwBMpWBRJuDuWWObEYdPmNXLtzIalidkfDEdn0k2+nDYXpQRk=,iv:bWluTbU6j0aKIOvRvweSTRVwTHOde2KZ5/O4WvuvPp8=,tag:e6Bk0rIWNODBuAQ4paCeWw==,type:str]
    pgp:
        - created_at: "2026-04-25T16:53:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/UkVVzYr3IkoY0+iHG+jEZ0bAFud9A6jiQt9Qa7eyDQF8
            ZsMTuBGrYiBWAsiWkHSqoeJBq2MS/Uu+uDnWcZk1c/GNNPZrEztXmhLbajvdnvAU
            sR4eIiJv98+b78yKzTf08f9t4iLPjnTJnO3nk3wUb8HYVGJ4nYuLqZaj0Du6H5vF
            aDmLDvNwu2HQwNnSJBJ9vOt8FHkITYwiKXXNxoInKAxB8/tpXnTC6h81R3nFAVNF
            trAl2MAjuKVrhhkD6NOwiboGaydIx2LCn2HVyOM09gVQFscAwmvgFbKFsXLbF9Bk
            S6U/1nPBJ3RuIRg8zCwa7A2+UC+DFUA89oXQXCd3XtqFKr4wnKLQGcW6M+baWBQx
            kdc5xPuz4Z7f8rMY3/T7LwUlY/lvAG/MPV1UVHTWuofZqxVgAyuRcfH2mTpf8lIu
            ExPFcyrDe4V2xK4adUyzh5Ag+ZCMIvsR7esXcNrueW1i90obFjjfZqmugAaQnKXK
            JMSXJby8qDBk3BlO20Bo0l4BeXlEahTgVB+2kXL7CKnqcfnJunlR+GksewrORXB/
            KSNmFk+6uZvO2C/4D/QF7ppoO9L0wXLz5NYP4+DMNkgHlV5bdprN1FwWmdJXRWiE
            26rCZ9YINHkzfWUu/tBn
            =/JBc
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: loki-secrets
    namespace: grafana
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:w+Qx93YU3v9MU2wBR2sriKAHl7DJ7QO2afOGnhXiZ30tGjIn0vEoHFxfNi4CCZ8HMPlsR0W9jVEjuXZ7VY7G2pJyq2OhUL0TmUQpTN9TGj1YrWu2ra4WcGkoN5yLGlJdqQelRZ45jfLtu5tNS6kINBFEaoUnQqvYsqFcCjgNZoMJsjYyX+iCZlU1o8fjJhIAbN8ef1c21oaZou2ZtDRiuF+lxQxvzVkB7V793fWZHYNcdjLSLUeTyqIC7scpwEWurXGJntJO/lSkzBIteBuror/9wrEBYsnGzR/fdA==,iv:dgdyk7lABDBHVLnoDSTg9qNjoFR8V6aAdwCym77M23s=,tag:lt069Deu9YK2C1EBt/RdyQ==,type:str]
sops:
    lastmodified: "2026-04-25T16:53:07Z"
    mac: ENC[AES256_GCM,data:3/VrZfzsVru44d6YUDtqRVqMniHi2POWTu3lGigE4RQp38Er4CYK53zAPyJi5egmauGXB3aPhmDyJrkZic1evxKfWY8PmRL5XfEtLlMr5IPNGBqPNDnN7ciXCBlwBMpWBRJuDuWWObEYdPmNXLtzIalidkfDEdn0k2+nDYXpQRk=,iv:bWluTbU6j0aKIOvRvweSTRVwTHOde2KZ5/O4WvuvPp8=,tag:e6Bk0rIWNODBuAQ4paCeWw==,type:str]
    pgp:
        - created_at: "2026-04-25T16:53:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/UkVVzYr3IkoY0+iHG+jEZ0bAFud9A6jiQt9Qa7eyDQF8
            ZsMTuBGrYiBWAsiWkHSqoeJBq2MS/Uu+uDnWcZk1c/GNNPZrEztXmhLbajvdnvAU
            sR4eIiJv98+b78yKzTf08f9t4iLPjnTJnO3nk3wUb8HYVGJ4nYuLqZaj0Du6H5vF
            aDmLDvNwu2HQwNnSJBJ9vOt8FHkITYwiKXXNxoInKAxB8/tpXnTC6h81R3nFAVNF
            trAl2MAjuKVrhhkD6NOwiboGaydIx2LCn2HVyOM09gVQFscAwmvgFbKFsXLbF9Bk
            S6U/1nPBJ3RuIRg8zCwa7A2+UC+DFUA89oXQXCd3XtqFKr4wnKLQGcW6M+baWBQx
            kdc5xPuz4Z7f8rMY3/T7LwUlY/lvAG/MPV1UVHTWuofZqxVgAyuRcfH2mTpf8lIu
            ExPFcyrDe4V2xK4adUyzh5Ag+ZCMIvsR7esXcNrueW1i90obFjjfZqmugAaQnKXK
            JMSXJby8qDBk3BlO20Bo0l4BeXlEahTgVB+2kXL7CKnqcfnJunlR+GksewrORXB/
            KSNmFk+6uZvO2C/4D/QF7ppoO9L0wXLz5NYP4+DMNkgHlV5bdprN1FwWmdJXRWiE
            26rCZ9YINHkzfWUu/tBn
            =/JBc
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: alloy-secret
    namespace: grafana
type: Opaque
stringData:
    LOKI_USERNAME: ENC[AES256_GCM,data:KHFr4A==,iv:+0JLr13zprCFZGECcKwqakmo8JojlDV8jMBfs6Q+yd8=,tag:muGWwjScrGwGbSYR4WKahQ==,type:str]
    LOKI_PASSWORD: ENC[AES256_GCM,data:+Tzw41FWoLa8oSEvico=,iv:Pm1+YOVEJovp6hJgWtviQW3r8ycMlm4bSaaZkJnNbh0=,tag:YXXwaPFwxDhxrJI3IDzTtQ==,type:str]
sops:
    lastmodified: "2026-04-25T16:53:07Z"
    mac: ENC[AES256_GCM,data:3/VrZfzsVru44d6YUDtqRVqMniHi2POWTu3lGigE4RQp38Er4CYK53zAPyJi5egmauGXB3aPhmDyJrkZic1evxKfWY8PmRL5XfEtLlMr5IPNGBqPNDnN7ciXCBlwBMpWBRJuDuWWObEYdPmNXLtzIalidkfDEdn0k2+nDYXpQRk=,iv:bWluTbU6j0aKIOvRvweSTRVwTHOde2KZ5/O4WvuvPp8=,tag:e6Bk0rIWNODBuAQ4paCeWw==,type:str]
    pgp:
        - created_at: "2026-04-25T16:53:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/UkVVzYr3IkoY0+iHG+jEZ0bAFud9A6jiQt9Qa7eyDQF8
            ZsMTuBGrYiBWAsiWkHSqoeJBq2MS/Uu+uDnWcZk1c/GNNPZrEztXmhLbajvdnvAU
            sR4eIiJv98+b78yKzTf08f9t4iLPjnTJnO3nk3wUb8HYVGJ4nYuLqZaj0Du6H5vF
            aDmLDvNwu2HQwNnSJBJ9vOt8FHkITYwiKXXNxoInKAxB8/tpXnTC6h81R3nFAVNF
            trAl2MAjuKVrhhkD6NOwiboGaydIx2LCn2HVyOM09gVQFscAwmvgFbKFsXLbF9Bk
            S6U/1nPBJ3RuIRg8zCwa7A2+UC+DFUA89oXQXCd3XtqFKr4wnKLQGcW6M+baWBQx
            kdc5xPuz4Z7f8rMY3/T7LwUlY/lvAG/MPV1UVHTWuofZqxVgAyuRcfH2mTpf8lIu
            ExPFcyrDe4V2xK4adUyzh5Ag+ZCMIvsR7esXcNrueW1i90obFjjfZqmugAaQnKXK
            JMSXJby8qDBk3BlO20Bo0l4BeXlEahTgVB+2kXL7CKnqcfnJunlR+GksewrORXB/
            KSNmFk+6uZvO2C/4D/QF7ppoO9L0wXLz5NYP4+DMNkgHlV5bdprN1FwWmdJXRWiE
            26rCZ9YINHkzfWUu/tBn
            =/JBc
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: prometheus-garage-token
    namespace: grafana
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:5wvEMUtIM03oxuHnsTl3co34Idk7HqH2+etInNnDWS0QS4T1XpEoyxeFMQA=,iv:TT3+x40/WKCzka+b3HP5gKSBJS0nIkccGTOThcvdymk=,tag:67zuU8r6JDn6BkDjNgBiww==,type:str]
sops:
    lastmodified: "2026-04-25T16:53:07Z"
    mac: ENC[AES256_GCM,data:3/VrZfzsVru44d6YUDtqRVqMniHi2POWTu3lGigE4RQp38Er4CYK53zAPyJi5egmauGXB3aPhmDyJrkZic1evxKfWY8PmRL5XfEtLlMr5IPNGBqPNDnN7ciXCBlwBMpWBRJuDuWWObEYdPmNXLtzIalidkfDEdn0k2+nDYXpQRk=,iv:bWluTbU6j0aKIOvRvweSTRVwTHOde2KZ5/O4WvuvPp8=,tag:e6Bk0rIWNODBuAQ4paCeWw==,type:str]
    pgp:
        - created_at: "2026-04-25T16:53:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/UkVVzYr3IkoY0+iHG+jEZ0bAFud9A6jiQt9Qa7eyDQF8
            ZsMTuBGrYiBWAsiWkHSqoeJBq2MS/Uu+uDnWcZk1c/GNNPZrEztXmhLbajvdnvAU
            sR4eIiJv98+b78yKzTf08f9t4iLPjnTJnO3nk3wUb8HYVGJ4nYuLqZaj0Du6H5vF
            aDmLDvNwu2HQwNnSJBJ9vOt8FHkITYwiKXXNxoInKAxB8/tpXnTC6h81R3nFAVNF
            trAl2MAjuKVrhhkD6NOwiboGaydIx2LCn2HVyOM09gVQFscAwmvgFbKFsXLbF9Bk
            S6U/1nPBJ3RuIRg8zCwa7A2+UC+DFUA89oXQXCd3XtqFKr4wnKLQGcW6M+baWBQx
            kdc5xPuz4Z7f8rMY3/T7LwUlY/lvAG/MPV1UVHTWuofZqxVgAyuRcfH2mTpf8lIu
            ExPFcyrDe4V2xK4adUyzh5Ag+ZCMIvsR7esXcNrueW1i90obFjjfZqmugAaQnKXK
            JMSXJby8qDBk3BlO20Bo0l4BeXlEahTgVB+2kXL7CKnqcfnJunlR+GksewrORXB/
            KSNmFk+6uZvO2C/4D/QF7ppoO9L0wXLz5NYP4+DMNkgHlV5bdprN1FwWmdJXRWiE
            26rCZ9YINHkzfWUu/tBn
            =/JBc
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
