apiVersion: v1
kind: Secret
metadata:
    name: outline-db-secret
    namespace: outline
type: Opaque
data:
    username: ENC[AES256_GCM,data:slEJTieyTSsomjQm,iv:Qo4L/OP+oVc7ZeFJg7tLpGx1Iy5FXX2gQlr3GO9/978=,tag:tAEGwrGl+GKjASP/l/4rXw==,type:str]
    password: ENC[AES256_GCM,data:FagvtzvkyKTqAdErPDbE5G7gX0c=,iv:iW75JmNrcJLVn6BAdrdmCXCGh3ZmDiT3W1GIuoTIjxc=,tag:betjEnVyVeF/kjqzhfyWMw==,type:str]
sops:
    lastmodified: "2025-11-11T15:56:29Z"
    mac: ENC[AES256_GCM,data:dwsPLo4PaCf3aVyKa6Co9rDEtUB26K0qMpEktVmbG0UTLFUx+1ZvL/7QWw2vf0PpGSaE9sHQ9IEtwAslmxREbzfiobEdGoYGE615VamVPk1sIS+abzWzO+KZRhGpcHpIU+YvSlX9VsMluSX9OXeIGdtKutOElhnzGkVSeWvAyiw=,iv:8Ck6JRTcH90YDuvjL/fjp5+RrIPrgKOdk+0sHbDzaPM=,tag:I4ErfoZKDj4JEV4eaZG8JA==,type:str]
    pgp:
        - created_at: "2025-11-11T15:56:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/Q7isvBkd6zsUo7F4vMnPClPfdcLAxx2oA/E0bLej6Pvm
            +aaG+5rCzKQilrLN7pJB9yUet2PVn7nwPMHWZNFQE60jaztzPVtCxkaMNt75k/gE
            aSK1ILks0t0uZ1X6n1FT/+r/JlJXAC+pJZ958stEE/3Cvm790UWe8IdM0vnNlaI7
            6hbF33p2uEZeAugepJ08lwyem9VRJciRHDOePuMNjTbNpNyFJC5B4PT6hrKN1r4o
            Vr44JQ5f5PsMyrHdMCmt9tEzQLKrRke1Q4vQ3SGnFYCij24RIJ0bWwyV0P4eG1eI
            nqMrTwxMscSof0Z+fb/lLkC3xID4RlF8jBKWT5hLuoo+6nopJn7vj/xNzAvDu0JQ
            PCIyuoKv38kp1gseMXMBm0IMKibuk+rB+7JflS940FhexibzaDNsb1i/HHpNQxmV
            nK/6vrBT/SI9zdAJupvRgobFZ1b64CfKM3eEGNCOOCLakxJqwvhUjWU9044G2W92
            clqy+hjBLjXrSBJh7pcP0l4BF6cIxq/8JfpyV2TGxzuF/95ptJiPRv1+Z1fuAYpy
            pOdLdXkPXQty2pH4R5ffZIXTLcdszoPAAA5cRYucSZbsad3f+WQMZO4GvAdy0OBL
            UpkqFiHe4Jc6OiSLT2Y/
            =NZeg
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: garage-creds
    namespace: outline
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:3Q3Wa8dgLYHQnvVQG5yb3pu2DUdvUGZbGko=,iv:UQEj8HrzIktBYrKVPE4PwQYHJyymYkzdZSKhh8Ur4+I=,tag:7zXdvc5zMHfraYpOfaqTpA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:09kVYpP2hqrCQdCf5Z9Xh8mRWJu/Kj984CxMEpx68Z7UrOpzUpur9b2Jj0mFBcOR3/AqYcbRfrEn5uHYjDgnVw==,iv:zJAdAbxqoiek3zQFfzGh+DRmpRg/XbP+6sB/+FOzETE=,tag:y7bJJKyJJlY3xru+R1bJXg==,type:str]
    region: ENC[AES256_GCM,data:PNAcCw==,iv:k5IaakVuON6KqOnixV0JrCfvw1DcoKLn697/GP1uB/Q=,tag:TSHoN7/CIMmHNNg7hP+Zbg==,type:str]
sops:
    lastmodified: "2025-11-11T15:56:29Z"
    mac: ENC[AES256_GCM,data:dwsPLo4PaCf3aVyKa6Co9rDEtUB26K0qMpEktVmbG0UTLFUx+1ZvL/7QWw2vf0PpGSaE9sHQ9IEtwAslmxREbzfiobEdGoYGE615VamVPk1sIS+abzWzO+KZRhGpcHpIU+YvSlX9VsMluSX9OXeIGdtKutOElhnzGkVSeWvAyiw=,iv:8Ck6JRTcH90YDuvjL/fjp5+RrIPrgKOdk+0sHbDzaPM=,tag:I4ErfoZKDj4JEV4eaZG8JA==,type:str]
    pgp:
        - created_at: "2025-11-11T15:56:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/Q7isvBkd6zsUo7F4vMnPClPfdcLAxx2oA/E0bLej6Pvm
            +aaG+5rCzKQilrLN7pJB9yUet2PVn7nwPMHWZNFQE60jaztzPVtCxkaMNt75k/gE
            aSK1ILks0t0uZ1X6n1FT/+r/JlJXAC+pJZ958stEE/3Cvm790UWe8IdM0vnNlaI7
            6hbF33p2uEZeAugepJ08lwyem9VRJciRHDOePuMNjTbNpNyFJC5B4PT6hrKN1r4o
            Vr44JQ5f5PsMyrHdMCmt9tEzQLKrRke1Q4vQ3SGnFYCij24RIJ0bWwyV0P4eG1eI
            nqMrTwxMscSof0Z+fb/lLkC3xID4RlF8jBKWT5hLuoo+6nopJn7vj/xNzAvDu0JQ
            PCIyuoKv38kp1gseMXMBm0IMKibuk+rB+7JflS940FhexibzaDNsb1i/HHpNQxmV
            nK/6vrBT/SI9zdAJupvRgobFZ1b64CfKM3eEGNCOOCLakxJqwvhUjWU9044G2W92
            clqy+hjBLjXrSBJh7pcP0l4BF6cIxq/8JfpyV2TGxzuF/95ptJiPRv1+Z1fuAYpy
            pOdLdXkPXQty2pH4R5ffZIXTLcdszoPAAA5cRYucSZbsad3f+WQMZO4GvAdy0OBL
            UpkqFiHe4Jc6OiSLT2Y/
            =NZeg
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: outline-secrets
    namespace: outline
stringData:
    values.yaml: ENC[AES256_GCM,data:656K1cEGKeX1Z2ZZHIaVELlxl+DWQKsBSn14Y111EDfSUM0kUY3ILb0p1Znl0zua72tOOE2l4f/n0K2l0+yngBIJl/WGIsTtcr0xKKDtbQvAUeldCgzZzP6bggAIkDVY9nZrjgJde7nVQAI1CeJKLwSZOQrHGyNPM4wldnLOfEFTQ2AJsRuHJlDa4gnFIsJtmuivbabcOwK3ERgFq9kZlKMFZwxh9Sg4XKkiS9t582N4O0h/85lOjsgbbIW7NbM1SDx/DPFb6HxNZaQ4azdwM5VpSvLCpil5tqt0T0Muhaz43nosNIWGVIGHBy97gj1r2dOZ30sxYXtVcRWZI20J9BeZEIvXxMnFIwnXtRyuVdn3VG8EbmLHSIQ9S/4++73xzW8/c/mIHipYOLeKIFwA7bikNGSUl6mA1JBwz1dNio+v1KcVCoJun0fWGNsRigciexm2X55If8WsCJZPoUN0UeuieBN3ZJrsrR5yJ0y1/AFGPUCOa2981zvHwtiwXJ3hRBVFtmeCmVkavZGRh98IYFET9ZVs3HwTlr58DBtYNiILsLGaSq6SquY2mhTvX4rkCQ6fekqmrkLQVr4Ilmkz8YQhvpwYsl4ycTzqa+O9lOUAfq9MgwM0IQBa73G5hIfKQelkEuAS/Fp/NcHsf+n5/23RjuIis0GB7oSt3rwpZKktT43zZgCor6YBnuCeH5vFpNMiWymSN2f5iEStqZEFATVF+/UU+qWeWKyeApEGfzICL4R5CIbJimn3+oAuTfGzOmVIPswS8dfYw5KtUk39lmoUnUsF+ZLOvyecR77jb9FWCVzTYMmj8pyIzz3hCF+w7j6QcTUuwoVdURwDNerJj3s1b1nr9Svbfnv2soqGueMl2/0ZtqXDVmLg4DJPNJvS40Uu,iv:LKNAuidLaP1jywXdcnY0jQLmMVd0PqDUfR8lcaleVN0=,tag:7gtEb6Bg0xCC3gZVbQ6dWg==,type:str]
type: Opaque
sops:
    lastmodified: "2025-11-11T15:56:29Z"
    mac: ENC[AES256_GCM,data:dwsPLo4PaCf3aVyKa6Co9rDEtUB26K0qMpEktVmbG0UTLFUx+1ZvL/7QWw2vf0PpGSaE9sHQ9IEtwAslmxREbzfiobEdGoYGE615VamVPk1sIS+abzWzO+KZRhGpcHpIU+YvSlX9VsMluSX9OXeIGdtKutOElhnzGkVSeWvAyiw=,iv:8Ck6JRTcH90YDuvjL/fjp5+RrIPrgKOdk+0sHbDzaPM=,tag:I4ErfoZKDj4JEV4eaZG8JA==,type:str]
    pgp:
        - created_at: "2025-11-11T15:56:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/Q7isvBkd6zsUo7F4vMnPClPfdcLAxx2oA/E0bLej6Pvm
            +aaG+5rCzKQilrLN7pJB9yUet2PVn7nwPMHWZNFQE60jaztzPVtCxkaMNt75k/gE
            aSK1ILks0t0uZ1X6n1FT/+r/JlJXAC+pJZ958stEE/3Cvm790UWe8IdM0vnNlaI7
            6hbF33p2uEZeAugepJ08lwyem9VRJciRHDOePuMNjTbNpNyFJC5B4PT6hrKN1r4o
            Vr44JQ5f5PsMyrHdMCmt9tEzQLKrRke1Q4vQ3SGnFYCij24RIJ0bWwyV0P4eG1eI
            nqMrTwxMscSof0Z+fb/lLkC3xID4RlF8jBKWT5hLuoo+6nopJn7vj/xNzAvDu0JQ
            PCIyuoKv38kp1gseMXMBm0IMKibuk+rB+7JflS940FhexibzaDNsb1i/HHpNQxmV
            nK/6vrBT/SI9zdAJupvRgobFZ1b64CfKM3eEGNCOOCLakxJqwvhUjWU9044G2W92
            clqy+hjBLjXrSBJh7pcP0l4BF6cIxq/8JfpyV2TGxzuF/95ptJiPRv1+Z1fuAYpy
            pOdLdXkPXQty2pH4R5ffZIXTLcdszoPAAA5cRYucSZbsad3f+WQMZO4GvAdy0OBL
            UpkqFiHe4Jc6OiSLT2Y/
            =NZeg
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
