apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - office.yaml
  - nextcloud.yaml
  - db.yaml
  - secrets.yaml
  - backup.yaml
  - network-policies.yaml