apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 10m
  install:
    createNamespace: true
    remediation:
      retries: 3
  chart:
    spec:
      chart: nextcloud
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
      version: "9.2.0"
  values:
    replicaCount: 3
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - nextcloud
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - app
            topologyKey: kubernetes.io/hostname

    podSecurityContext:
      fsGroup: 33
      fsGroupChangePolicy: OnRootMismatch
      seccompProfile:
        type: RuntimeDefault

    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
      capabilities:
        drop:
          - ALL

    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        memory: 2Gi

    ingress:
      enabled: true
      className: cilium
      annotations:
        kubernetes.io/tls-acme: "false"           


      tls:
        - secretName: external-tls
          hosts:
            - cloud.exmaple.com
      labels: {}
      path: /
      pathType: Prefix

    nextcloud:
      host: cloud.exmaple.com
      existingSecret:
        enabled: true
        secretName: nextcloud-secret
        usernameKey: nextcloud-username
        passwordKey: nextcloud-password
        tokenKey: ""
        smtpUsernameKey: smtp-username
        smtpPasswordKey: smtp-password
        smtpHostKey: smtp-host
      trustedDomains: cloud.exmaple.com
      mail:
        enabled: true
        fromAddress: user
        domain: cloud@exmaple.com
        smtp:
          secure: ssl
          port: 465
          authtype: LOGIN

      configs:
        custom.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' =>
              array (
                0 => '192.168.178.0/24',
                1 => '10.0.0.0/8',
              ),
            'forwarded_for_headers' =>
              array (
                0 => 'HTTP_X_FORWARDED',
                1 => 'HTTP_FORWARDED_FOR',
              ),
            'overwriteprotocol' => 'https',
            'overwritehost'     => 'cloud.exmaple.com',
            'overwrite.cli.url' => 'https://cloud.exmaple.com',
          );


    cronjob:
      enabled: true

    internalDatabase:
      enabled: false

    externalDatabase:
      enabled: true
      type: postgresql
      host: "nextcloud-db-rw"
      database: nextcloud  
      existingSecret:
        enabled: true
        secretName: nextcloud-db-secret
        usernameKey: username
        passwordKey: password

    redis:
      enabled: true
      architecture: standalone
      auth:
        enabled: false
      global:
        storageClass: ""
      master:
        persistence:
          enabled: false
      replica:
        replicaCount: 0
        enabled: false
        persistence:
          enabled: false

    persistence:
      enabled: true
      storageClass: csi-cephfs-sc
      size: 5Gi
      accessMode: ReadWriteMany
      nextcloudData:
        enabled: true
        existingClaim: nextcloud-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: csi-cephfs-sc
  resources:
    requests:
      storage: 150Gi 