apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 10m
  install:
    createNamespace: true
    remediation:
      retries: 3
  chart:
    spec:
      chart: nextcloud
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
      version: "9.1.1"
  values:
    replicaCount: 3
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - nextcloud
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - app
            topologyKey: kubernetes.io/hostname
    ingress:
      enabled: true
      className: cilium
      annotations:
#        nginx.ingress.kubernetes.io/proxy-body-size: "4G"
        kubernetes.io/tls-acme: "false"           
#        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
#        nginx.ingress.kubernetes.io/server-snippet: |-
#          server_tokens off;
#          proxy_hide_header X-Powered-By;
#          rewrite ^/.well‑known/webfinger /index.php/.well‑known/webfinger last;
#          rewrite ^/.well‑known/nodeinfo /index.php/.well‑known/nodeinfo last;
#          rewrite ^/.well‑known/host-meta /public.php?service=host-meta last;
#          rewrite ^/.well‑known/host-meta.json /public.php?service=host-meta‑json;
#          location = /.well‑known/carddav {
#            return 301 $scheme://$host/remote.php/dav;
#          }
#          location = /.well‑known/caldav {
#            return 301 $scheme://$host/remote.php/dav;
#          }
#          location = /robots.txt {
#            allow all;
#            log_not_found off;
#            access_log off;
#          }
#          location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
#            deny all;
#          }
#          location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
#            deny all;
#          }

      tls:
        - secretName: external-tls
          hosts:
            - cloud.exmaple.com
      labels: {}
      path: /
      pathType: Prefix

    nextcloud:
      host: cloud.exmaple.com
      existingSecret:
        enabled: true
        secretName: nextcloud-secret
        usernameKey: nextcloud-username
        passwordKey: nextcloud-password
        tokenKey: ""
        smtpUsernameKey: smtp-username
        smtpPasswordKey: smtp-password
        smtpHostKey: smtp-host
      trustedDomains: cloud.exmaple.com
      mail:
        enabled: true
        # the user we send email as
        fromAddress: user
        # the domain we send email from
        domain: cloud@exmaple.com
        smtp:
          secure: ssl
          port: 465
          authtype: LOGIN

      configs:
        custom.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' =>
              array (
                0 => '192.168.178.0/24',
                1 => '10.0.0.0/8',
              ),
            'forwarded_for_headers' =>
              array (
                0 => 'HTTP_X_FORWARDED',
                1 => 'HTTP_FORWARDED_FOR',
              ),
            'overwriteprotocol' => 'https',
            'overwritehost'     => 'cloud.exmaple.com',
            'overwrite.cli.url' => 'https://cloud.exmaple.com',
          );


    cronjob:
      enabled: true

    internalDatabase:
      enabled: false

    externalDatabase:
      enabled: true
      ## Supported database engines: mysql or postgresql
      type: postgresql
      ## Database host. You can optionally include a colon delimited port like "myhost:1234"
      host: "nextcloud-db-rw"
      ## Database user
      database: nextcloud  
      existingSecret:
        enabled: true
        secretName: nextcloud-db-secret
        usernameKey: username
        passwordKey: password

    redis:
      enabled: true
      architecture: standalone
      auth:
        enabled: false
      global:
        storageClass: ""
      master:
        persistence:
          enabled: false
      replica:
        replicaCount: 0
        enabled: false
        persistence:
          enabled: false

    persistence:
      # Nextcloud Data (/var/www/html)
      enabled: true
      storageClass: csi-cephfs-sc
      size: 5Gi
      accessMode: ReadWriteMany
      nextcloudData:
        enabled: true
        existingClaim: nextcloud-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: csi-cephfs-sc
  resources:
    requests:
      storage: 150Gi 