apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: euro-office
  namespace: nextcloud
spec:
  interval: 10m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true 
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: "5.0.1"
  values:
    controllers:
      euro-office:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "false"
        containers:
          euro-office: 
            image:
              repository: ghcr.io/euro-office/documentserver
              tag: "v9.3.1"
              pullPolicy: IfNotPresent
            env:
              TZ: Europe/Berlin
              JWT_ENABLED: "true"
              JWT_HEADER: AuthorizationJwt
              USE_UNAUTHORIZED_STORAGE: "true"     
              PLUGINS_ENABLED: "true"
              EXAMPLE_ENABLED: "false"
              GENERATE_FONTS: "true"         
            envFrom:
              - secretRef:
                  name: euro-office-env
      rabbitmq:
        containers:
          rabbitmq:
            image:
              repository: rabbitmq
              tag: "4.3-alpine"       

    service:
      euro-office:
        controller: euro-office
        ports:
          http:
            port: 80
          https:
            port: 443
      rabbitmq:
        controller: rabbitmq
        forceRename: rabbitmq
        ports:
          tcp:
            port: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: euro-office-lb
  namespace: nextcloud
  labels:
    app: euro-office
spec:
  type: LoadBalancer
  loadBalancerIP: 10.50.1.7
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: euro-office

