apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onlyoffice
  namespace: nextcloud
spec:
  interval: 10m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true 
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: "5.0.1"
  valuesFrom:
    - kind: Secret
      name: onlyoffice-secrets
      valuesKey: values.yaml
  values:
    controllers:
      onlyoffice:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "false"
        containers:
          app: 
            image:
              repository: onlyoffice/documentserver
              tag: "9.4@sha256:e3da62a847b9a5d51a11f73cfea1d9c13c3be3809614490d4edddcf01dcf919b"
              pullPolicy: IfNotPresent
            env:
              TZ: Europe/Berlin
              DB_TYPE: postgres
              DB_HOST: onlyoffice-db-rw
              DB_PORT: 5432
              DB_NAME: onlyoffice
              DB_USER: onlyoffice
            # Uncomment strings below to enable the JSON Web Token validation.
              JWT_ENABLED: true
              JWT_HEADER: AuthorizationJwt
              JWT_IN_BOD: true
              USE_UNAUTHORIZED_STORAGE: true              

       

    service:
      app:
        controller: onlyoffice
        ports:
          http:
            port: 80
          https:
            port: 443

---
apiVersion: v1
kind: Service
metadata:
  name: onlyoffice-lb
  namespace: nextcloud
  labels:
    app: onlyoffice
spec:
  type: LoadBalancer
  loadBalancerIP: 10.50.1.7
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: onlyoffice

