apiVersion: v1
kind: Secret
metadata:
    name: euro-office-db-secret
    namespace: nextcloud
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:wRCgkhuxQbAitWY=,iv:Ohom/rIKr8vtL5WDLsYB6d8B/72hySYjOGzi6pTH6wc=,tag:NY4gNgkE+vRSUPZRAw7tHQ==,type:str]
    password: ENC[AES256_GCM,data:ZwdDrG7EIRnAjxFPWe8=,iv:hu+rLgQZapZFSg6QcDHztCpLn5jn4pcmgV5tvqbGjVI=,tag:YGl8k7qFeJE+A1xQIbiQ3w==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T19:32:32Z"
    mac: ENC[AES256_GCM,data:ENyK97MvC/EuGOVA1j7l8xdWR/yc12oweQH6x9tcArj/6+jBHdMf6dNq/Q1N/0ddg64oHiWtNaizm/WwB85CIGJZQPeXAx8t4brhyb5zyv266IvWjTWB56amUBfY01xG1AmZWJVXaNSxBH8K9VCCyHWudDb4qH4mzyCkTPqHA6w=,iv:wgqhRd+g9LlH3UGgVe0yqOTbyWT6EBQ68Atu+Y+sKUs=,tag:qC0SC2UG9+TDlus2yddvrA==,type:str]
    pgp:
        - created_at: "2026-06-12T19:32:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv+PtLDBGbnNOxno++OmK2+rYENZka3zW3l14GvibVRisO9
            umXJD0M/blMk9Eqhh+HKr+myWngAcPqg6FI506GpdWWjUCFwK3WbIEF1b1HUciEY
            4RAraKyQSC37sD16eSLt+rCELkE110c8FwVnGnzNcY99YgsbCuAXIf44GpLrNBsV
            gVsuSP9azZxJQtw/Aoa39A+kEGy9HQ1PPAOAil2wTmv64TIhyZgbwOr0iEHD2y6T
            05Gx9qGamJnkan0KrBfoeojl0z8r2sT5BE2qmTIFpCvB5HLW3GsgNdc7D/kr4NUO
            YhI95OUYx07qVQPH1s/S5Clu4ZQnVLS5OVJ404iZS5Slvu/0nO44uFDsonIiKpib
            xR8ykWs4Slphp6sDagrYkIxLPyYPTIEpWCSwS6/16q/M8EnH33ruaDvDmpblOQF+
            X/TeqEVk3qJt9U3ekVe1ol0eJHlgC+G8gwCubzlh0CZgu0Gk73s6u2yPsvhZxIgd
            j8cu9oOqZARSVwfj/XWL0l4BWzVKDrrT4alb8m1cs0RSWuW2t0Z/Cr5IkvWEQbF6
            jfHmE2BStT59tNaxcmLbqNwKVbvcOsJtEQsgPymnpyl90zzWhCTv7r1zeImFb4R6
            VLRozwddEozz6zDuhoQx
            =bCfh
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: euro-office-env
    namespace: nextcloud
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:rcbxB+/L6nUtqN72rokExtyuqH/W21hVUYwVigdH3Iw=,iv:quFLlkQvA7+RmeWEmyV/gw0Jw2NwEge0LOtWxjwPKLE=,tag:OlUDOkIHwyPWlRKR+RdEZg==,type:str]
    AMQP_URI: ENC[AES256_GCM,data:HqHND1VZfRv88Desjc9FNPj533+6AHJsc48OzfDXD5Ccmuk1OKoUf7NUvCI=,iv:C6ZuOl+9k80pGYZ7wB7pwumRzxqI80zMkskFhPGFrpI=,tag:YHa/zufedPKo4TB0WrgzUA==,type:str]
type: Opaque
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T19:32:32Z"
    mac: ENC[AES256_GCM,data:ENyK97MvC/EuGOVA1j7l8xdWR/yc12oweQH6x9tcArj/6+jBHdMf6dNq/Q1N/0ddg64oHiWtNaizm/WwB85CIGJZQPeXAx8t4brhyb5zyv266IvWjTWB56amUBfY01xG1AmZWJVXaNSxBH8K9VCCyHWudDb4qH4mzyCkTPqHA6w=,iv:wgqhRd+g9LlH3UGgVe0yqOTbyWT6EBQ68Atu+Y+sKUs=,tag:qC0SC2UG9+TDlus2yddvrA==,type:str]
    pgp:
        - created_at: "2026-06-12T19:32:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv+PtLDBGbnNOxno++OmK2+rYENZka3zW3l14GvibVRisO9
            umXJD0M/blMk9Eqhh+HKr+myWngAcPqg6FI506GpdWWjUCFwK3WbIEF1b1HUciEY
            4RAraKyQSC37sD16eSLt+rCELkE110c8FwVnGnzNcY99YgsbCuAXIf44GpLrNBsV
            gVsuSP9azZxJQtw/Aoa39A+kEGy9HQ1PPAOAil2wTmv64TIhyZgbwOr0iEHD2y6T
            05Gx9qGamJnkan0KrBfoeojl0z8r2sT5BE2qmTIFpCvB5HLW3GsgNdc7D/kr4NUO
            YhI95OUYx07qVQPH1s/S5Clu4ZQnVLS5OVJ404iZS5Slvu/0nO44uFDsonIiKpib
            xR8ykWs4Slphp6sDagrYkIxLPyYPTIEpWCSwS6/16q/M8EnH33ruaDvDmpblOQF+
            X/TeqEVk3qJt9U3ekVe1ol0eJHlgC+G8gwCubzlh0CZgu0Gk73s6u2yPsvhZxIgd
            j8cu9oOqZARSVwfj/XWL0l4BWzVKDrrT4alb8m1cs0RSWuW2t0Z/Cr5IkvWEQbF6
            jfHmE2BStT59tNaxcmLbqNwKVbvcOsJtEQsgPymnpyl90zzWhCTv7r1zeImFb4R6
            VLRozwddEozz6zDuhoQx
            =bCfh
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-db-secret
    namespace: nextcloud
type: Opaque
stringData:
    db-username: ENC[AES256_GCM,data:a08yqtqiOiGN,iv:Yu2EWmnxCPeVu5gZOH2ALshMFUzJFjTwe01SykULROw=,tag:daLH/svi9kghihPAPYbjRw==,type:str]
    db-password: ENC[AES256_GCM,data:+JCCNdwIXHrr,iv:LLlewX5xTHSlVhJorjPSnsfVbRDriUkwJTTaoVE9a/Y=,tag:BrIth8rD1I5E5MQHLTgz3g==,type:str]
    username: ENC[AES256_GCM,data:01plkmwwddu7,iv:TC8Od/CGLrWgtQxb4vpGfel81QPZvb6k4XrZPBAZPlg=,tag:Y8OGGMQyl3Bf/2Ga4lDHAQ==,type:str]
    password: ENC[AES256_GCM,data:2gQE2gYYs4JYBXhzthHPlQ==,iv:LGSgxj8HYSYdmgF79qM6CMmeHeUxxsVxf+tGwoDyavg=,tag:QYKkQu0KOvxa3+pdkzg6hQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T19:32:32Z"
    mac: ENC[AES256_GCM,data:ENyK97MvC/EuGOVA1j7l8xdWR/yc12oweQH6x9tcArj/6+jBHdMf6dNq/Q1N/0ddg64oHiWtNaizm/WwB85CIGJZQPeXAx8t4brhyb5zyv266IvWjTWB56amUBfY01xG1AmZWJVXaNSxBH8K9VCCyHWudDb4qH4mzyCkTPqHA6w=,iv:wgqhRd+g9LlH3UGgVe0yqOTbyWT6EBQ68Atu+Y+sKUs=,tag:qC0SC2UG9+TDlus2yddvrA==,type:str]
    pgp:
        - created_at: "2026-06-12T19:32:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv+PtLDBGbnNOxno++OmK2+rYENZka3zW3l14GvibVRisO9
            umXJD0M/blMk9Eqhh+HKr+myWngAcPqg6FI506GpdWWjUCFwK3WbIEF1b1HUciEY
            4RAraKyQSC37sD16eSLt+rCELkE110c8FwVnGnzNcY99YgsbCuAXIf44GpLrNBsV
            gVsuSP9azZxJQtw/Aoa39A+kEGy9HQ1PPAOAil2wTmv64TIhyZgbwOr0iEHD2y6T
            05Gx9qGamJnkan0KrBfoeojl0z8r2sT5BE2qmTIFpCvB5HLW3GsgNdc7D/kr4NUO
            YhI95OUYx07qVQPH1s/S5Clu4ZQnVLS5OVJ404iZS5Slvu/0nO44uFDsonIiKpib
            xR8ykWs4Slphp6sDagrYkIxLPyYPTIEpWCSwS6/16q/M8EnH33ruaDvDmpblOQF+
            X/TeqEVk3qJt9U3ekVe1ol0eJHlgC+G8gwCubzlh0CZgu0Gk73s6u2yPsvhZxIgd
            j8cu9oOqZARSVwfj/XWL0l4BWzVKDrrT4alb8m1cs0RSWuW2t0Z/Cr5IkvWEQbF6
            jfHmE2BStT59tNaxcmLbqNwKVbvcOsJtEQsgPymnpyl90zzWhCTv7r1zeImFb4R6
            VLRozwddEozz6zDuhoQx
            =bCfh
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: garage-creds
    namespace: nextcloud
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:B9gqmRuqvcFA2b21YovOlJoYCVaDJYkAn5w=,iv:cjD7Cp3zUJdKldJv/TEma1YdqkuXZKxS4OaAwo1/viA=,tag:ewXB4pga1/71Emp6v1SmiA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:39SkGNWy5+SpdSsIMimYrR6L39JqCGw/+FaEn692rGXHswUIaHirffScei4e3hWZTN5rOvvhWbJ0Dle82f9w3g==,iv:i9D4z7zmvgXY/ZiCl7a70XllgnF/aQnLawNVtDL6OH4=,tag:9GNrOp+eZakn/k2xy6KfPA==,type:str]
    region: ENC[AES256_GCM,data:VCWQag==,iv:TBaHadWlGbK6XxGnum3y8A5GA/57CC0KMlhN1673WIw=,tag:Db3uAJ79gDAlSRZ1F7Bc/A==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T19:32:32Z"
    mac: ENC[AES256_GCM,data:ENyK97MvC/EuGOVA1j7l8xdWR/yc12oweQH6x9tcArj/6+jBHdMf6dNq/Q1N/0ddg64oHiWtNaizm/WwB85CIGJZQPeXAx8t4brhyb5zyv266IvWjTWB56amUBfY01xG1AmZWJVXaNSxBH8K9VCCyHWudDb4qH4mzyCkTPqHA6w=,iv:wgqhRd+g9LlH3UGgVe0yqOTbyWT6EBQ68Atu+Y+sKUs=,tag:qC0SC2UG9+TDlus2yddvrA==,type:str]
    pgp:
        - created_at: "2026-06-12T19:32:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv+PtLDBGbnNOxno++OmK2+rYENZka3zW3l14GvibVRisO9
            umXJD0M/blMk9Eqhh+HKr+myWngAcPqg6FI506GpdWWjUCFwK3WbIEF1b1HUciEY
            4RAraKyQSC37sD16eSLt+rCELkE110c8FwVnGnzNcY99YgsbCuAXIf44GpLrNBsV
            gVsuSP9azZxJQtw/Aoa39A+kEGy9HQ1PPAOAil2wTmv64TIhyZgbwOr0iEHD2y6T
            05Gx9qGamJnkan0KrBfoeojl0z8r2sT5BE2qmTIFpCvB5HLW3GsgNdc7D/kr4NUO
            YhI95OUYx07qVQPH1s/S5Clu4ZQnVLS5OVJ404iZS5Slvu/0nO44uFDsonIiKpib
            xR8ykWs4Slphp6sDagrYkIxLPyYPTIEpWCSwS6/16q/M8EnH33ruaDvDmpblOQF+
            X/TeqEVk3qJt9U3ekVe1ol0eJHlgC+G8gwCubzlh0CZgu0Gk73s6u2yPsvhZxIgd
            j8cu9oOqZARSVwfj/XWL0l4BWzVKDrrT4alb8m1cs0RSWuW2t0Z/Cr5IkvWEQbF6
            jfHmE2BStT59tNaxcmLbqNwKVbvcOsJtEQsgPymnpyl90zzWhCTv7r1zeImFb4R6
            VLRozwddEozz6zDuhoQx
            =bCfh
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
    namespace: nextcloud
type: Opaque
data:
    nextcloud-username: ENC[AES256_GCM,data:LdRCrVa8d/4=,iv:BRPWHOH72C2qNTlaTluAtJ6aGImjPO9lQM+TW/fnzJ8=,tag:fOX+4nbK22T2kYRYllr+7Q==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:AXm8KAuKHbsbKqfl,iv:Y89enIligJvZHKb7Hz7oYsZS3PBjFvMj0Yu7L4iA/Yc=,tag:5VT+Yn7OhaBH6WjYx1vvRA==,type:str]
    smtp-username: ENC[AES256_GCM,data:6s/6PC5dRBkNpE01EceLc+1/DHrbZNVJrJQUag==,iv:nPq0+p5x4lhwo493V9G8L4PHti6YDHNiXX3vDFF/3Jc=,tag:goaT8xvi3l8MHvgSzzM/nA==,type:str]
    smtp-password: ENC[AES256_GCM,data:XqObIZM5Qa2OsacdTu4rj7qyKj8=,iv:B9VqgTJkIzkOCU+VK+P7LI4VJLfy5pj9EXI6Ic7cBZA=,tag:8bEP2fMmgUrG9Z4jwiwDSw==,type:str]
    smtp-host: ENC[AES256_GCM,data:FgChLws3Qw5xbvlrwsVlHdHA/+cg/7Gj,iv:O6kk3gZ9mKC6q0LOQ8a4mf26eAVN7E4xO422oflhwnk=,tag:IRN6KN5g9TCk7JmV7O+o0A==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T19:32:32Z"
    mac: ENC[AES256_GCM,data:ENyK97MvC/EuGOVA1j7l8xdWR/yc12oweQH6x9tcArj/6+jBHdMf6dNq/Q1N/0ddg64oHiWtNaizm/WwB85CIGJZQPeXAx8t4brhyb5zyv266IvWjTWB56amUBfY01xG1AmZWJVXaNSxBH8K9VCCyHWudDb4qH4mzyCkTPqHA6w=,iv:wgqhRd+g9LlH3UGgVe0yqOTbyWT6EBQ68Atu+Y+sKUs=,tag:qC0SC2UG9+TDlus2yddvrA==,type:str]
    pgp:
        - created_at: "2026-06-12T19:32:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv+PtLDBGbnNOxno++OmK2+rYENZka3zW3l14GvibVRisO9
            umXJD0M/blMk9Eqhh+HKr+myWngAcPqg6FI506GpdWWjUCFwK3WbIEF1b1HUciEY
            4RAraKyQSC37sD16eSLt+rCELkE110c8FwVnGnzNcY99YgsbCuAXIf44GpLrNBsV
            gVsuSP9azZxJQtw/Aoa39A+kEGy9HQ1PPAOAil2wTmv64TIhyZgbwOr0iEHD2y6T
            05Gx9qGamJnkan0KrBfoeojl0z8r2sT5BE2qmTIFpCvB5HLW3GsgNdc7D/kr4NUO
            YhI95OUYx07qVQPH1s/S5Clu4ZQnVLS5OVJ404iZS5Slvu/0nO44uFDsonIiKpib
            xR8ykWs4Slphp6sDagrYkIxLPyYPTIEpWCSwS6/16q/M8EnH33ruaDvDmpblOQF+
            X/TeqEVk3qJt9U3ekVe1ol0eJHlgC+G8gwCubzlh0CZgu0Gk73s6u2yPsvhZxIgd
            j8cu9oOqZARSVwfj/XWL0l4BWzVKDrrT4alb8m1cs0RSWuW2t0Z/Cr5IkvWEQbF6
            jfHmE2BStT59tNaxcmLbqNwKVbvcOsJtEQsgPymnpyl90zzWhCTv7r1zeImFb4R6
            VLRozwddEozz6zDuhoQx
            =bCfh
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-config
    namespace: nextcloud
type: Opaque
stringData:
    #ENC[AES256_GCM,data:id/ibNYcdK3QUiZALKC+K32aHTTOmLHpvELx52OHph3uUB6mfK/45LXp6h6Kh3+QVsdPuKo/Z7uWBpWMVo3FS14=,iv:J/f+K9VdkLPSgkflrNpdTvne8GDpzizOGEeC7l1OAb8=,tag:XjDRdhC8u4HtkeNd4L9e8w==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:Eg9y/WmX+kMhMgIDDTf6eikbZcwQKlYicklLxT+Gt7F2aaDCD+LQ6sJIc//rMEjkpTfGOK8C8q8=,iv:B93z1gXoNoq5sKmm7GfVUlz6ALsYzK37IltVbce8y/c=,tag:nC01Fdf9Wv++Bz20FHrn0A==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:8WWkGxCWdCrUx+R3O7f0k0PBHUBogOF12FNMyiXvONV7/6bAgv9qIqDNrfmx92vi,iv:hIyGSYFirLrvThwdJ7YdtUZ+Rt6hbFw8THZEILOf42w=,tag:KeqfBbxsw2SJEZM2txlJ5w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:9O8aJufQIv7mDTtbz+gZW6PYdGORz2/yLPQ=,iv:SAc7uI76MgyhgJyr/BQwcGpF18okVMx+IIPwPxcm6Io=,tag:ufPjdHgfcDQw38/g3UmAmQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:sqClemhEMXGDRYwAmkSiW9tybUABMNp0t/V2BdFJ1yu8W5fs6fPw6lJf6G7ffSfklCzdafAhs4exDfURJBWNkA==,iv:sCeWqgFZuXKADAfoVGiSxSc36z1tNWYkNnejCdXugq0=,tag:s7FFq6f1x6Rf448Lcs1Crw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T19:32:32Z"
    mac: ENC[AES256_GCM,data:ENyK97MvC/EuGOVA1j7l8xdWR/yc12oweQH6x9tcArj/6+jBHdMf6dNq/Q1N/0ddg64oHiWtNaizm/WwB85CIGJZQPeXAx8t4brhyb5zyv266IvWjTWB56amUBfY01xG1AmZWJVXaNSxBH8K9VCCyHWudDb4qH4mzyCkTPqHA6w=,iv:wgqhRd+g9LlH3UGgVe0yqOTbyWT6EBQ68Atu+Y+sKUs=,tag:qC0SC2UG9+TDlus2yddvrA==,type:str]
    pgp:
        - created_at: "2026-06-12T19:32:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv+PtLDBGbnNOxno++OmK2+rYENZka3zW3l14GvibVRisO9
            umXJD0M/blMk9Eqhh+HKr+myWngAcPqg6FI506GpdWWjUCFwK3WbIEF1b1HUciEY
            4RAraKyQSC37sD16eSLt+rCELkE110c8FwVnGnzNcY99YgsbCuAXIf44GpLrNBsV
            gVsuSP9azZxJQtw/Aoa39A+kEGy9HQ1PPAOAil2wTmv64TIhyZgbwOr0iEHD2y6T
            05Gx9qGamJnkan0KrBfoeojl0z8r2sT5BE2qmTIFpCvB5HLW3GsgNdc7D/kr4NUO
            YhI95OUYx07qVQPH1s/S5Clu4ZQnVLS5OVJ404iZS5Slvu/0nO44uFDsonIiKpib
            xR8ykWs4Slphp6sDagrYkIxLPyYPTIEpWCSwS6/16q/M8EnH33ruaDvDmpblOQF+
            X/TeqEVk3qJt9U3ekVe1ol0eJHlgC+G8gwCubzlh0CZgu0Gk73s6u2yPsvhZxIgd
            j8cu9oOqZARSVwfj/XWL0l4BWzVKDrrT4alb8m1cs0RSWuW2t0Z/Cr5IkvWEQbF6
            jfHmE2BStT59tNaxcmLbqNwKVbvcOsJtEQsgPymnpyl90zzWhCTv7r1zeImFb4R6
            VLRozwddEozz6zDuhoQx
            =bCfh
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: data-restic-config
    namespace: nextcloud
type: Opaque
stringData:
    #ENC[AES256_GCM,data:RAt8qRKfppAtKUY2ikstiriW6wwLUkRelW8uRX6CFlU9wiSCioMjRM0svreMtar4t9utQX1A8ex/oF18/q0GdWc=,iv:9PJ5Jxxsabam96a48H8NxpeaYv5qOKsHsxZZ4RX9tW0=,tag:Lz5fQrcyyqq5oqf39yqYUw==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:ql8GgRpODfnnXC/apO4GnbyTaQwUcwYyk2aYmMAkbck6I3Z+Ln2rpOVTkXoOT1MtRGM0KN0C,iv:ba/zPYUs3AkY1JVUWINHWJCFwXh+ozEH1VheKbNXplg=,tag:RvcqjVGrGYJDCNjCZ0Y0Lw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:4kn7akH+uDOX3THx6nibVoH1papf9xzP9hYz4Z1ublFz3+/ABgMcVPEQg1+4Gpw+,iv:48X1iA1rc673FYf7ECBga5OQeq7l4xdn54oT7uQMQNM=,tag:v7K1Jga5KN+FqnFXR1RMnA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:6vKZk0uwn4xhcowEmJBy804MHBEUh7Uum3k=,iv:fRBwx+ETqD0iS+MFwMCfwCUJL4YebgDXaSjKBkm754w=,tag:DyZPBtMUSLy1SXZgHFWECQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:A6ZDvnVw+y6xDaBmYE4dK7eN6mmdPoz/8OzzrrYG3LXrYT+GR3qw8hc3tI6fx0OtsSMTHDAZGzHOLdWpX6zqWA==,iv:gRG1UHT6KxETAeNfNNnsHnt6J3cBD9HsFJ3jNI88VZQ=,tag:IaApjHcfGWDWam2sHlUmZA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T19:32:32Z"
    mac: ENC[AES256_GCM,data:ENyK97MvC/EuGOVA1j7l8xdWR/yc12oweQH6x9tcArj/6+jBHdMf6dNq/Q1N/0ddg64oHiWtNaizm/WwB85CIGJZQPeXAx8t4brhyb5zyv266IvWjTWB56amUBfY01xG1AmZWJVXaNSxBH8K9VCCyHWudDb4qH4mzyCkTPqHA6w=,iv:wgqhRd+g9LlH3UGgVe0yqOTbyWT6EBQ68Atu+Y+sKUs=,tag:qC0SC2UG9+TDlus2yddvrA==,type:str]
    pgp:
        - created_at: "2026-06-12T19:32:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv+PtLDBGbnNOxno++OmK2+rYENZka3zW3l14GvibVRisO9
            umXJD0M/blMk9Eqhh+HKr+myWngAcPqg6FI506GpdWWjUCFwK3WbIEF1b1HUciEY
            4RAraKyQSC37sD16eSLt+rCELkE110c8FwVnGnzNcY99YgsbCuAXIf44GpLrNBsV
            gVsuSP9azZxJQtw/Aoa39A+kEGy9HQ1PPAOAil2wTmv64TIhyZgbwOr0iEHD2y6T
            05Gx9qGamJnkan0KrBfoeojl0z8r2sT5BE2qmTIFpCvB5HLW3GsgNdc7D/kr4NUO
            YhI95OUYx07qVQPH1s/S5Clu4ZQnVLS5OVJ404iZS5Slvu/0nO44uFDsonIiKpib
            xR8ykWs4Slphp6sDagrYkIxLPyYPTIEpWCSwS6/16q/M8EnH33ruaDvDmpblOQF+
            X/TeqEVk3qJt9U3ekVe1ol0eJHlgC+G8gwCubzlh0CZgu0Gk73s6u2yPsvhZxIgd
            j8cu9oOqZARSVwfj/XWL0l4BWzVKDrrT4alb8m1cs0RSWuW2t0Z/Cr5IkvWEQbF6
            jfHmE2BStT59tNaxcmLbqNwKVbvcOsJtEQsgPymnpyl90zzWhCTv7r1zeImFb4R6
            VLRozwddEozz6zDuhoQx
            =bCfh
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
