apiVersion: v1
kind: Secret
metadata:
    name: onlyoffice-db-secret
    namespace: nextcloud
type: Opaque
data:
    username: ENC[AES256_GCM,data:GFtzXzIRvKeosqMjqvs0uw==,iv:c35yNXKCRra9Gf/S7CGlqabUkLmcQ72ljFuutgBM540=,tag:YXwsGsrGVhrRRLq42BHpnQ==,type:str]
    password: ENC[AES256_GCM,data:lc4BIQR6uDz2f1gr69JeT3pe6YQ=,iv:kjCdVO8L8Oog3ku1eyDj0LXD2jh7W/vp88hrtWSPo6s=,tag:8xqiHVn8wdKEFiCER05/mQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-10T12:50:35Z"
    mac: ENC[AES256_GCM,data:5B25O/D56EtbXAuR+FFyFF/RvZhQxHB80pwNY6VfHZadI89bCiGGjixHxS4ovLYjm+AYruOyoHBPoItL4+0Bq2IPkQGzi3QSAvzwlag3qnsRCiYIjYLe3H8pKFFeS4PO/3+uEbwTT3huw9MijW7uhgEOtQ76VueMMay5Z4BoVUY=,iv:pSIdhABs98IEG0W62xhvpCJAw/uXV/Ny0I9L8aa9aVg=,tag:xzmDwagLW0sgU+Sx23BSGQ==,type:str]
    pgp:
        - created_at: "2026-05-10T12:50:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQwAkBx8bONciyjk9Ho9AIucLTgFdNuLJoy7Yd9DYiMw9mgi
            yt8CDWznlW9MVOmoQ0sNj9CEGpmN8XZzEPArpvzqIho/71zHebm0AvkIBVXnyg1S
            5umaLdo4SOqrh7xK2qdTvqKARrL4Gpo8mXgcg/unwa66pV59gfNaKgFUYKnPws06
            oIeNRu4SdW+5WVodDtQEygMbW/VAr1C2jrgqKTn8u5om0oGxUG+zmv1RhJHoUoGe
            OsC89QXO4KPvR1Z/XWWKHwFaSG3ziO3xE9d/7nXiovxCnWZPm8PR+kzZaUG1NMzT
            ia6AXyPrf2RGdwgtb9DEl1DqyGSBpF7YU8qYE7lG0rq0p/OaMLRVKkjkPWV4s0RH
            QD1SkHGpCLwv5fuqAVQUbwnM30JNCbfUi9b693XCg0oczEEHRCXkzQnWeuGlxCwZ
            c5I3KcKB5cWKEZrrpo+PNXgRKUiSpJUGnQ+tPbF9OjN6Q2Y46DhLZKntJo+MWt8G
            G8Kv26vA9iRydecW4QbW0lwBjhRc12toa6ocDbO341WdIwI7fsjsq7nzwp3l32yu
            eI1Ar7085imRyH1BupekNLo7VlrHN0woIDZRtp4HNIfHLIY9h24o+MjIRPd/eex2
            L5Z/PU45VRsbV+x14w==
            =K0uf
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: onlyoffice-secrets
    namespace: nextcloud
stringData:
    values.yaml: ENC[AES256_GCM,data:2o2vpelnUjSaNO7lq67OPX71WMiTIoUNmv7IWwcRkZ8was3BVhQ9vqo3gW8YVhh56PUu8TGHJUtvMjF3D1hqIngXerPWNIypledTLN530fqpSUhW8otYO+ZIEpTzMucPdGXppSohATm+enZ+GzjwxZdO0ODxsLE9Zx3PzWQakAecDEuOFVw8BOh7cxtfuGXF48EZlO9417V54dV3ohNd2fflakXb7ME9yEYgWUTkDusdnHHrnzGZht4JU3xsT9HGEHwT6wJmrR+sgbUPJHjosKLeH3q9AqUH4EoJYBxf,iv:QomHrHCajBtFuWDjF4FfnqC2ak7+o/MUN3W64OG63QU=,tag:L+c8cZsPTMh64GQZ7mchCw==,type:str]
type: Opaque
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-10T12:50:35Z"
    mac: ENC[AES256_GCM,data:5B25O/D56EtbXAuR+FFyFF/RvZhQxHB80pwNY6VfHZadI89bCiGGjixHxS4ovLYjm+AYruOyoHBPoItL4+0Bq2IPkQGzi3QSAvzwlag3qnsRCiYIjYLe3H8pKFFeS4PO/3+uEbwTT3huw9MijW7uhgEOtQ76VueMMay5Z4BoVUY=,iv:pSIdhABs98IEG0W62xhvpCJAw/uXV/Ny0I9L8aa9aVg=,tag:xzmDwagLW0sgU+Sx23BSGQ==,type:str]
    pgp:
        - created_at: "2026-05-10T12:50:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQwAkBx8bONciyjk9Ho9AIucLTgFdNuLJoy7Yd9DYiMw9mgi
            yt8CDWznlW9MVOmoQ0sNj9CEGpmN8XZzEPArpvzqIho/71zHebm0AvkIBVXnyg1S
            5umaLdo4SOqrh7xK2qdTvqKARrL4Gpo8mXgcg/unwa66pV59gfNaKgFUYKnPws06
            oIeNRu4SdW+5WVodDtQEygMbW/VAr1C2jrgqKTn8u5om0oGxUG+zmv1RhJHoUoGe
            OsC89QXO4KPvR1Z/XWWKHwFaSG3ziO3xE9d/7nXiovxCnWZPm8PR+kzZaUG1NMzT
            ia6AXyPrf2RGdwgtb9DEl1DqyGSBpF7YU8qYE7lG0rq0p/OaMLRVKkjkPWV4s0RH
            QD1SkHGpCLwv5fuqAVQUbwnM30JNCbfUi9b693XCg0oczEEHRCXkzQnWeuGlxCwZ
            c5I3KcKB5cWKEZrrpo+PNXgRKUiSpJUGnQ+tPbF9OjN6Q2Y46DhLZKntJo+MWt8G
            G8Kv26vA9iRydecW4QbW0lwBjhRc12toa6ocDbO341WdIwI7fsjsq7nzwp3l32yu
            eI1Ar7085imRyH1BupekNLo7VlrHN0woIDZRtp4HNIfHLIY9h24o+MjIRPd/eex2
            L5Z/PU45VRsbV+x14w==
            =K0uf
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-db-secret
    namespace: nextcloud
type: Opaque
stringData:
    db-username: ENC[AES256_GCM,data:wVyWuh+CwQdp,iv:ZJTd3Ty7deePxdBzU/w+4PTe5EsNP/N+oaWkldt3DuQ=,tag:z9B1uSqIQfO0hpGDiFJgcA==,type:str]
    db-password: ENC[AES256_GCM,data:3lWXPM2ytVhf,iv:bQ2rp1r4vMuMZkvOrLVwCKQd0SyAfVocpgXXGnxhNi8=,tag:/CAHByYuWaXhwirRQiXkXQ==,type:str]
    username: ENC[AES256_GCM,data:bhjNmtbAWT9D,iv:7atyxW9MRJNotFgKzH1pMAJ03Qjqjp8+1il8pCy4OKI=,tag:+5annIgKrIMHPzpt6LAHBg==,type:str]
    password: ENC[AES256_GCM,data:CibsvyuRBnttqJh8htoJkw==,iv:XpHkk+tuT5lOoHrIpRrvhKoU7VAaPHqbC3z2nyj9Bmw=,tag:PlrMg0MS73hrDgz9lS6ohA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-10T12:50:35Z"
    mac: ENC[AES256_GCM,data:5B25O/D56EtbXAuR+FFyFF/RvZhQxHB80pwNY6VfHZadI89bCiGGjixHxS4ovLYjm+AYruOyoHBPoItL4+0Bq2IPkQGzi3QSAvzwlag3qnsRCiYIjYLe3H8pKFFeS4PO/3+uEbwTT3huw9MijW7uhgEOtQ76VueMMay5Z4BoVUY=,iv:pSIdhABs98IEG0W62xhvpCJAw/uXV/Ny0I9L8aa9aVg=,tag:xzmDwagLW0sgU+Sx23BSGQ==,type:str]
    pgp:
        - created_at: "2026-05-10T12:50:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQwAkBx8bONciyjk9Ho9AIucLTgFdNuLJoy7Yd9DYiMw9mgi
            yt8CDWznlW9MVOmoQ0sNj9CEGpmN8XZzEPArpvzqIho/71zHebm0AvkIBVXnyg1S
            5umaLdo4SOqrh7xK2qdTvqKARrL4Gpo8mXgcg/unwa66pV59gfNaKgFUYKnPws06
            oIeNRu4SdW+5WVodDtQEygMbW/VAr1C2jrgqKTn8u5om0oGxUG+zmv1RhJHoUoGe
            OsC89QXO4KPvR1Z/XWWKHwFaSG3ziO3xE9d/7nXiovxCnWZPm8PR+kzZaUG1NMzT
            ia6AXyPrf2RGdwgtb9DEl1DqyGSBpF7YU8qYE7lG0rq0p/OaMLRVKkjkPWV4s0RH
            QD1SkHGpCLwv5fuqAVQUbwnM30JNCbfUi9b693XCg0oczEEHRCXkzQnWeuGlxCwZ
            c5I3KcKB5cWKEZrrpo+PNXgRKUiSpJUGnQ+tPbF9OjN6Q2Y46DhLZKntJo+MWt8G
            G8Kv26vA9iRydecW4QbW0lwBjhRc12toa6ocDbO341WdIwI7fsjsq7nzwp3l32yu
            eI1Ar7085imRyH1BupekNLo7VlrHN0woIDZRtp4HNIfHLIY9h24o+MjIRPd/eex2
            L5Z/PU45VRsbV+x14w==
            =K0uf
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: garage-creds
    namespace: nextcloud
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:VCLS7JGs6dLJhGPWgxEU11CwSf1TBOSq+Cg=,iv:MvdWHl1Iux8iNTi0zPErYTJqT0NEU/ubWRg7UcTfwEE=,tag:HNG+BZDE+V6y7tVmwbMA9A==,type:str]
    secret-access-key: ENC[AES256_GCM,data:GOqXOnf95PMWBKS1JFocarkSIEKCRscbIF/lxjfhsW9sPmQTEajxPy9DtgpQCREOmzqD8wiSZJKWx064FKs2lA==,iv:aQeV06CeorJYC4TvsrnYFFNsSirXGNDxOBtUBgKZci4=,tag:JZ8AsqQzcv7jCiYMuIw7UQ==,type:str]
    region: ENC[AES256_GCM,data:KUcxaA==,iv:A4fFqwr6/dnajgy4yGat+5StpE5SlGxRKGNoEHd4mN0=,tag:Xjj/RzD2+3VE5doy/ZdHHQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-10T12:50:35Z"
    mac: ENC[AES256_GCM,data:5B25O/D56EtbXAuR+FFyFF/RvZhQxHB80pwNY6VfHZadI89bCiGGjixHxS4ovLYjm+AYruOyoHBPoItL4+0Bq2IPkQGzi3QSAvzwlag3qnsRCiYIjYLe3H8pKFFeS4PO/3+uEbwTT3huw9MijW7uhgEOtQ76VueMMay5Z4BoVUY=,iv:pSIdhABs98IEG0W62xhvpCJAw/uXV/Ny0I9L8aa9aVg=,tag:xzmDwagLW0sgU+Sx23BSGQ==,type:str]
    pgp:
        - created_at: "2026-05-10T12:50:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQwAkBx8bONciyjk9Ho9AIucLTgFdNuLJoy7Yd9DYiMw9mgi
            yt8CDWznlW9MVOmoQ0sNj9CEGpmN8XZzEPArpvzqIho/71zHebm0AvkIBVXnyg1S
            5umaLdo4SOqrh7xK2qdTvqKARrL4Gpo8mXgcg/unwa66pV59gfNaKgFUYKnPws06
            oIeNRu4SdW+5WVodDtQEygMbW/VAr1C2jrgqKTn8u5om0oGxUG+zmv1RhJHoUoGe
            OsC89QXO4KPvR1Z/XWWKHwFaSG3ziO3xE9d/7nXiovxCnWZPm8PR+kzZaUG1NMzT
            ia6AXyPrf2RGdwgtb9DEl1DqyGSBpF7YU8qYE7lG0rq0p/OaMLRVKkjkPWV4s0RH
            QD1SkHGpCLwv5fuqAVQUbwnM30JNCbfUi9b693XCg0oczEEHRCXkzQnWeuGlxCwZ
            c5I3KcKB5cWKEZrrpo+PNXgRKUiSpJUGnQ+tPbF9OjN6Q2Y46DhLZKntJo+MWt8G
            G8Kv26vA9iRydecW4QbW0lwBjhRc12toa6ocDbO341WdIwI7fsjsq7nzwp3l32yu
            eI1Ar7085imRyH1BupekNLo7VlrHN0woIDZRtp4HNIfHLIY9h24o+MjIRPd/eex2
            L5Z/PU45VRsbV+x14w==
            =K0uf
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
    namespace: nextcloud
type: Opaque
data:
    nextcloud-username: ENC[AES256_GCM,data:hBjyy3IwFms=,iv:aTUrRf+0cWaWx4hAZIec7RWbNvCQCmCoXMGruro16eY=,tag:J2/i0zTW6UZUe/CVwB6BiQ==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:LF4DRsuloB2S30hH,iv:SGr3s811faK0gFFqLBA7fL5+H9JZESMvfuHp17EO7qg=,tag:mwjXo2go0MJ0PMLTfr08Ng==,type:str]
    smtp-username: ENC[AES256_GCM,data:CyDMjypcnq1WGKbYyU5BC7wk6L63PFVR6HjQFw==,iv:nU4jBmuGpCXD4dgwHRdFq9wcyrJU3gEW+2gJldo/vjg=,tag:CQVqK8SUJ3iTWdH7ud6GPQ==,type:str]
    smtp-password: ENC[AES256_GCM,data:5qYLm+2xzqXqHq0eYb5rEAsXYyc=,iv:yGxkrVN3G/2QaOcUkZRKH6E6rkKHQ0+NdJNpB3saG1M=,tag:Y9ag3lZ1wzjVuXSxP0B8zA==,type:str]
    smtp-host: ENC[AES256_GCM,data:hxM/oAG6W11IS2DjdPCibIrl5EUIamSM,iv:lLHAZkwzudzEEbf3klQBuGZ4JqqRjwNlGOWvbegb/RQ=,tag:6CQG5bLpTncRUOEdPGgiuw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-10T12:50:35Z"
    mac: ENC[AES256_GCM,data:5B25O/D56EtbXAuR+FFyFF/RvZhQxHB80pwNY6VfHZadI89bCiGGjixHxS4ovLYjm+AYruOyoHBPoItL4+0Bq2IPkQGzi3QSAvzwlag3qnsRCiYIjYLe3H8pKFFeS4PO/3+uEbwTT3huw9MijW7uhgEOtQ76VueMMay5Z4BoVUY=,iv:pSIdhABs98IEG0W62xhvpCJAw/uXV/Ny0I9L8aa9aVg=,tag:xzmDwagLW0sgU+Sx23BSGQ==,type:str]
    pgp:
        - created_at: "2026-05-10T12:50:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQwAkBx8bONciyjk9Ho9AIucLTgFdNuLJoy7Yd9DYiMw9mgi
            yt8CDWznlW9MVOmoQ0sNj9CEGpmN8XZzEPArpvzqIho/71zHebm0AvkIBVXnyg1S
            5umaLdo4SOqrh7xK2qdTvqKARrL4Gpo8mXgcg/unwa66pV59gfNaKgFUYKnPws06
            oIeNRu4SdW+5WVodDtQEygMbW/VAr1C2jrgqKTn8u5om0oGxUG+zmv1RhJHoUoGe
            OsC89QXO4KPvR1Z/XWWKHwFaSG3ziO3xE9d/7nXiovxCnWZPm8PR+kzZaUG1NMzT
            ia6AXyPrf2RGdwgtb9DEl1DqyGSBpF7YU8qYE7lG0rq0p/OaMLRVKkjkPWV4s0RH
            QD1SkHGpCLwv5fuqAVQUbwnM30JNCbfUi9b693XCg0oczEEHRCXkzQnWeuGlxCwZ
            c5I3KcKB5cWKEZrrpo+PNXgRKUiSpJUGnQ+tPbF9OjN6Q2Y46DhLZKntJo+MWt8G
            G8Kv26vA9iRydecW4QbW0lwBjhRc12toa6ocDbO341WdIwI7fsjsq7nzwp3l32yu
            eI1Ar7085imRyH1BupekNLo7VlrHN0woIDZRtp4HNIfHLIY9h24o+MjIRPd/eex2
            L5Z/PU45VRsbV+x14w==
            =K0uf
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-config
    namespace: nextcloud
type: Opaque
stringData:
    #ENC[AES256_GCM,data:3rcAZqWx9gJSyTY18UOrNlApf1xg27rCI9L0+Y3SeoaoXBDhOsUtNBRDR7v6CORZfL73CH42jCEOP3lH7g9Kw8Y=,iv:S2i0X0mcugaEU0laYU4QYi4/wmQJkoCtVFpm1JrPQfo=,tag:EL7VRRL1BfWMhPPkeOQbfw==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:KrvxBSCGreaZjiKvOz+M4bggo+5YMcHdkuoM9Jk3NSRZkZrxxPvPIcZJwv2V+H3F3FjQ5n/+UIU=,iv:LFgbSYvdQDBKEZ6Px/hrc5EP/Ca0lGMZCF1z7zBsAJY=,tag:G4LvI9YaIUo8Bl9qZNgAJg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:VYm+JRWz1RI0itrWcGBY+RhsrT0uQosnNjDPz90ItfRpCg4Mwaq4bzV1Vs8YUtyt,iv:gZufSFDHX5aZaFsUcI5ixiQF9Q6Flgy/XwQv5R2s6N0=,tag:hKZjqoLipLTmh1wT4UMsrQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:TqeuzX+6UC4MAwqekSmWzs4YwfMAAf/yxv4=,iv:DeRDTct19LJ2tzO+NXxNyfmANwMecJg5jFpcZ28tpLs=,tag:ocLvlHZq3I+6KLzo+M3tBw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:c9iNBg/z/vXP3ZA7ReRYT4A5kn4FE8PcfNk6fBRfl9uasUJBBwzdlrDkOls5LnyD11RIdDfuGoXaT/wH2Z9EqA==,iv:Ac0BQIMDscK3xevSM2KFx0WeVFGfjnix4i/2+WXPCzE=,tag:KputO9o8nieBFhXloCdC2A==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-10T12:50:35Z"
    mac: ENC[AES256_GCM,data:5B25O/D56EtbXAuR+FFyFF/RvZhQxHB80pwNY6VfHZadI89bCiGGjixHxS4ovLYjm+AYruOyoHBPoItL4+0Bq2IPkQGzi3QSAvzwlag3qnsRCiYIjYLe3H8pKFFeS4PO/3+uEbwTT3huw9MijW7uhgEOtQ76VueMMay5Z4BoVUY=,iv:pSIdhABs98IEG0W62xhvpCJAw/uXV/Ny0I9L8aa9aVg=,tag:xzmDwagLW0sgU+Sx23BSGQ==,type:str]
    pgp:
        - created_at: "2026-05-10T12:50:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQwAkBx8bONciyjk9Ho9AIucLTgFdNuLJoy7Yd9DYiMw9mgi
            yt8CDWznlW9MVOmoQ0sNj9CEGpmN8XZzEPArpvzqIho/71zHebm0AvkIBVXnyg1S
            5umaLdo4SOqrh7xK2qdTvqKARrL4Gpo8mXgcg/unwa66pV59gfNaKgFUYKnPws06
            oIeNRu4SdW+5WVodDtQEygMbW/VAr1C2jrgqKTn8u5om0oGxUG+zmv1RhJHoUoGe
            OsC89QXO4KPvR1Z/XWWKHwFaSG3ziO3xE9d/7nXiovxCnWZPm8PR+kzZaUG1NMzT
            ia6AXyPrf2RGdwgtb9DEl1DqyGSBpF7YU8qYE7lG0rq0p/OaMLRVKkjkPWV4s0RH
            QD1SkHGpCLwv5fuqAVQUbwnM30JNCbfUi9b693XCg0oczEEHRCXkzQnWeuGlxCwZ
            c5I3KcKB5cWKEZrrpo+PNXgRKUiSpJUGnQ+tPbF9OjN6Q2Y46DhLZKntJo+MWt8G
            G8Kv26vA9iRydecW4QbW0lwBjhRc12toa6ocDbO341WdIwI7fsjsq7nzwp3l32yu
            eI1Ar7085imRyH1BupekNLo7VlrHN0woIDZRtp4HNIfHLIY9h24o+MjIRPd/eex2
            L5Z/PU45VRsbV+x14w==
            =K0uf
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: data-restic-config
    namespace: nextcloud
type: Opaque
stringData:
    #ENC[AES256_GCM,data:RM3iuOI/huByn+apCSBddLrYZsEA9x5oPLgUXfv8ek6gLYPriKs9ndloLCaICbOwdgQ16u5JKt2dGquBvIP56fw=,iv:WG+UlRe4G42r6e2Cc+4dXcEfkoI2khjR4VbH6G3sk7A=,tag:PhELN9l3scV6HVMhNjgnzQ==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:lsPSfwGgwAZc+NjeruGRqFnycxZ7ZyZVi6oQ10wjqQnyhbvEA2b268VUqNFI7fUBRDj0Hun+,iv:r1GBPyXr7v+b7ALIC/aeS9nuNZndM/IAiCInFjr24yw=,tag:OYXp8CHtfbe3du/Fv8mhxA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:kn7Yqk0y/cDSKPYyoxRQ5485KK3os80h3hC6V3oBskomE/W+hhLfAFTDkc5zkq3N,iv:+iSkWteXOOeheCrS6gqnct0/hWFVuX7boynZNjj4p88=,tag:+aNseeJ/qAdABAUGCCeayA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:6cjOLuTsw9W6nDS7WeIXiYGnFzG4iarGfRk=,iv:xhCRKGEQ20W7bXnucpRTj80ChVK2U/cgsyheKCme8gY=,tag:Ql1PgYUL9LFtExpXmV84pw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:0m7xPYGfQyiIWp4n1fZlaYKGp9GX59jlwZiwIdgFHOqGuchCmIQM2hSo4vnJMm4nROxw3/FTN+4B9Eb9cug9TA==,iv:VFnbEAnccI1FieBshZznEr1qOXsVjh6Q901tiv4H/Rs=,tag:oxD31ToCLLLteYgrwxpK3A==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-10T12:50:35Z"
    mac: ENC[AES256_GCM,data:5B25O/D56EtbXAuR+FFyFF/RvZhQxHB80pwNY6VfHZadI89bCiGGjixHxS4ovLYjm+AYruOyoHBPoItL4+0Bq2IPkQGzi3QSAvzwlag3qnsRCiYIjYLe3H8pKFFeS4PO/3+uEbwTT3huw9MijW7uhgEOtQ76VueMMay5Z4BoVUY=,iv:pSIdhABs98IEG0W62xhvpCJAw/uXV/Ny0I9L8aa9aVg=,tag:xzmDwagLW0sgU+Sx23BSGQ==,type:str]
    pgp:
        - created_at: "2026-05-10T12:50:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQwAkBx8bONciyjk9Ho9AIucLTgFdNuLJoy7Yd9DYiMw9mgi
            yt8CDWznlW9MVOmoQ0sNj9CEGpmN8XZzEPArpvzqIho/71zHebm0AvkIBVXnyg1S
            5umaLdo4SOqrh7xK2qdTvqKARrL4Gpo8mXgcg/unwa66pV59gfNaKgFUYKnPws06
            oIeNRu4SdW+5WVodDtQEygMbW/VAr1C2jrgqKTn8u5om0oGxUG+zmv1RhJHoUoGe
            OsC89QXO4KPvR1Z/XWWKHwFaSG3ziO3xE9d/7nXiovxCnWZPm8PR+kzZaUG1NMzT
            ia6AXyPrf2RGdwgtb9DEl1DqyGSBpF7YU8qYE7lG0rq0p/OaMLRVKkjkPWV4s0RH
            QD1SkHGpCLwv5fuqAVQUbwnM30JNCbfUi9b693XCg0oczEEHRCXkzQnWeuGlxCwZ
            c5I3KcKB5cWKEZrrpo+PNXgRKUiSpJUGnQ+tPbF9OjN6Q2Y46DhLZKntJo+MWt8G
            G8Kv26vA9iRydecW4QbW0lwBjhRc12toa6ocDbO341WdIwI7fsjsq7nzwp3l32yu
            eI1Ar7085imRyH1BupekNLo7VlrHN0woIDZRtp4HNIfHLIY9h24o+MjIRPd/eex2
            L5Z/PU45VRsbV+x14w==
            =K0uf
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.0
