apiVersion: v1
kind: Secret
metadata:
    name: talos-backup-env
    namespace: talos
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:+Ix5cDLKIsWGPv95W5V2cXx8z4jJUuJMjyw=,iv:oXNYn1I9aO26LpeovT3ilm1qr/l4V6J15ZPiQv4DCoo=,tag:WF4Fco4eWy8tmYykH2XRvQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:BGPxouBtZw5QG6FQB8bdQP3nIveN6+17+xXu68P1nxSkDQvHScppUFwoxBZKAu+/pXSG2SiPJpI+ggTMPrjdzQ==,iv:o1yQKAUhYUJ0K17NmaLiKFN1iVmo9n8MuzEsEy7EpAo=,tag:eofp9Xj5ihIUgXFG9G4foQ==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:xjw4VQ==,iv:ck+btMAdpnmr3xkxPGUAmG29g0kQjhbO4RJ0e8YJLAQ=,tag:tOQmM6sZJtWxxBBeenlhQw==,type:str]
    CUSTOM_S3_ENDPOINT: ENC[AES256_GCM,data:dk0Wyy6il0Z8nUaDA4TWwr9xTda+Nm/8Saz0rg==,iv:0zWWbbB//j9wxCocwSAVLNa9yS6H3WV5XvTZXGurvr8=,tag:emHQD04C0trdQsNiE+fTjg==,type:str]
    BUCKET: ENC[AES256_GCM,data:VPM08l8VhASP44qx,iv:nbfWBnkGx2sAfYcjow3trJXXDX20FFgYgdf/F3bWdpo=,tag:GMOn8ETcX8iSFjoKC3C2Jw==,type:str]
    CLUSTER_NAME: ENC[AES256_GCM,data:v8gCWgCjIHy9,iv:RxvMyZmTYYQ2oeMbE6rUAruk9m8Hs9zeNsn4uO0P1zk=,tag:QIyCXocJBkQnL+krcWFabg==,type:str]
    AGE_X25519_PUBLIC_KEY: ENC[AES256_GCM,data:EYYHMS1rg8GHYClCvlRV6IAknUkQC5+kYpiAFIZQFIA/TsDaEVR/Q4KowcV3hH/bmGYLTKn9ZiIfYHcZllg=,iv:FaOSjMR99ntfRBzwm3fGc4R/1mRbLLX6YqlHwrxuZ2A=,tag:Fcq2LMA6dd1RoybH6k69ZQ==,type:str]
    USE_PATH_STYLE: ENC[AES256_GCM,data:UlBvcw==,iv:+R8qq2XD8stRLXvKVjaA7OZ4ERuXTBtba+oxhGMvZHA=,tag:ltORMnWREGc5DqepWNbpXg==,type:str]
sops:
    lastmodified: "2026-03-24T16:57:48Z"
    mac: ENC[AES256_GCM,data:3ZJcytgCoBtPhMQQaQJA7u3dRJ1Wm0K9n40ADWVZGrKIFXZDMTWgZmqXQE8+DszPwPTJc/RnmYQFhENT8cankwpnfX069cgOy3sBbU66Xw0vJ4fiKkB+V0J488SqJiMVZeYvq4jBigmoH5daknbLmxG38TuGnc0vxQFRrmUbzas=,iv:BlGlzAFlMbIqlmMr2MJwtYT8xXnoSvOXuU44Wiz2e/8=,tag:ICHpoWIqX4M5NVj3vJxh7g==,type:str]
    pgp:
        - created_at: "2026-03-24T16:57:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQwAo0bhe19hBr5/FARdGHA9zzi0jZ3ujfgitusMSEJZ6RS+
            EGfsOaTUbdfpdXRAEhrmWSZHq7UHwvdQBh+JazjF5YgUuVYCXFi669eDRjLnF7Yt
            crLjXSd21KaYsHoRPLJxA6BwkqwFOSfLOGAxrW/4uEQ5CKT3qXdf5+LRAvLbcd52
            CMejbfsHED2KpVlcTo0prfaR5Th1fnFRjeeL0c5uj67bNTCuAug+yAc9ZcU9Sr9R
            1R4/7qSvmHiiR/1znZ72FPqrdYGqiJjn8LuGa97zMgRvhkeDDKWch7QWI0Q9+2ct
            tTtca+maxHH8T9UXrIZDvLr4DqZjgIZu3hXf4y7hWQ4ujCC5XHlze5hFkR7Jmoq6
            BgSDcUo6+U622IqRntWfLX7iZVgBZ4hJ6KV2pM1GFOIhn9f4sN0CV4a5c8QdvUsQ
            wU71RXj9W95zvbmcsu2fsHCXk5873x4Ns49sbqHI63y/kmq2vlRrxecyv2rtDPJl
            EzjCHL01tEa4FxS4CUrV0l4BIZdXCQ3lrgwdfCmjkOgdqgthnPP2gqMrBdsQ+UMK
            6qojoanzkZWnuxjx7j0zGM0fQPyw6izIKIG1brHCXpE6JZW0VvPe5xUefgzRAOUW
            hxmPwW8qxevjPXHGThWK
            =MD2V
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
