apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-csi-cephfs
  namespace: ceph-csi-cephfs
spec:
  interval: 10m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true 
  chart:
    spec:
      chart: ceph-csi-cephfs
      sourceRef:
        kind: HelmRepository
        name: ceph-csi
        namespace: flux-system
      version: "3.17.0"
  values:
    csiConfig:
      - clusterID: "31095d64-7bff-11f0-8065-d9f210f0c539"
        monitors: 
          - "10.50.0.21:6789"
          - "10.50.0.22:6789"
          - "10.50.0.23:6789"
        provisionerSecretName: "csi-cephfs-secret"
        provisionerSecretNamespace: "ceph-csi-cephfs"
        nodeStageSecretName: "csi-cephfs-secret"
        nodeStageSecretNamespace: "ceph-csi-cephfs"
        cephFS:
          subvolumeGroup: "csi"
    provisioner:
      name: provisioner
      replicaCount: 3
    storageClass:
      create: true
      name: csi-cephfs-sc
      clusterID: "31095d64-7bff-11f0-8065-d9f210f0c539"
      fsName: "talos-cephfs"
      provisionerSecret: csi-cephfs-secret
      provisionerSecretNamespace: "ceph-csi-cephfs"
      controllerExpandSecret: csi-cephfs-secret
      controllerExpandSecretNamespace: "ceph-csi-cephfs"
      nodeStageSecret: csi-cephfs-secret
      nodeStageSecretNamespace: "ceph-csi-cephfs"
      mounter: kernel
      reclaimPolicy: Delete
      allowVolumeExpansion: true
    volumeSnapshotClass:
      create: false