apiVersion: v1
kind: Secret
metadata:
    name: csi-rbd-secret
    namespace: ceph-csi
type: Opaque
stringData:
    userID: ENC[AES256_GCM,data:NTVJ0PXm730I,iv:yiZ7MVJqUXtLNJAuC3WdkQ20ic766Gb4SopxQIK+feE=,tag:8NvGjqFWbTcc0HoXxUSrWw==,type:str]
    userKey: ENC[AES256_GCM,data:cL9VJKOC0a3JJUOb60s3Exbxttl0lTwLAaS5uzPMkX+zJ65oObkSAA==,iv:4iiSMMciLdzIjYfL+l/N28xF5HZ7FiLVe7oHnxlC+6M=,tag:nCQgvrcx3Zvg0YhSTUBykQ==,type:str]
sops:
    lastmodified: "2026-03-16T15:49:22Z"
    mac: ENC[AES256_GCM,data:ZuqoIUoVQACsQ9AAXR3gk21+zPVDWmN6Kro3RKJF3lHAX/fXySou3vP4eu2Fb6hbYYZCluAv7UyRS3Q5xIIPlL91PSpdeP/vQycxgUGnFSJfxavfMBlBHiGSWRj+Nw6fGdahvMTzSBPNKvrkjzPe5GX424n6vK4TfXgO0QtVo7U=,iv:zxkPABkGlLCTmdHRp14acmVevoZC24TbGbtOVcC81GU=,tag:7bxzddJdcOQdBMQ1zgDLaA==,type:str]
    pgp:
        - created_at: "2026-03-16T15:49:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv+PPi/gexOGypt6xXGZ98JR9g2Ia03PGQctE2Nhde6m5Qu
            ViFYrsE+c93sXL857k3lVAl9o4EOQPAKiZaBoKe/e3jGglo1aQCKAVMqFYb5shcl
            F32bljJYCNuywLrRrtgJNqoHXS+8gqc5ZDeovXWfFQR6wDRvcurdUZp7kn/AGWFq
            /QvilwSm5ipmdGPMld6jWay4CHSpAQWhVtqJCEF9nzGdRsV3Wi+/WIPmAfVYEee8
            cod7Oa/b/RBWDGeMBCKaanw4bo+Q1faftSQ3Ij1NYkLzPjGTcAWTrCjkto0Ru9Z7
            MXKpvBlcX+/AZV+AagUZ4myCejnvES4PO7FSsHxJU7fCl12olVg8FP764gBiYT1q
            7Wh9BIVSYsz7SbGkO4tnvgjexx6vchiMnd5k/PADcOuSvbWFJMW8KBL6VIj42deJ
            79QxAAMp3XeL3XDozgOAm3EN6PfIg9K0Zqz2oTe7r5hzm0sEIrl9dz4rgqWt+x9A
            RULtaJIJg3bp9zT4bQ5K0l4BfoVAj0HdRyZiivWRhUX1WsoP23pysL3IwODBjAjK
            ovkIkyUicrFzSB0uZgNKcRa6APqPwWlCIg0RaI3F8YVY129ODYE7RKrPHj5hE3g1
            kXaf4sR6ve/W6GNgMCSe
            =olWJ
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: csi-cephfs-secret
    namespace: ceph-csi-cephfs
type: Opaque
stringData:
    userID: ENC[AES256_GCM,data:DUIMkkKqp65Oz/5V,iv:D3Qb6nvbiI3xAfXJYy6SNo1sFKtaJqcFyDqKzui/Nlw=,tag:P80vZdReFnFaVHD6RLhmJQ==,type:str]
    userKey: ENC[AES256_GCM,data:lT+G6xXbiCJ/vvI+/vhxd/yDTc3cBY/sUZd707IFJKuqCs1ycsXFQA==,iv:5ldyMIrodfceBOpkX3Yfk2Xkv/1x7vUyIz4QybW2xQU=,tag:dYkP9em+0tBF0SwGeUhe0Q==,type:str]
    adminID: ENC[AES256_GCM,data:GdB7xDI=,iv:a2BecMA/Od8mixrFaxJkDJnbUl3i4LyI3CROGExXLTg=,tag:Pr3V79uvlbw6BcyJMsWyzA==,type:str]
    adminKey: ENC[AES256_GCM,data:dqwB4/W6CkRfTEpY2nrYQlsuDvLzLYa55/sQ/27tb/bfQzzPomqvOQ==,iv:mb1AwkBRkFUrlgb/5PtZSDIlQlMVg+ZEoNtRJusJqNY=,tag:HYN9gKpRPsajyEbkZJScvA==,type:str]
sops:
    lastmodified: "2026-03-16T15:49:22Z"
    mac: ENC[AES256_GCM,data:ZuqoIUoVQACsQ9AAXR3gk21+zPVDWmN6Kro3RKJF3lHAX/fXySou3vP4eu2Fb6hbYYZCluAv7UyRS3Q5xIIPlL91PSpdeP/vQycxgUGnFSJfxavfMBlBHiGSWRj+Nw6fGdahvMTzSBPNKvrkjzPe5GX424n6vK4TfXgO0QtVo7U=,iv:zxkPABkGlLCTmdHRp14acmVevoZC24TbGbtOVcC81GU=,tag:7bxzddJdcOQdBMQ1zgDLaA==,type:str]
    pgp:
        - created_at: "2026-03-16T15:49:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv+PPi/gexOGypt6xXGZ98JR9g2Ia03PGQctE2Nhde6m5Qu
            ViFYrsE+c93sXL857k3lVAl9o4EOQPAKiZaBoKe/e3jGglo1aQCKAVMqFYb5shcl
            F32bljJYCNuywLrRrtgJNqoHXS+8gqc5ZDeovXWfFQR6wDRvcurdUZp7kn/AGWFq
            /QvilwSm5ipmdGPMld6jWay4CHSpAQWhVtqJCEF9nzGdRsV3Wi+/WIPmAfVYEee8
            cod7Oa/b/RBWDGeMBCKaanw4bo+Q1faftSQ3Ij1NYkLzPjGTcAWTrCjkto0Ru9Z7
            MXKpvBlcX+/AZV+AagUZ4myCejnvES4PO7FSsHxJU7fCl12olVg8FP764gBiYT1q
            7Wh9BIVSYsz7SbGkO4tnvgjexx6vchiMnd5k/PADcOuSvbWFJMW8KBL6VIj42deJ
            79QxAAMp3XeL3XDozgOAm3EN6PfIg9K0Zqz2oTe7r5hzm0sEIrl9dz4rgqWt+x9A
            RULtaJIJg3bp9zT4bQ5K0l4BfoVAj0HdRyZiivWRhUX1WsoP23pysL3IwODBjAjK
            ovkIkyUicrFzSB0uZgNKcRa6APqPwWlCIg0RaI3F8YVY129ODYE7RKrPHj5hE3g1
            kXaf4sR6ve/W6GNgMCSe
            =olWJ
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
