apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: global-image-updates
  namespace: flux-system
spec:
  interval: 10m

  sourceRef:
    kind: GitRepository
    name: flux-system

  git:
    checkout:
      ref:
        branch: main

    commit:
      author:
        name: flux-image-automation
        email: flux-image-automation@example.invalid
      messageTemplate: |
        chore(images): automated image updates

        {{ range .Changed.Changes -}}
        {{ .OldValue }} -> {{ .NewValue }}
        {{ end -}}

    push:
      branch: main

  update:
    path: ./clusters/talos-pve
    strategy: Setters