apiVersion: v1
kind: Secret
metadata:
    name: mailarchive-db-secret
    namespace: mailarchive
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:fKfOxv0O150U8Y4=,iv:p0gsXEVmHcwy9IJ0W4eQTvBvwKSfjrfuDP5muvWDkgU=,tag:hvPNbslt5nZ80wBnbI0pig==,type:str]
    password: ENC[AES256_GCM,data:7m7UpibIsoImghXmEgD0GQ==,iv:kVbarXFhlzdw9quALIyXCii76wyTDqkxxRL4UIsxQOg=,tag:YZhN7htp41QFJPEv5hl7nQ==,type:str]
sops:
    lastmodified: "2026-03-21T10:21:08Z"
    mac: ENC[AES256_GCM,data:iR55vD1WNpytk4Ed+yCIA1evTryM2xjZugiLHmpDyAR0E4OJGqX3dVbcZPiyw4s9nuWL/3oeU9Rtuw2bJ2qiMQoXRAJieRdahesWCCjd2dGiVgqv7AgA6L4Q4oTTVwTn5Gpece+oGXimG5fOCboeDRcImbWUGmcpQucgLuMO4w4=,iv:FRoz8mGTzO5ajHhIRt1SVMEWmaIVGiEHqWuHWlQX43Y=,tag:IGN5OCH5ehXMKMeBtfX+lw==,type:str]
    pgp:
        - created_at: "2026-03-21T10:21:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv+PcEW/6U11rYM1Qdxs7oB5xNxRUt5WOrG+xcYMFVfe9YM
            MmcqdJxKAPluGCjJN5Tdbv9ePgRgctS4Og1+3UbT7554koRTt89mScOrW5ZG027I
            jOsHRKDV/ktDMWmvIWCj32dUP17A8aBabWqZXMQCb/OJFGmRJtt1HmD4b9j0exdI
            /BYJKP9WrqseXdaHSZYBRcLR8d3MlSBxdV98Re2cIuwFoSN79YCi6IAvD7yUooQt
            WEX+J9iXMCZCY7xOUIGNSnftBgM27vF5mn4ewjc0U6Uqk1zt1ekE51LvBRlVhg5H
            Gs8/RM3U3RA2YcKL11DQEx/usL5i8xWTy0VUw0dYOa9QORGOS0auZrP6pklrVtDQ
            gY3EW4Lv0/WC0CpLdtdx0wfH0kSypzj0cBz1gR9UMzR0PyAnHSA5zXFZ4tIKHu51
            v1rqP+qKT6SIVyCLPoujpm3RvDGJyu/q+tB2Bt8G8i/kvIBZfFLdqWZaXhK94mU/
            o+RjGUZxsmspYxn3w4q+0l4B9IshmHG67LyJsU7NUS9mqyoqjhaqruN7ULNXq9pN
            niwvkMImAMFvWJHLyeHi4TmNynau7JM46SY+orgYB1pcxswcPET3WwFkM8m3kYY4
            ES/rMoghhX8Jq+Bk7EeY
            =ipOY
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: garage-creds
    namespace: mailarchive
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:qO0IEQt9SutIwWZKw/Qc4D8D2QuUIoDrQlk=,iv:FJmV0eeZ3817vF9hpdne3yVzy0Y6/4azf5ewBbjSlcM=,tag:vP6CXCYgPg301TT3o/J1pQ==,type:str]
    secret-access-key: ENC[AES256_GCM,data:r/JsgQETicFGz+yn0+uvSPAzRHR+IYEwsBveHR70TuIiPmoKM2fIv3hO3UfEgqgcU+8iB7i28wbBIT+NNv68rg==,iv:jeHRcENJyJvxxV30pQtxydGoHBUgSrSYfFLABtdaeJI=,tag:8jq55kvURfdWh7KEHI1dUA==,type:str]
    region: ENC[AES256_GCM,data:+cJqcQ==,iv:UfRMi1Ci04BGq5DThY1foe2uzJ3XGaMQkP/IS2lTfks=,tag:blx/7IAeSlLEl6JpbMrpnw==,type:str]
sops:
    lastmodified: "2026-03-21T10:21:08Z"
    mac: ENC[AES256_GCM,data:iR55vD1WNpytk4Ed+yCIA1evTryM2xjZugiLHmpDyAR0E4OJGqX3dVbcZPiyw4s9nuWL/3oeU9Rtuw2bJ2qiMQoXRAJieRdahesWCCjd2dGiVgqv7AgA6L4Q4oTTVwTn5Gpece+oGXimG5fOCboeDRcImbWUGmcpQucgLuMO4w4=,iv:FRoz8mGTzO5ajHhIRt1SVMEWmaIVGiEHqWuHWlQX43Y=,tag:IGN5OCH5ehXMKMeBtfX+lw==,type:str]
    pgp:
        - created_at: "2026-03-21T10:21:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv+PcEW/6U11rYM1Qdxs7oB5xNxRUt5WOrG+xcYMFVfe9YM
            MmcqdJxKAPluGCjJN5Tdbv9ePgRgctS4Og1+3UbT7554koRTt89mScOrW5ZG027I
            jOsHRKDV/ktDMWmvIWCj32dUP17A8aBabWqZXMQCb/OJFGmRJtt1HmD4b9j0exdI
            /BYJKP9WrqseXdaHSZYBRcLR8d3MlSBxdV98Re2cIuwFoSN79YCi6IAvD7yUooQt
            WEX+J9iXMCZCY7xOUIGNSnftBgM27vF5mn4ewjc0U6Uqk1zt1ekE51LvBRlVhg5H
            Gs8/RM3U3RA2YcKL11DQEx/usL5i8xWTy0VUw0dYOa9QORGOS0auZrP6pklrVtDQ
            gY3EW4Lv0/WC0CpLdtdx0wfH0kSypzj0cBz1gR9UMzR0PyAnHSA5zXFZ4tIKHu51
            v1rqP+qKT6SIVyCLPoujpm3RvDGJyu/q+tB2Bt8G8i/kvIBZfFLdqWZaXhK94mU/
            o+RjGUZxsmspYxn3w4q+0l4B9IshmHG67LyJsU7NUS9mqyoqjhaqruN7ULNXq9pN
            niwvkMImAMFvWJHLyeHi4TmNynau7JM46SY+orgYB1pcxswcPET3WwFkM8m3kYY4
            ES/rMoghhX8Jq+Bk7EeY
            =ipOY
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: mailarchive-env
    namespace: mailarchive
type: Opaque
stringData:
    ConnectionStrings__DefaultConnection: ENC[AES256_GCM,data:H4X08IPhH6hxf9rnCvHxoX+rPfx+w4MARdc40gTI45bRZq7jfo66jW/0ODZliO3ghW7+DZqO6isICFCDbkkw63GO1j3QukalvS5AC7My4FlTSbo9Tooph9Ep,iv:PZ5Fopnj0IM+5cXh3VBXmd9IB+21IhM3iFdJTbSd4Ec=,tag:0Nu8kTEvaDNIV4CHjRcIOg==,type:str]
    OAuth__ClientId: ENC[AES256_GCM,data:Ra2nxnXnwqPfgNe6KAjSh3QkYDMs2qUqeBw5ZMUEoUkkJumpRkYfRA==,iv:ZRG7lYRbRFVTe/tuLw7DpNVKtzfQDGsSXvrRL9rOESo=,tag:2douzgy3ucSfmSapdSa5NA==,type:str]
    OAuth__ClientSecret: ENC[AES256_GCM,data:iQE9TKRBzFtmaeBqVv98dcW1qTSDOcRpq9wm77pVP1gqoo+k48d8GYQFZUfq+0RZpahJnU+ZTL2Wor2YjmBTc0oU3CWgu1QePHBGCPk+o1nY97PXgOwwwLiZsV2nPY+dWrgP8KbVSETaJ2BjlrMSO8QUoAoygwbFMfFhYVGhR7g=,iv:EgW1mLeM4QRonYnmSaZwJdCwAPoM4TKMgvlRVVLurpw=,tag:ltsVLrRsIGREIQm1QlaJoA==,type:str]
sops:
    lastmodified: "2026-03-21T10:21:08Z"
    mac: ENC[AES256_GCM,data:iR55vD1WNpytk4Ed+yCIA1evTryM2xjZugiLHmpDyAR0E4OJGqX3dVbcZPiyw4s9nuWL/3oeU9Rtuw2bJ2qiMQoXRAJieRdahesWCCjd2dGiVgqv7AgA6L4Q4oTTVwTn5Gpece+oGXimG5fOCboeDRcImbWUGmcpQucgLuMO4w4=,iv:FRoz8mGTzO5ajHhIRt1SVMEWmaIVGiEHqWuHWlQX43Y=,tag:IGN5OCH5ehXMKMeBtfX+lw==,type:str]
    pgp:
        - created_at: "2026-03-21T10:21:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv+PcEW/6U11rYM1Qdxs7oB5xNxRUt5WOrG+xcYMFVfe9YM
            MmcqdJxKAPluGCjJN5Tdbv9ePgRgctS4Og1+3UbT7554koRTt89mScOrW5ZG027I
            jOsHRKDV/ktDMWmvIWCj32dUP17A8aBabWqZXMQCb/OJFGmRJtt1HmD4b9j0exdI
            /BYJKP9WrqseXdaHSZYBRcLR8d3MlSBxdV98Re2cIuwFoSN79YCi6IAvD7yUooQt
            WEX+J9iXMCZCY7xOUIGNSnftBgM27vF5mn4ewjc0U6Uqk1zt1ekE51LvBRlVhg5H
            Gs8/RM3U3RA2YcKL11DQEx/usL5i8xWTy0VUw0dYOa9QORGOS0auZrP6pklrVtDQ
            gY3EW4Lv0/WC0CpLdtdx0wfH0kSypzj0cBz1gR9UMzR0PyAnHSA5zXFZ4tIKHu51
            v1rqP+qKT6SIVyCLPoujpm3RvDGJyu/q+tB2Bt8G8i/kvIBZfFLdqWZaXhK94mU/
            o+RjGUZxsmspYxn3w4q+0l4B9IshmHG67LyJsU7NUS9mqyoqjhaqruN7ULNXq9pN
            niwvkMImAMFvWJHLyeHi4TmNynau7JM46SY+orgYB1pcxswcPET3WwFkM8m3kYY4
            ES/rMoghhX8Jq+Bk7EeY
            =ipOY
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
