apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
stringData:
    values.yaml: ENC[AES256_GCM,data:T+zUd78OVrUqn/CSiYcVF/I1ZogRlalH6MCxU729hPiDRLGpA/W1ihefQn8R3ewTn6cKLPcOYyJ+Pmzps+TcR1h5DN4FEUqFBKcVjyaVigsj62ARgbMRm90UnvGNVjcArmNRoq0r0Sr3+SORTISGabXeY1mI2NAtEwiznPaOivOvehov0+ScHApaP9FGKzgKMM6IksmxqRNDfTPrcAHRwA==,iv:syfkMoIgmRp1d6b3DJW7+gqIwHXwbWrmX4eQNrgSMyw=,tag:ZOMCkgIAs/sKa4PLVl0BxA==,type:str]
type: Opaque
sops:
    lastmodified: "2025-12-18T10:20:19Z"
    mac: ENC[AES256_GCM,data:3x4UhUuLWZ3vS22i1f+TqOR2Q/d8DnUZojJn4zh3/M84idJeuxBfLXUYpbArk0LOPH1doauKRAj3K2+1abgbMsJUFVGIzHyuWv0RB9AZWqRJskskW3nbMEMUemTSuhbPGR3J66Iwr47t1wxbd0nbI+L7AlD6zltTQDVykKopQDQ=,iv:+oP8Xx+J/RvzxWjXK5IBGcWEmpLNKJBloMpABBxUJnY=,tag:c9pDqZX/D3sXzBSoStKwnQ==,type:str]
    pgp:
        - created_at: "2025-12-18T10:20:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv8DaQ49JnrS3RDIPngiHpI1hNJxRrR8gQStEU8vsJnD2Yu
            vB0poqN7i8czKFaq+vG/gQQW5IyRrietnavYkEjhYzMSM7SlzdWnTrtqFBadITMI
            X1cl/K+e1sTpXchBfJWYGTnShu2KqdQliU3/EdyW8YoElbA2OUiDjWtsn6t6LWZp
            qnuy6Lcvt5kN6h3Y1ZrCVsAJRMruEtbwfTc12I9Ls4DL0UiZ1u/EImvGCCXCzAP1
            eR0RwNE3YV0jnSR/4Ss1eUNDmEa5duV2wu1RudeoJt7B0iHmwm0VsOuWZDtF9srn
            G6sQAdGiSdJeDXov6bne9fuNd1C2w3tvZGoshipTSqQPBwgUjiYwLslrPgU0szD6
            q0r1gnZbQ4EKuy8rKF18OXZy90cWpSSRvH94A1ZphBUR0Glnf20JXnu/EmpUXpli
            FM+QC8S7wDQoB1HSgUsJ+z6ILgWR0ul8T5pfUAmOt4yLYLK6kub4xRvZ8C03TRS/
            YXdmD9JbGlquF2AOyNLb0lwBkWRWh55//5iuoaZv4YWkhwdnxrXgyRbyusb7MOnZ
            4fMLxACy4tGVt9LtBo/Hdgd0muoUF6cSGIqWXi2AResTLUD/JsK530K7MhcsuMcJ
            Te5tGWdzr184u304Zw==
            =ykql
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
data:
    password: ENC[AES256_GCM,data:F++ja+o7mDpr6dfHZSs4QA==,iv:s5VAkn4uvBH1KvMQyGA0rIjd3QfqJZ2/ixhZNGq5AQk=,tag:ZWgTxMaEAn+WyDvLiplLfw==,type:str]
    username: ENC[AES256_GCM,data:7COfEMLiacuwdN4t,iv:kaBbI60QY1PYGXOnYrOnpCRwcFuYOVewNEp16exkRdI=,tag:HQw5c/AwIe9PQDKYp4xUQw==,type:str]
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: authentik
type: Opaque
sops:
    lastmodified: "2025-12-18T10:20:19Z"
    mac: ENC[AES256_GCM,data:3x4UhUuLWZ3vS22i1f+TqOR2Q/d8DnUZojJn4zh3/M84idJeuxBfLXUYpbArk0LOPH1doauKRAj3K2+1abgbMsJUFVGIzHyuWv0RB9AZWqRJskskW3nbMEMUemTSuhbPGR3J66Iwr47t1wxbd0nbI+L7AlD6zltTQDVykKopQDQ=,iv:+oP8Xx+J/RvzxWjXK5IBGcWEmpLNKJBloMpABBxUJnY=,tag:c9pDqZX/D3sXzBSoStKwnQ==,type:str]
    pgp:
        - created_at: "2025-12-18T10:20:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv8DaQ49JnrS3RDIPngiHpI1hNJxRrR8gQStEU8vsJnD2Yu
            vB0poqN7i8czKFaq+vG/gQQW5IyRrietnavYkEjhYzMSM7SlzdWnTrtqFBadITMI
            X1cl/K+e1sTpXchBfJWYGTnShu2KqdQliU3/EdyW8YoElbA2OUiDjWtsn6t6LWZp
            qnuy6Lcvt5kN6h3Y1ZrCVsAJRMruEtbwfTc12I9Ls4DL0UiZ1u/EImvGCCXCzAP1
            eR0RwNE3YV0jnSR/4Ss1eUNDmEa5duV2wu1RudeoJt7B0iHmwm0VsOuWZDtF9srn
            G6sQAdGiSdJeDXov6bne9fuNd1C2w3tvZGoshipTSqQPBwgUjiYwLslrPgU0szD6
            q0r1gnZbQ4EKuy8rKF18OXZy90cWpSSRvH94A1ZphBUR0Glnf20JXnu/EmpUXpli
            FM+QC8S7wDQoB1HSgUsJ+z6ILgWR0ul8T5pfUAmOt4yLYLK6kub4xRvZ8C03TRS/
            YXdmD9JbGlquF2AOyNLb0lwBkWRWh55//5iuoaZv4YWkhwdnxrXgyRbyusb7MOnZ
            4fMLxACy4tGVt9LtBo/Hdgd0muoUF6cSGIqWXi2AResTLUD/JsK530K7MhcsuMcJ
            Te5tGWdzr184u304Zw==
            =ykql
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: s3-creds
    namespace: authentik
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:4jo1Huj9VbvKK6xq89oCedOk4S6oovHomI4=,iv:AoTyL/mDBL/kYe3WIIRBAJJNxmuQ0uNXTXE/hUA6GTU=,tag:Z/nRtf9oIA8rjlWJIHF/Aw==,type:str]
    secret-access-key: ENC[AES256_GCM,data:798D5ZEBi6li1etenE+xcEKf96/AbIlivhIudZUecfT6aByr/7XhZcro8BBLcIb8sOz/m+1prLjzQcvRBPH00A==,iv:RI5EB26tDnD20uIq60us2nOyyys5v5+siPTjt1Tv7X0=,tag:dlg53XPcc2j6Winur1So1Q==,type:str]
    region: ENC[AES256_GCM,data:9STv2g==,iv:m8gpBETkKPIWoXL3zqgSmxkCX3YWeuNORewhuDRh1bQ=,tag:lVFhFsMhMLQV749fM/Ixig==,type:str]
sops:
    lastmodified: "2025-12-18T10:20:19Z"
    mac: ENC[AES256_GCM,data:3x4UhUuLWZ3vS22i1f+TqOR2Q/d8DnUZojJn4zh3/M84idJeuxBfLXUYpbArk0LOPH1doauKRAj3K2+1abgbMsJUFVGIzHyuWv0RB9AZWqRJskskW3nbMEMUemTSuhbPGR3J66Iwr47t1wxbd0nbI+L7AlD6zltTQDVykKopQDQ=,iv:+oP8Xx+J/RvzxWjXK5IBGcWEmpLNKJBloMpABBxUJnY=,tag:c9pDqZX/D3sXzBSoStKwnQ==,type:str]
    pgp:
        - created_at: "2025-12-18T10:20:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv8DaQ49JnrS3RDIPngiHpI1hNJxRrR8gQStEU8vsJnD2Yu
            vB0poqN7i8czKFaq+vG/gQQW5IyRrietnavYkEjhYzMSM7SlzdWnTrtqFBadITMI
            X1cl/K+e1sTpXchBfJWYGTnShu2KqdQliU3/EdyW8YoElbA2OUiDjWtsn6t6LWZp
            qnuy6Lcvt5kN6h3Y1ZrCVsAJRMruEtbwfTc12I9Ls4DL0UiZ1u/EImvGCCXCzAP1
            eR0RwNE3YV0jnSR/4Ss1eUNDmEa5duV2wu1RudeoJt7B0iHmwm0VsOuWZDtF9srn
            G6sQAdGiSdJeDXov6bne9fuNd1C2w3tvZGoshipTSqQPBwgUjiYwLslrPgU0szD6
            q0r1gnZbQ4EKuy8rKF18OXZy90cWpSSRvH94A1ZphBUR0Glnf20JXnu/EmpUXpli
            FM+QC8S7wDQoB1HSgUsJ+z6ILgWR0ul8T5pfUAmOt4yLYLK6kub4xRvZ8C03TRS/
            YXdmD9JbGlquF2AOyNLb0lwBkWRWh55//5iuoaZv4YWkhwdnxrXgyRbyusb7MOnZ
            4fMLxACy4tGVt9LtBo/Hdgd0muoUF6cSGIqWXi2AResTLUD/JsK530K7MhcsuMcJ
            Te5tGWdzr184u304Zw==
            =ykql
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: geoip-cred
    namespace: authentik
type: Opaque
stringData:
    account_id: ENC[AES256_GCM,data:XS70QmNC,iv:uHF9QbnLvqBZsY8yAc9TADg4Q+1mlyPujOAEJxxSBsA=,tag:wJpH7acs2BNA3rWlXOPj/w==,type:str]
    license_key: ENC[AES256_GCM,data:jgQcEjTLVIcA9v4CyNuu1P5pwYGLlYNJ1raO1fzY1T+PlggC4UW8Hg==,iv:iX8ahwvewx3/EgIv6EOUeeLbLgYAsSRTTym0Q4uaCxc=,tag:IMllQKfSvoktyfy5UY2VYA==,type:str]
sops:
    lastmodified: "2025-12-18T10:20:19Z"
    mac: ENC[AES256_GCM,data:3x4UhUuLWZ3vS22i1f+TqOR2Q/d8DnUZojJn4zh3/M84idJeuxBfLXUYpbArk0LOPH1doauKRAj3K2+1abgbMsJUFVGIzHyuWv0RB9AZWqRJskskW3nbMEMUemTSuhbPGR3J66Iwr47t1wxbd0nbI+L7AlD6zltTQDVykKopQDQ=,iv:+oP8Xx+J/RvzxWjXK5IBGcWEmpLNKJBloMpABBxUJnY=,tag:c9pDqZX/D3sXzBSoStKwnQ==,type:str]
    pgp:
        - created_at: "2025-12-18T10:20:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv8DaQ49JnrS3RDIPngiHpI1hNJxRrR8gQStEU8vsJnD2Yu
            vB0poqN7i8czKFaq+vG/gQQW5IyRrietnavYkEjhYzMSM7SlzdWnTrtqFBadITMI
            X1cl/K+e1sTpXchBfJWYGTnShu2KqdQliU3/EdyW8YoElbA2OUiDjWtsn6t6LWZp
            qnuy6Lcvt5kN6h3Y1ZrCVsAJRMruEtbwfTc12I9Ls4DL0UiZ1u/EImvGCCXCzAP1
            eR0RwNE3YV0jnSR/4Ss1eUNDmEa5duV2wu1RudeoJt7B0iHmwm0VsOuWZDtF9srn
            G6sQAdGiSdJeDXov6bne9fuNd1C2w3tvZGoshipTSqQPBwgUjiYwLslrPgU0szD6
            q0r1gnZbQ4EKuy8rKF18OXZy90cWpSSRvH94A1ZphBUR0Glnf20JXnu/EmpUXpli
            FM+QC8S7wDQoB1HSgUsJ+z6ILgWR0ul8T5pfUAmOt4yLYLK6kub4xRvZ8C03TRS/
            YXdmD9JbGlquF2AOyNLb0lwBkWRWh55//5iuoaZv4YWkhwdnxrXgyRbyusb7MOnZ
            4fMLxACy4tGVt9LtBo/Hdgd0muoUF6cSGIqWXi2AResTLUD/JsK530K7MhcsuMcJ
            Te5tGWdzr184u304Zw==
            =ykql
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
