apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
stringData:
    values.yaml: ENC[AES256_GCM,data:FHuIkFvk0eatcVnbqrLrCiM3yvuXN8CsKjj+FgFKfU9l+GG8p8a+eaBQT6t9VW/5AnW3A5vgwLEX1Xou2TE1rmWm9CxtsyIYVY2AFTy0Ldq7gnmKQF3anSw7l1Y2oChwVjJNG9C6lr0+jbg9mnvyh1pP0Wb4MzUL2+TdxV3k0H7aRv/z/vwy6DckasaT2BbxNYsS5ZJVd0odfNycMMR6xw==,iv:dz+PQkgGM8xlifZrk5WBmFs8139jPIE1CuqMwuyDYEY=,tag:BhTzxjl3wWqG7PKzZykqmA==,type:str]
type: Opaque
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T12:54:03Z"
    mac: ENC[AES256_GCM,data:yShdelBxfAeMguSkSjePu08M7c8qc2fwJhOmxbz184vN+izWWCjQ/3A6j9t6U96UCDcrmgEeb7Lkg8wT14XP+ntN4q+bWMT4ZEzwTyvEGtlpA6yfvZAxm0qRSQDT3l/KcbtNnl/IvV3r4ay3DO+synrY4bQnPKFGyDf660yk2is=,iv:nMqEnR0p6MPZLxThRX9ayk1AMgZCUXwpOOptH7mr2RQ=,tag:NHmJJZwHCoq5Eomsgy0wZA==,type:str]
    pgp:
        - created_at: "2026-07-04T12:54:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv+MVdkeG5ThufxbynLOFg8WQolH9x4+bKnOFcIvIoOzeRd
            RfGFj314kANHxRJdAXCkmknvUqrgpcakMb/aI8mpK66I3UJDZIqnWrnPwp59H9QN
            10xMujaqJIZQbQ8J9pI8Ae/LsYVItfawplvXJQfPGDgo9uUYTSUwL0F9D8en/kgY
            aq16FC9mSd+unTLKOVeN2fjdWCWWuWdWnuSMtFZTtqSpZyPEK3Z3Hs96EQX9gPyU
            5pEvC6QNU74SyDg+J2zYpsqVVO0KrF+R0FasSDbtqrh/ffvD4Fc2xMBTCHlMXdKS
            ZGN0h6DTZPSuYkkDmMihWTLez8BOP2QdOIDvCm3AxnEEMEYAhxQAAuJZgM+hEBEk
            VsCCO+fzOdL5dEJaW3s3NJ8ftx+u6rIYEQ4FU8ejKP3LTSjPSWDYSkygZjJ3fyg/
            1sSSw4BGKljRHfhAAHbkbwnEu6xVQATzYqgNuJQRZVpwsznPK1mmrs29iWH+/xbU
            eHH4PF1DBA459RaqHS/80lwBkUWUdRZM6JwTsbXzOLSa1hleozBgGXFWzxuryBk5
            AJEvmNvEMuQpNoecqHCV4C1d7o6WfN58UrKO6byLMLYXjMSiHyV6KNbYlStn6S+N
            GmWf5/Nh7bEvI7huOA==
            =fb+e
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.2
---
apiVersion: v1
data:
    password: ENC[AES256_GCM,data:3pgBl+jwbKd1anwdMFoKTA==,iv:EiY2eH7BdfAnjwjmcQ+ficpUdrUys4RPamtCpv4cxNs=,tag:/BsmqKN8qn/dJU6+M2Welw==,type:str]
    username: ENC[AES256_GCM,data:mF/R0ua6MyFIdPBA,iv:e0SL6FYmvQe+OhIjhgv84z+D09eyZD45XOkE/nlJ2sI=,tag:EREpkDUkdLuDXVCnL7PcdA==,type:str]
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: authentik
type: Opaque
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T12:54:03Z"
    mac: ENC[AES256_GCM,data:yShdelBxfAeMguSkSjePu08M7c8qc2fwJhOmxbz184vN+izWWCjQ/3A6j9t6U96UCDcrmgEeb7Lkg8wT14XP+ntN4q+bWMT4ZEzwTyvEGtlpA6yfvZAxm0qRSQDT3l/KcbtNnl/IvV3r4ay3DO+synrY4bQnPKFGyDf660yk2is=,iv:nMqEnR0p6MPZLxThRX9ayk1AMgZCUXwpOOptH7mr2RQ=,tag:NHmJJZwHCoq5Eomsgy0wZA==,type:str]
    pgp:
        - created_at: "2026-07-04T12:54:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv+MVdkeG5ThufxbynLOFg8WQolH9x4+bKnOFcIvIoOzeRd
            RfGFj314kANHxRJdAXCkmknvUqrgpcakMb/aI8mpK66I3UJDZIqnWrnPwp59H9QN
            10xMujaqJIZQbQ8J9pI8Ae/LsYVItfawplvXJQfPGDgo9uUYTSUwL0F9D8en/kgY
            aq16FC9mSd+unTLKOVeN2fjdWCWWuWdWnuSMtFZTtqSpZyPEK3Z3Hs96EQX9gPyU
            5pEvC6QNU74SyDg+J2zYpsqVVO0KrF+R0FasSDbtqrh/ffvD4Fc2xMBTCHlMXdKS
            ZGN0h6DTZPSuYkkDmMihWTLez8BOP2QdOIDvCm3AxnEEMEYAhxQAAuJZgM+hEBEk
            VsCCO+fzOdL5dEJaW3s3NJ8ftx+u6rIYEQ4FU8ejKP3LTSjPSWDYSkygZjJ3fyg/
            1sSSw4BGKljRHfhAAHbkbwnEu6xVQATzYqgNuJQRZVpwsznPK1mmrs29iWH+/xbU
            eHH4PF1DBA459RaqHS/80lwBkUWUdRZM6JwTsbXzOLSa1hleozBgGXFWzxuryBk5
            AJEvmNvEMuQpNoecqHCV4C1d7o6WfN58UrKO6byLMLYXjMSiHyV6KNbYlStn6S+N
            GmWf5/Nh7bEvI7huOA==
            =fb+e
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: s3-creds
    namespace: authentik
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:86QHKr1IkcxdkWjoayNulpFYaJuhFqtgde4=,iv:VpC1y4duSbuaFK73SD6MTXQySF0RSzxNuZKWvqxI9dI=,tag:P2Rq7V6Nf4E5lXAFMSDVng==,type:str]
    secret-access-key: ENC[AES256_GCM,data:LWqKJftKhs2SBMd+7T3+DygHoqwSI8g4B86C/DdfM2AoOEQvsZkCnxw+qVfmyJmXkwYnS8pjVv0lkBG4Nd/AZw==,iv:jn36DuHPsoTBhXb2vxaudDxLZgbj0Q6mZnZn3QWbn/o=,tag:WOTAqJuIyfNmZjnT/HgYqA==,type:str]
    region: ENC[AES256_GCM,data:EcIi4A==,iv:wxsKBviV9r9YrZ77rZ2pG6/qyBlV/l0xI9cLJV/zq+g=,tag:nstqiZwM4JmChc96HMQybw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T12:54:03Z"
    mac: ENC[AES256_GCM,data:yShdelBxfAeMguSkSjePu08M7c8qc2fwJhOmxbz184vN+izWWCjQ/3A6j9t6U96UCDcrmgEeb7Lkg8wT14XP+ntN4q+bWMT4ZEzwTyvEGtlpA6yfvZAxm0qRSQDT3l/KcbtNnl/IvV3r4ay3DO+synrY4bQnPKFGyDf660yk2is=,iv:nMqEnR0p6MPZLxThRX9ayk1AMgZCUXwpOOptH7mr2RQ=,tag:NHmJJZwHCoq5Eomsgy0wZA==,type:str]
    pgp:
        - created_at: "2026-07-04T12:54:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv+MVdkeG5ThufxbynLOFg8WQolH9x4+bKnOFcIvIoOzeRd
            RfGFj314kANHxRJdAXCkmknvUqrgpcakMb/aI8mpK66I3UJDZIqnWrnPwp59H9QN
            10xMujaqJIZQbQ8J9pI8Ae/LsYVItfawplvXJQfPGDgo9uUYTSUwL0F9D8en/kgY
            aq16FC9mSd+unTLKOVeN2fjdWCWWuWdWnuSMtFZTtqSpZyPEK3Z3Hs96EQX9gPyU
            5pEvC6QNU74SyDg+J2zYpsqVVO0KrF+R0FasSDbtqrh/ffvD4Fc2xMBTCHlMXdKS
            ZGN0h6DTZPSuYkkDmMihWTLez8BOP2QdOIDvCm3AxnEEMEYAhxQAAuJZgM+hEBEk
            VsCCO+fzOdL5dEJaW3s3NJ8ftx+u6rIYEQ4FU8ejKP3LTSjPSWDYSkygZjJ3fyg/
            1sSSw4BGKljRHfhAAHbkbwnEu6xVQATzYqgNuJQRZVpwsznPK1mmrs29iWH+/xbU
            eHH4PF1DBA459RaqHS/80lwBkUWUdRZM6JwTsbXzOLSa1hleozBgGXFWzxuryBk5
            AJEvmNvEMuQpNoecqHCV4C1d7o6WfN58UrKO6byLMLYXjMSiHyV6KNbYlStn6S+N
            GmWf5/Nh7bEvI7huOA==
            =fb+e
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: geoip-creds
    namespace: authentik
type: Opaque
stringData:
    account_id: ENC[AES256_GCM,data:z2Gjt0LS,iv:QjjeicYOKFr2bhwN4RScAQ5hUN2pwIfGiXVFrlwBjOE=,tag:VX1oo4i2OCQ/EPmoUMtdSg==,type:str]
    license_key: ENC[AES256_GCM,data:oI1ZpHxlxpor+WJ8CcMrUKbYmsRk/voGn4vXtfqOKOGc1JeksH9ckw==,iv:/VeUyCxuZFdY5oyBr9DCiKoWXXImIC9FkaiIkgaR9Ag=,tag:qycY99SNRjSfXuLhukZxvQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T12:54:03Z"
    mac: ENC[AES256_GCM,data:yShdelBxfAeMguSkSjePu08M7c8qc2fwJhOmxbz184vN+izWWCjQ/3A6j9t6U96UCDcrmgEeb7Lkg8wT14XP+ntN4q+bWMT4ZEzwTyvEGtlpA6yfvZAxm0qRSQDT3l/KcbtNnl/IvV3r4ay3DO+synrY4bQnPKFGyDf660yk2is=,iv:nMqEnR0p6MPZLxThRX9ayk1AMgZCUXwpOOptH7mr2RQ=,tag:NHmJJZwHCoq5Eomsgy0wZA==,type:str]
    pgp:
        - created_at: "2026-07-04T12:54:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv+MVdkeG5ThufxbynLOFg8WQolH9x4+bKnOFcIvIoOzeRd
            RfGFj314kANHxRJdAXCkmknvUqrgpcakMb/aI8mpK66I3UJDZIqnWrnPwp59H9QN
            10xMujaqJIZQbQ8J9pI8Ae/LsYVItfawplvXJQfPGDgo9uUYTSUwL0F9D8en/kgY
            aq16FC9mSd+unTLKOVeN2fjdWCWWuWdWnuSMtFZTtqSpZyPEK3Z3Hs96EQX9gPyU
            5pEvC6QNU74SyDg+J2zYpsqVVO0KrF+R0FasSDbtqrh/ffvD4Fc2xMBTCHlMXdKS
            ZGN0h6DTZPSuYkkDmMihWTLez8BOP2QdOIDvCm3AxnEEMEYAhxQAAuJZgM+hEBEk
            VsCCO+fzOdL5dEJaW3s3NJ8ftx+u6rIYEQ4FU8ejKP3LTSjPSWDYSkygZjJ3fyg/
            1sSSw4BGKljRHfhAAHbkbwnEu6xVQATzYqgNuJQRZVpwsznPK1mmrs29iWH+/xbU
            eHH4PF1DBA459RaqHS/80lwBkUWUdRZM6JwTsbXzOLSa1hleozBgGXFWzxuryBk5
            AJEvmNvEMuQpNoecqHCV4C1d7o6WfN58UrKO6byLMLYXjMSiHyV6KNbYlStn6S+N
            GmWf5/Nh7bEvI7huOA==
            =fb+e
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.2
