apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefly
  namespace: firefly
spec:
  interval: 10m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true 
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: "5.0.1"
  values:
    controllers:
      firefly:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "false"
        containers:
          firefly: 
            image:
              repository: fireflyiii/core
              tag: "version-6.6"
            env:
              DB_HOST: "firefly-db-rw"
              DB_PORT: "5432"
              DB_CONNECTION: "pgsql"
              DB_DATABASE: "firefly"
              APP_URL: "https://firefly.k8s.exmaple.com"
              TRUSTED_PROXIES: "**"
              APP_ENV: "production"
              APP_DEBUG: "false"
            envFrom:
              - secretRef:
                  name: firefly-env      


    service:
      firefly:
        controller: firefly
        ports:
          http:
            port: 8080

    persistence:
      data:
        existingClaim: firefly-data
        advancedMounts:
          firefly:
            firefly:
               - path: /var/www/html/storage/upload  
    ingress:
      firefly:
        className: "cilium"
        hosts:
          - host: "firefly.k8s.exmaple.com"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: firefly
                  port: http
        tls:
          - hosts:
              - "firefly.k8s.exmaple.com"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-data
  namespace: firefly
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: csi-cephfs-sc
  resources:
    requests:
      storage: 10Gi 