apiVersion: v1
kind: Secret
metadata:
    name: firefly-db-secret
    namespace: firefly
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:h7vUCWH4rw==,iv:PDKT2ALl8wzMquFw+4BkyZ5qmI84Vf0fcGIPmEiSKZU=,tag:CKuD4V2kI1u14nZN3O/iHA==,type:str]
    password: ENC[AES256_GCM,data:RgRap7M/OYJP892pSbzvHg==,iv:A3zoxoedNj1vsD6EYxVdFFjWkjpxx6xECmkFiYtUVLA=,tag:lUWGCiyerbOQ1S66CJ5hoA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T09:50:52Z"
    mac: ENC[AES256_GCM,data:UF+6VcoZVv8CK2wAYeZJNdLyEBZO7kbdPVxbtfH3UvQtVr5k8OjzoKkvvrMh7lhQlogwFNBSTNcJsvD5jqC1CObltmhXAsPcp1jiEaIDcDFH8QLAW0FvwoE/gBBNVdAfAIebtzRWnEQhI8MT9rvzKhYSIuRikweDq9Ic8VXEG3M=,iv:7uFw5Lwt1hIgZx2Ijez1aPhWKZmdcYhG2W21ACrHyqo=,tag:OO1b0PJC9myJb2q3CJdlEw==,type:str]
    pgp:
        - created_at: "2026-05-30T09:50:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/QSOG9rNKXMi13RopOK39jCBaPWFTHwtyRgEef4p8hmL4
            kh4QhxWdngRbHj0xzgcY5wsZYXCJMT4zir+Qp4Ztenw4JmeJiu/VuNmda3IGLM0+
            /MbkgLBsBVgh+t0fxochjSAD9T9Q8SeAS29ZqRzjHPAimG1lhMilsSNoOEjvfy40
            xKb2huog5gk0JrJ1+2sB6kZ35yNVMf4r/QoTJCuDcitpuwnzfCQgeKtQuDje2TVf
            s0V+5INp87Dtb43ZMIF6IcId6J+AjiE2gPPlstWhOlTjuuDQpIpN4HKICKJ939zr
            S2LTZj6YvGaoPmUlx1RJPdlJi+A3GXFEGREUrQH9KgcpRR0b6b7Sa0pR5iI1NY23
            875yS/qG0muQv1BXpdXoFxR3Mgoddi1cJ7H8UgNAHsqhX3qCYJKkSsrJA+DYkS7x
            k9HfuTSHsWxeomAnZmERDqtxOJEdgveG+V8GOlWTPLlfinYaGJDFuztEMioEnTxw
            OhlBh+mo7MTZ6D0GbzzQ0lwBk0uTKkV4GiHOWVKjCTSKFA8d9KhYufL+I5u3lLpA
            d2N4aRgm+8GTNN8GLrIptgi2neGJEXXHBpd8V5x447yRfuvAIDC4AcDzZ4AnF/UJ
            okhF/5eViqYcQT8zjA==
            =SxNJ
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: garage-creds
    namespace: firefly
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:4oDn6cdxETufjvSlwrao5qFaCLs0ukFDjzQ=,iv:DgGVSAbEPdCq/E2ARgyWSk4ApEGNa8BFrumJXxRtlgw=,tag:5R7+IxWsDq1p5UbIr3JtMA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:piC4B5/WHPVHapI8yVCkCZWYbqfzkpoEPCpbUYHwmk/+9hKd5xQYnxSRY5RhC8H5UOwiopi5g6h1nWtEkBtR8Q==,iv:q+hxHAmSpsKCjdPvIb0SzfUodAI4ZpxRs3j1BAsXlPQ=,tag:mJc9zCOfthBp8Nk1SpOtBA==,type:str]
    region: ENC[AES256_GCM,data:N5b7/g==,iv:Xpzxl3ZFHgVeLbyyrF9WaU0Tc9IeXXoNpe+8sumhJhU=,tag:FXs5jrk3qoqPxQAnA48bew==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T09:50:52Z"
    mac: ENC[AES256_GCM,data:UF+6VcoZVv8CK2wAYeZJNdLyEBZO7kbdPVxbtfH3UvQtVr5k8OjzoKkvvrMh7lhQlogwFNBSTNcJsvD5jqC1CObltmhXAsPcp1jiEaIDcDFH8QLAW0FvwoE/gBBNVdAfAIebtzRWnEQhI8MT9rvzKhYSIuRikweDq9Ic8VXEG3M=,iv:7uFw5Lwt1hIgZx2Ijez1aPhWKZmdcYhG2W21ACrHyqo=,tag:OO1b0PJC9myJb2q3CJdlEw==,type:str]
    pgp:
        - created_at: "2026-05-30T09:50:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/QSOG9rNKXMi13RopOK39jCBaPWFTHwtyRgEef4p8hmL4
            kh4QhxWdngRbHj0xzgcY5wsZYXCJMT4zir+Qp4Ztenw4JmeJiu/VuNmda3IGLM0+
            /MbkgLBsBVgh+t0fxochjSAD9T9Q8SeAS29ZqRzjHPAimG1lhMilsSNoOEjvfy40
            xKb2huog5gk0JrJ1+2sB6kZ35yNVMf4r/QoTJCuDcitpuwnzfCQgeKtQuDje2TVf
            s0V+5INp87Dtb43ZMIF6IcId6J+AjiE2gPPlstWhOlTjuuDQpIpN4HKICKJ939zr
            S2LTZj6YvGaoPmUlx1RJPdlJi+A3GXFEGREUrQH9KgcpRR0b6b7Sa0pR5iI1NY23
            875yS/qG0muQv1BXpdXoFxR3Mgoddi1cJ7H8UgNAHsqhX3qCYJKkSsrJA+DYkS7x
            k9HfuTSHsWxeomAnZmERDqtxOJEdgveG+V8GOlWTPLlfinYaGJDFuztEMioEnTxw
            OhlBh+mo7MTZ6D0GbzzQ0lwBk0uTKkV4GiHOWVKjCTSKFA8d9KhYufL+I5u3lLpA
            d2N4aRgm+8GTNN8GLrIptgi2neGJEXXHBpd8V5x447yRfuvAIDC4AcDzZ4AnF/UJ
            okhF/5eViqYcQT8zjA==
            =SxNJ
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: firefly-env
    namespace: firefly
type: Opaque
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:XKQYS0AXDg==,iv:aieU9HBhtxHQNsYjIO2NUs2XXmTxnySuSjpmEgn68F0=,tag:gnYoQJthGkY7GB9nS7ziiQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:M2C4M9TZnGJux4Sg9nWsMg==,iv:VXfc0HRmzUbL7cqOeX4lh8LF/M6QVPlenW1UNMg/K1g=,tag:WfPYPVDELQVCKgRzrnw14w==,type:str]
    APP_KEY: ENC[AES256_GCM,data:rRcHa/hvcjM9ArAbpAuwRvulGENvxH6/P81J5vkDcJo=,iv:/cmZS4K88V6tnzh8IphuJpQNob58v+9yMgbnplk7qkg=,tag:eBuNn1/AnwLp0Hs9KW1YwA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T09:50:52Z"
    mac: ENC[AES256_GCM,data:UF+6VcoZVv8CK2wAYeZJNdLyEBZO7kbdPVxbtfH3UvQtVr5k8OjzoKkvvrMh7lhQlogwFNBSTNcJsvD5jqC1CObltmhXAsPcp1jiEaIDcDFH8QLAW0FvwoE/gBBNVdAfAIebtzRWnEQhI8MT9rvzKhYSIuRikweDq9Ic8VXEG3M=,iv:7uFw5Lwt1hIgZx2Ijez1aPhWKZmdcYhG2W21ACrHyqo=,tag:OO1b0PJC9myJb2q3CJdlEw==,type:str]
    pgp:
        - created_at: "2026-05-30T09:50:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/QSOG9rNKXMi13RopOK39jCBaPWFTHwtyRgEef4p8hmL4
            kh4QhxWdngRbHj0xzgcY5wsZYXCJMT4zir+Qp4Ztenw4JmeJiu/VuNmda3IGLM0+
            /MbkgLBsBVgh+t0fxochjSAD9T9Q8SeAS29ZqRzjHPAimG1lhMilsSNoOEjvfy40
            xKb2huog5gk0JrJ1+2sB6kZ35yNVMf4r/QoTJCuDcitpuwnzfCQgeKtQuDje2TVf
            s0V+5INp87Dtb43ZMIF6IcId6J+AjiE2gPPlstWhOlTjuuDQpIpN4HKICKJ939zr
            S2LTZj6YvGaoPmUlx1RJPdlJi+A3GXFEGREUrQH9KgcpRR0b6b7Sa0pR5iI1NY23
            875yS/qG0muQv1BXpdXoFxR3Mgoddi1cJ7H8UgNAHsqhX3qCYJKkSsrJA+DYkS7x
            k9HfuTSHsWxeomAnZmERDqtxOJEdgveG+V8GOlWTPLlfinYaGJDFuztEMioEnTxw
            OhlBh+mo7MTZ6D0GbzzQ0lwBk0uTKkV4GiHOWVKjCTSKFA8d9KhYufL+I5u3lLpA
            d2N4aRgm+8GTNN8GLrIptgi2neGJEXXHBpd8V5x447yRfuvAIDC4AcDzZ4AnF/UJ
            okhF/5eViqYcQT8zjA==
            =SxNJ
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
