apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crafty
  namespace: gameserver
spec:
  interval: 10m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true 
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: "5.0.1"
  values:
    controllers:
      crafty:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app: 
            image:
              repository: registry.gitlab.com/crafty-controller/crafty-4
              tag: "4.10.7@sha256:67c2cbab1c88b75efb41b2970b1faca1a736b3532f6d1a806a7fe3f81664a199"
            env:
              TZ: Europe/Berlin

    service:
      app:
        controller: crafty 
        ports:
          https:
            port: 8443
            targetPort: 8443
            protocol: TCP
      lb:
        controller: crafty
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.50.1.6
        ports:
          dynmap:
            port: 8123
            targetPort: 8123
            protocol: TCP
          bedrock:
            port: 19132
            targetPort: 19132
            protocol: UDP
          java:
            port: 25565
            targetPort: 25565
            protocol: TCP          
          
    persistence:
      storage:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: crafty-data
        globalMounts:
          - path: /crafty/backups
            subPath: backups
          - path: /crafty/logs
            subPath: logs
          - path: /crafty/servers
            subPath: servers
          - path: /crafty/app/config
            subPath: config
          - path: /crafty/import
            subPath: import
      tls: 
        enabled: true
        type: secret
        name: default-tls
        advancedMounts:
          crafty:
            app:
              - path: /crafty/app/config/web/certs/commander.cert.pem
                subPath: tls.crt     
                readOnly: true
              - path: /crafty/app/config/web/certs/commander.key.pem
                subPath: tls.key      
                readOnly: true

    ingress:
      app:
        className: "cilium"
        annotations:
          ingress.cilium.io/tls-passthrough: "enabled"
        hosts:
          - host: "crafty.k8s.exmaple.com"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: https
        tls:
          - hosts:
              - "crafty.k8s.exmaple.com"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crafty-data
  namespace: gameserver
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: csi-cephfs-sc
  resources:
    requests:
      storage: 20Gi 