apiVersion: v1
kind: Secret
metadata:
    name: restic-config
    namespace: gameserver
type: Opaque
stringData:
    #ENC[AES256_GCM,data:4LtKBVfgEFRVX1RwNckRP45jhQUhpYSZo4cP6TsmItp9HmdY1LHkgyphrcQry27zD8MQ+ct1Bu2ECi6Ve4TB5ak=,iv:rgEZ4LU+Wbp849RvuXYNcc/0sSQSyNHoyYUJGwP3Pko=,tag:bOHDhqKGQ9iLg4yj8mAHfQ==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:ZG1JvueNaVDjtILBjOgl6K3KqAbtURk8O86wcpGxLAkKwjMIXsg6U44a4iMmiw==,iv:AKwDnQ5Tuvgl95sqIzK2+hBZmn7dDydrbIORNHl8VvE=,tag:u15h8lnIusqQF2ZSnrIVhQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:CZtWqDK+4oCp5tH7MiZiEKmbtCchGxf5S/tStCyU/YVYmu/d4YM1U775vlvQsRAh,iv:SYQ+doCn+B29kYUs/Xh4zd6prDIrBGR/LJgMPTH9Q/Y=,tag:II+bZcd94TSSr1qL9xgqeA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:hb5SMDuXp2bIAjn+DwU2qAzbtNTCePbr0fU=,iv:2xFT4aaFQvew35liDwQkiaIcAhC2WRY6FbGZCU6UHHY=,tag:YEu2ztnAkT79gPH1y9wCzw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:/j2zt+AZslCa9/95lMxj8ECyLbMSQSmXFSl79p0CHbgqOvGw1Qj1ruLlygLi56CyY9z7JdyATGOVRXiUcx22cA==,iv:v+SZ+2/E8FbKIsu//GXO6TVv8u5G3qXqQbcr6H+dN4k=,tag:Qn1ZWSCoxxVDbdU/c+ccrg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-01T16:03:21Z"
    mac: ENC[AES256_GCM,data:dM4vALMoTPv0VWdUhaiF8qDRLqkm6adnlNnXR9QPMEftWjEysn+scDDDwwDkivKYDIBgTABH7ujvimI4Xy9/CUoiElgHCvLSX6X4kzI0Q18SH2JJkKmUp7RyVY/eUoINS098STJ62375GSZksMO88S5oiOlCARCl4j4snPTiXwo=,iv:wktqbppdvRmm77PCo8V6+e58aAAtJWXYIxZEyihbYWo=,tag:OCQ9NwU1sZGUx9WpnmovVg==,type:str]
    pgp:
        - created_at: "2026-06-01T16:03:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQwAjee2Z/ZBf6UKyK4LPMVGomQ12RmswnV+/bhlciK2b677
            F/pWaFpVUh4/QPHyXjmAwBrofXek7rE1uEB/9erFrxxwqTEz1Xe52NvdatDiBRMO
            BVBc4wtBk7tuV0zvarAq5G8EzOBOk4sNSgHZprHjybHfo64XkS+F5EhTbRpqLecB
            eeIrm+6IKAZOsu40HWOsab3Z5u6PfBNCL1tyFtamTfJg0xVPZprsjzor74rti9PJ
            rmegFphEefiCy1EVrvNQwSZvRAiYXrDZ2rYlCuT7KbsLKp/ANs+bBTs5Ao5xR0t9
            qtXjPzmNQrZhNFyaSLYzS3sEwh00Ra7oDv3GLvtsRA4U1xKdsxxaZEjxiwJQe7Bu
            fp7V+fh0I6s4nMCBRLD89zHM3KpsAE6eXhZM9RknDV5h6nqn6o0Ja0G8Xb6csFwd
            YH8g94TY1gBPaqUVk7/v+n3CrLUUfrdqAg5W8cTCeBczVJKaqTGHK4N1CcIjTOXN
            fsbEQ2c+YkWr2LCIKZiK0lwBskd2i+TO6FergbODiGTtTQdE4yGFHxGRNAwpMhcZ
            u3v37NdiccbadiVvgvv1Igx/ORE5wxM+Mg3iu6cwMV5RyebuGFvecAwL2ZpvrBve
            3Es6VxeoO7iyCTuS0g==
            =xjtq
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
