apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: jellystat-db
  namespace: media
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:15.2
  instances: 1
  stopDelay: 30
  smartShutdownTimeout: 180
  enablePDB: false
  primaryUpdateStrategy: unsupervised
# affinity:
#   enablePodAntiAffinity: true
#    topologyKey: "kubernetes.io/hostname"
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
    roles:
      - name: jellystat
        superuser: true
        login: true
        passwordSecret:
          name: jellystat-db-secret
  postgresql:
#    synchronous:
#      method: any
#      number: 1          
    parameters:
      max_connections: "200"
  bootstrap:
    initdb:
      database: jfstat
      owner: jellystat
      secret:
        name: jellystat-db-secret
  storage:
    size: 4Gi
    storageClass: csi-rbd-sc

