apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - kavita.yaml
  - jellyseerr.yaml
  - audiobookshelf.yaml
  - pinchflat.yaml
  - slskd.yaml
  - omni-tools.yaml
  - secrets.yaml
  - backup.yaml
  - lidarr.yaml
  - lidify.yaml
  - sonarr.yaml
  - radarr.yaml
  - network-policies.yaml