apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: omni-tools
  namespace: media
spec:
  interval: 10m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true 
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: "5.0.1"
  values:
    controllers:
      omni-tools:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "false"
        containers:
          app: 
            image:
              repository: iib0011/omni-tools
              tag: "latest"
            env:
              TZ: Europe/Berlin

    service:
      app:
        controller: omni-tools
        ports:
          http:
            port: 80        

    ingress:
      app:
        className: "cilium"
        hosts:
          - host: "tools.k8s.exmaple.com"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - "tools.k8s.exmaple.com"