apiVersion: v1
kind: Secret
metadata:
    name: linkwarden-db-secret
    namespace: linkwarden
type: Opaque
data:
    username: ENC[AES256_GCM,data:/mTsqbMyoqFAcI7uMFGlug==,iv:UVdqPofW47hmmCZJoaPieTVz8IxbkJUtHE9ovx/r/vo=,tag:LJ6d1IlX/LvL5dZ5Dp3AXA==,type:str]
    password: ENC[AES256_GCM,data:CNJBuO/PYJkRxP4hCF4L+4Hq8vs=,iv:A4BR+LALHtaLTHNUhXxqxgEqOa/eWxMno6sxgyX8gxA=,tag:Nn9xOskoWm8xCtZAUvm+HQ==,type:str]
sops:
    lastmodified: "2026-04-05T13:05:07Z"
    mac: ENC[AES256_GCM,data:6Pfn+5tTWKMr0W/NZp4FpL9KyAPBBUZv3FwCnLA55IiS+OIN1p+XCgJ6D80k39CGqw1YotfhPn0hUSLVaKFZbz0n0BT8SFUDDtdGRra3G69QoC7LBh51GqzsVmNZS951VlkVcIXC6p2O1tBJxNhpFtjjlSzsUwE7bQT+Po09nhM=,iv:oOSUHLmpBOFMbn/V4MyrEAlh+P5PkwNPCPUuCVOTvJI=,tag:+vueRex3AXr3+m7oCvvNgQ==,type:str]
    pgp:
        - created_at: "2026-04-05T13:05:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/c3uaP7kJPj8gnaMbSb49Ly+WwFnFYoHzc1UtiQXpDPRs
            Ck7EnL1jRWxSF9sgRYzphayOPdPip13wvpkZxfeftVcbbmo/+yQWEu8l7bnc7Zcz
            qXL2ykItweODtVtmTxKeTD9CFD977s4OpVqofm/gCCrCgTctZqYPxkRN+RELSwZY
            gGWBTMYvp7z8LYBW1o2Drnc+Qiqmfkf/yi05DRfS4GbwxzI5aFhJovVkXnjlFTYv
            iiWlYHgo4Fe/5cDjKPnwGBsT2EGS86DVIjWBLC6dCh3iU0jyGWIWLZnzWscGXs8t
            /qHGb2esTVjiynB1uyR1kO3fZL5J9Cwli6wPjcfkIeHRaUEbpiDz9PTJwXYpXcTL
            YH/vlIVm/SYUmjZJP1WDIEeQDQoLQu2fHxLTNrdWSEW31WNacAPxG+xLZfqUjvUS
            dyCscgPiQbjr6YZJaMGe0mzhYMnGQB5V+Two0MAiqHbfBlncmeVUB80nAWpFKiNF
            +VWPquFIjscw7Kop0pPR0lwBZVAdOog9NXumMnYK0bqA2cqkKA1u3DBkdaJ1Lmh8
            kwbVS728GpwFnoU+XAC3Z0PYPW6YK02K20FKzMj2jQpQVs2GEPP//UKcP7LDHVR0
            ooLMcZyeQbcYyyoBpw==
            =v5Tx
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: garage-creds
    namespace: linkwarden
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:HQQthjScM0WWTMnedznaA45bgQ1623dynaE=,iv:gDpUAXvCIMytRK84r8JpVEmPTe51A3ypPsm9145u6wc=,tag:VI+G4g27lyJ4HMO33TJFlw==,type:str]
    secret-access-key: ENC[AES256_GCM,data:CzLswMciv7CUcfwGB+800Rg9qapSC1KwsjCLbv1hPZXsnUhKGNDRRqB1WCJHcG/iu/ld+4Lm1Q4aPkX22W4VYA==,iv:NDjpPWTEKRCueJSrlrB5EBr1eQEDEDHFUHCYsxSt8vs=,tag:seLaLgrDAo4fSmXYpeqAxw==,type:str]
    region: ENC[AES256_GCM,data:zStEzw==,iv:9/Qf+lolDomeXf41stH4MzuWba5RYToowZ3ptXTrcdY=,tag:07QjB8CGse6fzoL46zZOzQ==,type:str]
sops:
    lastmodified: "2026-04-05T13:05:07Z"
    mac: ENC[AES256_GCM,data:6Pfn+5tTWKMr0W/NZp4FpL9KyAPBBUZv3FwCnLA55IiS+OIN1p+XCgJ6D80k39CGqw1YotfhPn0hUSLVaKFZbz0n0BT8SFUDDtdGRra3G69QoC7LBh51GqzsVmNZS951VlkVcIXC6p2O1tBJxNhpFtjjlSzsUwE7bQT+Po09nhM=,iv:oOSUHLmpBOFMbn/V4MyrEAlh+P5PkwNPCPUuCVOTvJI=,tag:+vueRex3AXr3+m7oCvvNgQ==,type:str]
    pgp:
        - created_at: "2026-04-05T13:05:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/c3uaP7kJPj8gnaMbSb49Ly+WwFnFYoHzc1UtiQXpDPRs
            Ck7EnL1jRWxSF9sgRYzphayOPdPip13wvpkZxfeftVcbbmo/+yQWEu8l7bnc7Zcz
            qXL2ykItweODtVtmTxKeTD9CFD977s4OpVqofm/gCCrCgTctZqYPxkRN+RELSwZY
            gGWBTMYvp7z8LYBW1o2Drnc+Qiqmfkf/yi05DRfS4GbwxzI5aFhJovVkXnjlFTYv
            iiWlYHgo4Fe/5cDjKPnwGBsT2EGS86DVIjWBLC6dCh3iU0jyGWIWLZnzWscGXs8t
            /qHGb2esTVjiynB1uyR1kO3fZL5J9Cwli6wPjcfkIeHRaUEbpiDz9PTJwXYpXcTL
            YH/vlIVm/SYUmjZJP1WDIEeQDQoLQu2fHxLTNrdWSEW31WNacAPxG+xLZfqUjvUS
            dyCscgPiQbjr6YZJaMGe0mzhYMnGQB5V+Two0MAiqHbfBlncmeVUB80nAWpFKiNF
            +VWPquFIjscw7Kop0pPR0lwBZVAdOog9NXumMnYK0bqA2cqkKA1u3DBkdaJ1Lmh8
            kwbVS728GpwFnoU+XAC3Z0PYPW6YK02K20FKzMj2jQpQVs2GEPP//UKcP7LDHVR0
            ooLMcZyeQbcYyyoBpw==
            =v5Tx
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: linkwarden-env
    namespace: linkwarden
type: Opaque
stringData:
    AUTHENTIK_CLIENT_ID: ENC[AES256_GCM,data:jv21FKxkIu7te+zAJ6MyCcRF1MJZaorLXCcw5pUbNJI9oOZDVgcnCg==,iv:Vk273yxFKlNZ75CC12vZQ4FyP+X3HhUt+ve1x/iODA0=,tag:7RziZ8cAfjPdh0Nj2Ej95A==,type:str]
    AUTHENTIK_CLIENT_SECRET: ENC[AES256_GCM,data:B3BvdOD8oXMGsn8SR8NUU028e3NcIK+cMLYeLV6GeEoNvwEGLSZ/MIOXsWz3A4Ru97CAxxV3D1ZV91SQ4gEwTGv1UEdkgrYpJgeGSISfzmyFRBjG7mTN/+iRH4eJlgUpIi49wOiUpHVXxMAgKYcL5EsFGa76q8Bwqi18y9MAvJg=,iv:sZ95US19VdRqVx5rqSRrt5OZoQki61bSgUXDAuI2fs4=,tag:4d97lcsDj2Vx0s10OA4MPA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:sDLYRtiT7RB1TuZqy4E=,iv:bvGxtiXvmmt47GG+k09dMfzrl4thBGskSOkWqWN8PT4=,tag:ckvk3sGf+sdW8735ziGadw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:dDmHK3TtG1cLziA3iDwLrnZVxkrm4kGilMRivZzX26JF+BT4vjA6EAhZl7vYDfXbwNWn3jFGmjNVtOxe+yOQ7Nt7/6BF76U=,iv:A5GvhuJJaZBI3Gd5sm/1B/Ka+fSLk1MgiAFpv6/zHBA=,tag:pb38ByX7Sg/bm+y4gu8/ig==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:Z6oPnAKT8ao16Ffraoc=,iv:40x64/FRRwtOID1D0EuiVDzK7iC38vqb4m4GdodVm88=,tag:hB3yY38DdChECKPYF+8gQA==,type:str]
sops:
    lastmodified: "2026-04-05T13:05:07Z"
    mac: ENC[AES256_GCM,data:6Pfn+5tTWKMr0W/NZp4FpL9KyAPBBUZv3FwCnLA55IiS+OIN1p+XCgJ6D80k39CGqw1YotfhPn0hUSLVaKFZbz0n0BT8SFUDDtdGRra3G69QoC7LBh51GqzsVmNZS951VlkVcIXC6p2O1tBJxNhpFtjjlSzsUwE7bQT+Po09nhM=,iv:oOSUHLmpBOFMbn/V4MyrEAlh+P5PkwNPCPUuCVOTvJI=,tag:+vueRex3AXr3+m7oCvvNgQ==,type:str]
    pgp:
        - created_at: "2026-04-05T13:05:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/c3uaP7kJPj8gnaMbSb49Ly+WwFnFYoHzc1UtiQXpDPRs
            Ck7EnL1jRWxSF9sgRYzphayOPdPip13wvpkZxfeftVcbbmo/+yQWEu8l7bnc7Zcz
            qXL2ykItweODtVtmTxKeTD9CFD977s4OpVqofm/gCCrCgTctZqYPxkRN+RELSwZY
            gGWBTMYvp7z8LYBW1o2Drnc+Qiqmfkf/yi05DRfS4GbwxzI5aFhJovVkXnjlFTYv
            iiWlYHgo4Fe/5cDjKPnwGBsT2EGS86DVIjWBLC6dCh3iU0jyGWIWLZnzWscGXs8t
            /qHGb2esTVjiynB1uyR1kO3fZL5J9Cwli6wPjcfkIeHRaUEbpiDz9PTJwXYpXcTL
            YH/vlIVm/SYUmjZJP1WDIEeQDQoLQu2fHxLTNrdWSEW31WNacAPxG+xLZfqUjvUS
            dyCscgPiQbjr6YZJaMGe0mzhYMnGQB5V+Two0MAiqHbfBlncmeVUB80nAWpFKiNF
            +VWPquFIjscw7Kop0pPR0lwBZVAdOog9NXumMnYK0bqA2cqkKA1u3DBkdaJ1Lmh8
            kwbVS728GpwFnoU+XAC3Z0PYPW6YK02K20FKzMj2jQpQVs2GEPP//UKcP7LDHVR0
            ooLMcZyeQbcYyyoBpw==
            =v5Tx
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
