apiVersion: v1
kind: Secret
metadata:
    name: phpipam-env
    namespace: phpipam
type: Opaque
stringData:
    IPAM_DATABASE_PASS: ENC[AES256_GCM,data:/a7DHAnliAjF2Q0RfsQTVQ==,iv:IlqooDPlROsT+e3jDHGZrINdQvrRA6McJHY5WvSnz40=,tag:Mm9Q691hZFvxsqR1ZT78+A==,type:str]
    MARIADB_PASSWORD: ENC[AES256_GCM,data:vZLCg+PglrmM7J0tt54qqg==,iv:iBqnyDmH3i278kd5LWD/Fp/T0EjBHckv4b50Q8P+Ug4=,tag:Ju+jpLYWcG6XNsYMU7AQdw==,type:str]
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:kt1dy2KGV+vKIsSnSZFeSQ==,iv:Wqr1BvwL8C9mWOsvoWbrD41aVN7KtHvHHv4ae03fnw4=,tag:FYCXI0CIDLOm65E1Pf1Jyg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T12:29:07Z"
    mac: ENC[AES256_GCM,data:B8BWCJxNdPug25Xj6Eqw/9u5t0oJ/mWRuxBm2W0jTwqqf8tECafSQ3U7O4x+aKQWBxVHTh/ImXHXxUxfJEj9nH43EeuNFLxJeDITnJYhK6ksIFNQUXA26W8uDTUEqMN5FviLsvFoSbeHdf2GgkQ2CSVll1prddAnJAigRrkajWk=,iv:DEHKIoH0U64WTXIrghO9gM8BI6HjDYCJ3dJqY3+g57I=,tag:1GQ9AX0c6jYCbgQODwthdA==,type:str]
    pgp:
        - created_at: "2026-05-24T12:29:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQwAjv9OEXE+F6ZCEy3ixHBoCm+zpYEEf3XlcFCzSbQ/usO2
            JfFybQP7l4puZ90aTxR3OTvCNXMFnLMY0du+6DOiAK3r4I2czdvDm1YlbayAjxtR
            DTugPnBPOqTer/szkXnW9ElZ7Rzl7NnmwqckPcJqB6OfVW/qGaQiy3rLeE5UUttG
            F6yDPnCb+/xONF6bq2QslyQdbajGYuU2px7BWsou5XRaZ/XH6pnCKvFq3zDcjAA9
            uXfFZ+ZmK0nSM+mvxQt77en7PoyixfIjzQ7HHmVbzSThfXp42KE4vaGFSCSfWpy2
            YF0UgPX42L44yCcpkSPd4z9VlFdd6VT1hU/r8j/O9nYdUXO4B0PRMzuUw9OGG+eY
            vE3D7L9vtn8j7f4/NZs1T3lf1varrmkycjiFlq6QzA0yRPR8FVZbgK39ikY37BdJ
            VdR+PXHW0HdO6EFNUs8xND/Yq2yE2WP8EfJ+eLrdSRjOq54kHz5aqkMBJoJKaF79
            g+X6cVNbVJ0Z8sy0a/Jt0l4BaWc+S+JdT1fxh9DEVMWoMXLwibJ+1xD0gvE+/ZWb
            V66pafx77h14fia1soEW/zJpb5v17UEFWm0uBP6SxINQ35eMm33tGOc0f8MG118R
            fdM5QihGP1YthIWcqGbD
            =gJUC
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
