apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ftp
  namespace: paperless
spec:
  interval: 10m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true 
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: "5.0.1"
  values:
    controllers:
      ftp:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "false"
        containers:
          app: 
            image:
              repository: garethflowers/ftp-server
              tag: "latest"
            env:
              PUBLIC_IP: "10.50.1.5"
              FTP_PASS: "ftp"
              FTP_USER: "user"

    service:
      app:
        controller: ftp
        ports:
          ftp-listen:
            port: 21
          ftp-data:
            port: 20
          pasv-40000:
            port: 40000
            targetPort: 40000
            protocol: TCP
          pasv-40001:
            port: 40001
            targetPort: 40001
            protocol: TCP
          pasv-40002:
            port: 40002
            targetPort: 40002
            protocol: TCP
          pasv-40003:
            port: 40003
            targetPort: 40003
            protocol: TCP
          pasv-40004:
            port: 40004
            targetPort: 40004
            protocol: TCP
          pasv-40005:
            port: 40005
            targetPort: 40005
            protocol: TCP
          pasv-40006:
            port: 40006
            targetPort: 40006
            protocol: TCP
          pasv-40007:
            port: 40007
            targetPort: 40007
            protocol: TCP
          pasv-40008:
            port: 40008
            targetPort: 40008
            protocol: TCP
          pasv-40009:
            port: 40009
            targetPort: 40009
            protocol: TCP

    persistence:
      storage:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: paperless-data
        globalMounts:
          - path: /home/user
            subPath: consume
---
apiVersion: v1
kind: Service
metadata:
  name: ftp-lb
  namespace: paperless
  labels:
    app: ftp
spec:
  type: LoadBalancer
  loadBalancerIP: 10.50.1.5
  ports:
  - port: 21
    targetPort: 21
    protocol: TCP
    name: ftp-listen
  - port: 20
    targetPort: 20
    protocol: TCP                                                                                                                                                                                                                                 
    name: ftp-data
  - name: pasv-40000
    port: 40000
    targetPort: 40000
    protocol: TCP
  - name: pasv-40001
    port: 40001
    targetPort: 40001
    protocol: TCP
  - name: pasv-40002
    port: 40002
    targetPort: 40002
    protocol: TCP
  - name: pasv-40003
    port: 40003
    targetPort: 40003
    protocol: TCP
  - name: pasv-40004
    port: 40004
    targetPort: 40004
    protocol: TCP
  - name: pasv-40005
    port: 40005
    targetPort: 40005
    protocol: TCP
  - name: pasv-40006
    port: 40006
    targetPort: 40006
    protocol: TCP
  - name: pasv-40007
    port: 40007
    targetPort: 40007
    protocol: TCP
  - name: pasv-40008
    port: 40008
    targetPort: 40008
    protocol: TCP
  - name: pasv-40009
    port: 40009
    targetPort: 40009
    protocol: TCP                                                           
  selector:
    app.kubernetes.io/name: ftp