apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless
  namespace: paperless
spec:
  interval: 10m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true 
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: "5.2.1"
  values:
    controllers:
      paperless:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "false"
        containers:
          app: 
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: "3.2@sha256:5fa76604a81df6945086e0837b14b56543d137e8ce4f311cc5d9ebe907e74e79"
            env:
              PAPERLESS_ENABLE_ALLAUTH: true
              PAPERLESS_APPS: "allauth.socialaccount.providers.openid_connect"
              PAPERLESS_AUTO_LOGIN: true
              PAPERLESS_AUTO_CREATE: true
              PAPERLESS_LOGOUT_REDIRECT_URL: "https://idm.exmaple.com/application/o/paperless/end-session/"              
              PAPERLESS_TIME_ZONE: Europe/Berlin
              PAPERLESS_URL: "https://paperless.k8s.exmaple.com"
              PAPERLESS_OCR_LANGUAGE: deu
              PAPERLESS_DBENGINE: postgresql
              PAPERLESS_DBHOST: "paperless-db-rw"
              PAPERLESS_REDIS: "redis://paperless-valkey:6379"
              PAPERLESS_TIKA_ENABLED: true
              PAPERLESS_TIKA_ENDPOINT: "http://paperless-tika:9998"
              PAPERLESS_TIKA_GOTENBERG_ENDPOINT: "http://paperless-gotenberg:3000"
              PAPERLESS_CONSUMER_RECURSIVE: true        
            envFrom:
              - secretRef:
                  name: paperless-env      
            resources:
              requests:
                cpu: 500m
                memory: 512Mi
              limits:
                cpu: 2
                memory: 1Gi
      valkey:
        containers:
          valkey:
            image:
              repository: valkey/valkey
              tag: "9-alpine@sha256:48332870af354a799964c0012ae1194a0bf2bf894eb508f945810596dc2d8d11"
            resources:
              requests:
                memory: 32Mi
              limits:
                memory: 64Mi
      tika:
        containers:
          tika:
            image:
              repository: docker.io/apache/tika
              tag: "latest"
            resources:
              requests:
                memory: 256Mi
              limits:
                memory: 512Mi
      gotenberg: 
        containers: 
          gotenberg:
            image:
              repository: docker.io/gotenberg/gotenberg
              tag: "8.37@sha256:f29984bd1e226bf1b93ba90af06000afa8b315853e99d27b9aaa41b93f15c769"
            command: 
              - "gotenberg"
            args:
              - "--chromium-disable-javascript=true"
              - "--chromium-allow-list=file:///tmp/.*"
            resources:
              requests:
                memory: 256Mi
              limits:
                memory: 768Mi

    service:
      app:
        controller: paperless
        ports:
          http:
            port: 8000
      valkey:
        controller: valkey 
        ports:
          valkey:
            port: 6379
      tika:
        controller: tika
        ports:
          http:
            port: 9998
      gotenberg:
        controller: gotenberg
        ports: 
          http:
            port: 3000

    persistence:
      storage:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: paperless-data
        globalMounts:
          - path: /usr/src/paperless/data
            subPath: data
          - path: /usr/src/paperless/media
            subPath: media
          - path: /usr/src/paperless/export
            subPath: export
          - path: /usr/src/paperless/consume
            subPath: consume

    ingress:
      app:
        className: "cilium"
        hosts:
          - host: "paperless.k8s.exmaple.com"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - "paperless.k8s.exmaple.com"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data
  namespace: paperless
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: csi-cephfs-sc
  resources:
    requests:
      storage: 10Gi 