apiVersion: v1
kind: Secret
metadata:
    name: paperless-db-secret
    namespace: paperless
type: Opaque
data:
    username: ENC[AES256_GCM,data:hx5lFOt3lnNlJWh7,iv:D29abuSio15XuFmmDXzEbhk1JpGoxeJ0bUuSC78l3BQ=,tag:UtzsYZ2/Y62KtZjs6gOJ4Q==,type:str]
    password: ENC[AES256_GCM,data:yPKTzxMVS7KdTc65PRsvD/WB2Qc=,iv:KIwIXIuJ2E9clOPevgt9wO/NOIavnRzSUeg/0h4LNU8=,tag:pvuRE5y+k19q6aOdHG1wgw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T09:08:10Z"
    mac: ENC[AES256_GCM,data:Ck/in1ZX3zaFPYSsniyfuKC5MtK9xIVYYtrE//KlknDgH30Kvpy3177owgMWCwtZGmQjDD/+0vV/PivNDED0tzSqbd5x7vvkdzGbuUuSKBMvVrxJurNp2MQkw+dSGSpCMyHDtD8v4ihHdMZxp6P7mbW/MD5VB0XIpnQQGKLJ+9I=,iv:E3Fj4+eOM7phCpRv4VC7WB4p/N/ZLY8EJIJB9Gz/pME=,tag:G+end4dIlt+wM51MxzvTuw==,type:str]
    pgp:
        - created_at: "2026-06-21T09:08:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/fktm8IloLuozDHcEP1wbvDtFXwXfO33VN4Ppuq+RprYL
            tyJQzPm8kWh9vGOQZDWzhMyWlNMO71U0xxFXUwq4PmhLuFtFr26zETVO8tdWyF7e
            xd2we22mq6Y6ymyUimw1qEYVq/1x7Zu19ZXTt/u8EYjbxxpxO8Puukq1vc5/Ck5o
            x5xjr4VEObOXcbKWV50sVcRl9OmdroxXc/JGvBjli3Hpys3rl3Vf8ii8s2GMS0XE
            BUd8NgMdbRaUlHwUcSo+8M3gTc8W0AVyf9UYskjqVSLUf9CpSKRMILAFzWWWli4U
            YP04zKIhYKGqo8shvCjgizqX86AUoNWvNv7GMQn4ptnYATyr2AOWZ5u5+z6bXnYa
            /DvynjxfmUmcFp3IGDz8p8Wp2xWnvjLpiSmpYqCWKx1XtxK54TT17mmEaleuRcVd
            uHFzT2NF4BCwF0j+Ejpp4jkjX/sx/zmo+9ASs3J4ns5XOdnH5rSe8tsuxUvMyUUv
            4LJlvDnDZITDEaoHtgW50lwB3ZvOA8Zt6VZZC4FqVdB1P3FRdd8mNSiBzLq45JlK
            BUZJi0txqfCrQo3RLYdqlHmmci06QKfJ8Oqjoi8QmFOIojqiHOTKv2Yty5j1GyHb
            pMvZz3uR3AgYK6TfoQ==
            =pIQo
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: garage-creds
    namespace: paperless
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:dJkOW+lQvo7JzbACRf7mjmVvd1x+x9eNXGQ=,iv:IDaGcmh4647w7wGsMUkWwVy6Lt3hvkXoYDT4/b3Sh2M=,tag:qYQtu85BVC13l7qG8ay58Q==,type:str]
    secret-access-key: ENC[AES256_GCM,data:oeMamjY5rvlIUzEduFIaLGqN3OccwAMh169Z1aUYawI8+P0o3NUolPiw8+aEil82OSUUH0D/lmaGVcUIcm7L6w==,iv:Qhl/RomvrsJ7kRVCgm2LZulFSl7h3O0CNKPz3Pf0jVc=,tag:9pGkUNloht7tKpJc0XBdLg==,type:str]
    region: ENC[AES256_GCM,data:wsnIWQ==,iv:HQSW8L6/o8p/umcWXFCRr2trC+zN18S31ETPmgGGq6U=,tag:7zajlm1C9P5PH3QoyIuU2g==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T09:08:10Z"
    mac: ENC[AES256_GCM,data:Ck/in1ZX3zaFPYSsniyfuKC5MtK9xIVYYtrE//KlknDgH30Kvpy3177owgMWCwtZGmQjDD/+0vV/PivNDED0tzSqbd5x7vvkdzGbuUuSKBMvVrxJurNp2MQkw+dSGSpCMyHDtD8v4ihHdMZxp6P7mbW/MD5VB0XIpnQQGKLJ+9I=,iv:E3Fj4+eOM7phCpRv4VC7WB4p/N/ZLY8EJIJB9Gz/pME=,tag:G+end4dIlt+wM51MxzvTuw==,type:str]
    pgp:
        - created_at: "2026-06-21T09:08:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/fktm8IloLuozDHcEP1wbvDtFXwXfO33VN4Ppuq+RprYL
            tyJQzPm8kWh9vGOQZDWzhMyWlNMO71U0xxFXUwq4PmhLuFtFr26zETVO8tdWyF7e
            xd2we22mq6Y6ymyUimw1qEYVq/1x7Zu19ZXTt/u8EYjbxxpxO8Puukq1vc5/Ck5o
            x5xjr4VEObOXcbKWV50sVcRl9OmdroxXc/JGvBjli3Hpys3rl3Vf8ii8s2GMS0XE
            BUd8NgMdbRaUlHwUcSo+8M3gTc8W0AVyf9UYskjqVSLUf9CpSKRMILAFzWWWli4U
            YP04zKIhYKGqo8shvCjgizqX86AUoNWvNv7GMQn4ptnYATyr2AOWZ5u5+z6bXnYa
            /DvynjxfmUmcFp3IGDz8p8Wp2xWnvjLpiSmpYqCWKx1XtxK54TT17mmEaleuRcVd
            uHFzT2NF4BCwF0j+Ejpp4jkjX/sx/zmo+9ASs3J4ns5XOdnH5rSe8tsuxUvMyUUv
            4LJlvDnDZITDEaoHtgW50lwB3ZvOA8Zt6VZZC4FqVdB1P3FRdd8mNSiBzLq45JlK
            BUZJi0txqfCrQo3RLYdqlHmmci06QKfJ8Oqjoi8QmFOIojqiHOTKv2Yty5j1GyHb
            pMvZz3uR3AgYK6TfoQ==
            =pIQo
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-config-paperless
    namespace: paperless
type: Opaque
stringData:
    #ENC[AES256_GCM,data:ZYlmBHvEDUaC40Y7+CXDtp3PsqwgoPShRPGmF/XnDYRlL7wEZ585dhG+18Q8ykndD8Dpn2lsG0dv5PxU63T6pGs=,iv:uT11Jb8fjBgL2IaCaq0eAYCpGtxTmvn35DkJNDRu+d4=,tag:FJWjg6NUsSIhjm+qwiuWhQ==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:+yvykOrLoljr2Fy7r/sgMKW9kzeO2IhgZmNkc1Sq0IGNBMBWVE5hWMTr5KfdIJwhgQ==,iv:yooyHQpekcGJNyAnyY3VQ0HbE3+LzRc5wpuhtIvRNgM=,tag:+0cU5gOd5hAFaYRjdStFpA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:ZhdHQFxzpzF/AmunSebkCJpYsIR4NJS7Jpq0NqT8iaCLdLGi+ovCMuYCT31HeiZ2,iv:G001KkcTL9ljh5o+cXkuDY30Ny1UliH3fHGiLhRlAbE=,tag:+Vg41zHCr0MGCUtsFMVzig==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:coZpJghwGrkknPYmWm5W8DvdjOg21wMJDBE=,iv:713PgOtmXOaPQKEmGyso+2mN/ujmQqCvhGAEXKuLNCU=,tag:y/hZYrwEZwxNmf7syaLSgg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:13Pa+3Aej8v0K4Cov/DwuIDtI72G8SsMxwezcqzpbaPIpN7f5uXt4QxYCcfaqqMOr4OpgqDa4oE5+z7nHres/A==,iv:DggA2/1F92yyo6PnYXVLaGHCnxIvp5DCoZACEyp9jys=,tag:CwRwdzMpMu7WOOLEZNC3yg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T09:08:10Z"
    mac: ENC[AES256_GCM,data:Ck/in1ZX3zaFPYSsniyfuKC5MtK9xIVYYtrE//KlknDgH30Kvpy3177owgMWCwtZGmQjDD/+0vV/PivNDED0tzSqbd5x7vvkdzGbuUuSKBMvVrxJurNp2MQkw+dSGSpCMyHDtD8v4ihHdMZxp6P7mbW/MD5VB0XIpnQQGKLJ+9I=,iv:E3Fj4+eOM7phCpRv4VC7WB4p/N/ZLY8EJIJB9Gz/pME=,tag:G+end4dIlt+wM51MxzvTuw==,type:str]
    pgp:
        - created_at: "2026-06-21T09:08:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/fktm8IloLuozDHcEP1wbvDtFXwXfO33VN4Ppuq+RprYL
            tyJQzPm8kWh9vGOQZDWzhMyWlNMO71U0xxFXUwq4PmhLuFtFr26zETVO8tdWyF7e
            xd2we22mq6Y6ymyUimw1qEYVq/1x7Zu19ZXTt/u8EYjbxxpxO8Puukq1vc5/Ck5o
            x5xjr4VEObOXcbKWV50sVcRl9OmdroxXc/JGvBjli3Hpys3rl3Vf8ii8s2GMS0XE
            BUd8NgMdbRaUlHwUcSo+8M3gTc8W0AVyf9UYskjqVSLUf9CpSKRMILAFzWWWli4U
            YP04zKIhYKGqo8shvCjgizqX86AUoNWvNv7GMQn4ptnYATyr2AOWZ5u5+z6bXnYa
            /DvynjxfmUmcFp3IGDz8p8Wp2xWnvjLpiSmpYqCWKx1XtxK54TT17mmEaleuRcVd
            uHFzT2NF4BCwF0j+Ejpp4jkjX/sx/zmo+9ASs3J4ns5XOdnH5rSe8tsuxUvMyUUv
            4LJlvDnDZITDEaoHtgW50lwB3ZvOA8Zt6VZZC4FqVdB1P3FRdd8mNSiBzLq45JlK
            BUZJi0txqfCrQo3RLYdqlHmmci06QKfJ8Oqjoi8QmFOIojqiHOTKv2Yty5j1GyHb
            pMvZz3uR3AgYK6TfoQ==
            =pIQo
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: paperless-env
    namespace: paperless
type: Opaque
stringData:
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:0w1AhAN1kOJ+zSl9+ZE=,iv:GIROtNrD6zy8CIMX9FE+WvrSS7sCw1IYuk0uZimvoz4=,tag:8/6K8acZUzG6xDW1FW8n9Q==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:e/8vyfDd/qWE11SH/Nc=,iv:bGK3BZ5UOtaWcGSGwSum/AjSxi/i+o9+PHgzAs+YDsA=,tag:Snd0e4NVeok2T3Pl3KXdjQ==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:+9sXz13O7l8X9QDjvKE2Zp5imofTXyH3vwqZyrksE60JeHD0IbvqLzYewpPA1XZtok7jnhWvzKQ2B2tw747LjTxEeG55tK37D8AwHuPHgYalHpliSEjxpqRPIOnp87bGcbW7IhKCSKuT8shLzKNeDSQ++RE3YWrYAsrvr1vpiJbKO84jveC+FqWHeZspfA43d7Z9TZ1zcZamNLvjP1zDkgOf5WJoEJAKPNl9dBNGSu3+G3b/Dw4A766XBru1TSdqlQt5XGC/GlNnGaTP5C+DuJA8g0+7ji3HKTbjULzNV8Qjc87n4GVIYuT0qKassz2KbK/VvkXYG4llwdi573J8gcwJa8JUYPaygzQJ3CAvi4Y6WxUkkOjQ+k3EOEX47QTWtW2EsH1F8EPq+Ya+ug4cqtz5IfdhXN2ecvu8JwxNgxnAXEpOTuC+z4EHbK8wPabfucvbBziSMnMYfhUUL0Q7QB4y1AcSVTmUOCFGnq7mOqOGie9QehvoaM36lJFkOWBT4VxE2XVTTXD5ymzS8OKsmNipdcD7xprcB0HyIDYaemGYUydEKY7r43DGtJIJoQwmQuQuBqwpv5xfiPdDSSlq7jAt2iR+Ij41OExEUM/d3hsLcHnR79FjK5SS9Wfn4oNn9P76HtDt8tEQiHWyW9o/+JI9bewucA74t7aDuTguAfzOt2dH5wZlfHpLTJJ4PzyH09DUjnoUeii0tQLepPiacBxhoumfhHbbUsa4LAn6yKfZKwwE,iv:zJ9NUFhJ7xs1cFvVavlMMpVg953Y3M46/TQGwaC4cy8=,tag:hsQjqFONVAvX1t7pZyjWEQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T09:08:10Z"
    mac: ENC[AES256_GCM,data:Ck/in1ZX3zaFPYSsniyfuKC5MtK9xIVYYtrE//KlknDgH30Kvpy3177owgMWCwtZGmQjDD/+0vV/PivNDED0tzSqbd5x7vvkdzGbuUuSKBMvVrxJurNp2MQkw+dSGSpCMyHDtD8v4ihHdMZxp6P7mbW/MD5VB0XIpnQQGKLJ+9I=,iv:E3Fj4+eOM7phCpRv4VC7WB4p/N/ZLY8EJIJB9Gz/pME=,tag:G+end4dIlt+wM51MxzvTuw==,type:str]
    pgp:
        - created_at: "2026-06-21T09:08:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/fktm8IloLuozDHcEP1wbvDtFXwXfO33VN4Ppuq+RprYL
            tyJQzPm8kWh9vGOQZDWzhMyWlNMO71U0xxFXUwq4PmhLuFtFr26zETVO8tdWyF7e
            xd2we22mq6Y6ymyUimw1qEYVq/1x7Zu19ZXTt/u8EYjbxxpxO8Puukq1vc5/Ck5o
            x5xjr4VEObOXcbKWV50sVcRl9OmdroxXc/JGvBjli3Hpys3rl3Vf8ii8s2GMS0XE
            BUd8NgMdbRaUlHwUcSo+8M3gTc8W0AVyf9UYskjqVSLUf9CpSKRMILAFzWWWli4U
            YP04zKIhYKGqo8shvCjgizqX86AUoNWvNv7GMQn4ptnYATyr2AOWZ5u5+z6bXnYa
            /DvynjxfmUmcFp3IGDz8p8Wp2xWnvjLpiSmpYqCWKx1XtxK54TT17mmEaleuRcVd
            uHFzT2NF4BCwF0j+Ejpp4jkjX/sx/zmo+9ASs3J4ns5XOdnH5rSe8tsuxUvMyUUv
            4LJlvDnDZITDEaoHtgW50lwB3ZvOA8Zt6VZZC4FqVdB1P3FRdd8mNSiBzLq45JlK
            BUZJi0txqfCrQo3RLYdqlHmmci06QKfJ8Oqjoi8QmFOIojqiHOTKv2Yty5j1GyHb
            pMvZz3uR3AgYK6TfoQ==
            =pIQo
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: samba-paperless-secret
    namespace: paperless
type: Opaque
stringData:
    ACCOUNT_scan: ENC[AES256_GCM,data:EXZpVWCa2g==,iv:Cy8sx2K7H8oiBHVEJJsFgHSg/6remzjRSoKPSb0rx64=,tag:V9diV0e3kV+uYzVH1XJtcQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T09:08:10Z"
    mac: ENC[AES256_GCM,data:Ck/in1ZX3zaFPYSsniyfuKC5MtK9xIVYYtrE//KlknDgH30Kvpy3177owgMWCwtZGmQjDD/+0vV/PivNDED0tzSqbd5x7vvkdzGbuUuSKBMvVrxJurNp2MQkw+dSGSpCMyHDtD8v4ihHdMZxp6P7mbW/MD5VB0XIpnQQGKLJ+9I=,iv:E3Fj4+eOM7phCpRv4VC7WB4p/N/ZLY8EJIJB9Gz/pME=,tag:G+end4dIlt+wM51MxzvTuw==,type:str]
    pgp:
        - created_at: "2026-06-21T09:08:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/fktm8IloLuozDHcEP1wbvDtFXwXfO33VN4Ppuq+RprYL
            tyJQzPm8kWh9vGOQZDWzhMyWlNMO71U0xxFXUwq4PmhLuFtFr26zETVO8tdWyF7e
            xd2we22mq6Y6ymyUimw1qEYVq/1x7Zu19ZXTt/u8EYjbxxpxO8Puukq1vc5/Ck5o
            x5xjr4VEObOXcbKWV50sVcRl9OmdroxXc/JGvBjli3Hpys3rl3Vf8ii8s2GMS0XE
            BUd8NgMdbRaUlHwUcSo+8M3gTc8W0AVyf9UYskjqVSLUf9CpSKRMILAFzWWWli4U
            YP04zKIhYKGqo8shvCjgizqX86AUoNWvNv7GMQn4ptnYATyr2AOWZ5u5+z6bXnYa
            /DvynjxfmUmcFp3IGDz8p8Wp2xWnvjLpiSmpYqCWKx1XtxK54TT17mmEaleuRcVd
            uHFzT2NF4BCwF0j+Ejpp4jkjX/sx/zmo+9ASs3J4ns5XOdnH5rSe8tsuxUvMyUUv
            4LJlvDnDZITDEaoHtgW50lwB3ZvOA8Zt6VZZC4FqVdB1P3FRdd8mNSiBzLq45JlK
            BUZJi0txqfCrQo3RLYdqlHmmci06QKfJ8Oqjoi8QmFOIojqiHOTKv2Yty5j1GyHb
            pMvZz3uR3AgYK6TfoQ==
            =pIQo
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
