apiVersion: v1
kind: Secret
metadata:
    name: paperless-db-secret
    namespace: paperless
type: Opaque
data:
    username: ENC[AES256_GCM,data:C1DtiRueq9fm/EgJ,iv:pCyGJDIsnkvDtUVlwhdL8dHD6dGYAD84lEDZ7vqEvDw=,tag:bKnmjoik/dWTldlIIkXtag==,type:str]
    password: ENC[AES256_GCM,data:2x+mb8HWncCb7x3bge/bpfajuCk=,iv:3xYblFO4ULEFzaGf2YiRJHh8ELVwFDp/oXMUooR2I8E=,tag:azG0hTkNwOG+XHY4WYLceg==,type:str]
sops:
    lastmodified: "2026-03-23T18:27:06Z"
    mac: ENC[AES256_GCM,data:0rtuKvm1zo5U1CrHqBIUbl/VBH5j4chGmcKNXZSNm6iT4lxhEh+wjPVa6IKj3RVkgeSPjX0ZLas7qOq3XrFSenq8Iw9I3TaqYppaOPfRyc2/NZx+pOGiUEu4glhNoOrvOfJXPkHOewhXaHKg4UV8ZqRoA0BsSMZ1iv0Sf481GRk=,iv:7Ucb48VpC5vkNsqlyxTZIwqL+l0FDzPG7t5zlVwdW2E=,tag:ekZMt7GBFM8QNs6JJVMfQQ==,type:str]
    pgp:
        - created_at: "2026-03-23T18:27:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv+IO/fD0d5P5P5XmdTyo84iQLCD6eH5xC53RRywghWAIHE
            l8FGn88Q5urxnr/ns/teq/NiR7mmYy6A+etPqGS9/zCYVgR6rl3clDQ80jRLqtB7
            25x2Qb0cpuonTo7ceFLVHsI1bCQdF7H+FoPjNxlMq57THXL8KtPRJSArisMXzp+o
            SAbpy23z9jQLmTg3Bbtw3TZOU1WFi+Posj9yHVJRIClNUJm3MBli/8RTwoSwihWP
            lyi3PTIfyZWJRnv4i7LFECCBr/Cd25IMJlZSI+RXRvFeM5xqwXSRZsqMXW+Z9uH5
            0QNGslb2S3uFI7j3b+IDQqUMFR4f8YvDLkOLX/tJ8RhREeBaWlsGmh2L42MnVpFE
            xNss6XOzgffHjh3dTtEA7DdXXdaRYtcILdL3w1fGM9Qa6CfpmpthApbe971+A1tg
            KaiRmLxv3qBuPqF37y++Ebd4HzDRk5f7uFMTcx/Cyu1toC/nMVHFxeZw65HcVZo2
            BRHtEIb8vEvmadGpfnO40l4BI0jwVIy478gO/NPljIwrQv2I9azpKBMWM3l1C9R7
            Aa6nNMCKXnrHUyY0iHhgfLTP8WstO477aIFTevdriG9szV+4s7p7M/kcTVmQk/Ww
            5ipWOoR7Ctg7TfHSrNSC
            =43KI
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: garage-creds
    namespace: paperless
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:uVmbsAPs5Vyd3/DOmlAbo+pdz/ANfGQB1Ko=,iv:5IIdphlc7vrVERsXHDSI1FAk4VqUOWJL8HIehjaIXGQ=,tag:PQmLM8Z+LHGe5ZDuqU3hyQ==,type:str]
    secret-access-key: ENC[AES256_GCM,data:LeBG7RBqiuBii6bB2x0a4JyjaUtZTOwtNQEW9UKsg75FnrU12YQSRw6k29T9rAbG7G17b8Rj0cswOjjorgHxPg==,iv:p7SP22du3awDO3NPp49IIOEgS3WoiGcCzfU/NuKZo04=,tag:ndBMSJM2cQKZvYamb77pLg==,type:str]
    region: ENC[AES256_GCM,data:E4rPXQ==,iv:+BAZmLFHgJ/quY0b8VmNmRiB/sGCdCut/XkhhXY2Kw8=,tag:UHTW9lI8qL60rDV/w1LCZQ==,type:str]
sops:
    lastmodified: "2026-03-23T18:27:06Z"
    mac: ENC[AES256_GCM,data:0rtuKvm1zo5U1CrHqBIUbl/VBH5j4chGmcKNXZSNm6iT4lxhEh+wjPVa6IKj3RVkgeSPjX0ZLas7qOq3XrFSenq8Iw9I3TaqYppaOPfRyc2/NZx+pOGiUEu4glhNoOrvOfJXPkHOewhXaHKg4UV8ZqRoA0BsSMZ1iv0Sf481GRk=,iv:7Ucb48VpC5vkNsqlyxTZIwqL+l0FDzPG7t5zlVwdW2E=,tag:ekZMt7GBFM8QNs6JJVMfQQ==,type:str]
    pgp:
        - created_at: "2026-03-23T18:27:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv+IO/fD0d5P5P5XmdTyo84iQLCD6eH5xC53RRywghWAIHE
            l8FGn88Q5urxnr/ns/teq/NiR7mmYy6A+etPqGS9/zCYVgR6rl3clDQ80jRLqtB7
            25x2Qb0cpuonTo7ceFLVHsI1bCQdF7H+FoPjNxlMq57THXL8KtPRJSArisMXzp+o
            SAbpy23z9jQLmTg3Bbtw3TZOU1WFi+Posj9yHVJRIClNUJm3MBli/8RTwoSwihWP
            lyi3PTIfyZWJRnv4i7LFECCBr/Cd25IMJlZSI+RXRvFeM5xqwXSRZsqMXW+Z9uH5
            0QNGslb2S3uFI7j3b+IDQqUMFR4f8YvDLkOLX/tJ8RhREeBaWlsGmh2L42MnVpFE
            xNss6XOzgffHjh3dTtEA7DdXXdaRYtcILdL3w1fGM9Qa6CfpmpthApbe971+A1tg
            KaiRmLxv3qBuPqF37y++Ebd4HzDRk5f7uFMTcx/Cyu1toC/nMVHFxeZw65HcVZo2
            BRHtEIb8vEvmadGpfnO40l4BI0jwVIy478gO/NPljIwrQv2I9azpKBMWM3l1C9R7
            Aa6nNMCKXnrHUyY0iHhgfLTP8WstO477aIFTevdriG9szV+4s7p7M/kcTVmQk/Ww
            5ipWOoR7Ctg7TfHSrNSC
            =43KI
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-config-paperless
    namespace: paperless
type: Opaque
stringData:
    #ENC[AES256_GCM,data:+4DEbPMOaqlogOeMz2vTk8W3kG6obLSG4AWujMj6aZSkEHnb7Zq3GfPZwjQ7grSRq3gXRa0Uusb5ICVeI1fKfeg=,iv:ErNicpGjlV0QMESqCtE+bzQEuK3XtYrCAe4zywP1xAU=,tag:abSJNRhIxEn5gM9136Xy8g==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:Um+GDdDgYKoOFwYznahChLKbEOAL3JSKmWCjYuGvNwpP+G8hqp/Sj+fjXUyGyILnxg==,iv:PD+UzhFZNeLOU57uFkGBGgaXbw3+rAufnCc6WO7fSJk=,tag:RmIoxgvePTiUDnkjUHsx1A==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:6V8jCprcuVBca398lzDxKKqNl67cqexeuePYuuDK3XP7OrOGFoQGLNck8djHs/K0,iv:vgsZ7zmkWFptU0SV/TMnD6tbb2NCz7f7CuSkJvssb3w=,tag:jfhIby/DuIKkhv2vl9Xk2A==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:aQGCOUnRBthoIujqOdM6K/bOOEM3t0+pi+c=,iv:SPQhl3pB8tw9rhPp1NMis6nMeWHSNiL3+dje4OSq+cE=,tag:si1yffNYGBLuP6FTpyfOvQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:a1zPBpLIP1JhN/phd7op02j6lR3AJzs+GW/ECppRdP3UDXDh54NeuswK7F9n6s0YYUCsUun4XFKBW5dRX2alHA==,iv:eVnvYQbDlPKaAY1Sbioywn/ehaPRZdXki+KufXSjr0A=,tag:+ulpdjV1FxdoryGeM3+YEg==,type:str]
sops:
    lastmodified: "2026-03-23T18:27:06Z"
    mac: ENC[AES256_GCM,data:0rtuKvm1zo5U1CrHqBIUbl/VBH5j4chGmcKNXZSNm6iT4lxhEh+wjPVa6IKj3RVkgeSPjX0ZLas7qOq3XrFSenq8Iw9I3TaqYppaOPfRyc2/NZx+pOGiUEu4glhNoOrvOfJXPkHOewhXaHKg4UV8ZqRoA0BsSMZ1iv0Sf481GRk=,iv:7Ucb48VpC5vkNsqlyxTZIwqL+l0FDzPG7t5zlVwdW2E=,tag:ekZMt7GBFM8QNs6JJVMfQQ==,type:str]
    pgp:
        - created_at: "2026-03-23T18:27:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv+IO/fD0d5P5P5XmdTyo84iQLCD6eH5xC53RRywghWAIHE
            l8FGn88Q5urxnr/ns/teq/NiR7mmYy6A+etPqGS9/zCYVgR6rl3clDQ80jRLqtB7
            25x2Qb0cpuonTo7ceFLVHsI1bCQdF7H+FoPjNxlMq57THXL8KtPRJSArisMXzp+o
            SAbpy23z9jQLmTg3Bbtw3TZOU1WFi+Posj9yHVJRIClNUJm3MBli/8RTwoSwihWP
            lyi3PTIfyZWJRnv4i7LFECCBr/Cd25IMJlZSI+RXRvFeM5xqwXSRZsqMXW+Z9uH5
            0QNGslb2S3uFI7j3b+IDQqUMFR4f8YvDLkOLX/tJ8RhREeBaWlsGmh2L42MnVpFE
            xNss6XOzgffHjh3dTtEA7DdXXdaRYtcILdL3w1fGM9Qa6CfpmpthApbe971+A1tg
            KaiRmLxv3qBuPqF37y++Ebd4HzDRk5f7uFMTcx/Cyu1toC/nMVHFxeZw65HcVZo2
            BRHtEIb8vEvmadGpfnO40l4BI0jwVIy478gO/NPljIwrQv2I9azpKBMWM3l1C9R7
            Aa6nNMCKXnrHUyY0iHhgfLTP8WstO477aIFTevdriG9szV+4s7p7M/kcTVmQk/Ww
            5ipWOoR7Ctg7TfHSrNSC
            =43KI
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: paperless-env
    namespace: paperless
type: Opaque
stringData:
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:b0Kf4c+oJio7YLrTh/E=,iv:y7GT0V1A3wu0ws5Mv5XbrfUykLKjTNn7WcawUtsIZ1U=,tag:B5I5tDguqL4KC4YDBnhI7w==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:3ijF87XEa+lZIbQ0JoY=,iv:4Qb32i9aqT4j83BVe4LVfZ5otmr15q3jn3bPWgPy4Cc=,tag:vU7tSHmvDBC0LwwVR/CxtA==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:vUt5IpEx8A9w2abVSX6OO24Gx9jHx5fOTCHRj0KS/dbnYXLT6oOGciPC4IpMZCQPSRoujldY239YewZhNAEOLpdl8zahjEpBDa4gEcWezC6zPbDWCueUu0ahvgbJuL8jJCxdmMQFsmpUN9q+ZvDnuz1I7jCOeXAwAtAZCMdis7g5dN+HnJtVfugkc19Qw80yZeW1g9vB8tQftETjVpem7w81Cfzq5e2ftQ3akLjlDRFK+FLxNHtuOJmfEe++AvQkwz1rgCG7HjmBVUc2QkvfIbnp1yRK0DrLzA07l+avTew66clLlSEq3T1/ZN6rRWw4q6GLKzZLCk0O1WPIP49BDkf/pnC6BXu7iD4/7frQjo/QY3vDe3vw312ruEpXBf3+/giRYcwRRXjm0raQ8ZzHBzQFLxnSh9FIxzYNTmShJXMdylM3yktyaQMaiHOYQdUNLOp5JP8zUFOGIUlA27IPrRfllPXLo0X6peCd+XY2y+JEVQMgVP9MFl614HBbkWtcoTmtaOQGS8PzIAsieI9NiptG0oqSgfii3/9NpCaV3Jet2BmhRqogCrTiaQDxq98lrgJao9Yjw+emAmLuhFDfs7WYxCW4lUtLeDp5MRRJUt73Xp34xyhs1Pe0ERFRKeKj0ALMaTq3Tgb0+MawRKXQk9muzX3XXor4wkaerohaz9qN5z5+xVP4+yO4Yg/j//B8T6lRIqjEOFLxD7Er8SAWdZ0fb5RMeLvEu+1T/JjaNGkdCEhv,iv:nmMi+45w2aB7fhHXaC3zKvClVY24SdPz5Myhu+k0joI=,tag:a3MAvfqvltb+4xwCv3lRqw==,type:str]
sops:
    lastmodified: "2026-03-23T18:27:06Z"
    mac: ENC[AES256_GCM,data:0rtuKvm1zo5U1CrHqBIUbl/VBH5j4chGmcKNXZSNm6iT4lxhEh+wjPVa6IKj3RVkgeSPjX0ZLas7qOq3XrFSenq8Iw9I3TaqYppaOPfRyc2/NZx+pOGiUEu4glhNoOrvOfJXPkHOewhXaHKg4UV8ZqRoA0BsSMZ1iv0Sf481GRk=,iv:7Ucb48VpC5vkNsqlyxTZIwqL+l0FDzPG7t5zlVwdW2E=,tag:ekZMt7GBFM8QNs6JJVMfQQ==,type:str]
    pgp:
        - created_at: "2026-03-23T18:27:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv+IO/fD0d5P5P5XmdTyo84iQLCD6eH5xC53RRywghWAIHE
            l8FGn88Q5urxnr/ns/teq/NiR7mmYy6A+etPqGS9/zCYVgR6rl3clDQ80jRLqtB7
            25x2Qb0cpuonTo7ceFLVHsI1bCQdF7H+FoPjNxlMq57THXL8KtPRJSArisMXzp+o
            SAbpy23z9jQLmTg3Bbtw3TZOU1WFi+Posj9yHVJRIClNUJm3MBli/8RTwoSwihWP
            lyi3PTIfyZWJRnv4i7LFECCBr/Cd25IMJlZSI+RXRvFeM5xqwXSRZsqMXW+Z9uH5
            0QNGslb2S3uFI7j3b+IDQqUMFR4f8YvDLkOLX/tJ8RhREeBaWlsGmh2L42MnVpFE
            xNss6XOzgffHjh3dTtEA7DdXXdaRYtcILdL3w1fGM9Qa6CfpmpthApbe971+A1tg
            KaiRmLxv3qBuPqF37y++Ebd4HzDRk5f7uFMTcx/Cyu1toC/nMVHFxeZw65HcVZo2
            BRHtEIb8vEvmadGpfnO40l4BI0jwVIy478gO/NPljIwrQv2I9azpKBMWM3l1C9R7
            Aa6nNMCKXnrHUyY0iHhgfLTP8WstO477aIFTevdriG9szV+4s7p7M/kcTVmQk/Ww
            5ipWOoR7Ctg7TfHSrNSC
            =43KI
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
