apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - jdownloader.yaml
  - nfs.yaml
  - metube.yaml
  - qbittorrent.yaml
  - tranga.yaml
  - secrets.yaml
  - tranga-db.yaml
  - sabnzbd.yaml
  - backup.yaml