---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jdownloader2-nfs-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.178.118  
    path: /mnt/zfs-pool/media/downloads/jdownloader

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jdownloader2-nfs
  namespace: downloader
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: ''
  volumeMode: Filesystem
  volumeName: jdownloader2-nfs-pv