apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: downloader
spec:
  interval: 10m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true 
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: "5.0.1"
  values:
    controllers:
      sabnzbd:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "false"
        containers:
          app: 
            image:
              repository: lscr.io/linuxserver/sabnzbd
              tag: 5.0.4@sha256:c2f1826a3d231b9506554a60447e763157fd8ba4f600a4a864d6d0ddae00a0aa
              pullPolicy: Always
            env:
              TZ: Europe/Berlin
            resources:
              requests:
                cpu: "250m"     
                memory: "128Mi"  
              limits:
                cpu: "1"     
                memory: "2048Mi"  
          gluetun:
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.41
            env:
              VPN_SERVICE_PROVIDER: custom
              VPN_TYPE: wireguard
              VPN_INTERFACE: wg0
              VPN_ENDPOINT_PORT: 51820
              VPN_PORT_FORWARDING: off
              VPN_PORT_FORWARDING_PROVIDER: protonvpn
              WIREGUARD_MTU: 1280
              HEALTH_ICMP_TARGET_IPS: "1.1.1.1"
              DOT: off
              FIREWALL_INPUT_PORTS: 8080
              FIREWALL_OUTBOUND_SUBNETS: 10.10.10.0/24,10.50.0.0/23,10.244.0.0/16,192.168.178.0/24
              WIREGUARD_PERSISTENT_KEEPALIVE_INTERVAL: 25s
            envFrom:
              - secretRef:
                  name: sabnzb-secret
            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  exec:
                    command: ["/gluetun-entrypoint", "healthcheck"]
                  periodSeconds: 10
                  failureThreshold: 30
              liveness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command: ["/gluetun-entrypoint", "healthcheck"]
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 3
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
              allowPrivilegeEscalation: false
            resources:
              requests:
                cpu: 100m
              limits:
                cpu: 200m
                memory: 512Mi


    service:
      app:
        controller: sabnzbd
        ports:
          http:
            port: 8080

    ingress:
      app:
        className: "cilium"
        hosts:
          - host: "sabnzbd.k8s.exmaple.com"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - "sabnzbd.k8s.exmaple.com"

    persistence:
      config:
        existingClaim: sabnzbd-config
        advancedMounts:
          sabnzbd:
            app:
              - path: /config         

      cache:
        existingClaim: sabnzbd-cache
        advancedMounts:
          sabnzbd:
            app:
              - path: /incomplete-downloads  

      serien:
        type: nfs
        server: 192.168.178.118
        path: /mnt/zfs-pool/media/downloads/sabnzb/serien
        globalMounts:
          - path: /serien

      filme:
        type: nfs
        server: 192.168.178.118
        path: /mnt/zfs-pool/media/downloads/sabnzb/filme
        globalMounts:
          - path: /filme

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config
  namespace: downloader
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-rbd-sc
  resources:
    requests:
      storage: 10Gi 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-cache
  namespace: downloader
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-rbd-sc
  resources:
    requests:
      storage: 100Gi 