apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: downloader
spec:
  interval: 10m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true 
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: "5.2.1"
  values:
    controllers:
      sabnzbd:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "false"
        pod:
          securityContext:
            fsGroup: 0
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app: 
            image:
              repository: lscr.io/linuxserver/sabnzbd
              tag: 5.1.3@sha256:793828eab1722556131d37187115a9d3e3b9703e03a55731a07f2e0fe4edc2c7
              pullPolicy: Always
            env:
              TZ: Europe/Berlin
              PUID: 0
              PGID: 0
              UMASK: "002"
            resources:
              requests:
                cpu: "250m"     
                memory: "128Mi"  
              limits:
                cpu: "1"     
                memory: "1250Mi"  
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              seccompProfile:
                type: RuntimeDefault

    service:
      app:
        controller: sabnzbd
        ports:
          http:
            port: 8080

    ingress:
      app:
        className: "cilium"
        hosts:
          - host: "sabnzbd.k8s.exmaple.com"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - "sabnzbd.k8s.exmaple.com"

    persistence:
      config:
        existingClaim: sabnzbd-config
        advancedMounts:
          sabnzbd:
            app:
              - path: /config         

      cache:
        existingClaim: sabnzbd-cache
        advancedMounts:
          sabnzbd:
            app:
              - path: /incomplete-downloads  

      downloads:
        type: nfs
        server: 192.168.178.118
        path: /mnt/zfs-pool/media/downloads/sabnzb
        globalMounts:
          - path: /downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config
  namespace: downloader
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-rbd-sc
  resources:
    requests:
      storage: 10Gi 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-cache
  namespace: downloader
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-rbd-sc
  resources:
    requests:
      storage: 100Gi 