apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: downloader
spec:
  interval: 10m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true 
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: "5.0.1"
  values:
    controllers:
      sabnzbd:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "false"
        containers:
          app: 
            image:
              repository: lscr.io/linuxserver/sabnzbd
              tag: 5.0.3@sha256:2924efdf345e8e69cc2137b21fd3222843ac882ee0bf54207e6524774f89121e
              pullPolicy: Always
            env:
              TZ: Europe/Berlin
            resources:
              requests:
                cpu: "250m"     
                memory: "128Mi"  
              limits:
                cpu: "1"     
                memory: "2048Mi"  

    service:
      app:
        controller: sabnzbd
        ports:
          http:
            port: 8080

    ingress:
      app:
        className: "cilium"
        hosts:
          - host: "sabnzbd.k8s.exmaple.com"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - "sabnzbd.k8s.exmaple.com"

    persistence:
      config:
        existingClaim: sabnzbd-config
        advancedMounts:
          sabnzbd:
            app:
              - path: /config         

      cache:
        existingClaim: sabnzbd-cache
        advancedMounts:
          sabnzbd:
            app:
              - path: /incomplete-downloads  

      serien:
        type: nfs
        server: 192.168.178.118
        path: /mnt/zfs-pool/media/downloads/sabnzb/serien
        globalMounts:
          - path: /serien

      filme:
        type: nfs
        server: 192.168.178.118
        path: /mnt/zfs-pool/media/downloads/sabnzb/filme
        globalMounts:
          - path: /filme

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config
  namespace: downloader
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-rbd-sc
  resources:
    requests:
      storage: 10Gi 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-cache
  namespace: downloader
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-rbd-sc
  resources:
    requests:
      storage: 100Gi 