apiVersion: v1
kind: Secret
metadata:
    name: jdownloader2-secrets
    namespace: downloader
data:
    email: ENC[AES256_GCM,data:jO6kyz0velmpwEuBoPT3tLoM+vk=,iv:7Q25ILLi8zh/YcDoghjmf9h5YCosgqWnZvSU0K2Wm64=,tag:XJZsHxbOgkDbZlqc1VzVvQ==,type:str]
    password: ENC[AES256_GCM,data:xKzsFXc5cXwBkde8HT7BWLvE/CM=,iv:JmNjsC6tnImY5HTHXpf1AhymFSVuFh+nsIi6gB1lLvU=,tag:06/DGgiXND7r/uXh27a9cw==,type:str]
sops:
    lastmodified: "2025-12-31T13:35:25Z"
    mac: ENC[AES256_GCM,data:EGO6me6AvYja0ZJDtuMdtvcUu8o1+8y7RaITv7WzZV5SrvQc2YOXEF6ALcCAuX51SpWssT0gzEOTQab9jJpLO+VZEHJHVAitrGiWfPQC/MvML+JshxWPiJV4eFA44Ls4Qj/qSmOs7NtmQpPUoRQHc5x3WYYG23/Thut9hH2tFdg=,iv:HMNLWhGIRZLq84aQyFkMwZUfNmj4xfcZNfKigrwPFNM=,tag:ArsiPyiXVrognSXhUJUD+g==,type:str]
    pgp:
        - created_at: "2025-12-31T13:35:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQwAnwbBMa3Fs1q6RfTpJDNlODi0nhsvZTE/O7HcSdiGqwEo
            Meb1eISUVaOKDOBG2FgIseajOxgvNVHO3AMZtPV9io4K1x6M1PNyILjb9zyY+ew6
            Htn3V5a+6xBmz5KRmmJZB66sqyyTVqd4swhr1Fs0G8d5G2gFv1i7brWLS1GAdiah
            mxwtvwinHyicErLwvVhyFjIzHfk2CO1hUmRkqVH2d003AhPhuoq1K6/bRLPGoXx3
            l2OMgvvT6GswuZ/SC8/td0Nu6Ff5Yp+XAvKuwLyTekhtgOaB5IudbwuFlesQuFr/
            WCPKap69VH+4eswm3/6WJT7D0ELoOTuDXAk0SpFWLU8v93jymdEpRUpfEFC+HjYH
            jwDhsspp6F6Od7Lq8ad2g671jk2o8OwokJFWmlhf6sWNY02/NXrXLkuXXtBVNvFm
            jzdtzU3cQzqv9bJrPlGmEmvqJKjENt3Xolj8jCzP27rtBuSEmtVI/FEIz/iqrCN5
            5QnatpPd6YmiRHxiVLV40lwBukkgJMj4Wzobbxedfg2kjC/SPESbuzva+65sx2GM
            J5/eNTFZDDYnpSZrZdZ1TTcK2g8KJzQfGwtw+PqpmE8dkY2KT2Qkw6ULS8R0L+b3
            eWIvZid/UtWqcMv+OA==
            =os/u
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: transmission-secrets
    namespace: downloader
data:
    OPENVPN_USERNAME: ENC[AES256_GCM,data:n24idlfP3S/eBZ8k5WaxcakWqQzLkZ5M,iv:HieENtuFZBTU6O2k/AaygcJOEKINRhxzMNqFic4ylmw=,tag:ycy4xQpXYLnxYBI9UrUOsw==,type:str]
sops:
    lastmodified: "2025-12-31T13:35:25Z"
    mac: ENC[AES256_GCM,data:EGO6me6AvYja0ZJDtuMdtvcUu8o1+8y7RaITv7WzZV5SrvQc2YOXEF6ALcCAuX51SpWssT0gzEOTQab9jJpLO+VZEHJHVAitrGiWfPQC/MvML+JshxWPiJV4eFA44Ls4Qj/qSmOs7NtmQpPUoRQHc5x3WYYG23/Thut9hH2tFdg=,iv:HMNLWhGIRZLq84aQyFkMwZUfNmj4xfcZNfKigrwPFNM=,tag:ArsiPyiXVrognSXhUJUD+g==,type:str]
    pgp:
        - created_at: "2025-12-31T13:35:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQwAnwbBMa3Fs1q6RfTpJDNlODi0nhsvZTE/O7HcSdiGqwEo
            Meb1eISUVaOKDOBG2FgIseajOxgvNVHO3AMZtPV9io4K1x6M1PNyILjb9zyY+ew6
            Htn3V5a+6xBmz5KRmmJZB66sqyyTVqd4swhr1Fs0G8d5G2gFv1i7brWLS1GAdiah
            mxwtvwinHyicErLwvVhyFjIzHfk2CO1hUmRkqVH2d003AhPhuoq1K6/bRLPGoXx3
            l2OMgvvT6GswuZ/SC8/td0Nu6Ff5Yp+XAvKuwLyTekhtgOaB5IudbwuFlesQuFr/
            WCPKap69VH+4eswm3/6WJT7D0ELoOTuDXAk0SpFWLU8v93jymdEpRUpfEFC+HjYH
            jwDhsspp6F6Od7Lq8ad2g671jk2o8OwokJFWmlhf6sWNY02/NXrXLkuXXtBVNvFm
            jzdtzU3cQzqv9bJrPlGmEmvqJKjENt3Xolj8jCzP27rtBuSEmtVI/FEIz/iqrCN5
            5QnatpPd6YmiRHxiVLV40lwBukkgJMj4Wzobbxedfg2kjC/SPESbuzva+65sx2GM
            J5/eNTFZDDYnpSZrZdZ1TTcK2g8KJzQfGwtw+PqpmE8dkY2KT2Qkw6ULS8R0L+b3
            eWIvZid/UtWqcMv+OA==
            =os/u
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
data:
    password: ENC[AES256_GCM,data:VZxr4cqsiad7FP04pb88jg7jnLs=,iv:AypdDKaxSDn5d89e7rnsl3NGJUx66tv05MsrL9VWau4=,tag:B9Kxhg8cGm+EbsIEGGGBzQ==,type:str]
    username: ENC[AES256_GCM,data:mjGAt+tHDGQ=,iv:CkPnNGPj572hqjSPFi3i3O1mSGpaCjY3P7Afy97KyP0=,tag:vMThf/ndeZbAQujs9gPKGw==,type:str]
kind: Secret
metadata:
    name: tranga-db-secret
    namespace: downloader
type: Opaque
sops:
    lastmodified: "2025-12-31T13:35:25Z"
    mac: ENC[AES256_GCM,data:EGO6me6AvYja0ZJDtuMdtvcUu8o1+8y7RaITv7WzZV5SrvQc2YOXEF6ALcCAuX51SpWssT0gzEOTQab9jJpLO+VZEHJHVAitrGiWfPQC/MvML+JshxWPiJV4eFA44Ls4Qj/qSmOs7NtmQpPUoRQHc5x3WYYG23/Thut9hH2tFdg=,iv:HMNLWhGIRZLq84aQyFkMwZUfNmj4xfcZNfKigrwPFNM=,tag:ArsiPyiXVrognSXhUJUD+g==,type:str]
    pgp:
        - created_at: "2025-12-31T13:35:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQwAnwbBMa3Fs1q6RfTpJDNlODi0nhsvZTE/O7HcSdiGqwEo
            Meb1eISUVaOKDOBG2FgIseajOxgvNVHO3AMZtPV9io4K1x6M1PNyILjb9zyY+ew6
            Htn3V5a+6xBmz5KRmmJZB66sqyyTVqd4swhr1Fs0G8d5G2gFv1i7brWLS1GAdiah
            mxwtvwinHyicErLwvVhyFjIzHfk2CO1hUmRkqVH2d003AhPhuoq1K6/bRLPGoXx3
            l2OMgvvT6GswuZ/SC8/td0Nu6Ff5Yp+XAvKuwLyTekhtgOaB5IudbwuFlesQuFr/
            WCPKap69VH+4eswm3/6WJT7D0ELoOTuDXAk0SpFWLU8v93jymdEpRUpfEFC+HjYH
            jwDhsspp6F6Od7Lq8ad2g671jk2o8OwokJFWmlhf6sWNY02/NXrXLkuXXtBVNvFm
            jzdtzU3cQzqv9bJrPlGmEmvqJKjENt3Xolj8jCzP27rtBuSEmtVI/FEIz/iqrCN5
            5QnatpPd6YmiRHxiVLV40lwBukkgJMj4Wzobbxedfg2kjC/SPESbuzva+65sx2GM
            J5/eNTFZDDYnpSZrZdZ1TTcK2g8KJzQfGwtw+PqpmE8dkY2KT2Qkw6ULS8R0L+b3
            eWIvZid/UtWqcMv+OA==
            =os/u
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: garage-creds
    namespace: downloader
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:6EWfMSo4M+8vuSF0CrDM0gc19lp2VhHRgbQ=,iv:ZaNUp107ucA60Nidf3/XnWqzECggjpxMAIPGmjzUaOw=,tag:FvXGoWteeOH3HLCsiz+fEg==,type:str]
    secret-access-key: ENC[AES256_GCM,data:LsrQVJUCGUUPnhbPAf8KhsB4gOVbBeWBknjNYyvX+buVZjwTVYJCJ3p9hjrobv7JDhW+gPpqo4TJaf8fvdajZw==,iv:5bfyuGg/KHF0MJqEUTqXJSrRGVFVh0nLttKAMjUqztY=,tag:4mWs9HE7j7MHdf3RzMlzgw==,type:str]
    region: ENC[AES256_GCM,data:/jy8Qg==,iv:TiytV71/5F7Y3hHTfl0qs4uucw1LyFdrc7wM7Ah+H4U=,tag:Kl7rkwj5LRjFz7loqdbPrA==,type:str]
sops:
    lastmodified: "2025-12-31T13:35:25Z"
    mac: ENC[AES256_GCM,data:EGO6me6AvYja0ZJDtuMdtvcUu8o1+8y7RaITv7WzZV5SrvQc2YOXEF6ALcCAuX51SpWssT0gzEOTQab9jJpLO+VZEHJHVAitrGiWfPQC/MvML+JshxWPiJV4eFA44Ls4Qj/qSmOs7NtmQpPUoRQHc5x3WYYG23/Thut9hH2tFdg=,iv:HMNLWhGIRZLq84aQyFkMwZUfNmj4xfcZNfKigrwPFNM=,tag:ArsiPyiXVrognSXhUJUD+g==,type:str]
    pgp:
        - created_at: "2025-12-31T13:35:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQwAnwbBMa3Fs1q6RfTpJDNlODi0nhsvZTE/O7HcSdiGqwEo
            Meb1eISUVaOKDOBG2FgIseajOxgvNVHO3AMZtPV9io4K1x6M1PNyILjb9zyY+ew6
            Htn3V5a+6xBmz5KRmmJZB66sqyyTVqd4swhr1Fs0G8d5G2gFv1i7brWLS1GAdiah
            mxwtvwinHyicErLwvVhyFjIzHfk2CO1hUmRkqVH2d003AhPhuoq1K6/bRLPGoXx3
            l2OMgvvT6GswuZ/SC8/td0Nu6Ff5Yp+XAvKuwLyTekhtgOaB5IudbwuFlesQuFr/
            WCPKap69VH+4eswm3/6WJT7D0ELoOTuDXAk0SpFWLU8v93jymdEpRUpfEFC+HjYH
            jwDhsspp6F6Od7Lq8ad2g671jk2o8OwokJFWmlhf6sWNY02/NXrXLkuXXtBVNvFm
            jzdtzU3cQzqv9bJrPlGmEmvqJKjENt3Xolj8jCzP27rtBuSEmtVI/FEIz/iqrCN5
            5QnatpPd6YmiRHxiVLV40lwBukkgJMj4Wzobbxedfg2kjC/SPESbuzva+65sx2GM
            J5/eNTFZDDYnpSZrZdZ1TTcK2g8KJzQfGwtw+PqpmE8dkY2KT2Qkw6ULS8R0L+b3
            eWIvZid/UtWqcMv+OA==
            =os/u
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-secret
    namespace: downloader
type: Opaque
stringData:
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:6vk1xSAwp2KyQpi7AQ==,iv:QcJcplpT4oC97OunITEO74fYi2uuqhY6nqjt0AUO9NM=,tag:g+sklWA9oZx9ptol40gBiQ==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:fVUSJgU=,iv:YvU2eCPeTMa4d12qbVriXkkeE7Ng5tdlmADWg/BYdII=,tag:+OVfLlAG3+U2mPN5wG9F6g==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:BY0fD2oOuEwhl3HWFq5OWAbTZeoIQooiHN8ld4ays8ASlk5IjH1YNqf+H0w=,iv:1Kkf5h92LY5SQrrkQuTAM43/dNef49w3wcqrhcrVfHs=,tag:jCUVX9CWCNaKe6KIhj+n7w==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:c0cUv2T0YjjuGsyEmEaEYRbhDvbzpteLCC4SfE18VkMqPDlF9pR3jc4+Z74=,iv:pshzutbZCj8WImCLO0nNKPwfZyBaV7mlLgP3uV469Lo=,tag:EeN1DMNk+/ZgePtGMO6QzQ==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:OE6CbdDEbjPCK+I=,iv:98AlSQ6eIk8WgdQy1fMuyZhfdEM15V6vU4FZwuiBskM=,tag:So/BBmHtAgiTo8tF+rtiQQ==,type:str]
sops:
    lastmodified: "2025-12-31T13:35:25Z"
    mac: ENC[AES256_GCM,data:EGO6me6AvYja0ZJDtuMdtvcUu8o1+8y7RaITv7WzZV5SrvQc2YOXEF6ALcCAuX51SpWssT0gzEOTQab9jJpLO+VZEHJHVAitrGiWfPQC/MvML+JshxWPiJV4eFA44Ls4Qj/qSmOs7NtmQpPUoRQHc5x3WYYG23/Thut9hH2tFdg=,iv:HMNLWhGIRZLq84aQyFkMwZUfNmj4xfcZNfKigrwPFNM=,tag:ArsiPyiXVrognSXhUJUD+g==,type:str]
    pgp:
        - created_at: "2025-12-31T13:35:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQwAnwbBMa3Fs1q6RfTpJDNlODi0nhsvZTE/O7HcSdiGqwEo
            Meb1eISUVaOKDOBG2FgIseajOxgvNVHO3AMZtPV9io4K1x6M1PNyILjb9zyY+ew6
            Htn3V5a+6xBmz5KRmmJZB66sqyyTVqd4swhr1Fs0G8d5G2gFv1i7brWLS1GAdiah
            mxwtvwinHyicErLwvVhyFjIzHfk2CO1hUmRkqVH2d003AhPhuoq1K6/bRLPGoXx3
            l2OMgvvT6GswuZ/SC8/td0Nu6Ff5Yp+XAvKuwLyTekhtgOaB5IudbwuFlesQuFr/
            WCPKap69VH+4eswm3/6WJT7D0ELoOTuDXAk0SpFWLU8v93jymdEpRUpfEFC+HjYH
            jwDhsspp6F6Od7Lq8ad2g671jk2o8OwokJFWmlhf6sWNY02/NXrXLkuXXtBVNvFm
            jzdtzU3cQzqv9bJrPlGmEmvqJKjENt3Xolj8jCzP27rtBuSEmtVI/FEIz/iqrCN5
            5QnatpPd6YmiRHxiVLV40lwBukkgJMj4Wzobbxedfg2kjC/SPESbuzva+65sx2GM
            J5/eNTFZDDYnpSZrZdZ1TTcK2g8KJzQfGwtw+PqpmE8dkY2KT2Qkw6ULS8R0L+b3
            eWIvZid/UtWqcMv+OA==
            =os/u
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-config-sabnzbd
    namespace: downloader
type: Opaque
stringData:
    #ENC[AES256_GCM,data:NslL9SLRsh1YDl73pZCnYs8NreE9Gm105czTYv2dDHIf0L+SZ9citg0I7rdIyGwXl0IaYnZzBNNn3WU3B7vVzX0=,iv:5vecmrnhI2QFjQe0WCPtsXVrZ9IxukRUTCfK3J4tvb8=,tag:/xDUY+7TaCuURI+OchSDNg==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:Aw1tpIg9Tdo9h/xK6SqmrJozNCq+qdtcU5e7B7iku/7LaJU/5Qst8ipB2lSDmTY=,iv:fDMUNuEBsRO5thkStIBZb04qutfNF288WBU0OLUmGvc=,tag:zDbKMyrDuKKRP6hS0MPJJw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:dG27csk7ugAMuIF5V8cS/XntsE68p9rnS1tsz8Oe5TwXlR4RdEi2qN0xBk+Qiisz,iv:LZiozYUHZhqNybdrdaitcg+e9aYrqm/Cf2qcmXu5P/8=,tag:dYRdirl1G+YTWDdLLJebag==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:wSZdTpJ8heDADqAGoHF+xNXIdVxJ+X22Qe4=,iv:V5zX18gOqPSTh5Nd6FFqecapZVbbhj2CTTL8ljNqtps=,tag:cec+Xt2ib9zwvHGNuOBi4A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:RO+c6/rsnyLjGAf+wsMOuvGlDjvpgQlN+uLEJjf/lifwpIFn5o14GSt55HTBGL2WNUYQx7BYvOtrrow+EgSXQg==,iv:tIf3AVEUhhZO+O5KvJVCmTCWHKG+Vn4L+quZG4BGd1U=,tag:+UJVroGbOlEul3KlAy2YKQ==,type:str]
sops:
    lastmodified: "2025-12-31T13:35:25Z"
    mac: ENC[AES256_GCM,data:EGO6me6AvYja0ZJDtuMdtvcUu8o1+8y7RaITv7WzZV5SrvQc2YOXEF6ALcCAuX51SpWssT0gzEOTQab9jJpLO+VZEHJHVAitrGiWfPQC/MvML+JshxWPiJV4eFA44Ls4Qj/qSmOs7NtmQpPUoRQHc5x3WYYG23/Thut9hH2tFdg=,iv:HMNLWhGIRZLq84aQyFkMwZUfNmj4xfcZNfKigrwPFNM=,tag:ArsiPyiXVrognSXhUJUD+g==,type:str]
    pgp:
        - created_at: "2025-12-31T13:35:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQwAnwbBMa3Fs1q6RfTpJDNlODi0nhsvZTE/O7HcSdiGqwEo
            Meb1eISUVaOKDOBG2FgIseajOxgvNVHO3AMZtPV9io4K1x6M1PNyILjb9zyY+ew6
            Htn3V5a+6xBmz5KRmmJZB66sqyyTVqd4swhr1Fs0G8d5G2gFv1i7brWLS1GAdiah
            mxwtvwinHyicErLwvVhyFjIzHfk2CO1hUmRkqVH2d003AhPhuoq1K6/bRLPGoXx3
            l2OMgvvT6GswuZ/SC8/td0Nu6Ff5Yp+XAvKuwLyTekhtgOaB5IudbwuFlesQuFr/
            WCPKap69VH+4eswm3/6WJT7D0ELoOTuDXAk0SpFWLU8v93jymdEpRUpfEFC+HjYH
            jwDhsspp6F6Od7Lq8ad2g671jk2o8OwokJFWmlhf6sWNY02/NXrXLkuXXtBVNvFm
            jzdtzU3cQzqv9bJrPlGmEmvqJKjENt3Xolj8jCzP27rtBuSEmtVI/FEIz/iqrCN5
            5QnatpPd6YmiRHxiVLV40lwBukkgJMj4Wzobbxedfg2kjC/SPESbuzva+65sx2GM
            J5/eNTFZDDYnpSZrZdZ1TTcK2g8KJzQfGwtw+PqpmE8dkY2KT2Qkw6ULS8R0L+b3
            eWIvZid/UtWqcMv+OA==
            =os/u
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
