apiVersion: v1
kind: Secret
metadata:
    name: jdownloader2-secrets
    namespace: downloader
data:
    email: ENC[AES256_GCM,data:b2K3xVbYeaW7pJ+q1w2RyBKpo1s=,iv:t7IbNgQvBq92tFpmHzK14tzuZxWIXErlvzYq//kBPE8=,tag:bCY3wOco0DHrqghUr/E3EA==,type:str]
    password: ENC[AES256_GCM,data:OlL5Nv2Qy2Etr9OdBxAR0DfzcUw=,iv:uR+al2raMlzwFj7LxBnsvQo5XgdpIq0xWymUNd62n4M=,tag:KRuEYCvRr2qcuUU8DlUZ8Q==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T11:06:53Z"
    mac: ENC[AES256_GCM,data:0c6HHh4bdQBMjz3xhmavFk72hhitw+DPQCOva6YGjCUN+bC8zHXg3cLQf2UQ4pDHq9Xiwb61BGVFKqI/cAX0fAsa99zrfdDpSFSPLZNuOaNiyVsdFCk/xTAljABYiB5/AIYf5nm6eCPTtWmVpUwf5R+dyyfvNUBbIehCDoHTmCM=,iv:5YoyOOYi7oEKaWsvTAteD+ER/vezJGSFESFgtAB+UnQ=,tag:gWMaPdLl3rCSXlO749QQ4g==,type:str]
    pgp:
        - created_at: "2026-06-04T11:06:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/cF+a8el8idrQsEPtNsMnw3ohnqIzOa42KGmP3JiVk5rK
            w8JlJ4nVumnJ2aq/oV5oopXFXUDRKDSyYrkPbZGAQKmXhwRItulRMEapDjU3TQ4G
            sS/pcE3bJjxIokKsEJe9Kdth0qQrAdmmHxFwYJrW217NT30UT8o+WDDp4iPa7a3E
            3yQA4sBTxZV+ySQFBeGNj8H5ZTxNqP9QVB4wr6RJtwzWuLMB8McsRu5X/eiSSfdO
            KtS2EDbDgGV4nsQbS0bqxaGPUgcYC1/Pp+QNhJxvXzwJbJRa/qCvvWolAJ2axkjr
            YOLipxPg8TL3QzJyN5gy1L8gAzMpbq2WONBJPSEyPv90yZmeuTW5SsTWsAidMNxe
            5v2qMSjrmoUbXczM5p6EyxSmMgrcp/BzhoRxb2gu1xC/XmPp1i4dbM7ttWhWmR29
            asFGKw+BCCSUAR/e7J56tVc3GMfjh9Q/fP2eFMzgoF0OcY7uNFXe9i1te7HwcqYm
            bpY/DmhZT9vro8EI3kKy0l4B1zDrEt5BF7ggOIqK70g97Z4+kS9i/MfHNDcCqtyA
            sStwGQUofLMJ3LpHNhH6gedRTOceRymgorJpk6dRbcINcswNB1QgUKtVaL+K5Nd0
            62zDrzJQZ4fbMzsRoxqR
            =Bqpj
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: transmission-secrets
    namespace: downloader
data:
    OPENVPN_USERNAME: ENC[AES256_GCM,data:DUNadkI9UziPbxQZCoj9E43hNhkrbsV+,iv:1dfJFpYSw9F6UWRgdX8zhqFmMuLxUiGJun1aRwj2JPI=,tag:jmabw5OVJRXL4W81sBBqTQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T11:06:53Z"
    mac: ENC[AES256_GCM,data:0c6HHh4bdQBMjz3xhmavFk72hhitw+DPQCOva6YGjCUN+bC8zHXg3cLQf2UQ4pDHq9Xiwb61BGVFKqI/cAX0fAsa99zrfdDpSFSPLZNuOaNiyVsdFCk/xTAljABYiB5/AIYf5nm6eCPTtWmVpUwf5R+dyyfvNUBbIehCDoHTmCM=,iv:5YoyOOYi7oEKaWsvTAteD+ER/vezJGSFESFgtAB+UnQ=,tag:gWMaPdLl3rCSXlO749QQ4g==,type:str]
    pgp:
        - created_at: "2026-06-04T11:06:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/cF+a8el8idrQsEPtNsMnw3ohnqIzOa42KGmP3JiVk5rK
            w8JlJ4nVumnJ2aq/oV5oopXFXUDRKDSyYrkPbZGAQKmXhwRItulRMEapDjU3TQ4G
            sS/pcE3bJjxIokKsEJe9Kdth0qQrAdmmHxFwYJrW217NT30UT8o+WDDp4iPa7a3E
            3yQA4sBTxZV+ySQFBeGNj8H5ZTxNqP9QVB4wr6RJtwzWuLMB8McsRu5X/eiSSfdO
            KtS2EDbDgGV4nsQbS0bqxaGPUgcYC1/Pp+QNhJxvXzwJbJRa/qCvvWolAJ2axkjr
            YOLipxPg8TL3QzJyN5gy1L8gAzMpbq2WONBJPSEyPv90yZmeuTW5SsTWsAidMNxe
            5v2qMSjrmoUbXczM5p6EyxSmMgrcp/BzhoRxb2gu1xC/XmPp1i4dbM7ttWhWmR29
            asFGKw+BCCSUAR/e7J56tVc3GMfjh9Q/fP2eFMzgoF0OcY7uNFXe9i1te7HwcqYm
            bpY/DmhZT9vro8EI3kKy0l4B1zDrEt5BF7ggOIqK70g97Z4+kS9i/MfHNDcCqtyA
            sStwGQUofLMJ3LpHNhH6gedRTOceRymgorJpk6dRbcINcswNB1QgUKtVaL+K5Nd0
            62zDrzJQZ4fbMzsRoxqR
            =Bqpj
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
---
apiVersion: v1
data:
    password: ENC[AES256_GCM,data:XmCVtMmCAPUUjhq1geR6lTtdum8=,iv:yLLng/WP1DV1d/LheLEfwcSI+/U5/+FB4vrjljuVoRY=,tag:732udX5GKWpOvBsrQBJGSw==,type:str]
    username: ENC[AES256_GCM,data:7rfvUW1rbwk=,iv:gnd+4VFhhpcK14vHoUapbcpdmDFp1vPW69WjoH722Mo=,tag:qxgAVNmeUBWPhnm7MVswcw==,type:str]
kind: Secret
metadata:
    name: tranga-db-secret
    namespace: downloader
type: Opaque
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T11:06:53Z"
    mac: ENC[AES256_GCM,data:0c6HHh4bdQBMjz3xhmavFk72hhitw+DPQCOva6YGjCUN+bC8zHXg3cLQf2UQ4pDHq9Xiwb61BGVFKqI/cAX0fAsa99zrfdDpSFSPLZNuOaNiyVsdFCk/xTAljABYiB5/AIYf5nm6eCPTtWmVpUwf5R+dyyfvNUBbIehCDoHTmCM=,iv:5YoyOOYi7oEKaWsvTAteD+ER/vezJGSFESFgtAB+UnQ=,tag:gWMaPdLl3rCSXlO749QQ4g==,type:str]
    pgp:
        - created_at: "2026-06-04T11:06:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/cF+a8el8idrQsEPtNsMnw3ohnqIzOa42KGmP3JiVk5rK
            w8JlJ4nVumnJ2aq/oV5oopXFXUDRKDSyYrkPbZGAQKmXhwRItulRMEapDjU3TQ4G
            sS/pcE3bJjxIokKsEJe9Kdth0qQrAdmmHxFwYJrW217NT30UT8o+WDDp4iPa7a3E
            3yQA4sBTxZV+ySQFBeGNj8H5ZTxNqP9QVB4wr6RJtwzWuLMB8McsRu5X/eiSSfdO
            KtS2EDbDgGV4nsQbS0bqxaGPUgcYC1/Pp+QNhJxvXzwJbJRa/qCvvWolAJ2axkjr
            YOLipxPg8TL3QzJyN5gy1L8gAzMpbq2WONBJPSEyPv90yZmeuTW5SsTWsAidMNxe
            5v2qMSjrmoUbXczM5p6EyxSmMgrcp/BzhoRxb2gu1xC/XmPp1i4dbM7ttWhWmR29
            asFGKw+BCCSUAR/e7J56tVc3GMfjh9Q/fP2eFMzgoF0OcY7uNFXe9i1te7HwcqYm
            bpY/DmhZT9vro8EI3kKy0l4B1zDrEt5BF7ggOIqK70g97Z4+kS9i/MfHNDcCqtyA
            sStwGQUofLMJ3LpHNhH6gedRTOceRymgorJpk6dRbcINcswNB1QgUKtVaL+K5Nd0
            62zDrzJQZ4fbMzsRoxqR
            =Bqpj
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: garage-creds
    namespace: downloader
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:n/pqtx1ge2rz1XNXYdx++7g0jyTcr3+gZ9A=,iv:jvrzaPRD3PQ1m0NRsrNWcqIhGclYXGqpaBKbu5vKmL0=,tag:M+vrVA+JDQcwHXSHnTyo8Q==,type:str]
    secret-access-key: ENC[AES256_GCM,data:lye5ZjU3O2cYDwv1ReMfztLY1o9qoYzMbUUndsgztjsWeN9OARAtQ1cO6k6iXsXq3ONwp/61NqraTFWdTSD5xA==,iv:sGbCkLuvvkGxiquX0U7cAW2lanrW/D/EySzc+VTUVmI=,tag:Xmgrx4hpjQHDKO7kin36wQ==,type:str]
    region: ENC[AES256_GCM,data:DqTMbQ==,iv:8iceCivELq9z4z1w2ATfOMHMhBQpmGUecYi5X0b8Jlo=,tag:iw4MsLP3ZoRTc5Kx4GV8ZQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T11:06:53Z"
    mac: ENC[AES256_GCM,data:0c6HHh4bdQBMjz3xhmavFk72hhitw+DPQCOva6YGjCUN+bC8zHXg3cLQf2UQ4pDHq9Xiwb61BGVFKqI/cAX0fAsa99zrfdDpSFSPLZNuOaNiyVsdFCk/xTAljABYiB5/AIYf5nm6eCPTtWmVpUwf5R+dyyfvNUBbIehCDoHTmCM=,iv:5YoyOOYi7oEKaWsvTAteD+ER/vezJGSFESFgtAB+UnQ=,tag:gWMaPdLl3rCSXlO749QQ4g==,type:str]
    pgp:
        - created_at: "2026-06-04T11:06:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/cF+a8el8idrQsEPtNsMnw3ohnqIzOa42KGmP3JiVk5rK
            w8JlJ4nVumnJ2aq/oV5oopXFXUDRKDSyYrkPbZGAQKmXhwRItulRMEapDjU3TQ4G
            sS/pcE3bJjxIokKsEJe9Kdth0qQrAdmmHxFwYJrW217NT30UT8o+WDDp4iPa7a3E
            3yQA4sBTxZV+ySQFBeGNj8H5ZTxNqP9QVB4wr6RJtwzWuLMB8McsRu5X/eiSSfdO
            KtS2EDbDgGV4nsQbS0bqxaGPUgcYC1/Pp+QNhJxvXzwJbJRa/qCvvWolAJ2axkjr
            YOLipxPg8TL3QzJyN5gy1L8gAzMpbq2WONBJPSEyPv90yZmeuTW5SsTWsAidMNxe
            5v2qMSjrmoUbXczM5p6EyxSmMgrcp/BzhoRxb2gu1xC/XmPp1i4dbM7ttWhWmR29
            asFGKw+BCCSUAR/e7J56tVc3GMfjh9Q/fP2eFMzgoF0OcY7uNFXe9i1te7HwcqYm
            bpY/DmhZT9vro8EI3kKy0l4B1zDrEt5BF7ggOIqK70g97Z4+kS9i/MfHNDcCqtyA
            sStwGQUofLMJ3LpHNhH6gedRTOceRymgorJpk6dRbcINcswNB1QgUKtVaL+K5Nd0
            62zDrzJQZ4fbMzsRoxqR
            =Bqpj
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-secret
    namespace: downloader
type: Opaque
stringData:
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:lwl/rnn+BPQeDLtl,iv:gAIQ3VP/EXOos31W76wtR5ixLu3DuBicQRhrES4axyQ=,tag:QEnlZu+rfcVOCYlTVyVZoA==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:SD1K9LM=,iv:b5DSciuicdLk5QdDU7HIbdt1DOTB6GZDOPgpIH0IZns=,tag:ItMbwP7Gx++puZuoW2FzzQ==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:B/Lc8/xyDSCA0orPPgvKwdNWsu/oMRY63KKrpFG5l6Yq3+kIjjpOQlqVZHY=,iv:5mXdNZkboqCoz1l5jT5xP2PkFsHMExJ0wxFDYVX66Ic=,tag:Hrx0hKycqAkpI+VEPDFbbA==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:Lkf5Dr629F9P7Xcd3eyobMx6dsvLaTHF80EW6HKV0lVsNIafpqNf2RSXkG0=,iv:kN/3E67qVRVYKb22Ge7xp/FD4DUOdp83JEn49A5wALw=,tag:n0lxolxT1rgJ94Z/SawrqQ==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:TQ4NV6NIfket1GU=,iv:1/gz/OymX2NojR1ncoe5EIkfEuUC0WxapnukoH+9Lnc=,tag:wQEW+XZIry5csT6ZFA8a3A==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T11:06:53Z"
    mac: ENC[AES256_GCM,data:0c6HHh4bdQBMjz3xhmavFk72hhitw+DPQCOva6YGjCUN+bC8zHXg3cLQf2UQ4pDHq9Xiwb61BGVFKqI/cAX0fAsa99zrfdDpSFSPLZNuOaNiyVsdFCk/xTAljABYiB5/AIYf5nm6eCPTtWmVpUwf5R+dyyfvNUBbIehCDoHTmCM=,iv:5YoyOOYi7oEKaWsvTAteD+ER/vezJGSFESFgtAB+UnQ=,tag:gWMaPdLl3rCSXlO749QQ4g==,type:str]
    pgp:
        - created_at: "2026-06-04T11:06:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/cF+a8el8idrQsEPtNsMnw3ohnqIzOa42KGmP3JiVk5rK
            w8JlJ4nVumnJ2aq/oV5oopXFXUDRKDSyYrkPbZGAQKmXhwRItulRMEapDjU3TQ4G
            sS/pcE3bJjxIokKsEJe9Kdth0qQrAdmmHxFwYJrW217NT30UT8o+WDDp4iPa7a3E
            3yQA4sBTxZV+ySQFBeGNj8H5ZTxNqP9QVB4wr6RJtwzWuLMB8McsRu5X/eiSSfdO
            KtS2EDbDgGV4nsQbS0bqxaGPUgcYC1/Pp+QNhJxvXzwJbJRa/qCvvWolAJ2axkjr
            YOLipxPg8TL3QzJyN5gy1L8gAzMpbq2WONBJPSEyPv90yZmeuTW5SsTWsAidMNxe
            5v2qMSjrmoUbXczM5p6EyxSmMgrcp/BzhoRxb2gu1xC/XmPp1i4dbM7ttWhWmR29
            asFGKw+BCCSUAR/e7J56tVc3GMfjh9Q/fP2eFMzgoF0OcY7uNFXe9i1te7HwcqYm
            bpY/DmhZT9vro8EI3kKy0l4B1zDrEt5BF7ggOIqK70g97Z4+kS9i/MfHNDcCqtyA
            sStwGQUofLMJ3LpHNhH6gedRTOceRymgorJpk6dRbcINcswNB1QgUKtVaL+K5Nd0
            62zDrzJQZ4fbMzsRoxqR
            =Bqpj
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: sabnzb-secret
    namespace: downloader
type: Opaque
stringData:
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:gL0SjygmKpdEAhiOiQ==,iv:A+EbmxtF2Zg19IgS5WNeuvl4XILvbN/rf20w0er9T74=,tag:3S0LSP4vsRt8J2GR6iJMSA==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:+L2CUfY=,iv:jgju5bb43TxNO4JWnsXMFt4tW3X4RuTRXn0HFguhM+s=,tag:nOxfMytXlB4QawsEUBE/Jw==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:cr8C8ZmATJAkzEeUzF9jHfqUHp1l+6L3NZoDHc82HLkT4UtM3Tog8bVLOko=,iv:q6l5jxsxiblOorQ45e+72dvqp2yjd34fstnPq2T8jVI=,tag:84vihApNvFJOtyiUsspQ1Q==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:UePooIKkgiD05B7KQxRsUnKeAz7AQVyzoikO65+najZe66+FZkYWY3N4JWM=,iv:QVsPdP76iygB0MjAEDPfGhRXzvodvt5ze5cjH/tBlww=,tag:+lmkZZiDR+hUSEAtGh6opg==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:vu3fX2U52QrUT0E=,iv:19oexlU2XQxXcG8nkotRuwGB/hoAkPT0hATXoY5UeZE=,tag:pWCCTQB82cK9zNT+IbT2Eg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T11:06:53Z"
    mac: ENC[AES256_GCM,data:0c6HHh4bdQBMjz3xhmavFk72hhitw+DPQCOva6YGjCUN+bC8zHXg3cLQf2UQ4pDHq9Xiwb61BGVFKqI/cAX0fAsa99zrfdDpSFSPLZNuOaNiyVsdFCk/xTAljABYiB5/AIYf5nm6eCPTtWmVpUwf5R+dyyfvNUBbIehCDoHTmCM=,iv:5YoyOOYi7oEKaWsvTAteD+ER/vezJGSFESFgtAB+UnQ=,tag:gWMaPdLl3rCSXlO749QQ4g==,type:str]
    pgp:
        - created_at: "2026-06-04T11:06:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/cF+a8el8idrQsEPtNsMnw3ohnqIzOa42KGmP3JiVk5rK
            w8JlJ4nVumnJ2aq/oV5oopXFXUDRKDSyYrkPbZGAQKmXhwRItulRMEapDjU3TQ4G
            sS/pcE3bJjxIokKsEJe9Kdth0qQrAdmmHxFwYJrW217NT30UT8o+WDDp4iPa7a3E
            3yQA4sBTxZV+ySQFBeGNj8H5ZTxNqP9QVB4wr6RJtwzWuLMB8McsRu5X/eiSSfdO
            KtS2EDbDgGV4nsQbS0bqxaGPUgcYC1/Pp+QNhJxvXzwJbJRa/qCvvWolAJ2axkjr
            YOLipxPg8TL3QzJyN5gy1L8gAzMpbq2WONBJPSEyPv90yZmeuTW5SsTWsAidMNxe
            5v2qMSjrmoUbXczM5p6EyxSmMgrcp/BzhoRxb2gu1xC/XmPp1i4dbM7ttWhWmR29
            asFGKw+BCCSUAR/e7J56tVc3GMfjh9Q/fP2eFMzgoF0OcY7uNFXe9i1te7HwcqYm
            bpY/DmhZT9vro8EI3kKy0l4B1zDrEt5BF7ggOIqK70g97Z4+kS9i/MfHNDcCqtyA
            sStwGQUofLMJ3LpHNhH6gedRTOceRymgorJpk6dRbcINcswNB1QgUKtVaL+K5Nd0
            62zDrzJQZ4fbMzsRoxqR
            =Bqpj
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-config-sabnzbd
    namespace: downloader
type: Opaque
stringData:
    #ENC[AES256_GCM,data:nXpUoBxhkb+Qq1UfRC9tbLRRrUm2865U/fIHMG/nf5QQDJVtz+B8oFmBU7BpFTzrgh2tNaAb0aIDu941+hgdTFo=,iv:YWwkNuYTFWRqF+ZQXHz7/+asVhsRuc4y1JrsWbHMo10=,tag:tcNeOfw438h0jTClmQg0zw==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:40YD9SVOj7YjgP3A7H/oEQEl8J88wPeCM40ZIrNr+IzJMiXt11fQ6XtcaArBpck=,iv:Ru6EirZOekHjQAMV3lF6mFnQQc7Xy9kB9VT+htMJPdo=,tag:umVMB4NI6N7qDrWOZx1S4g==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:OU0YcGj4fBixAHDjqFk7YSAEDnBD8wofIAn5KI5EpvtHvxK5jO4jqWWzg0mhyATj,iv:4/2nTdyrRWJcbOFI6zFEepkGmahoQDvg0OZgORYiavw=,tag:qZiz1ZgWLBcSSD5wsFjOxQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:3R+MiDcUfkXrEZ2bDiKpAryH5LJJiCW1O44=,iv:v0slfzu58Nzk3lna5crkVaO6itcN71Rtph8PBpSdgds=,tag:A2fNCj1FSxzeEJXx5k5zgA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:fyhaweYYNxTLInBMmBD4kXTlEs5xEUbVacvhxMkIZKhIfaDlKyzvA/moyOEBC2s0Al15IhMfpQSkDlETgn7LFw==,iv:TeAOqvgibRqqEIxb20zkN0bO6ULQoQ70ZEs/ZCW4fng=,tag:WohMATMowC/wIuTSCbvUtQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T11:06:53Z"
    mac: ENC[AES256_GCM,data:0c6HHh4bdQBMjz3xhmavFk72hhitw+DPQCOva6YGjCUN+bC8zHXg3cLQf2UQ4pDHq9Xiwb61BGVFKqI/cAX0fAsa99zrfdDpSFSPLZNuOaNiyVsdFCk/xTAljABYiB5/AIYf5nm6eCPTtWmVpUwf5R+dyyfvNUBbIehCDoHTmCM=,iv:5YoyOOYi7oEKaWsvTAteD+ER/vezJGSFESFgtAB+UnQ=,tag:gWMaPdLl3rCSXlO749QQ4g==,type:str]
    pgp:
        - created_at: "2026-06-04T11:06:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/cF+a8el8idrQsEPtNsMnw3ohnqIzOa42KGmP3JiVk5rK
            w8JlJ4nVumnJ2aq/oV5oopXFXUDRKDSyYrkPbZGAQKmXhwRItulRMEapDjU3TQ4G
            sS/pcE3bJjxIokKsEJe9Kdth0qQrAdmmHxFwYJrW217NT30UT8o+WDDp4iPa7a3E
            3yQA4sBTxZV+ySQFBeGNj8H5ZTxNqP9QVB4wr6RJtwzWuLMB8McsRu5X/eiSSfdO
            KtS2EDbDgGV4nsQbS0bqxaGPUgcYC1/Pp+QNhJxvXzwJbJRa/qCvvWolAJ2axkjr
            YOLipxPg8TL3QzJyN5gy1L8gAzMpbq2WONBJPSEyPv90yZmeuTW5SsTWsAidMNxe
            5v2qMSjrmoUbXczM5p6EyxSmMgrcp/BzhoRxb2gu1xC/XmPp1i4dbM7ttWhWmR29
            asFGKw+BCCSUAR/e7J56tVc3GMfjh9Q/fP2eFMzgoF0OcY7uNFXe9i1te7HwcqYm
            bpY/DmhZT9vro8EI3kKy0l4B1zDrEt5BF7ggOIqK70g97Z4+kS9i/MfHNDcCqtyA
            sStwGQUofLMJ3LpHNhH6gedRTOceRymgorJpk6dRbcINcswNB1QgUKtVaL+K5Nd0
            62zDrzJQZ4fbMzsRoxqR
            =Bqpj
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
