apiVersion: v1
kind: Secret
metadata:
    name: woodpecker-server-env
    namespace: woodpecker
type: Opaque
stringData:
    WOODPECKER_FORGEJO_CLIENT: ENC[AES256_GCM,data:o66RWq0+gwHrdB8UgEFFmL7NeusxugMqAm/jJgR3B3IGvpwS,iv:hzj60tJi3lxyQRcrqX0tFQJU9feuDxH+duGSDhNoss0=,tag:z+MWD2AigMufV3FbnhWMNw==,type:str]
    WOODPECKER_FORGEJO_SECRET: ENC[AES256_GCM,data:yDAypWekTTukx8WOYIB4ehWjjTzdC4GG1WKqD1ZpTjX+XJ6nANzZ6POHCdCvJMF5Y2V2MjPHPc0=,iv:uq89Zfj8ThaIpaJ1Va81VfPIv39Dk4xdDLVO7Kuryyo=,tag:oUQQ8YkAVuRLrMmmrad06A==,type:str]
sops:
    lastmodified: "2026-03-29T12:40:49Z"
    mac: ENC[AES256_GCM,data:6bL9xswLJDN2u9PM5mHBOeUFMouM/ppvS3gO91WCBsUb5ig9lSrpRQS+qJhzW3P/tr+tpCHKSzw7arGJv4kf3KjKEdtubOCifW/lhh7BzHsN++Mb8swIiyV6j9jAsY9/OnlP2R8/Pk9mlRvUk6YyA6yitPLMEvLw8OuqZZ9ZrFY=,iv:CVpsEaN7v/NowwfQp/aDAQXP3tmQJWL/z5rntKqr8uo=,tag:EqPL4VRJccO0SJ4nX7medw==,type:str]
    pgp:
        - created_at: "2026-03-29T12:40:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/Sace+zrTDGDyHIVSpNU8WYbwdiOAhRaRb/v4C4DzG9KK
            B1YMCP+SUKQvBdQMGll8Dal+S7yeYw8yw4C3mw7WHemotuE9mtAbgnVBriiT/rUa
            6uUGM6J50OMO8MCpVaGcj4/prZEOur+Dvb/c+nm9+/Y10l2Ls5w5SVmhxJ5HkJS2
            3EV+KMJeSE+wqDmQQ9M96P0mCdUa9Ova8FLN4cCuHfhMjwU6fcZeumykwYFHTK67
            ELelG2Is8lfLCt4WIaFdVuenQ8/1sE50wDdt0iOO2tx49LDfx6xYGhMiB8i6cBqz
            3KTxa/5/bLrDn+76Bp3DN+Yrj2ksWz3nVrswCcyvsVZPSl+yPIqVKxrTh8CF35Bk
            kn9LOrc6A/QP7XTh7494mFzJCwvSoNz6IGPwLut+pGQcn2+PbCQi78BhsDYjmRFC
            W9Ag7+j28yfYgxH1NqRpctfyTEdiZbxwf+3b9XNUKz6+hue11PjE8d52Rx9dS0n9
            kDj5IeKGyqlQqzn/AsyT0l4BFM+D6waOn1jWgqHU0CEwy/2HEiMTZiF5u4D3v43n
            67XsAKSmzT7fToqsO40gl1+BtM/12dAFUt4KzEr9Uzr1jAx/fR8HEw2BlZYBTeZ8
            Ly7XAUJPXXjUq1NnFFCN
            =gQqz
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-config-woodpecker
    namespace: woodpecker
type: Opaque
stringData:
    #ENC[AES256_GCM,data:Gv9dII2smah167F5I7N3zk7PNnc6nHpsJkMM3ZZCeOPPjkUGugZW30z0Pfb8k/g2Yz0Bgne5+RE4uzTqGNTeihg=,iv:VKoEyK9+V7Itz3U2KeFIK31058MvHH10MZraJUIM8Sw=,tag:PiUp+zOBUsD1beQBuOfoeQ==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:KzANDIxClYdc+RsRrN2nwNwaS+i8i9BRk8tjimPEYgL5upKFR+0MgjbvErUjHW6vwf4=,iv:+BiEHmthmiwDFW0bKmvMDaG9OQCZi2e3coCe5cIdNw8=,tag:3AW6eSJzsUsT4YIPTdqsYw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:6EEBr9e99YbeHawo7mTgQ3+xSGzeTxvhCKzG9sADG5vaOZ7zOqmRv9iFd44gyb8+,iv:ywu3e5BZg9dSMHqhMuFqPEiK0GsPciorIBg4gbyfTLM=,tag:+XYS+ZnEoXRvmYCa5LSB9g==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:tjP4d5IbDFS1s8dcqfl4pzJPK2C9m05UMQ0=,iv:xdZs58lRhQSwJqr9yc/wahHmBw+qBwPeIVCP9NUTF4A=,tag:yQzePaBTYw2na1BrvEDMhA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:SCMQJKVhJYSZIZVZVyNB14VyvCRc1Btf00obgUTi90n2dh9aofSlvT6ASQZwZH0dprn+05Lm2VjPDybIq1jzow==,iv:UtzHK0fA8NbLzw+xqeb1WQlq4Gc7qYbA6pIm5iBVBgg=,tag:nXWOTdkAtwJtPltJaR351A==,type:str]
sops:
    lastmodified: "2026-03-29T12:40:49Z"
    mac: ENC[AES256_GCM,data:6bL9xswLJDN2u9PM5mHBOeUFMouM/ppvS3gO91WCBsUb5ig9lSrpRQS+qJhzW3P/tr+tpCHKSzw7arGJv4kf3KjKEdtubOCifW/lhh7BzHsN++Mb8swIiyV6j9jAsY9/OnlP2R8/Pk9mlRvUk6YyA6yitPLMEvLw8OuqZZ9ZrFY=,iv:CVpsEaN7v/NowwfQp/aDAQXP3tmQJWL/z5rntKqr8uo=,tag:EqPL4VRJccO0SJ4nX7medw==,type:str]
    pgp:
        - created_at: "2026-03-29T12:40:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/Sace+zrTDGDyHIVSpNU8WYbwdiOAhRaRb/v4C4DzG9KK
            B1YMCP+SUKQvBdQMGll8Dal+S7yeYw8yw4C3mw7WHemotuE9mtAbgnVBriiT/rUa
            6uUGM6J50OMO8MCpVaGcj4/prZEOur+Dvb/c+nm9+/Y10l2Ls5w5SVmhxJ5HkJS2
            3EV+KMJeSE+wqDmQQ9M96P0mCdUa9Ova8FLN4cCuHfhMjwU6fcZeumykwYFHTK67
            ELelG2Is8lfLCt4WIaFdVuenQ8/1sE50wDdt0iOO2tx49LDfx6xYGhMiB8i6cBqz
            3KTxa/5/bLrDn+76Bp3DN+Yrj2ksWz3nVrswCcyvsVZPSl+yPIqVKxrTh8CF35Bk
            kn9LOrc6A/QP7XTh7494mFzJCwvSoNz6IGPwLut+pGQcn2+PbCQi78BhsDYjmRFC
            W9Ag7+j28yfYgxH1NqRpctfyTEdiZbxwf+3b9XNUKz6+hue11PjE8d52Rx9dS0n9
            kDj5IeKGyqlQqzn/AsyT0l4BFM+D6waOn1jWgqHU0CEwy/2HEiMTZiF5u4D3v43n
            67XsAKSmzT7fToqsO40gl1+BtM/12dAFUt4KzEr9Uzr1jAx/fR8HEw2BlZYBTeZ8
            Ly7XAUJPXXjUq1NnFFCN
            =gQqz
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
