apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: scanopy
  namespace: scanopy
spec:
  interval: 10m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true 
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: "5.2.1"
  values:
    controllers:
      scanopy:
        strategy: Recreate
        containers:
          scanopy:
            image:
              repository: ghcr.io/scanopy/scanopy/server
              tag: "v0.17.20@sha256:3216ab8fc97d19dd06e87c83ec9b16e1263e6f85f5f116227e7dbae808d1f701"
            env:
              SCANOPY_WEB_EXTERNAL_PATH: /app/static
              SCANOPY_PUBLIC_URL: https://scanopy.k8s.exmaple.com
            envFrom:
              - secretRef:
                  name: scanopy-env
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 250m
                memory: 256Mi

    service:
      scanopy:
        controller: scanopy
        ports:
          http:
            port: 60072


    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: scanopy-data
        globalMounts:
          - path: /app/data

    ingress:
      scanopy:
        className: "cilium"
        hosts:
          - host: "scanopy.k8s.exmaple.com"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: scanopy
                  port: http
        tls:
          - hosts:
              - "scanopy.k8s.exmaple.com"   

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scanopy-data
  namespace: scanopy
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-rbd-sc
  resources:
    requests:
      storage: 5Gi     