apiVersion: v1
kind: Secret
metadata:
    name: scanopy-db-secret
    namespace: scanopy
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:N/G2XdQWDQ==,iv:8U2l59L+ZKx2yRlMcduEN0TZOtCuxlSAC7HM3JrBnL4=,tag:ltZVK3IH1Gs0nphoEeuLjg==,type:str]
    password: ENC[AES256_GCM,data:swQZSoHznzio5qu5nbiOiVwg,iv:St7PmpH+vTEplcbZOoXQgzjUZUgtoexBGB7M2/k43dk=,tag:pJiBHU0TN18gVOJ3QeTwTg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T11:20:05Z"
    mac: ENC[AES256_GCM,data:y/EmowMy+XJlsc7mvroAhwztkSm23p4L8/eQK1vIa7yd9TrqR6uCx6CYYU/ekemB567EiHJjBdrmztrQdh8CJyXTBRpgE73+aa739dzqHjFp64ml+o2qNIRMKIMmIo9ipzIrrM0/ZwgxH5+/1+eioNWlAoXP9dwPUk1nFvTXlZc=,iv:F+5ZpmqyL5a7q/wXXRyYzSuP0Cku8PN3TfWewoQBqfU=,tag:HJEFqY+cPQzsVIphpzMdow==,type:str]
    pgp:
        - created_at: "2026-06-13T11:20:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/ZaBrK4re9rSz+muuaGqImo/+3gkfQf0xHYbgava+VJHq
            lxIRv3InpkAmPe+IpPF4vcoxwEoIvD2Cyz5P1b4+nqw1jxdhQuooC7XiVBWQ40cV
            Wt4lWUQfdEhgbVGVmvMIGXb/sI+UGtwLc6Rvj41InS2oCjTDuwD2U59I1S+d7jfO
            m9k3Vs65S5mRf6C346Xuv4TGxTw5ddl4RK9C/u0YLWXaC1w7swK2nv6AIJ1eHHAl
            3bjEpM/8ooPyB4r/Oc9RodKM2hJ9LXMMiI4SfbdVDEzcIaSdhFERJTy3ZkBmdfch
            9jWV+z+8C4unhaWzTMxcvdMUZ0R5+sxJaiTMOGAkK+ZukB7XFq29lNicMaVfW7te
            /gGyL5i35EB5+tJjJ++p9EEBjZmwFuhGmYdThMZ38dxWdeCyf38JGIpJAmLCjrna
            ziygE3g+7cFsIGbp1MZkBSq+3yXsdcTlQ96Ng0rTQ97arM+tFWDafXonxkBybYfs
            H2ubRBG+Z3KLgAKtpiYv0l4B8cQoUAV3IKngHwYJSAlY61YGaSZZcjAqsHlVHz+6
            XtA6t/1HzlDXA+C7VPdX7IpXXwd9uM2rkShgzrmrlcY5L1ZoUzhVSf3tu0WCE6tj
            19prpJR2xyA8cs/uJuPk
            =FWnO
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: garage-creds
    namespace: scanopy
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:Fb/p3A5uAunzlguoyL2jsvaTLC/CQT1/51s=,iv:DwExbqNHZX2kASgyihp83UDjtgVaSmGqkvMy89kQuOE=,tag:0i1r0YnbM9nhOYOVS8XHKg==,type:str]
    secret-access-key: ENC[AES256_GCM,data:MC6J9XdLVLEa+QVnVepZ8nNMcoQDWH3LMLs4/C7EgEtdBpym5A3BMD4tJeEvfs30/xYJvv9M9CmVQjyZ7II76g==,iv:vOSk0HPXhNDeuos56PjoLyTe3cdYNK8dr2qcqF5NflQ=,tag:MYAn3gDh5csaX6PhJxgksA==,type:str]
    region: ENC[AES256_GCM,data:8wSf6A==,iv:zETJBLGA6qHzjDH/fFAKP5eV38i8qngOb9OFJ4ZQx3I=,tag:2m8euJLCVRnd4XZOYTTwlw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T11:20:05Z"
    mac: ENC[AES256_GCM,data:y/EmowMy+XJlsc7mvroAhwztkSm23p4L8/eQK1vIa7yd9TrqR6uCx6CYYU/ekemB567EiHJjBdrmztrQdh8CJyXTBRpgE73+aa739dzqHjFp64ml+o2qNIRMKIMmIo9ipzIrrM0/ZwgxH5+/1+eioNWlAoXP9dwPUk1nFvTXlZc=,iv:F+5ZpmqyL5a7q/wXXRyYzSuP0Cku8PN3TfWewoQBqfU=,tag:HJEFqY+cPQzsVIphpzMdow==,type:str]
    pgp:
        - created_at: "2026-06-13T11:20:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/ZaBrK4re9rSz+muuaGqImo/+3gkfQf0xHYbgava+VJHq
            lxIRv3InpkAmPe+IpPF4vcoxwEoIvD2Cyz5P1b4+nqw1jxdhQuooC7XiVBWQ40cV
            Wt4lWUQfdEhgbVGVmvMIGXb/sI+UGtwLc6Rvj41InS2oCjTDuwD2U59I1S+d7jfO
            m9k3Vs65S5mRf6C346Xuv4TGxTw5ddl4RK9C/u0YLWXaC1w7swK2nv6AIJ1eHHAl
            3bjEpM/8ooPyB4r/Oc9RodKM2hJ9LXMMiI4SfbdVDEzcIaSdhFERJTy3ZkBmdfch
            9jWV+z+8C4unhaWzTMxcvdMUZ0R5+sxJaiTMOGAkK+ZukB7XFq29lNicMaVfW7te
            /gGyL5i35EB5+tJjJ++p9EEBjZmwFuhGmYdThMZ38dxWdeCyf38JGIpJAmLCjrna
            ziygE3g+7cFsIGbp1MZkBSq+3yXsdcTlQ96Ng0rTQ97arM+tFWDafXonxkBybYfs
            H2ubRBG+Z3KLgAKtpiYv0l4B8cQoUAV3IKngHwYJSAlY61YGaSZZcjAqsHlVHz+6
            XtA6t/1HzlDXA+C7VPdX7IpXXwd9uM2rkShgzrmrlcY5L1ZoUzhVSf3tu0WCE6tj
            19prpJR2xyA8cs/uJuPk
            =FWnO
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: scanopy-env
    namespace: scanopy
type: Opaque
stringData:
    SCANOPY_DATABASE_URL: ENC[AES256_GCM,data:/OCxYY9jHMbJ8tCXyCKfe29UWcv1hO/aQmCMSGQzXtmoMwMybM/3CnFxsuDU3S9eqA2d6hzaMf3b1dKUgmqx9MU0,iv:WwEsMsfEeqU7LQEihERb78YdcL648cLju5uotU+AFNo=,tag:5TRNMJmfA4sh0YK0ALlQqw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T11:20:05Z"
    mac: ENC[AES256_GCM,data:y/EmowMy+XJlsc7mvroAhwztkSm23p4L8/eQK1vIa7yd9TrqR6uCx6CYYU/ekemB567EiHJjBdrmztrQdh8CJyXTBRpgE73+aa739dzqHjFp64ml+o2qNIRMKIMmIo9ipzIrrM0/ZwgxH5+/1+eioNWlAoXP9dwPUk1nFvTXlZc=,iv:F+5ZpmqyL5a7q/wXXRyYzSuP0Cku8PN3TfWewoQBqfU=,tag:HJEFqY+cPQzsVIphpzMdow==,type:str]
    pgp:
        - created_at: "2026-06-13T11:20:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/ZaBrK4re9rSz+muuaGqImo/+3gkfQf0xHYbgava+VJHq
            lxIRv3InpkAmPe+IpPF4vcoxwEoIvD2Cyz5P1b4+nqw1jxdhQuooC7XiVBWQ40cV
            Wt4lWUQfdEhgbVGVmvMIGXb/sI+UGtwLc6Rvj41InS2oCjTDuwD2U59I1S+d7jfO
            m9k3Vs65S5mRf6C346Xuv4TGxTw5ddl4RK9C/u0YLWXaC1w7swK2nv6AIJ1eHHAl
            3bjEpM/8ooPyB4r/Oc9RodKM2hJ9LXMMiI4SfbdVDEzcIaSdhFERJTy3ZkBmdfch
            9jWV+z+8C4unhaWzTMxcvdMUZ0R5+sxJaiTMOGAkK+ZukB7XFq29lNicMaVfW7te
            /gGyL5i35EB5+tJjJ++p9EEBjZmwFuhGmYdThMZ38dxWdeCyf38JGIpJAmLCjrna
            ziygE3g+7cFsIGbp1MZkBSq+3yXsdcTlQ96Ng0rTQ97arM+tFWDafXonxkBybYfs
            H2ubRBG+Z3KLgAKtpiYv0l4B8cQoUAV3IKngHwYJSAlY61YGaSZZcjAqsHlVHz+6
            XtA6t/1HzlDXA+C7VPdX7IpXXwd9uM2rkShgzrmrlcY5L1ZoUzhVSf3tu0WCE6tj
            19prpJR2xyA8cs/uJuPk
            =FWnO
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
