apiVersion: v1
kind: Secret
metadata:
    name: excalidash-env
    namespace: excalidash
type: Opaque
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:Zte7ymAXl/CzivEWw73Lo9Zl5V2OSW6AKI3FtROXW2236JxY3bgwrw==,iv:15XlsYyT8AMzSiofFLN4iWWmr4uA+b9UjGS88s5gmGk=,tag:6AN6QCEEWQpzWHKNqj/A/g==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:rPb4meHNmOnCjtql7WzaYNyqn1AkFlCMG0sTVuodfMGtqnF4BqDvHe6rqP6df4bCanUueWEn/Z0hJnNhUP+9Jqpt6OTAVIQcW2OTX1ioq/eOwuVQ4zr7YlWsdiMwhcPnlOoURm8rn5+N5a1L+M6JSp4fUGUr50WECWYaiKzrjnE=,iv:jm9D9N9/Jv5OufG5vVGP2MA8xPwJT5xuz0RX5vbrGyg=,tag:l32vNnW3izWCcOi0NvGvcw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:AbH+Bzbr00qzEZXp4XX5+EpadJGr/ILoaV+vLfCoKKc=,iv:yygyDNGmLNvxCMbRKH/brEKq+/K2+uW8mJY4kWT3dK8=,tag:K0ySg7gFKqFgoo79NnihCw==,type:str]
sops:
    lastmodified: "2026-03-23T18:08:17Z"
    mac: ENC[AES256_GCM,data:6p4IPyXkz528zw3BQftKuT+uInlurdkuzVNfqgkCaSF9OD4Y28navEn9biw4wPBdj+SYP/hKlwm4Ty3iw7Qdk0pbm7FvoE5I4gLUnPxw372S1SwCTEuW4di7VvXMVB4TUAJtBLYKFxmelQ9GhJcdSjLWc6BNfF7KPM0uu9HwG88=,iv:eMiXZOHeDfNsfguULZ8GKI6yIpQwEsStcE5PfgJUS8A=,tag:tVy8gTr4x2pnDj99NKY3/Q==,type:str]
    pgp:
        - created_at: "2026-03-23T18:08:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQwAqhVI8Fji500xWMH/dvQTXvW8dlfA9gdK4dMNWKIExvPk
            KIPwfRVAcMgjxM2DW749quzYCmoTITV6xBTd46TLVNEeofbX3sL48lKgFxP+7CsE
            ZUYjL8hH9dT50g0KVzoDQ314YbU+rQDvnId5qTVE1/3JtSp/gt6JGZzDAZwZ1dH7
            ldJb60BfBLULmi/CAQj7CPIhbeOcJ4AaCuN8SiExIMGqYq/xMOX1gtP59VhADvvq
            iU4G0G9NK5FudY4Xbk+QhbhQzxEaCJaHTe+3G6kXeYBtJk42/pMcXtrmc6kl4Ja4
            TArgnbTe6QEeVMGsftcUPHDukDwygUDwcy9xJA4zRbJ/6WWYDjnNpPnuQ4BgV8m9
            IiCeOi9MbXyJ5tZTqVuWRgsZ3vMjiuw2vRO6l8JWkZs3dThn31iJGRSLdgzKpDYL
            jI1ZWsjhjm6JMVjerTuj1Gw2ReAGese9jzBywCK9II2lpDXxOAkcl9rkjcGpvJEC
            ZCZQ+wpyaRS5UtTY8NDL0lwBzCC0yzYK+nuP9Yko3sREHFavcvmcy6u76Y9viOGp
            RPnYbQcve2Q0Tybzb/gpmSKU1r8rrJRtv+FJ701bSTveogZFtoQnkPuV7/R7kRWN
            QzPMaD+cqkzWa5xHGA==
            =C6Ar
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
