apiVersion: v1
kind: Secret
metadata:
    name: vymanager-db-secret
    namespace: vymanager
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:6aw7d+AO2rn/,iv:99Dj+GJTs6HhYg60p/6i9EUx1jqtwwvkWRTB1iufU4w=,tag:7PaxDh7v/yxKD/wkWJO6ww==,type:str]
    password: ENC[AES256_GCM,data:T0rPOZT5a7TTpDv9p1/a9w==,iv:yUkE+vtgxvajdZzMBtBWuXmoGFVcfimrwLLCS/vEbO4=,tag:c+qg4OpylbAYwVj6/pM6vg==,type:str]
sops:
    lastmodified: "2026-04-11T15:23:23Z"
    mac: ENC[AES256_GCM,data:UdEX5vPu33V0/7rX+7JeNdUZV1Hv4Et+X7KwewUdH1VPKy/rkjm5P2x6QIFgBD9kTghY4CvTfTBmZvCTayb3SVtGj6rqVVUGKpKM6+sANyGSneZZP4rcL+mSHmFbk+DgsuuScv+/mGvAvAZnlyy3qeW5qyTO3b6uAAS8esQfil4=,iv:AFhygS7lQxxT+GzTsiaaSsV6UwOdFWCNFeHtSeHs5oI=,tag:OjxQtgib8oxxSljH+fYS6Q==,type:str]
    pgp:
        - created_at: "2026-04-11T15:23:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQwAj0DE7su+jv5ocZSwzgjZLvPAxEcNlrZrWnjF2Y+FH11R
            YuGHIAdR0GzIBNVszHx8Kbecs81BPb18QA/CNB/b68cmC+r9dkqtcWKewwblRPXf
            cOdCWn9uJ5XfugR3085DbRKvHLoS8dpSTfRyZELgC40QTKammnDUs4uNFJDL7sE6
            K9KgXpYvj2No1bxZhptayhqhXEMFP2qr5U5zzJJV4iNO9KK/J9LCyhKwq9qs3QWi
            BxtHWilQhDwyKTYjBkxSW58GT5E31YWfBPEAcesoPucjEaSJxbEj+TZvSZd4thkX
            9IcqFMuVgFCyOy8aMN4Eg7lmIiygiU7GPJezFvDqEU1wnLia3teD8LIyge9G0CUu
            5/VWNSfQwI8ekEbVaAffBu5X/Iy6mEXVk9C7vOBAs4LH2sE+DFiPiHuUZMASIpa2
            6hfnJAjLkxLgTF2H4ehWValI6RYpgIaBY9S1KEJOg4uX+okCwy9qcjBgnbxMNjd1
            C8bkDKOL5ILCCZUPODYA0l4BGvvBU1QGgrwiX/jkHidey85IVWl8YO4O2SsK87jt
            MHI504712NXrocWBK0GEQMfvefsEEYnNKYaJw/POsifu64qWNAWOICBQ6Q6dF2ct
            AzV9c2YuThsK2aG6FGX8
            =4CVr
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: garage-creds
    namespace: vymanager
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:SaLb0jj4At1IFLD/eHuehNLtJPYRLjwdzlI=,iv:SjYEQP46zlpS4qcoGKN6MdC42BD/V5ELKM9a7UIPgRI=,tag:A3dcsgD50A8ZDpSzBFT4Bw==,type:str]
    secret-access-key: ENC[AES256_GCM,data:qfiUG37bku5YMG+zRpEdBcDfy+FN/684KsCs3f4EThZssWX15sqwMmEdU86mzLgH5+AUI70fPgnA6LecfoxvhQ==,iv:feMGNW9rv++OETrKdcnCjeWql/uNbqHN1bJU4YANDZQ=,tag:L+fSunugbUHAHBFUSdmfBg==,type:str]
    region: ENC[AES256_GCM,data:iM8eRQ==,iv:w6ule0xgaGZArmxWVGez2LtylGgQeUAkBNLlXBrvt24=,tag:14QZNRRBJpVlCIiJbQSvcA==,type:str]
sops:
    lastmodified: "2026-04-11T15:23:23Z"
    mac: ENC[AES256_GCM,data:UdEX5vPu33V0/7rX+7JeNdUZV1Hv4Et+X7KwewUdH1VPKy/rkjm5P2x6QIFgBD9kTghY4CvTfTBmZvCTayb3SVtGj6rqVVUGKpKM6+sANyGSneZZP4rcL+mSHmFbk+DgsuuScv+/mGvAvAZnlyy3qeW5qyTO3b6uAAS8esQfil4=,iv:AFhygS7lQxxT+GzTsiaaSsV6UwOdFWCNFeHtSeHs5oI=,tag:OjxQtgib8oxxSljH+fYS6Q==,type:str]
    pgp:
        - created_at: "2026-04-11T15:23:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQwAj0DE7su+jv5ocZSwzgjZLvPAxEcNlrZrWnjF2Y+FH11R
            YuGHIAdR0GzIBNVszHx8Kbecs81BPb18QA/CNB/b68cmC+r9dkqtcWKewwblRPXf
            cOdCWn9uJ5XfugR3085DbRKvHLoS8dpSTfRyZELgC40QTKammnDUs4uNFJDL7sE6
            K9KgXpYvj2No1bxZhptayhqhXEMFP2qr5U5zzJJV4iNO9KK/J9LCyhKwq9qs3QWi
            BxtHWilQhDwyKTYjBkxSW58GT5E31YWfBPEAcesoPucjEaSJxbEj+TZvSZd4thkX
            9IcqFMuVgFCyOy8aMN4Eg7lmIiygiU7GPJezFvDqEU1wnLia3teD8LIyge9G0CUu
            5/VWNSfQwI8ekEbVaAffBu5X/Iy6mEXVk9C7vOBAs4LH2sE+DFiPiHuUZMASIpa2
            6hfnJAjLkxLgTF2H4ehWValI6RYpgIaBY9S1KEJOg4uX+okCwy9qcjBgnbxMNjd1
            C8bkDKOL5ILCCZUPODYA0l4BGvvBU1QGgrwiX/jkHidey85IVWl8YO4O2SsK87jt
            MHI504712NXrocWBK0GEQMfvefsEEYnNKYaJw/POsifu64qWNAWOICBQ6Q6dF2ct
            AzV9c2YuThsK2aG6FGX8
            =4CVr
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: vymanager-env
    namespace: vymanager
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:ePeZIM6ddEAWsWHVi4Tkpxe9+QPXgVmW3MkGkRycMuCogpPYOrMUjWD3DpHp0bUKZHp9+PIvtaqp4Jp/ocgJMAnVFE/gukSxIyff,iv:EmZRTHndoqnk5P4VRmL1/AEHIwa1LBEctO9+jCz2I1M=,tag:ZZk+zSPS/Zu2ea+Bd93H5Q==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:p1fNgKHen7p4se3L2H2uqmCVlcMwa7Hp6Y+fc7z81WGcCmcpJzoEOPtNlwOQUnZ60LtJ6DEBskebGLjcrW/1Hg==,iv:84rsnNu2GF5w2sOzu7o1lTHUB2eWg/yzdwGkJls1CXg=,tag:trZ9uJ3NfhC42HpaJfFfeA==,type:str]
    SSH_ENCRYPTION_KEY: ENC[AES256_GCM,data:zrUd1ooUaS6+L/ydMe5j1m7NB5YiFLRZU8yAohqQDi51sSMx0I8xFX8nThcpEZ3FfKInEGEeqcQPhnewI9R5+A==,iv:4ketmswghpR7yNnCJ0g6FmQXEcmdxV1HV+tVsb/uf0w=,tag:iyE3vH5qarSU9hkJ18yUHA==,type:str]
sops:
    lastmodified: "2026-04-11T15:23:23Z"
    mac: ENC[AES256_GCM,data:UdEX5vPu33V0/7rX+7JeNdUZV1Hv4Et+X7KwewUdH1VPKy/rkjm5P2x6QIFgBD9kTghY4CvTfTBmZvCTayb3SVtGj6rqVVUGKpKM6+sANyGSneZZP4rcL+mSHmFbk+DgsuuScv+/mGvAvAZnlyy3qeW5qyTO3b6uAAS8esQfil4=,iv:AFhygS7lQxxT+GzTsiaaSsV6UwOdFWCNFeHtSeHs5oI=,tag:OjxQtgib8oxxSljH+fYS6Q==,type:str]
    pgp:
        - created_at: "2026-04-11T15:23:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQwAj0DE7su+jv5ocZSwzgjZLvPAxEcNlrZrWnjF2Y+FH11R
            YuGHIAdR0GzIBNVszHx8Kbecs81BPb18QA/CNB/b68cmC+r9dkqtcWKewwblRPXf
            cOdCWn9uJ5XfugR3085DbRKvHLoS8dpSTfRyZELgC40QTKammnDUs4uNFJDL7sE6
            K9KgXpYvj2No1bxZhptayhqhXEMFP2qr5U5zzJJV4iNO9KK/J9LCyhKwq9qs3QWi
            BxtHWilQhDwyKTYjBkxSW58GT5E31YWfBPEAcesoPucjEaSJxbEj+TZvSZd4thkX
            9IcqFMuVgFCyOy8aMN4Eg7lmIiygiU7GPJezFvDqEU1wnLia3teD8LIyge9G0CUu
            5/VWNSfQwI8ekEbVaAffBu5X/Iy6mEXVk9C7vOBAs4LH2sE+DFiPiHuUZMASIpa2
            6hfnJAjLkxLgTF2H4ehWValI6RYpgIaBY9S1KEJOg4uX+okCwy9qcjBgnbxMNjd1
            C8bkDKOL5ILCCZUPODYA0l4BGvvBU1QGgrwiX/jkHidey85IVWl8YO4O2SsK87jt
            MHI504712NXrocWBK0GEQMfvefsEEYnNKYaJw/POsifu64qWNAWOICBQ6Q6dF2ct
            AzV9c2YuThsK2aG6FGX8
            =4CVr
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
