apiVersion: v1
kind: Secret
metadata:
    name: saml-cert
    namespace: zabbix
type: Opaque
stringData:
    sp.key: ENC[AES256_GCM,data:U9yXd0H8OSEVkbuLZvEwcchPPwdm2V8eM3FfJ19UyItg4sStFcqSw7R2+HZfHUN7U7lt9q/UFRfBYQtluhnd4vYder1F4nW2Sla4/7TLofuhU3pGlbJC/I1pgCYf69p7ib9+L2sTwm2UYLvsRfCKtFUgLGoqvlQLU+3bRrkG542ocBGSQowfNysqjqJRK0bN18hIT5LnFoHTOdXjYtGOLmr1nt4XfRpdTxXkLZ9+UgrCE9U/lJqS1gjqSp7/sEBeItVYpoC6lQqUXnx/eilGhB1N8JSDU+CAOTVQFCzF9c7ccw9InCGRf0byznViWHUbpSk81Q3lLxbPTHaA5AXmznLpl83NIPVLFdEOIUAqlIqtMd87WFKUIERqtKWS1T7GAxR7WaEqg3XOAXD9T1mkkteZmEn1NASZlSQ5XWC4nKMUDp+Fpyz7CdzzsbaoGcHD3V/1dmAHokbF4IPAOeBWLJ0VjpfaqMpf2K5Sq9LfkS0Qc87lIC6W982mdYTK6Soayg8/FckQAV4nRlcdPdOD+7dUOIAJxi/2wsLoZTzrgAcmZGHDzqLCkB1808Q6tqgG30gR7NZ+AvEivNruLRsO/acU8a1jy5WLLvZ8jkJTcVM87Eb7ZNX2ABQY27K/SXhSFSEZFF1vHexZzQaCPZ4133rlRZGgacRic9xbKEtKjaNpTIaZRnefs5DO5fVDjHiRmXXYMpOZYxu4sJF5KFABBCRB8OGw6ROsaMxyB8CTLTHNfA5MKdihE1v0lh09eX3h52i7ypuN4BCCTrfV2hqMemdF8cvXybKoX2xRAWyBQQF1a2MVknmtr0guSDVbEdtHUMBV53jySZ6okVzgkz0Cns77j8ehhn1LIs312LK6B84DubGDjrYT1+y5/yUJmBaoIBK4oKtTYnrwPgscW9fnz0f6xV1fQAliZ7JUslNfXZw7g6mEtHFREj/uBRNjSdc2n82rbVSCzTLCKfrq1y3GwXMbSJor2eXgQCWGYusvuHq36DZmB47n9j8BJIKQOvLGLYROg0MzwmjCdm7uDZJsYGXpxoy/DVqhSXgBc/iumrQqkxmjpb/vElX69AU9RfFFbZ4jsW6f6V4jDOvK+RpbE3Odk38TbjUHfRml9MhatP9jYyN78VAas0KwKoIKKO79teqaIAltQ7cEssZgknEith5Et9COwHu6LTwJkzaDcMGQEStSu1y72p9IJzcdGsEsj1ZYMTN6nHlDJ5dXmyj42cgeTqfFI30KWKKOQnmy1ij7zysmLkzaFr9X6b/zvfzgbAo3kPJxbNJ1FInAERkT0rauDDMkGss5QFsygUj/5yXtZXGNQl93ZRwsW4sMYB0mjcGeEOAUzjxbspa0GrI9CNx3pNi2pYF5iSdTGR9gqvr31bSTCgO5Q7AzmWPH+Oq1IjKi9t3dwORJ9LSBwZBEudhNUOZvMJXSLcgHYE5ZON+W+1LShTfqjHsys5cMl3CF3WmFX4FDBELy+ti+1CZFKGotAUqdqoMDw3nmvT2qUjSSgHNa1oj50K7BCpUdRWCkQh1Tw2HmNENn4MADDufM5cIsQVFmRVUl3tcgaN0qDx+0+5w4GLYsfkx86VjKLgUKvi2JvNNS2Ovx0au5nuDX/lX3FNAF/PNgG4kWJheM0+6hZ6os+wUA/PtjmOXBu8bl0vj3ajPOfS/zGboKOv7fneDXXMFN8RRWu84Ch2yFdBlm5rWGNDGu378vKEEldLL0A3NnXdfqThtDZtOfdLPAJJAo7WEUYhymQ9di47YUsj5zOg/yqLhn9fGRQ56xwGkKkJTXHO5p8/4mWsdRWzDy1idPtfpyZGjYJNifPo/n1oHZI/UDr4BeT8IFUfOoAuhfo9wf+NcHJaO7X41OKXKFlQ5JsPKhGwu41lcd2i7+0dSssa+0H9Pz1Gvr73QDjieGdom7R8ljDP3fRyWZLCw7pzNpOedBrb9YS8utF6rVKihx6v09HTMYoKVKtwSINbKrbysUJFZmkVkmWT1QA6l9IExYz+4r7llZYjovwOi3fXp6DI13UalEpyt4gP75lSBfjmdMYsXCB+rcwNgo6I+Mi4agGcqMjtD24FChH18LFdbDPAViBZqqLiBXeWx0kgyxtnIn79Ss92pidx0K0cm8H0BV1eqGHfyupx4N/NTr4fl3rUhKoCjAvGXzwQZRraPyYZuQm2e3OsFFGEUhQZkrirN88YZAp2icCX6wBJHCS+M5+svvxrnHSA618qUEXIKTYQMCsUZdYwMBVOVDOjwJiAOfYJizHSg=,iv:XfnYejKXwYFdbA8L4qKgfI8wMhTTBrhnQTF/QjSQ4ps=,tag:HP9yHudwMrJGpuKETPWoeQ==,type:str]
    sp.crt: ENC[AES256_GCM,data:BuFAMHMSBfrqX5jLFaUhQ3j1TVszYlVMH1C6psEizsEogz5fDi9BJlcL/2/6g57UxC7QtRTodj5w5wCujmEmi/8Q5bxDPAWesbt1jQXjcR28wmHaf2wiuA4P3Q92NJCWZX/jBD25qf88TNR8IFyXWn/6OWRHHpxDefsTP/IHj5686wqHLNpG7Llf6MowXfBU9h8GJ5dNnSfJZZYyYGNSR+gnqzwdprBnXhtT9TagHE6QAVnnJ2zft8+Xtxq4T8Yc4VP5c39CDxZyuNX5zoTakIZxe3TOG4mhh0NVZDk5DoRtfEzD1si6wWtDmzc1uf7JKcHozr1Xx+N2yJbi0NspkCjjcqaxUmjVfIL6vRW1ox4GH7kBNHcK0NgmarHs4HJnKXCnP7eZypwC80p5oy3KdjkFzMGgn+Qgc24GpiSa/P5zXYyym12/FviF6fHo5OM38+Oa3nt7fjWf3oGDsAsfXaENDKNfjHwZwAz5QB90RoorclcTqZNUDtaxSR3vth71wEbgqCARquQje0ryUiMMU3zd2ceTQxcpIIsAFSXu4K1bNq51qG1JIVIUt4H47o2L4oiB+0n/xq+2z4+2B578SavRMrokuoKKkg/jReA/P9CZMjNgeWAnw8XlSaBJy6Jw/yi2xP9udLehs2qMZaz1xSR4JYRjHX4afk5CXSQUQCrjWn8XTk308sZc/neZGagUH6BUUuFfv7yiCFu+mmMOU1tVXNCwX72hKnVZHaX30camJFW7o/Fl6Ucw0/eovkcn/S5A3mucYlgGW6jfBaDej2t/vnKOySTVefSp38Tq7xtaC7ETZZSsfOCR+dDKziVuGYT5LfFmZ1t/7Szjv/E7oGaxZIqQH9tFDMzo76FYF0sya1a2+0fugZ7VUkuOQC+PUsFLI8dKxFR8ySAVL00quF59PuUp2O/OwZcxdAn0t+QfajrTsJYrEdhvpo5d54FXQ3d1WAQ4QFohXmrmcLCUbl6DkVghJDsggMzbIn7gYIab1WDP8a8bsGUcoCCiNMmX6PxXevZC6g9GAKEPsgHmfYFDbWHR7na/deZDrbgCsjXIfElRuSX/EXG+gTAg6MAsyEa/XRB0VxiBCHdZINnARXo45O4LfpUHXTwsvkny9CEAgHo+yXGNMzw3L3XNzMXunfpXXAIikCCYRChAnKHODX+MGbu3SgH+gkzagPFBfa3VfP5EkKagzbdaXXKUGFrwr4KDv2nJrqJLBdIHs/BZqizCWukpfaN2e14ntFH7hCO4/fWGum0lkAl6aqV1Ppdvl43mrrhhDW+Z5avqsVwyfAAjb6Rnky4y1VyAbk/SV5JCopkMJSLKhdhmS61i54GsonmFymsEcacK6NO6S8u5Y2q22iKiUD/eFCdxQDDDourRPCM/r3yw/O80nDMSMSCp2nK+jnAmw7grDpN8WUBZkIedJ/LK+sFB9RQxDByRFfmVeX9W20fXkKnQ1majICm8j00HjpZPehfgmaWjbOkfVl+p1lNfnAOtiColi/CCTWjNiZujydZx2bPyT0BiTNsAF1Q=,iv:tWN3v8P3hicJIw5DZxrjRGcHnKnAwwRz7Mr4ZqHPblY=,tag:Tu61DnaYl95UtfCVVSefnw==,type:str]
    idp.crt: ENC[AES256_GCM,data:1v7jJQoVri04WLVwT38vP97rPhw23EmKtbPs8336XX1COm6KVYXaM7sR9YSn5thCZPySth9hVgS0KNXNz1lzZoB/8/vUh/00Dj5RrL+3Tq1W9S4eL3iYwYYvfohadEFE4zhSLGqxRXU6tj9zU2V/m9nWS4L+wo+i+sNuOCReRmHWzMIEgtYNdlezFB44RsgvGeSTFY+v0ZunW+cvLXATNJfbasa3dcSjUWDkqVtSMEpAAf0Jcv6sFM2yY+BjyanPhufLM/1/0wanBnXMHDT0JiS4yrfZvBiUSGiCRs6eWS5qcOdYLeOetp70+PZEMfxtJObMIjXEYXxk8lRBmlwrSITBrdCBgqorFQ7Qu+6Ki+UJracV8EBSayp5caZgW+uhrXYk9YZpz0n3s4IMDXOeQBOhgAJjpN8z6V4DdoWs8EldQ+3qYTCyJ3+T4EzSPxBd2v1kyekDjJ5wjKWEWNbjXtnMkdvGNZHOTtqgIj99tMyUmE6RxOKsXWKv1sxg486qUAIyP2SUJSYgZKxFaHHPoUO/bpglSPGpZBoF1Q2qiSEr2ZZlE4uLq2f7ROVxAAvDp83w/Jkm0S8QtI1cocXQcnwIcp8WgfkbkTHz8cGrXPNPxPpSufMNjc22na7y7jFHLa3jAq2Zqn7iqAbLF5LQPtZbl/r+ppEAdzoPGeRM6dMzq5egDJpkS1Fw3VRzY6UIPMrqyyFnhf03KdYPirs8PwK1QpBah/A07f5dYAqnpcuGTCTsfLtxf+mD8wjbGznOF5ec04kRplCeHWx49LhiGxqmnetsQLIKI+/AgfXOE6Rv93Fd2XiLosQAvI9vn0llKf/tz1cAb2ewd+jlvRj0L2o+MJ3+hLYTZbas2YNHj+8VTI0gF6a/jjKZZ5rYbbO4xaCUCoKDLcKOHWGvcl1IBaZ8aWKdNzqrnvjgi29wRIbeMswhZ9LSyZk3DLXV1bgjcghtvIsLgOJTMAYWNb0QcMYaKECHHUl7lZI31+OzXgIDlV3lfj55Be55WlI2lza9c6a9HhHEyI6cCXQe2I8AWlpSwEsxBnRHwszhGLBMMGAsz5w6nM48NPbh8mLgeda4chTY9H/RKc8Wm1L+5ArWQJjVOOER9UQ3XnMKE5xHtbB5FWXPf3M5PvsFJY4jYG9OuwlvuXhdzLT4SkqlfG3V/DzdnT6eTbdU2zexTplDHP+Tt1D/4/Eyg6evXpRfUsFMX/aoS0t6kB2tR5qKYDi/HVbMIy7ZDoL67AHQvp9nFx2oPhjnqBNzAw2dyAJmLCUVJN3e+jxOCxYSewKRWUhHELNhVzUqCO0NyZ0salnDNtKhyMZEMH9iN5hDBF57R3OqBccPHZEz4ZQS2Mx//xy7nXeIGz32zkFU3U8f/8ynNY3dy5PMrjzbwe7mhfSkih3o9SPmSgOEEPDTmOVVs6bWqcRVLHh0iyo2jM6gcfowCFFuP1z/UwBvRuAjuDxdZHqQeqew9bN7pTiN4LIH7qAWRiWIhuKOA2YmCOcZIFax/x+vD5R1EPEQu8nJZd+whcrY/VlHdDY5pOYTNiWvJA9FWxZSkZrLdyNWsFBLHBOWSVeufS5vvVsRQ4i+XtMy5tKe1QRBuA8MhPyBH6EejLt7OWYOi55zd0++MXnv5I+SNItiJ1WFqtbFGg2bVW2NcqXddt4Q35U3E8WPfLbcdHwRQ2nZED7JB5wTp5lgI8GcVswljLhrjaLPtdPNnMvk47rygVZ9BrQJbrgvZrFo+XLyNCUrP58zkifcHuFhjJ4Ky3l+2pn9RqhG+KgYLjSiohFvd8RNyIhOHb0S59MYSec4dgNjrZWhch8Bqf2KeH1qPVUFVZNq6/C47JdbrF0pRkZRjsv0/jQGoB69LowkRZbUl/AA0rKga1A0r52DlhjUDxpQ19XdQ1IQLgAUQg4tGis91dxJPCUoXOLdu7dq3srddXras0fdBjWwbEAOCz63m6dbR/e8aEJAEQ5/WtReERkrzMJJ4bIZADGom1lMIBSNvsL2aXJe56RC08gY3o30Sub2jZ3i+pvEQH7/hLpQunJcDw5bmgfmIvOo9XkyoDKvR5V7g37BBV5izbXWkcRYXsbNJ1xYfqEMImxgobqa9AmUMJxijiDDyo46h/G9o6IJN2TT2v9ecTvvDMRa+gHS7Iyg4xwrwYYR6Skz7fkqiCXZ1zoqbbn3zQpa8fRdA+sVmrmR6b8OmKLUFSbRnNLFaG2Y6ZMShyzJN+c/0EdH3AlMjTfrJTeqjqbVcO+q3jaFMuTV3cxqd0OA7ecrsQEZ1QfueGGm9ObZbZ3zQijjlkGDNGAI13MB38uJ4ePpAYsYZjkGQCATMSQ4rxuQtga+iMw9pfEHHTWvUqSIUiWTo6NLG1Cyl9W1ShGGddsuub1FcZMkCABmDmH324o7gvgVak8ju/GYZ0HixMNcXkWGAHvp7Pm1c3Rj0fULSNY541sEN4wMVIiUrWd53NGXQCchY/3pDRVlFrjKrSseQqth/NOF0SeSBBKB35MPfjDCY2o/I/65h28WIzZspd0m4MfKjCPs7g==,iv:3K6faLW1HjTBlzuRwYGvh+l5NnyCyQr3HnoJnbHxvIk=,tag:dFUW86YS3AWfqos7N39yTw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T07:59:56Z"
    mac: ENC[AES256_GCM,data:LVcaCFLSDs0Bw87O3eaRFIbKUjV9FfEOS9uXt99UABJslg71KgyrKyhSelH1DzA00s0p7YnwaJfdJwuPNRuBnGD3SXmqDSA16PlQJgrBxwZfpzI+Gt5803i80rDodfJphwjpQPFJa+jrghP15cjGaN9QmE54fqFaBUmVFkv/E4Q=,iv:v6OLDoAQBWeKsHwpo7POn+VFjvBhDO6YJO0SKR3I5mI=,tag:FjmQ1ECKpjsz0d4xNbPi/A==,type:str]
    pgp:
        - created_at: "2026-06-04T07:59:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv6ArcFBnD0YvIPIphczgRS51YWE0OiqhkddVxVLwhYDev7
            RQzg/EHgUPW3KGaepbjF1As8DDnS3SrVNSflE3zjTxCazQDbRTU+echFGNMqukCw
            mHKB+ojU9l7ZhiKVipoSp9QuU9UPddJBzlfEJPu3oCqgPK1gYipL1e0GgarSUObC
            LDxW6wPbqYhHeHdwsXBqHoMi7l0m7kBucgHMnr/lZ1b27trnfkxToGeJ7J76db1E
            seRHlrS1F5msD8gL0b2b2ERU8ZmOizFebS6u9J3d+FEzJ8D5a7OTGgXiIlwQg+eA
            NMMtmYoIb/VycWgsXtnk3JSWqNcXls9gE4nb6K2ECS1id9PlQiVfqvnst2SFB/xv
            wioxVnw9LAPVrMUoIGdIMt11jk7nOeR7xKtCu+S2/tfBuyYues42TBOROiJ4ntrg
            PhTBVj4lIiELGKmufi7byDcPuOXencFVTnwB5Uxm7icto6Gi1gjr5b8jFy093pYp
            RQwHfaO9xaiyqcpCy92x0l4BkztVFV66h6/wlebQ8EkauHOGXYB7h9b1fsdivvZF
            N3tw6WXfGMMq0qIb4J0fXiEoYWPU2AA7p9DNdvSW7fp/2kiCl+4db/NFmcT7x20p
            kNSfzVmGu6j7V2pioKHr
            =ZyBn
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: zabbix-db-secret
    namespace: zabbix
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:22ONvJGJ,iv:FDPWPpL8i46jvbHba20NChBqmqbTCzPe+EuusZvEJls=,tag:Ws4teLWuh0tgEMnRGQUEgg==,type:str]
    password: ENC[AES256_GCM,data:7lBdS11YNhrPwNoz6fk=,iv:Slr3vn/GB2YSkgxFZ7dcrzd0IYxpoScWqeBKbxEOaj8=,tag:lx7sMXzQJQa9Ul0c7qcmBA==,type:str]
    host: ENC[AES256_GCM,data:XQ3PVC5k4Tcdy/7i,iv:yrqJKEgX+Ao17WTMlZ9OFGEulFO45Ek8LoIUDUKZ1sc=,tag:eprYTWERDEk+4Ir3huO5Rw==,type:str]
    port: ENC[AES256_GCM,data:INHsWg==,iv:9i96/cKd+WOhd1ZAgKdzS3Zv0I7WETOAOEIEcpD597E=,tag:HcfLVgrk9Z/mucPBtUAa1Q==,type:str]
    dbname: ENC[AES256_GCM,data:rtytwAMd,iv:Hwrx87siTxEjPh/uX9gLxEYLzo5g9KnhslJE3uKHMA8=,tag:NwoWA6pRTLeQZt16LwM0Qg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T07:59:56Z"
    mac: ENC[AES256_GCM,data:LVcaCFLSDs0Bw87O3eaRFIbKUjV9FfEOS9uXt99UABJslg71KgyrKyhSelH1DzA00s0p7YnwaJfdJwuPNRuBnGD3SXmqDSA16PlQJgrBxwZfpzI+Gt5803i80rDodfJphwjpQPFJa+jrghP15cjGaN9QmE54fqFaBUmVFkv/E4Q=,iv:v6OLDoAQBWeKsHwpo7POn+VFjvBhDO6YJO0SKR3I5mI=,tag:FjmQ1ECKpjsz0d4xNbPi/A==,type:str]
    pgp:
        - created_at: "2026-06-04T07:59:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv6ArcFBnD0YvIPIphczgRS51YWE0OiqhkddVxVLwhYDev7
            RQzg/EHgUPW3KGaepbjF1As8DDnS3SrVNSflE3zjTxCazQDbRTU+echFGNMqukCw
            mHKB+ojU9l7ZhiKVipoSp9QuU9UPddJBzlfEJPu3oCqgPK1gYipL1e0GgarSUObC
            LDxW6wPbqYhHeHdwsXBqHoMi7l0m7kBucgHMnr/lZ1b27trnfkxToGeJ7J76db1E
            seRHlrS1F5msD8gL0b2b2ERU8ZmOizFebS6u9J3d+FEzJ8D5a7OTGgXiIlwQg+eA
            NMMtmYoIb/VycWgsXtnk3JSWqNcXls9gE4nb6K2ECS1id9PlQiVfqvnst2SFB/xv
            wioxVnw9LAPVrMUoIGdIMt11jk7nOeR7xKtCu+S2/tfBuyYues42TBOROiJ4ntrg
            PhTBVj4lIiELGKmufi7byDcPuOXencFVTnwB5Uxm7icto6Gi1gjr5b8jFy093pYp
            RQwHfaO9xaiyqcpCy92x0l4BkztVFV66h6/wlebQ8EkauHOGXYB7h9b1fsdivvZF
            N3tw6WXfGMMq0qIb4J0fXiEoYWPU2AA7p9DNdvSW7fp/2kiCl+4db/NFmcT7x20p
            kNSfzVmGu6j7V2pioKHr
            =ZyBn
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: garage-creds
    namespace: zabbix
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:oHCdxFsTYDyKdlVAcNw75unSG3CFqP93uN8=,iv:PVEkd5yZ8UlDxHbtGFjwGhfWo43FNrLczNEM9pfkalk=,tag:nJ8bJb85390SSXGyNxsrXA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:0XQDIw/XaOzdqVnJAEVvdKyxDWxvGEE08p9oZ75YL3IlGCl7a92Hg0ni+Et/GLKHximEh6JRtqmsZ0XRIwIh6A==,iv:idgk+XFMgTzrdsXlG+5xYGI/8CjNq5jete9aD5Ck08Y=,tag:o3zFMRabsAPhXrBItBjJaA==,type:str]
    region: ENC[AES256_GCM,data:uTOJSQ==,iv:6aE68gWgVGQmkrmQm92RcrhtZwaUTMUcxVlvIPFAbCk=,tag:A/65X0czeIiGHHs3G4X4kw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T07:59:56Z"
    mac: ENC[AES256_GCM,data:LVcaCFLSDs0Bw87O3eaRFIbKUjV9FfEOS9uXt99UABJslg71KgyrKyhSelH1DzA00s0p7YnwaJfdJwuPNRuBnGD3SXmqDSA16PlQJgrBxwZfpzI+Gt5803i80rDodfJphwjpQPFJa+jrghP15cjGaN9QmE54fqFaBUmVFkv/E4Q=,iv:v6OLDoAQBWeKsHwpo7POn+VFjvBhDO6YJO0SKR3I5mI=,tag:FjmQ1ECKpjsz0d4xNbPi/A==,type:str]
    pgp:
        - created_at: "2026-06-04T07:59:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv6ArcFBnD0YvIPIphczgRS51YWE0OiqhkddVxVLwhYDev7
            RQzg/EHgUPW3KGaepbjF1As8DDnS3SrVNSflE3zjTxCazQDbRTU+echFGNMqukCw
            mHKB+ojU9l7ZhiKVipoSp9QuU9UPddJBzlfEJPu3oCqgPK1gYipL1e0GgarSUObC
            LDxW6wPbqYhHeHdwsXBqHoMi7l0m7kBucgHMnr/lZ1b27trnfkxToGeJ7J76db1E
            seRHlrS1F5msD8gL0b2b2ERU8ZmOizFebS6u9J3d+FEzJ8D5a7OTGgXiIlwQg+eA
            NMMtmYoIb/VycWgsXtnk3JSWqNcXls9gE4nb6K2ECS1id9PlQiVfqvnst2SFB/xv
            wioxVnw9LAPVrMUoIGdIMt11jk7nOeR7xKtCu+S2/tfBuyYues42TBOROiJ4ntrg
            PhTBVj4lIiELGKmufi7byDcPuOXencFVTnwB5Uxm7icto6Gi1gjr5b8jFy093pYp
            RQwHfaO9xaiyqcpCy92x0l4BkztVFV66h6/wlebQ8EkauHOGXYB7h9b1fsdivvZF
            N3tw6WXfGMMq0qIb4J0fXiEoYWPU2AA7p9DNdvSW7fp/2kiCl+4db/NFmcT7x20p
            kNSfzVmGu6j7V2pioKHr
            =ZyBn
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: pull-secrets
    namespace: zabbix
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:mi83pIU1JmtYYnxCbv9/jEh5CINYYM+2+t/H4NAOc9aXKxosPPK3I4rOxjgYdtEiF//f/LHUrn/Pb+KAQ9V8XsHuW9vsNnLiEaLqSHJtLAjwvdrKl6l4mqOeP1DuDyQy5McJo6x78j8LF1zzo1UYqABqETSymSOVmxyKQMxJ8e90xVh3Y98E+el6o3ZCnhjlLvEDo4Lljm1SwLTr9KTFME/tbnHeOb8Mg/I=,iv:ch6fpEgEx36qIpIwa3YAgIwZdoj4tg09A0RDRVpOLWI=,tag:eedMDoKE/REdy35D+wdUlA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T07:59:56Z"
    mac: ENC[AES256_GCM,data:LVcaCFLSDs0Bw87O3eaRFIbKUjV9FfEOS9uXt99UABJslg71KgyrKyhSelH1DzA00s0p7YnwaJfdJwuPNRuBnGD3SXmqDSA16PlQJgrBxwZfpzI+Gt5803i80rDodfJphwjpQPFJa+jrghP15cjGaN9QmE54fqFaBUmVFkv/E4Q=,iv:v6OLDoAQBWeKsHwpo7POn+VFjvBhDO6YJO0SKR3I5mI=,tag:FjmQ1ECKpjsz0d4xNbPi/A==,type:str]
    pgp:
        - created_at: "2026-06-04T07:59:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv6ArcFBnD0YvIPIphczgRS51YWE0OiqhkddVxVLwhYDev7
            RQzg/EHgUPW3KGaepbjF1As8DDnS3SrVNSflE3zjTxCazQDbRTU+echFGNMqukCw
            mHKB+ojU9l7ZhiKVipoSp9QuU9UPddJBzlfEJPu3oCqgPK1gYipL1e0GgarSUObC
            LDxW6wPbqYhHeHdwsXBqHoMi7l0m7kBucgHMnr/lZ1b27trnfkxToGeJ7J76db1E
            seRHlrS1F5msD8gL0b2b2ERU8ZmOizFebS6u9J3d+FEzJ8D5a7OTGgXiIlwQg+eA
            NMMtmYoIb/VycWgsXtnk3JSWqNcXls9gE4nb6K2ECS1id9PlQiVfqvnst2SFB/xv
            wioxVnw9LAPVrMUoIGdIMt11jk7nOeR7xKtCu+S2/tfBuyYues42TBOROiJ4ntrg
            PhTBVj4lIiELGKmufi7byDcPuOXencFVTnwB5Uxm7icto6Gi1gjr5b8jFy093pYp
            RQwHfaO9xaiyqcpCy92x0l4BkztVFV66h6/wlebQ8EkauHOGXYB7h9b1fsdivvZF
            N3tw6WXfGMMq0qIb4J0fXiEoYWPU2AA7p9DNdvSW7fp/2kiCl+4db/NFmcT7x20p
            kNSfzVmGu6j7V2pioKHr
            =ZyBn
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    version: 3.13.1
