apiVersion: v1
kind: Secret
metadata:
    name: saml-cert
    namespace: zabbix
type: Opaque
stringData:
    sp.key: ENC[AES256_GCM,data:zln7jlRmxUjWNpCU45Y5OYXSmq8ouz13VZynh46Ht+1fSnGBwfG43tJ08WFZuG6QvH3cp+sJ9itO6p0OOKhz4J3+4jSikoAysaLZDZhLM5R6iIzhIbAZZLiErIcoY+EoOdx3NbM96JF5PUgPSHcyLxTR7KIX3hI9Fvy6U280IXTsarVznkfBNfkqu3E3HjTRHvfCfhCVVtEVH55sq6dtQb7AYBtUSovzBfLrQfar9u9IH3TtQuV1rlY6oJiHFq9z7CL6yeGAXGi2oUtVbIGvICCG2K+HbWI8Hegrq7LyavEbmHoA0RpCO9SYBrQiXBHSHXAI9Td6i4H56G+fTRPy8AVh8zqwGt7WETyet6Lo9C2qY++2foze0Bb+bkC9Nb30oOTHfNibLsIZw9+BoXS7tjnJT1KS19KzqawCHzBUnhFRJ65i9P8O124fL6GUlLawHHolye/I8tqKC8w2dIWQMvKXhcaEy3jwIgGvW1cnEH8A9/0B0dF8jsqfqwjCvnRAzNZ/Kc3SkSkVqIuHQj5Gtwr8cjK+AYx4yrZgU1fHyI9BCA60WtbKxYtJB2VrnVu9JKwM748lYAxByJMChZg0aoVuIFYKdfyKXTCF/ow2AFLPWRU6OY+fAnqrh/4YqdxDADywV7/swr68ufw9GWBMVfD3E6leBPI1KMHS1kjMyE6afY5TLmLPXyUA7aeqcufP4M2zkp2MYwxh3BTVA0TQ4lSrS17HFAi5qzpDjUrgaZO8hQRQGxzxtrWpTZPDEnTn54Z7IKL2P15Xzd3+N+jkTxZx7llOLGqknQIDAqjgR946DZNl7a4IAwEwKUJs/X0z4H9DRP952tzkW7k8XfK/GGar9ycorlRnoP3EsRb3RTSaoXJ6CCalZiIqZ92DFPK9GFt0058aqY2RRJxeTMVPuQjdol9n5MVp3eDQ8kASOPKd8ku5bC5DPioDbMKZWZv/IigG4UKzmCVDXhyYOAKk9McdhI0wLA/eXgj1e8Axlf40hyt0l9bq0gi2nqjWHYBbonxnCATvY8zkJPp8H2p50KwsKAs4Mlp91noYLwhNNjL4+Xyu+3Bu+x9qQ3JTIeU4zXcgA+WH2SJgnIy26zdxtXQJcRlHO0KyU+Ge6Rv7hGU5hG1t9GbHmPmHYt6VYseExCgjvW+2NRe+338vdjIw0VuYPxEJJbc1IgvRi/s57rln7LUsGN7QQ3EBAyRomfgzYi5+ojb0xym9KIhHgueIy2CdJN2xvvcrzxWKWtmSAGpn7jwJVErIpsIutTpAxh4en8WSSdbeAyfKEc6cN+rRUnSBv1AgUx7AEA4JGLIIhIf5CnvoCtHI9scfbJdEEVm/B69o20X3Lkz6/JtF5nOIWKUTFlkektPhKzCb305Y7hUvWzfq1rPCHJgUTngA8K0j2pvQkGnVI9I4rSEta9J0SmUof9L3mqb+/+Xn3VprVp8+fAOyMtDr6u1+c28bmpGR1OuWZuvZMEAlp0CyrxeiK+6Xd7LwEbC4HucKUaIN7uRILusOqDACvxMxRMl1Tcd/hmmwPE8otY5b7ZYTyrh7qR0VB+D5bzjZr3nHFoHZ9zct+PM6ibGyfVphEK/ObXpBLWDokiO6UKYouBq0JGbgYg/UYBquM/aLXt1eyUGsGdx5YOe/+koX3HK8Ihy33RcRvhz7XEAxXQjK+NhDupoOoRDr9Ko+RP43qmNsaTqJa5r6aHGuWJtHBDCevvNHFzIAPBGrSLNygdewbce5rhes2e/XacYC93bM+VdHAamsrX14cuoTFYZNyw0Ojekfog6C+bZXRESsHiqqrDdVZpm3mNF8+B4msBB/3FxP3flMcPFTnAw7lPENCKx6OvpIjA9vdzpAUWcqOSvz3P3tCdHRTajq7xFudpbDvDqTSZv+uLWfbBv3wXjL2wtcgA4vnT0E0K+Wt1amSnD470K2xRgh3kmxqcN6O1bB61c/Azq0fnGvwhboDzqZx2mPmelootHT3URobvH7VOHU/yd9pM0Y5nWQ3ADZopzVtyuvvHSb8C3tgIqnFdFrULEy0909u79Axb4LuahV+v66xaCf3oy6vmvYB45lDDNRNFR8lgn4lqY9ka0+/PTKohQsvSn5NU4NKDxoYbo8mm+o9tVi4M3IHiijaYt+zf2va4+6OAuXjM34Ty0BidM9uIC3W6XJGl5WIGZ+aizP/fkB0Os45tuZ4v22GMDkleVYfDbb3EwfqoJOuXN0Qkcr7fBSRjMZr/uUmFHEsrdQ9jZ594G8H1ZF4bb0XvhtQQ4=,iv:kHY4IHPhkVCGU/NKVsN16gEPG9FFi+GuSANdhVyqvy8=,tag:9bao6/H5BmwSC2EWiPWedA==,type:str]
    sp.crt: ENC[AES256_GCM,data:+a9G3qatEh5ByNY1mEtEoqnAI5cZZVjzenZWKnhh3/DHGpCZZRjroUHoOe4X8aZGdMMHPynzgoDgWOj5emOHswl/MeYHZbQPMJvaqI4eodkqCuwbsNLt3H26AyBeOXdrXXHCj/bkbKeXzLniIuv+20E4eK/7VMTAG3nCN9Ud4qFWtF7U95YLi/M8EqTpTafVxEgHRJ/y8eAHz8pZE0Gy0aLYpORjDyqszxc969ETwLDwxHDV36XyfFsd9vOL/86cryVcaEG9AT2Zq2ViQyEGS1kKJ8dveJdXAv8FKSJ8gfozY46qWVOP2Fv7lHyom73QwkZTKy/9EE6WiW9gHTtU1P8phuvYMWl64RchAv1/DHvmcu2TM71p+VJH9eiufYxSw93zkBrAJ5wFqfR+wc9VKa609i9smZWmG8zGy1nznDAd5M/5bFTrfTcYBBrxlDgwuq/ZV0CQ8avVErQj5LIYJ7ZGI/V/UXqjE0W/PXFGg2v7JX6OCvD9xFBNWEA76GVuAHq1oWiAMOuJsFekJ+ou9mVQ1BmxsyR/FS8ORFrGSA2GU2YDMihnaG+2/QJG0B5uwIFunb/gKE6roQNX9Ric6dmMf2SiYFQardNdzbfskDJsNUnFWfKF2/hFgDs3xJhjVGuKJrDaZ9fVjwFBIxEuxg0W8SnekkY4BtR7M/A5DXKHEukIu5wMazpK7O1k6mHumCKtRQgx2T3mcvnawMwRol6tnuNu4o0emQVH63hf+dYe+QKwr7bSIX0Ui5q64kAXIfEcwoeEs0nwqvWjqn6OCOUfwgDLk7SwTzGt0tnsEZAbDPB5Qovy0RyPrMLHU9qEcfJnW6r2Jl8ieQ1jqKyUjz85RXqI5RdgFqJTynTkVe1CrQBIyRfQxVtLiiqpl9+V6wRyqflID+4/ZwB/ehHq92XQWcF05uipypUPWMor+LES4XJEcBdaT1glXkdouORJViPQRqecdDW8nG5TBWgzwfu0aG9Tr4wUhNLqEbFSSUdQSWHsI8MSMxhPL1dMINljx/tQK4GRfjiAC+dmub/9gXhdUoF330MDUcp2JN2ydT0L3YPn3JQzgldVFVDJoJWwdQrYk/toegnclshVtlfOzWJ7hJrK7K0llUYN4hckf2snD+zV/klBpCFFmk4U3uDbAXDRwzHtSbjHggcwIoT7TJ096rGQNW9deS0laJB0RTNSgdXKC4CmgMOz1WcGReu4431NierMJCRm9gS8gAEn7raBWxcuDjJdEH86exaeOIjZIabVXQB7u618fa7iSbH1iGCrUEjbposU+osE10h8RR+6eU6BPRvTrv5g5cMOAAU3O1bWQDVanM7+FtrqdaZPA5m+2M1reM6VRgH2eDPGv6AmNn5Q80AU+fO11tPJQKmAcj0NIcyH62NkxqttMZLOQ9RZE74bTjlK0/Pj7aH05EChhQRS7eGdRHpRusPxzSV70t6h5xa/A7V1A6lgogsslQ1eN7Ti2lRxGJBbxv4+UjoEg1gGgJ/f0NecxdmGmmbMkYtya/XGGSLVW/ra+RpotGo=,iv:biGRsekN+jglqYRbLhdhL/MKp5kQCeoYmdMWBCt9LdQ=,tag:vOaNsud1Lt7hshSQQjmZ9w==,type:str]
    idp.crt: ENC[AES256_GCM,data:9HkwbfNFSbagu5+lmnmVX1yXrH2YhVnVHx4oG6eEwezGdJN2XYTjeUoBJxNeeGOXpW/oJF7plTmLfOS6DfWjTOsoBdRhYTCoUlecAOUpu8H8u4nLTY/kAwsiVOu5mu/ML8nzswRDUeHqeUjRIWu2QY0+oaGtqbR6msSdu03nYnwnhdLhz3xVYRek/56JUFMuSRQa5AMfLV5w80HdqBMtLhjR91hUTx1xZWKWfy2PPVTy7cNVe9nxTKlO5ffkq5lDybmizj/9JSrt2Z0S+LEL5up1gWXxTKaMZqDrGdnvgrW9xOjUoiYvKWSXC3T+JkcJaucuZIdwfRHbU7Ezj9Fu8lc2JOHg4cawBsqgIa50HM+kUtlAMfppTkg0SI1XDltDp3bFBRKv85tjmFeYkNXnUtTbnyyxLdECUcacMxE+CjMCSQuA8i6dCfhUocOzGBpUNXknEfBuL6hahxXzIYBTBw43NPbEPwoml0VaHiakEVgNySmMO8nxJBAj7naO0E0E/P3DX3s/+JK1ZzQBC/oacDhve+0TPYKi853sBirNUodQxkPbXcCL63oO7cx3AfOPKYfSMzKAGvx7J/Yp/zIDItLeoqDSuKDGPRBeRl5fe0pQv6GU4sA1yMzfrqX0fhUg3m/DGXVyaNnOL0ZS7oSqeHz1N80ldROXi7y9bymD4vM4iVb+mkGpLm29aUM5X7G3GnNt4ctoPh1tYjOYG2ZpYhzJ7XLtsC57Myx7mTFs4RqvL1OPBg7mJG8dtpjV8JzYEbiBAHNhzE8f0Zu7Wcpv8KQSQu87z8qCw1oOokaWTGLe0xy8untjRwzL21KYImcqt9iE7ybVOLy3YoBfnkoR8qMprRrz2y6vFF0YTfJYU9U/xkpWPcb/NPwhRC/EVPGd57qygBzU9DxWx1KxqND2EV07941PgZIATfffTohDJ8ZtSTiZSLyA66VizGmd4gVfPEAC+peu8PUvjlHG/2qY6cc4/uJG983PUQWZlwM/anMp57HzAryFP+ywiCM3qozcH0ICZe94v4wxisY87t26zu5ApeTriAdTn5muv8o2zc7Btq4zfZUofJHVpmtnG9dtpumJ4O6BNNiu72ABIBtlCMgqBhfsiT7s34w5dzh2L8+4p7e344kBrROH8VRYKnpo3O1kCSAGnIaSWRCuHp01qOY8vB/eXny47ouPFc00fZQibImD4Ue72TeKthDOmW3UGAoVfh0W7SirnlSZiUhTlgaWCQpm+DiRamxmBtoq5T+/ylgP63fk0HtYdVW0hx2OYT1KtUxck+BaT+h11NOifRt0ZJ1SY2+yaaC1uqzEV9g5S9d9QoW5et6ch7AedFnB3jHBET6zoNqgDDVLH1U3JeP5cnrXlaDlPHFk+j7Xy4M2v9Ysnn3xYM1FnxXtdCnG6IjcDZAI59RffUfSIIiq4WUlEezIIk8JOcJtjNFEbCr1H7qZgeWa46cl4Bmi6nhz+kVjWDYGVEWKK44ALCDjpXoAncWJijMRUk9F/WyCv+04g2MsHb3Yy8sltP9wnRyr1zgYR7GMg6+D2jFmgTwaU2uwVXELlydeVXEFPXMAEKa6ldYOR+bYbBWXNmdPNdBcTtrQCNDhPgzXu43ntkJW5zG/bu0E3NbnRGXXgsI+jM/J2rLs0zhiEWjllZSMvQSu1zavOR+CQ/kXGxEjXr/DnpFV4j9UFgpjsBs+neW4gDbCqwPDH5EFXQfQ94k3EEZAvwTfgRwLcZ3YS1Nqgr1aaH1g1o8AmtFzBL4hYzpftxDFk6Mg/nPui5LSBYpJBSpQVkfuI+7sCJ/ZfvuiJWsMaONwqVei1FXuAWgE4J7q47Kpsa1QcGK5owEZfLCGXhY5+fArg3b7tcpNxIHgOy/AOFe6wyw0nn/OAuepAdtNkUvs8M5r9VtZfD4ezl/8rWx7345b1d77HytAPYWcPyZ1sn6TdC7SrpMzc98Au0EgxMxBE3Y9UNU/rfSpVLOfQztrJNi/4tkQ25J1T/kArc2mMXcQcnnv1UA0e/BXxL7rEk40g+PP5c75kRn3XJO8M6YCcHxdxfo+Mrst13v5xk3ptPY3zm/udB1bNm0WwMIF5tStQ474SlDLibF1eUrktLXBaysj7NVNQrIztEwerp3SnxRQfyd3FU5S0OJJrhZLGBiJx35q2CZJTOgeNtkvSPvrytlC8lZ4kekrx++PevZQrPlBAC1QAt7jg8wy/kPHlv9xfubuxL5Qot1zliroLOflk6xtW30EdJlRolcdwhkwihmwgO3xvsXZZnaYno67wohzCrCLajrDZwk0Wp3CtxPbRQT806w9OAShZ1yaRPxEzxPhSNRMEOOB46+ZxYi42MwRRHy4G2xFN/9iv/sj1FbGj4xXDzCeW+bcHJV36Y/b7T79tJ5n+ZbPvuvFRR8ynQi7wReDBd8eUutwI83GMFep3AMVH8zmS/YDCJFFRE6VLcXFJT18iD0L52XFdu4IuZ+EwycQ3XZBjEQs2hz6adtQMucVtYyWpdUrUce5PwsA9gKtE2sxN84bCCavkJ9wd11Kgg==,iv:c4i+11D4QQU25aNnY3Cra5SOVuIJ6eL8ALZvZOxzWnQ=,tag:r0W70G2cTfY3KQ2ItH/40Q==,type:str]
sops:
    lastmodified: "2026-03-08T11:59:57Z"
    mac: ENC[AES256_GCM,data:rR+amklj9SOu9SsWJ/pgDyFnLgNJHZC17LkN9vEAGcwC1xWNTCxd026P1mWGUABzSepYsujTeHzmMhUOcaBC9b6b2yRTl+m7DfbWERUOlMp+cHjTytkqgaQON98AV+2J+uuhcj47y64kiOHqeG4sWsKJ+JWxJWYMZ5Pim9nBWV8=,iv:Bvv4ESaOv+0cscEeoFGdO3vPcoFuZOmpC6ER3Xxsdvc=,tag:if/++dV0+4JH9TM4tDxwDA==,type:str]
    pgp:
        - created_at: "2026-03-08T11:59:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/fkgfKhIiNh+6sqixKPGjN1CTRIotaMhhCrf9E9+K1zqg
            6wqBAEp2dHrzUJkyEkVjw5tY1g7xejL+tatXIPczolZ3kAp+xvNzdD9tLyCcR1n8
            UgWbpoe14G5Hy4ZeKN/aPF7Kl3RfQApOBIMVp6AfyBD04TtOkX0WrY3pr8iFOudm
            KQj0tQGz1eJREQxFKpw5DlfTndD/7cUBCAVQ8KxdOSaJtZWcjpkvOP5s+9gfXd7E
            4yhOHaISDGIpiVGHPsRhoeoIeVXXWOQZhutm6NKbiTJ7x2A3rtHhYgCUG9rHQaPH
            EEZYXx2IGBuB0P9ckGyOWzKRuow/xGnqwvk5YPimjRxLicttSM8Z8VJnwk0wUlFS
            z4K6yxqY2GDIasdQ0ZAlhXzH7p6wXW23v5whzFdMvGfx/4koZpFj5onovwqkVC2a
            HJzKxn4At0LO8MU13s+fXfpd67QfiGMnytHIFfX0PJHhUtEDivJuo1VljArWUBzC
            GXLqHAjydfatcPmQmKEZ0l4BKygUiONIVTjofKmSnE2P8SZDD2VSY7lCEItOoWmp
            9eFZBLAkDqYIYj0EcnXAYD3m21zpNgTQpFsk3b/kjniGh1J5mhWCsiGavBch5pFh
            qZlewe5bq2H33HlUHU5p
            =zduV
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: zabbix-db-secret
    namespace: zabbix
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:pv4g84u7,iv:a+dyli3r5At/N7HpZ/oNnSZjX4IZBSd4sqXdtv9YscQ=,tag:fyHbcRA/9jJ69DUcknlU7Q==,type:str]
    password: ENC[AES256_GCM,data:JIpr2glVwebvGoDxC3k=,iv:kHmoIseDbgljDXdV7tIhVtzzs9jOpDovVqjVpG//Rk8=,tag:bJeJaL29YSJTzmtHlLejug==,type:str]
    host: ENC[AES256_GCM,data:Xad7K7PrpCyQ4ycK,iv:8R/3eQRRQpeL2OrXaY5EOORp5aizGaeO9ILHHjrN1aA=,tag:vdxUZJtyrdKppAqbNPOhJg==,type:str]
    port: ENC[AES256_GCM,data:oHv9Qg==,iv:qS/eScQyrq6VupOqQC6tELDyWKrhFkolXwHQFZAbhv4=,tag:/xkeb+P2WXRg7uubMyAkEQ==,type:str]
    dbname: ENC[AES256_GCM,data:lQsRXcJn,iv:y9U7hozYvkRP16oyH2eOJ4aoOzLEXPQVyRjphD+E2HA=,tag:6zJqfvMXvnjgB4PHRsm+xw==,type:str]
sops:
    lastmodified: "2026-03-08T11:59:57Z"
    mac: ENC[AES256_GCM,data:rR+amklj9SOu9SsWJ/pgDyFnLgNJHZC17LkN9vEAGcwC1xWNTCxd026P1mWGUABzSepYsujTeHzmMhUOcaBC9b6b2yRTl+m7DfbWERUOlMp+cHjTytkqgaQON98AV+2J+uuhcj47y64kiOHqeG4sWsKJ+JWxJWYMZ5Pim9nBWV8=,iv:Bvv4ESaOv+0cscEeoFGdO3vPcoFuZOmpC6ER3Xxsdvc=,tag:if/++dV0+4JH9TM4tDxwDA==,type:str]
    pgp:
        - created_at: "2026-03-08T11:59:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/fkgfKhIiNh+6sqixKPGjN1CTRIotaMhhCrf9E9+K1zqg
            6wqBAEp2dHrzUJkyEkVjw5tY1g7xejL+tatXIPczolZ3kAp+xvNzdD9tLyCcR1n8
            UgWbpoe14G5Hy4ZeKN/aPF7Kl3RfQApOBIMVp6AfyBD04TtOkX0WrY3pr8iFOudm
            KQj0tQGz1eJREQxFKpw5DlfTndD/7cUBCAVQ8KxdOSaJtZWcjpkvOP5s+9gfXd7E
            4yhOHaISDGIpiVGHPsRhoeoIeVXXWOQZhutm6NKbiTJ7x2A3rtHhYgCUG9rHQaPH
            EEZYXx2IGBuB0P9ckGyOWzKRuow/xGnqwvk5YPimjRxLicttSM8Z8VJnwk0wUlFS
            z4K6yxqY2GDIasdQ0ZAlhXzH7p6wXW23v5whzFdMvGfx/4koZpFj5onovwqkVC2a
            HJzKxn4At0LO8MU13s+fXfpd67QfiGMnytHIFfX0PJHhUtEDivJuo1VljArWUBzC
            GXLqHAjydfatcPmQmKEZ0l4BKygUiONIVTjofKmSnE2P8SZDD2VSY7lCEItOoWmp
            9eFZBLAkDqYIYj0EcnXAYD3m21zpNgTQpFsk3b/kjniGh1J5mhWCsiGavBch5pFh
            qZlewe5bq2H33HlUHU5p
            =zduV
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: garage-creds
    namespace: zabbix
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:ID5Z0AzjsaRnL5lHOhl/bIjswmGZU+31bDY=,iv:TRtgYmbJv8184kBSiiCpl82VQTg1tBWcXC1OJHBu7DA=,tag:qbIC7JaO44S5EcquGkjZnw==,type:str]
    secret-access-key: ENC[AES256_GCM,data:2pqj+6hZ+VvqavJSYl3hu1dXw5V2Rqzzck3Tz5M0MeJuabTODhRLUmsN49YsJbjoTDq4WaR0CBNjqTziHC0JNg==,iv:1gxI4CFEZOyifnKuCOgjYgiZZzpXODHx8StWrwunW3s=,tag:xsPC9EGX4ShPLeNXa6f06g==,type:str]
    region: ENC[AES256_GCM,data:EQb1LA==,iv:nA3B/EjKj0K+L6bKZFEcssUTQmA5zJM4QNQFMFNg40o=,tag:eTa2J206N1j0Ltlta3rQBg==,type:str]
sops:
    lastmodified: "2026-03-08T11:59:57Z"
    mac: ENC[AES256_GCM,data:rR+amklj9SOu9SsWJ/pgDyFnLgNJHZC17LkN9vEAGcwC1xWNTCxd026P1mWGUABzSepYsujTeHzmMhUOcaBC9b6b2yRTl+m7DfbWERUOlMp+cHjTytkqgaQON98AV+2J+uuhcj47y64kiOHqeG4sWsKJ+JWxJWYMZ5Pim9nBWV8=,iv:Bvv4ESaOv+0cscEeoFGdO3vPcoFuZOmpC6ER3Xxsdvc=,tag:if/++dV0+4JH9TM4tDxwDA==,type:str]
    pgp:
        - created_at: "2026-03-08T11:59:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/fkgfKhIiNh+6sqixKPGjN1CTRIotaMhhCrf9E9+K1zqg
            6wqBAEp2dHrzUJkyEkVjw5tY1g7xejL+tatXIPczolZ3kAp+xvNzdD9tLyCcR1n8
            UgWbpoe14G5Hy4ZeKN/aPF7Kl3RfQApOBIMVp6AfyBD04TtOkX0WrY3pr8iFOudm
            KQj0tQGz1eJREQxFKpw5DlfTndD/7cUBCAVQ8KxdOSaJtZWcjpkvOP5s+9gfXd7E
            4yhOHaISDGIpiVGHPsRhoeoIeVXXWOQZhutm6NKbiTJ7x2A3rtHhYgCUG9rHQaPH
            EEZYXx2IGBuB0P9ckGyOWzKRuow/xGnqwvk5YPimjRxLicttSM8Z8VJnwk0wUlFS
            z4K6yxqY2GDIasdQ0ZAlhXzH7p6wXW23v5whzFdMvGfx/4koZpFj5onovwqkVC2a
            HJzKxn4At0LO8MU13s+fXfpd67QfiGMnytHIFfX0PJHhUtEDivJuo1VljArWUBzC
            GXLqHAjydfatcPmQmKEZ0l4BKygUiONIVTjofKmSnE2P8SZDD2VSY7lCEItOoWmp
            9eFZBLAkDqYIYj0EcnXAYD3m21zpNgTQpFsk3b/kjniGh1J5mhWCsiGavBch5pFh
            qZlewe5bq2H33HlUHU5p
            =zduV
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
