apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: zot-session-cache
  namespace: zot
spec:
  replicas: 3

  serviceSpec:
    name: zot-session-cache
    type: ClusterIP

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 356Mi

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              dragonflydb.io/name: zot-session-cache
