apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zot
  namespace: zot
spec:
  interval: 10m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true 
  releaseName: zot
  chart:
    spec:
      chart: zot
      version: "0.1.125"
      sourceRef:
        kind: HelmRepository
        name: project-zot
        namespace: flux-system
  values:
    replicaCount: 3
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/name: zot
                app.kubernetes.io/instance: zot
            topologyKey: kubernetes.io/hostname
    ingress:
      enabled: true
      className: cilium
      pathtype: Prefix
      hosts:
        - host: registry.k8s.exmaple.com
          paths:
            - path: /
      tls:
        - hosts:
            - registry.k8s.exmaple.com
      
    mountConfig: true
    mountSecret: true
    persistence: false

    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: zot-s3-credentials
            key: AWS_ACCESS_KEY_ID

      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: zot-s3-credentials
            key: AWS_SECRET_ACCESS_KEY


    extraVolumes:
      - name: zot-auth
        secret:
          secretName: zot-htpasswd
      - name: zot-tmp
        emptyDir:
          sizeLimit: 5Gi
      - name: zot-sync-download
        emptyDir:
          sizeLimit: 10Gi

    extraVolumeMounts:
      - name: zot-auth
        mountPath: /etc/zot/auth
        readOnly: true
      - name: zot-tmp
        mountPath: /tmp
      - name: zot-sync-download
        mountPath: /var/lib/zot-sync

    resources:
      requests:
        cpu: 500m
        memory: 128Mi
      limits:
        cpu: 1000m
        memory: 512Mi

    configFiles:
      config.json: |
        {
          "distSpecVersion": "1.1.0",
          "storage": {
            "rootDirectory": "/tmp/zot",
            "dedupe": false,
            "gc": true,
            "gcInterval": "24h",
            "commit": false,
            "remoteCache": true,
            "storageDriver": {
              "name": "s3",
              "region": "local",
              "regionendpoint": "10.50.0.30",
              "bucket": "registry",
              "rootdirectory": "/zot",
              "forcepathstyle": true,
              "secure": false,
              "skipverify": false
            },
            "cacheDriver": {
              "name": "redis",
              "url": "redis://zot-session-cache.zot.svc.cluster.local:6379",
              "keyprefix": "zot-cache"
            }
          },
          "http": {
            "address": "0.0.0.0",
            "port": "5000",
            "realm": "zot",
            "compat": ["docker2s2"],
            "readTimeout": "600s",
            "writeTimeout": "600s",
            "auth": {
              "htpasswd": {
                "path": "/etc/zot/auth/htpasswd"
              },
              "sessionDriver": {
                "name": "redis",
                "url": "redis://zot-session-cache.zot.svc.cluster.local:6379",
                "keyprefix": "zot-session"
              }
            },
            "accessControl": {
              "repositories": {
                "**": {
                  "anonymousPolicy": ["read"],
                  "defaultPolicy": []
                }
              },
              "adminPolicy": {
                "users": ["registry"],
                "actions": ["read", "create", "update", "delete"]
              }
            }
          },
          "log": {
            "level": "info"
          },
          "extensions": {
            "search": {
              "enable": true
            },
            "ui": {
              "enable": true
            },
            "scrub": {
              "enable": true,
              "interval": "24h"
            }
          }
        }