apiVersion: v1
kind: Secret
metadata:
    name: zot-s3-credentials
    namespace: zot
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:n3ZStYfHV/4qpob+4tTTBhgCnTs=,iv:Y2XBgxVCgfuemN08czyIDEYVWxqY2qLECYUVfjAZD4A=,tag:HXwN/AoXizeJ7TcV0dbe3w==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:OM1AecrqsUr02KyJ6CRuZtLfxC7qfaX0OKiwL5T2g+PRgFfEZzarFw==,iv:N/mcbxJ+RSaAJPBR5bTMbn+AE8mtC5Ad5nA5wbu9lOc=,tag:O8//gr6v8I1806K9FNdgmA==,type:str]
sops:
    lastmodified: "2026-03-25T18:11:33Z"
    mac: ENC[AES256_GCM,data:NJtjCAli9gb+eGtXL8TZ8hz0VsKGYYES4JMbfxt/Bp1KLCOmamcsbwE71GJuQPTeQNhuiP8D86Qm9/V4oFdM3EoLntyH0Ots+YMo9ahc92Pl6iEy4flBZZVswCXVDVLHfPSuTd5TwLMPb1K08eTOWMGpGM5WL3/0PupxSGnTyYE=,iv:jGDt6Jgu+P90/COXL0SjaiQCnYVp0RAtOqxgsaYd+VI=,tag:teLCusM38rRvVFh++HdN3Q==,type:str]
    pgp:
        - created_at: "2026-03-25T18:11:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQwAqm+i1yeg1fqM9gPAkXXFTcnhpMVohDT+yBa7c1GcZv/2
            ACRPXldbobtTm/zKaIjCNmmb7qFF8VYXVtgt+up7VCRURU0bv/WzbfaSiR3aBj8I
            un2lAIZoZILSd0CVFEWIDqdF0Z7gqr5f0XatJE2nfkq3KC2qEHrtoMipqfenq5Te
            8bUVdqrTju+IRVZvqvx53eKPmrqyg+ObxQSBFXS0s6AAytPaTnw2RB3pWp731q84
            nO6p17zBakpPqzZnmYJdNrXl0UtpzwOMpFgU7gbDWJ7OXB2rQZVn4UwSwNjet/wE
            Jje7tLGwnCytPdLhmIny8360xlW0VmnuFCaMu5LofigAvisJlup1cAOQD9UbrPlX
            oSHSOhADcOBx57/SDeQbkmoMz3J3VgfJUQwEobzZqc7rVyrmEyyql+EXA+cl2UDa
            YieISbBwaK4l7udq5n7Cj/1dR1jPfvDtX2ziQWAdcl9EJ28sH48ZOF9NM7csw6pg
            saA10SQdZpsPCgNKzIEj0l4BMpS2Y51L1ZTNDHU7ClUS/PUhzgkRx7DnDDBBSmTm
            uTZsQL+JsqbyJtpJXKKV9PLzxkOWsUrQ02s1yk9ucH2OY5LmUr7LKoa3vTAzT6DW
            rMCOGwMSFejYLRy8Lk19
            =nyY5
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: zot-htpasswd
    namespace: zot
type: Opaque
stringData:
    htpasswd: ENC[AES256_GCM,data:SAMjnbDNxsjXhGODhuFjevXT7v3W+xiJuJjLxLyR41xsQfkyFMPa9CQWpyBQmRJFxfFO9L6ywCnGzTm29S93igwUxlxr,iv:64+M7NsYw2UJpKpCdpuRXLNoDtZdsC3n2vFk9WlMZSs=,tag:ZIWLMusLtTWc09a8ykPUtQ==,type:str]
sops:
    lastmodified: "2026-03-25T18:11:33Z"
    mac: ENC[AES256_GCM,data:NJtjCAli9gb+eGtXL8TZ8hz0VsKGYYES4JMbfxt/Bp1KLCOmamcsbwE71GJuQPTeQNhuiP8D86Qm9/V4oFdM3EoLntyH0Ots+YMo9ahc92Pl6iEy4flBZZVswCXVDVLHfPSuTd5TwLMPb1K08eTOWMGpGM5WL3/0PupxSGnTyYE=,iv:jGDt6Jgu+P90/COXL0SjaiQCnYVp0RAtOqxgsaYd+VI=,tag:teLCusM38rRvVFh++HdN3Q==,type:str]
    pgp:
        - created_at: "2026-03-25T18:11:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQwAqm+i1yeg1fqM9gPAkXXFTcnhpMVohDT+yBa7c1GcZv/2
            ACRPXldbobtTm/zKaIjCNmmb7qFF8VYXVtgt+up7VCRURU0bv/WzbfaSiR3aBj8I
            un2lAIZoZILSd0CVFEWIDqdF0Z7gqr5f0XatJE2nfkq3KC2qEHrtoMipqfenq5Te
            8bUVdqrTju+IRVZvqvx53eKPmrqyg+ObxQSBFXS0s6AAytPaTnw2RB3pWp731q84
            nO6p17zBakpPqzZnmYJdNrXl0UtpzwOMpFgU7gbDWJ7OXB2rQZVn4UwSwNjet/wE
            Jje7tLGwnCytPdLhmIny8360xlW0VmnuFCaMu5LofigAvisJlup1cAOQD9UbrPlX
            oSHSOhADcOBx57/SDeQbkmoMz3J3VgfJUQwEobzZqc7rVyrmEyyql+EXA+cl2UDa
            YieISbBwaK4l7udq5n7Cj/1dR1jPfvDtX2ziQWAdcl9EJ28sH48ZOF9NM7csw6pg
            saA10SQdZpsPCgNKzIEj0l4BMpS2Y51L1ZTNDHU7ClUS/PUhzgkRx7DnDDBBSmTm
            uTZsQL+JsqbyJtpJXKKV9PLzxkOWsUrQ02s1yk9ucH2OY5LmUr7LKoa3vTAzT6DW
            rMCOGwMSFejYLRy8Lk19
            =nyY5
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
