apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 10m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true 
  chart:
    spec:
      chart: jellyfin
      version: 3.2.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/jellyfin/jellyfin
      tag: "10.11.11@sha256:45f648c382a0c8b552582fcea40e95cb17c5d475473a891cba0eb7523fb92112"
    ingress:
      enabled: true
      className: cilium
      hosts:
        - host: media.exmaple.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: external-tls
          hosts:
            - media.exmaple.com

    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch

    securityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL

    resources: 
      limits:
        cpu: 2000m
        memory: 2Gi
        gpu.intel.com/i915: "1"
      requests:
        cpu: 100m
        memory: 128Mi  

    jellyfin:
      enableDLNA: false 

    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 30Gi
        storageClass: 'csi-rbd-sc'
      cache:
        enabled: true
        accessMode: ReadWriteOnce
        size: 25Gi
        storageClass: 'csi-rbd-sc'
      media:
        enabled: false

    volumes:
      - name: jellyfin-video
        persistentVolumeClaim:
          claimName: jellyfin-video
      - name: jellyfin-music
        persistentVolumeClaim:
          claimName: jellyfin-music

    volumeMounts:
      - name: cache
        mountPath: /cache
      - name: jellyfin-video
        mountPath: /data2/video
      - name: jellyfin-music
        mountPath: /data2/music

