apiVersion: v1
kind: Secret
metadata:
    name: restic-config-jellyfin
    namespace: jellyfin
type: Opaque
stringData:
    #ENC[AES256_GCM,data:QKAoRvgE6vUlKHMNOuyG1AMKxh/aIZZBcC6OuimfLOq1W6/7Xrl0S6EGsFafXKLDvO7WTkS2KcDvjS6Y+aBrY8M=,iv:2mzkPfS5j8cUNxYTFRKvqledPKKyxJEaaBwiK6NvqiE=,tag:SrpftlGdVzUFs6rt7ITGzA==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:MKBN9Cc2zptOwSYW9khfEcVOJwVZZT5vmrLTRcXADaaZAAuBjUelIn2oyn0tDAmo,iv:NIQapPsYdrLRZ+8mb+fQRmXqrMhFeiCs6n05wdO1dRY=,tag:jFLvwxo1KKAKDo0tCUL2Mw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:BcGEb9iQGgFQhf9SWtDzuQG4XJRwGtY3bRdvtkIaRi+sbpD6gLKpKLcBnAP/uiSx,iv:GU2d+ulvlpCOX8rNYKg3nlcN8dTPvzeJgVHQcgJJRxA=,tag:D1fdvNg6GygrEYv0NmoKgA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:FDJx+s6sf7m/JfKbvpQrNCkcjXkasaNR3DY=,iv:QnZxkto0r7vrPU5ZlGbUckTQaGcadOQ4X7BxU4DyIj0=,tag:0O1KE0T5+taoWqVhyBVv5w==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:R5gHGKncksB65Vji6YHlk/4ry4Yg066BBZldqonPbTt65NEbvejEfGAdo/RFvTY4t0deu058JCyvM+I858uhhw==,iv:0go3XQ5eMrErb0agrSMseyTX/kKA29QeKhqfwnN0g1s=,tag:8wv2asP6fKARoSnTUrRsdw==,type:str]
sops:
    lastmodified: "2025-11-22T11:40:19Z"
    mac: ENC[AES256_GCM,data:sIGjDA+YxvGwy62x6R5S4TU8LkbqfI4+t1Y1f2O9Sb8VTW3KARpAMyYNZtQn1QYvM/F09GLmeJSJiALrx7AAADNgB2inCIhIloB3G5RsSriG12kVri8GlhIQBGPoxg4ogvfXwwKa2Xqn3iOqcliQt67ke9m/on8IYZ1E3Gybf+c=,iv:NwrQzPbaK0c3JCXkGK0TlsjADA253HoSPOalyEl9n2s=,tag:hGWVm93yvPPO3ttzdF4uHw==,type:str]
    pgp:
        - created_at: "2025-11-22T11:40:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5XCW1/hnAi8AQv/eqGDkA8oG9xOL5LwvTwyJPHxM3h8GTduondkYCFd/yuA
            IWPMbpi8KFRIw+4rMh0iaaGRWe8rVOxc5VvNFMbloSTpybL7yDduEKEuxMOPBIAz
            DPsAsDSSRnUPW1hphEM9QduNRAsI1tQdJUx2cGvdRgS1Ob9T0uexc9e+VPnU/R1C
            3NjRPbO7j0iuKAdvCRuKyspXkxfSAR+w41IkaUQCOfAYIxzPK/siCt8yG/BgiH/Q
            vJEnYISycGK8NZTyMeq4IP+hFGp3tMAzKzonZDXTgc8dYC2mw/lY7nHr3gSaNgjd
            TQzXb/EwzrKCSSaVExBgYw9PdFIVXPX6jhxuSNjivZEvKcb7OnZhU7PL+TVbf2cu
            chn6p7gWiU4xEEtNJHnJTg8FC1jG12fuj7S3ac/tflOZYC7V5GaTOiuHgD5eeF4B
            dugKDlOfVjmVpKfloZO2jEnMllHQq/XbhijG6P7aS18cblf3y5RZ6DNJu3XMZfTV
            gQm48HTTL6vIpS3RYGqr0lwBSuQPeReEgQsI8xY63N37ZTcXOeE25bnDgcXwtRIM
            6nvUMJUG+Kl9PtjEJXX+ZpMNMnXPZ82thqVhKuM8WppfZ9QvV/JuHuEbkGz30mzj
            HOuG2u2l7p/XhD8jRg==
            =s9gW
            -----END PGP MESSAGE-----
          fp: 02596567E2B03B75ACBC73740EBB3B7EC2111305
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
