---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-rbd-sc
  resources:
    requests:
      storage: 25Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-video-nfs-pv
spec:
  capacity:
    storage: 15Ti
  accessModes:
    - ReadWriteMany
  mountOptions:
    - vers=4.1
    - nconnect=12
  nfs:
    server: 192.168.178.118  
    path: /mnt/zfs-pool/media/video
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-video
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Ti
  storageClassName: ''
  volumeMode: Filesystem
  volumeName: jellyfin-video-nfs-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-music-nfs-pv
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  mountOptions:
    - vers=4.1
    - nconnect=12
  nfs:
    server: 192.168.178.118  
    path: /mnt/zfs-pool/media/music
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-music
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  storageClassName: ''
  volumeMode: Filesystem
  volumeName: jellyfin-music-nfs-pv